/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,     *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
*
* prvCpssIronmanTxqPdxRegFile.h
*
*Automaticly generated from :
*
* DESCRIPTION:
*      Describe TXQ PDX registers (Automaticly generated from CIDER)
*
* DEPENDENCIES:
*       None.
*
* FILE REVISION NUMBER:
*       $Revision: 1 $
*
*******************************************************************************/
#ifndef _TXQ_IRONMAN__PDX_REGFILE_H_
#define _TXQ_IRONMAN__PDX_REGFILE_H_

/* start of register pdx_metal_fix*/

#define      TXQ_IRONMAN_PDX_PDX_METAL_FIX_PDX_METAL_FIX_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDX_PDX_METAL_FIX_PDX_METAL_FIX_FIELD_SIZE         32

/* end of pdx_metal_fix*/


/* start of register Preemption_Enable*/

#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_0_FIELD_OFFSET            0
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_1_FIELD_OFFSET            1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_2_FIELD_OFFSET            2
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_3_FIELD_OFFSET            3
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_4_FIELD_OFFSET            4
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_5_FIELD_OFFSET            5
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_6_FIELD_OFFSET            6
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_7_FIELD_OFFSET            7
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_8_FIELD_OFFSET            8
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_9_FIELD_OFFSET            9
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_10_FIELD_OFFSET           10
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_11_FIELD_OFFSET           11
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_12_FIELD_OFFSET           12
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_13_FIELD_OFFSET           13
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_14_FIELD_OFFSET           14
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_15_FIELD_OFFSET           15
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_16_FIELD_OFFSET           16
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_17_FIELD_OFFSET           17
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_18_FIELD_OFFSET           18
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_19_FIELD_OFFSET           19
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_20_FIELD_OFFSET           20
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_21_FIELD_OFFSET           21
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_22_FIELD_OFFSET           22
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_23_FIELD_OFFSET           23
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_24_FIELD_OFFSET           24
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_25_FIELD_OFFSET           25
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_26_FIELD_OFFSET           26
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_27_FIELD_OFFSET           27
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_28_FIELD_OFFSET           28
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_29_FIELD_OFFSET           29
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_30_FIELD_OFFSET           30
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_31_FIELD_OFFSET           31


#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_0_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_1_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_2_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_3_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_4_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_5_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_6_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_7_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_8_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_9_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_10_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_11_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_12_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_13_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_14_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_15_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_16_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_17_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_18_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_19_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_20_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_21_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_22_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_23_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_24_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_25_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_26_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_27_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_28_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_29_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_30_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PREEMPTION_ENABLE_PREEMPT_EN_31_FIELD_SIZE         1

/* end of Preemption_Enable*/


/* start of register PDX_Functional_Interrupt_Cause*/

#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_FUNC_INTSUM_FIELD_OFFSET            0
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_ILLEGAL_ADDRESS_ACCESS_FIELD_OFFSET         1
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_QCX_WRONG_QGRP_ADDR_INT_FIELD_OFFSET            2
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_DX_WRONG_QGRP_ADDR_INT_FIELD_OFFSET         4
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_DX_DESC_DROP_INT_FIELD_OFFSET           12
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_QGRP_SER_INT_FIELD_OFFSET           16


#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_PDX_FUNC_INTSUM_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_ILLEGAL_ADDRESS_ACCESS_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_QCX_WRONG_QGRP_ADDR_INT_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_DX_WRONG_QGRP_ADDR_INT_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_DX_DESC_DROP_INT_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_CAUSE_QGRP_SER_INT_FIELD_SIZE         1

/* end of PDX_Functional_Interrupt_Cause*/


/* start of register PDX_Functional_Interrupt_Mask*/

#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_FUNC_INT_MASK_1_FIELD_OFFSET         1
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_FUNC_INT_MASK_2_FIELD_OFFSET         2
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_FUNC_INT_MASK_4_FIELD_OFFSET         4
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_FUNC_INT_MASK_8_FIELD_OFFSET         8
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_FUNC_INT_MASK_12_FIELD_OFFSET            12
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_FUNC_INT_MASK_16_FIELD_OFFSET            16


#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_FUNC_INT_MASK_1_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_FUNC_INT_MASK_2_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_FUNC_INT_MASK_4_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_FUNC_INT_MASK_8_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_FUNC_INT_MASK_12_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDX_PDX_FUNCTIONAL_INTERRUPT_MASK_PDX_FUNC_INT_MASK_16_FIELD_SIZE          1

/* end of PDX_Functional_Interrupt_Mask*/


/* start of register Address_Violation*/

#define      TXQ_IRONMAN_PDX_ADDRESS_VIOLATION_ADDRESS_VIOLATION_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDX_ADDRESS_VIOLATION_ADDRESS_VIOLATION_FIELD_SIZE         32

/* end of Address_Violation*/


/* start of register PDX_Interrupt_Summary_Cause*/

#define      TXQ_IRONMAN_PDX_PDX_INTERRUPT_SUMMARY_CAUSE_PDX_INT_SUM_FIELD_OFFSET           0
#define      TXQ_IRONMAN_PDX_PDX_INTERRUPT_SUMMARY_CAUSE_PDX_FUNC_INT_SUM_FIELD_OFFSET          1
#define      TXQ_IRONMAN_PDX_PDX_INTERRUPT_SUMMARY_CAUSE_PDX_DBG_INT_SUM_FIELD_OFFSET           2


#define      TXQ_IRONMAN_PDX_PDX_INTERRUPT_SUMMARY_CAUSE_PDX_INT_SUM_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PDX_INTERRUPT_SUMMARY_CAUSE_PDX_FUNC_INT_SUM_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDX_PDX_INTERRUPT_SUMMARY_CAUSE_PDX_DBG_INT_SUM_FIELD_SIZE         1

/* end of PDX_Interrupt_Summary_Cause*/


/* start of register PDX_Interrupt_Summary_Mask*/

#define      TXQ_IRONMAN_PDX_PDX_INTERRUPT_SUMMARY_MASK_PDX_FUNC_INT_SUM_MASK_FIELD_OFFSET          1
#define      TXQ_IRONMAN_PDX_PDX_INTERRUPT_SUMMARY_MASK_PDX_DBG_INT_SUM_MASK_FIELD_OFFSET           2


#define      TXQ_IRONMAN_PDX_PDX_INTERRUPT_SUMMARY_MASK_PDX_FUNC_INT_SUM_MASK_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDX_PDX_INTERRUPT_SUMMARY_MASK_PDX_DBG_INT_SUM_MASK_FIELD_SIZE         1

/* end of PDX_Interrupt_Summary_Mask*/


/* start of register PDX_Debug_Interrupt_Cause*/

#define      TXQ_IRONMAN_PDX_PDX_DEBUG_INTERRUPT_CAUSE_PDX_DBG_INTSUM_FIELD_OFFSET          0
#define      TXQ_IRONMAN_PDX_PDX_DEBUG_INTERRUPT_CAUSE_DX_DESC_FIFO_FULL_0_FIELD_OFFSET         1
#define      TXQ_IRONMAN_PDX_PDX_DEBUG_INTERRUPT_CAUSE_DX_MAP_FIFO_OVRFLW_0_FIELD_OFFSET            5


#define      TXQ_IRONMAN_PDX_PDX_DEBUG_INTERRUPT_CAUSE_PDX_DBG_INTSUM_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDX_PDX_DEBUG_INTERRUPT_CAUSE_DX_DESC_FIFO_FULL_0_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDX_PDX_DEBUG_INTERRUPT_CAUSE_DX_MAP_FIFO_OVRFLW_0_FIELD_SIZE          1

/* end of PDX_Debug_Interrupt_Cause*/


/* start of register PDX_Debug_Interrupt_Mask*/

#define      TXQ_IRONMAN_PDX_PDX_DEBUG_INTERRUPT_MASK_PDX_DBG_INT_MASK_1_FIELD_OFFSET           1
#define      TXQ_IRONMAN_PDX_PDX_DEBUG_INTERRUPT_MASK_PDX_DBG_INT_MASK_5_FIELD_OFFSET           5


#define      TXQ_IRONMAN_PDX_PDX_DEBUG_INTERRUPT_MASK_PDX_DBG_INT_MASK_1_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDX_PDX_DEBUG_INTERRUPT_MASK_PDX_DBG_INT_MASK_5_FIELD_SIZE         1

/* end of PDX_Debug_Interrupt_Mask*/


/* start of register pfcc_burst_fifo_thr*/

#define      TXQ_IRONMAN_PDX_PFCC_BURST_FIFO_THR_PFCC_BURST_FIFO_THR_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDX_PFCC_BURST_FIFO_THR_PFCC_BURST_FIFO_THR_FIELD_SIZE         16

/* end of pfcc_burst_fifo_thr*/


/* start of register global_burst_fifo_thr*/

#define      TXQ_IRONMAN_PDX_GLOBAL_BURST_FIFO_THR_GLOBAL_BURST_FIFO_THR_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDX_GLOBAL_BURST_FIFO_THR_GLOBAL_BURST_FIFO_THR_FIELD_SIZE         16

/* end of global_burst_fifo_thr*/


/* start of register global_burst_fifo_available_entries*/

#define      TXQ_IRONMAN_PDX_GLOBAL_BURST_FIFO_AVAILABLE_ENTRIES_GLOBAL_BURST_FIFO_AVAILABLE_ENTRIES_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDX_GLOBAL_BURST_FIFO_AVAILABLE_ENTRIES_GLOBAL_BURST_FIFO_AVAILABLE_ENTRIES_FIELD_SIZE         16

/* end of global_burst_fifo_available_entries*/


/* start of register DB_Read_Control*/

#define      TXQ_IRONMAN_PDX_DB_READ_CONTROL_QCX_DB_READ_CONTROL_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDX_DB_READ_CONTROL_QCX_DB_READ_CONTROL_FIELD_SIZE         18

/* end of DB_Read_Control*/


/* start of register QCX_Read_qu_db*/

#define      TXQ_IRONMAN_PDX_QCX_READ_QU_DB_QCX_READ_QU_DB_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDX_QCX_READ_QU_DB_QCX_READ_QU_DB_FIELD_SIZE           20

/* end of QCX_Read_qu_db*/


/* start of register QCX_Read_Port_DB*/

#define      TXQ_IRONMAN_PDX_QCX_READ_PORT_DB_QCX_READ_PORT_DB_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDX_QCX_READ_PORT_DB_QCX_READ_PORT_DB_FIELD_SIZE           20

/* end of QCX_Read_Port_DB*/


/* start of register QCX_Wrong_Qgrpmap_Addr*/

#define      TXQ_IRONMAN_PDX_QCX_WRONG_QGRPMAP_ADDR_QCX_WRONG_QUEUE_GROUP_INDEX_FIELD_OFFSET            0


#define      TXQ_IRONMAN_PDX_QCX_WRONG_QGRPMAP_ADDR_QCX_WRONG_QUEUE_GROUP_INDEX_FIELD_SIZE          10

/* end of QCX_Wrong_Qgrpmap_Addr*/


/* start of register DX_Wrong_Qgrpmap_Addr*/

#define      TXQ_IRONMAN_PDX_DX_WRONG_QGRPMAP_ADDR_DX_WRONG_QUEUE_GROUP_INDEX_FIELD_OFFSET          0


#define      TXQ_IRONMAN_PDX_DX_WRONG_QGRPMAP_ADDR_DX_WRONG_QUEUE_GROUP_INDEX_FIELD_SIZE            10

/* end of DX_Wrong_Qgrpmap_Addr*/


/* start of register Drop_Counter*/

#define      TXQ_IRONMAN_PDX_DROP_COUNTER_DESC_DROP_COUNT_FIELD_OFFSET          0


#define      TXQ_IRONMAN_PDX_DROP_COUNTER_DESC_DROP_COUNT_FIELD_SIZE            32

/* end of Drop_Counter*/


/* start of register PDS_Drop_Counter*/

#define      TXQ_IRONMAN_PDX_PDS_DROP_COUNTER_PDS_DESC_DROP_COUNT_FIELD_OFFSET          0


#define      TXQ_IRONMAN_PDX_PDS_DROP_COUNTER_PDS_DESC_DROP_COUNT_FIELD_SIZE            32

/* end of PDS_Drop_Counter*/


/* start of table entry dx_qgrpmap_0*/

#define      TXQ_IRONMAN_PDX_DX_QGRPMAP_0_QUEUE_BASE_FIELD_OFFSET           0
#define      TXQ_IRONMAN_PDX_DX_QGRPMAP_0_DP_CORE_LOCAL_TRG_PORT_FIELD_OFFSET           9
#define      TXQ_IRONMAN_PDX_DX_QGRPMAP_0_QUEUE_PDS_INDEX_FIELD_OFFSET          15


#define      TXQ_IRONMAN_PDX_DX_QGRPMAP_0_QUEUE_BASE_FIELD_SIZE         9
#define      TXQ_IRONMAN_PDX_DX_QGRPMAP_0_DP_CORE_LOCAL_TRG_PORT_FIELD_SIZE         6
#define      TXQ_IRONMAN_PDX_DX_QGRPMAP_0_QUEUE_PDS_INDEX_FIELD_SIZE            1

/* end of dx_qgrpmap_0*/


/* start of table entry qcx_qgrpmap_0*/

#define      TXQ_IRONMAN_PDX_QCX_QGRPMAP_QUEUE_BASE_FIELD_OFFSET            0
#define      TXQ_IRONMAN_PDX_QCX_QGRPMAP_DP_CORE_LOCAL_TRG_PORT_FIELD_OFFSET            9
#define      TXQ_IRONMAN_PDX_QCX_QGRPMAP_QUEUE_PDS_INDEX_FIELD_OFFSET           15


#define      TXQ_IRONMAN_PDX_QCX_QGRPMAP_QUEUE_BASE_FIELD_SIZE          9
#define      TXQ_IRONMAN_PDX_QCX_QGRPMAP_DP_CORE_LOCAL_TRG_PORT_FIELD_SIZE          6
#define      TXQ_IRONMAN_PDX_QCX_QGRPMAP_QUEUE_PDS_INDEX_FIELD_SIZE         1

/* end of qcx_qgrpmap_0*/

/*obsolete - added manually*/

#define TXQ_IRONMAN_PDX_QCX_QGRPMAP_QUEUE_PDX_INDEX_FIELD_OFFSET CPSS_SIP6_TXQ_INVAL_DATA_CNS
#define TXQ_IRONMAN_PDX_QCX_QGRPMAP_QUEUE_PDX_INDEX_FIELD_SIZE   CPSS_SIP6_TXQ_INVAL_DATA_CNS

#endif
