/*===========================================================================*/
#ifndef exp_h_conf_PKS_INCLUDED
#define exp_h_conf_PKS_INCLUDED
/*!**************************************************************************
*!                  P A C K A G E       S P E C I F I C A T I O N
*!==========================================================================
*$ TITLE: I/O utils for 80960
*!--------------------------------------------------------------------------
*$ FILENAME: c:\temp\radlan\local\h_conf\EXP\h_conf.h
*!--------------------------------------------------------------------------
*$ SYSTEM, SUBSYSTEM: ET16
*!--------------------------------------------------------------------------
*$ AUTHORS: avi_c
*!--------------------------------------------------------------------------
*$ LATEST UPDATE:                              CREATION DATE: 20-Sep-92
*!--------------------------------------------------------------------------
*$ HISTORY:   $LOG$
*!**************************************************************************
*!
*$ GENERAL DESCRIPTION:
*!
*$ PROCESS AND ALGORITHM: (local)
*!
*$ PACKAGE GLOBAL SERVICES:
*!     (A list of package global services).
*!
*$ PACKAGE LOCAL SERVICES:  (local)
*!     (A list of package local services).
*!
*$ PACKAGE USAGE:
*!     (How to use the package services,
*!     routines calling order, restrictions, etc.)
*!
*$ ASSUMPTIONS:
*!
*$ SIDE EFFECTS:
*!
*$ RELATED DOCUMENTS:     (local)
*!
*$ REMARKS:               (local)
*!
*!**************************************************************************
*/
/*!**************************************************************************
*$            EXTERNAL DECLARATIONS (IMPORT AND EXPORT)
*!**************************************************************************
*!*/
    #include <HOST_D/EXP/HOST_D.H>
/*!**************************************************************************
*$            PUBLIC DECLARATIONS  (EXPORT)
*!**************************************************************************
*!*/
/*!**************************************************************************
*$            PUBLIC VARIABLE DEFINITIONS (EXPORT)
*!**************************************************************************
*!*/
/*===========================================================================*/
/*!**************************************************RND Template version 4.1
 *!        P U B L I C   V A R I A B L E   D E C L A R A T I O N S
 *!==========================================================================
 *$ TITLE: <Title>
 *!--------------------------------------------------------------------------
 *$ FILENAME: u:\sw\Hot_swap\g\shost\v3\v300\local\h_conf\inc\config.pub
 *!--------------------------------------------------------------------------
 *$ SYSTEM, SUBSYSTEM: LRE
 *!--------------------------------------------------------------------------
 *$ AUTHORS: YURI_A
 *!--------------------------------------------------------------------------
 *$ LATEST UPDATE: 3-Jan-2002, 6:17 PM CREATION DATE: 30-Apr-96
 *!**************************************************************************
 *!
 *!**************************************************************************
 *!
 *$ GENERAL DESCRIPTION:
 *!
 *$ INCLUDE REQUIRED:
 *!
 *$ REMARKS:
 *!
 *!**************************************************************************
 *!*/

extern char      CNFG_cofig_file_name[80] ;
extern char      CNFG_cofig_file_name_back[80] ;

 #define   CNFG_max_line_length_CNS   128


/*===========================================================================*/
/*!**************************************************************************
*$            PUBLIC FUNCTION DEFINITIONS (EXPORT)
*!**************************************************************************
*!*/
/*===========================================================================*/
/*!**************************************************RND Template version 4.1
 *!     F U N C T I O N    P R O T O T Y P E    D E F I N I T I O N
 *!==========================================================================
 *$ TITLE: <Title>
 *!--------------------------------------------------------------------------
 *$ FILENAME: c:\temp\radlan\local\h_conf\EXP\chck_str.fud
 *!--------------------------------------------------------------------------
 *$ SYSTEM, SUBSYSTEM: LRE
 *!--------------------------------------------------------------------------
 *$ AUTHORS: YURI_A    
 *!--------------------------------------------------------------------------
 *$ LATEST UPDATE:                             CREATION DATE: 25-Jul-96
 *!**************************************************************************
 *!
 *!**************************************************************************
 *!
 *$ FUNCTION: <FuncName>
 *!
 *$ GENERAL DESCRIPTION:
 *!
 *$ RETURNS:
 *!
 *$ ALGORITHM:   (local)
 *!
 *$ ASSUMPTIONS:
 *!
 *$ REMARKS:     (local)
 *!
 *!**************************************************************************
 *!*/

extern  char*  CNFG_chck_str(
    /*!     INPUTS:             */
      char    *str
);
/*$ END OF CNFG_chck_str */
/*$ END OF <FuncName> */
/*===========================================================================*/
/*===========================================================================*/
/**
* @internal CNFG_get_cnf_value function
* @endinternal
*
*
* @retval $ REMARKS: AmitK         - 10/09/2002 - check that the match is for the total val_name
*                                       !                not only to the same start of string !!!
*                                       !
*                                       !
*/

extern  unsigned  CNFG_get_cnf_value(
    /*!     INPUTS:             */
         char     *chap_name,
         char     *val_name,
         UINT_32  data_len,
    /*!     INPUTS / OUTPUTS:   */
    /*!     OUTPUTS:            */
         char     *val_buf
);
/*$ END OF CNFG_get_cnf_value */
/*$ END OF <FuncName> */

/*===========================================================================*/
/*===========================================================================*/
/**
* @internal CNFG_set_cnf_value function
* @endinternal
*
*/

extern unsigned CNFG_set_cnf_value(
    /*!     INPUTS:             */
    char       * chap_name,
    char       * val_name,
    UINT_32      data_len,
    /*!     INPUTS / OUTPUTS:   */
    /*!     OUTPUTS:            */
    char    * val_buf
);
/*$ END OF CNFG_set_cnf_value */

/*$ END OF CNFG_get_cnf_value */

/*===========================================================================*/
/*===========================================================================*/
/**
* @internal CNFG_set_cnf_file function
* @endinternal
*
*/

extern void CNFG_set_cnf_file (

    /*!     INPUTS:             */

    UINT_8 *file_name           /*!*/
);
/*$ END OF CNFG_set_cnf_file */
/*===========================================================================*/
/*===========================================================================*/
/**
* @internal CNFG_create_backup_file function
* @endinternal
*
*/

extern  BOOLEAN  CNFG_create_backup_file(
    /*!     INPUTS:             */
         void

);
/*$ END OF CNFG_create_backup_file */
/*$ END OF CNFG_get_cnf_value */

/*===========================================================================*/

#endif
/*$ END OF h_conf */

