/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,       *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
* prvCpssDxChPacketAnalyzerLog.c
*       WARNING!!! this is a generated file, please don't edit it manually
* COMMENTS:
*
* FILE REVISION NUMBER:
*       $Revision: 1 $
*******************************************************************************/

/* disable deprecation warnings (if one) */
#ifdef __GNUC__
#if  (__GNUC__*100+__GNUC_MINOR__) >= 406
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif
#endif

#include <cpss/generic/log/cpssLog.h>
#include <cpss/generic/log/prvCpssLog.h>
#include <cpss/extServices/private/prvCpssBindFunc.h>
#include <cpss/common/private/globalShared/prvCpssGlobalDb.h>
#include <cpss/common/private/globalShared/prvCpssGlobalDbInterface.h>
#include <cpss/dxCh/dxChxGen/packetAnalyzer/cpssDxChPacketAnalyzerTypes.h>
#include <cpss/dxCh/dxChxGen/packetAnalyzer/private/prvCpssDxChPacketAnalyzerLog.h>
#include <cpss/generic/log/prvCpssGenCommonTypesLog.h>
#include <cpss/generic/log/prvCpssGenDbLog.h>


/********* enums *********/

const char * const prvCpssLogEnum_CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT[]  =
{
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ASSIGN_ALL_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ASSIGN_PARTIAL_E"
};
PRV_CPSS_LOG_STC_ENUM_ARRAY_SIZE_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT);
const char * const prvCpssLogEnum_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT[]  =
{
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_LOCAL_DEV_SRC_IS_TRUNK_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_LOCAL_DEV_SRC_PORT_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_LOCAL_DEV_SRC_TRUNK_ID_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_LOCAL_DEV_SRC_EPORT_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_LOCAL_DEV_TRG_PHY_PORT_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_ORIG_IS_TRUNK_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_ORIG_SRC_DEV_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_ORIG_SRC_PHY_IS_TRUNK_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_ORIG_SRC_PHY_PORT_OR_TRUNK_ID_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_ORIG_SRC_TRUNK_ID_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_TRG_EPORT_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_TRG_PHY_PORT_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_MAC_SA_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_MAC_DA_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_ORIG_VID_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_EVIDX_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_EVLAN_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_ETHER_TYPE_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_IPV4_SIP_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_IPV4_DIP_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_IPV6_SIP_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_IPV6_DIP_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_IPX_PROTOCOL_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_DSCP_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_BYTE_COUNT_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_IS_IP_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_IS_IPV4_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_IS_IPV6_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_IP_LEGAL_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_IPM_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_L4_VALID_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_MAC_TO_ME_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_PACKET_CMD_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_QUEUE_PORT_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_QUEUE_PRIORITY_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_USE_VIDX_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_EGRESS_FILTER_DROP_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_EGRESS_FILTER_EN_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_EGRESS_FILTER_REGISTERED_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_CPU_CODE_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_MARVELL_TAGGED_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_MARVELL_TAGGED_EXTENDED_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_BYPASS_BRIDGE_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_BYPASS_INGRESS_PIPE_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_TUNNEL_START_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_TUNNEL_TERMINATED_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_EGRESS_PACKET_CMD_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_PACKET_TRACE_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_OUTGOING_MTAG_CMD_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_QUEUE_OFFSET_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_0_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_1_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_2_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_3_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_4_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_5_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_6_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_7_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_8_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_9_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_10_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_11_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_12_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_13_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_14_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_15_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_16_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_17_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_18_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_19_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_20_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_21_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_22_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_23_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_24_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_25_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_26_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_27_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_28_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_29_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_30_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_31_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_32_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_33_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_34_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_35_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_36_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_37_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_38_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_39_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_40_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_41_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_42_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_43_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_44_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_45_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_46_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_47_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_48_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_49_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_50_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_51_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_52_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_53_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_54_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_55_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_56_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_57_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_58_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_59_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_60_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_61_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_62_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_UDF_63_E",
    "CPSS_DXCH_PACKET_ANALYZER_FIELD_LAST_E"
};
PRV_CPSS_LOG_STC_ENUM_ARRAY_SIZE_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT);
const char * const prvCpssLogEnum_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT[]  =
{
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_INGRESS_PRE_TTI_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_INGRESS_PRE_PCL_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_INGRESS_PRE_BRIDGE_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_INGRESS_PRE_ROUTER_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_INGRESS_PRE_OAM_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_INGRESS_PRE_POLICER_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_INGRESS_PRE_MLL_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_INGRESS_PRE_E_QUEUE_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_EGRESS_PRE_FILTER_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_EGRESS_PRE_TRANSMIT_QUEUE_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_EGRESS_PRE_HEADER_ALTERATION_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_EGRESS_PRE_OAM_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_EGRESS_PRE_PCL_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_EGRESS_PRE_POLICER_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_EGRESS_PRE_TIMESTAMP_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_EGRESS_PRE_MAC_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_EGRESS_PRE_PHA_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_EGRESS_PRE_REPLICATION_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_0_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_1_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_2_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_3_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_4_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_5_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_6_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_7_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_8_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_9_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_10_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_11_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_12_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_13_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_14_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_15_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_16_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_17_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_18_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_UDS_19_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ALL_INGRESS_STAGES_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ALL_EGRESS_STAGES_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ALL_STAGES_E",
    "CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_LAST_E"
};
PRV_CPSS_LOG_STC_ENUM_ARRAY_SIZE_MAC(CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT);
const char * const prvCpssLogEnum_CPSS_DXCH_PACKET_ANALYZER_SAMPLING_MODE_ENT[]  =
{
    "CPSS_DXCH_PACKET_ANALYZER_SAMPLING_MODE_FIRST_MATCH_E",
    "CPSS_DXCH_PACKET_ANALYZER_SAMPLING_MODE_LAST_MATCH_E"
};
PRV_CPSS_LOG_STC_ENUM_ARRAY_SIZE_MAC(CPSS_DXCH_PACKET_ANALYZER_SAMPLING_MODE_ENT);
const char * const prvCpssLogEnum_CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_TYPE_ENT[]  =
{
    "CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_TYPE_CORE_E",
    "CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_TYPE_PORT_E"
};
PRV_CPSS_LOG_STC_ENUM_ARRAY_SIZE_MAC(CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_TYPE_ENT);


/********* structure fields log functions *********/

void prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_ACTION_STC_PTR
(
    IN CPSS_LOG_LIB_ENT         contextLib,
    IN CPSS_LOG_TYPE_ENT        logType,
    IN GT_CHAR_PTR              namePtr,
    IN void                   * fieldPtr,
    INOUT PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC     * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_FIELD_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_ACTION_STC *, valPtr);
    PRV_CPSS_LOG_UNUSED_MAC(inOutParamInfoPtr);
    PRV_CPSS_LOG_STC_BOOL_MAC(valPtr, samplingEnable);
    PRV_CPSS_LOG_STC_ENUM_MAC(valPtr, samplingMode, CPSS_DXCH_PACKET_ANALYZER_SAMPLING_MODE_ENT);
    PRV_CPSS_LOG_STC_BOOL_MAC(valPtr, matchCounterEnable);
    PRV_CPSS_LOG_STC_STC_MAC(valPtr, matchCounterIntThresh, CPSS_DXCH_PACKET_ANALYZER_COUNTER_INTERRUPT_THRESH_STC);
    PRV_CPSS_LOG_STC_BOOL_MAC(valPtr, interruptSamplingEnable);
    PRV_CPSS_LOG_STC_BOOL_MAC(valPtr, interruptMatchCounterEnable);
    PRV_CPSS_LOG_STC_BOOL_MAC(valPtr, inverseEnable);
    prvCpssLogStcLogEnd(contextLib, logType);
}
void prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_FIELD_NAME_STC_PTR
(
    IN CPSS_LOG_LIB_ENT         contextLib,
    IN CPSS_LOG_TYPE_ENT        logType,
    IN GT_CHAR_PTR              namePtr,
    IN void                   * fieldPtr,
    INOUT PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC     * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_FIELD_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_NAME_STC *, valPtr);
    PRV_CPSS_LOG_UNUSED_MAC(inOutParamInfoPtr);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, fieldNameArr, CPSS_DXCH_PACKET_ANALYZER_MAX_NAME_LENGTH_CNS, GT_CHAR);
    prvCpssLogStcLogEnd(contextLib, logType);
}
void prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR
(
    IN CPSS_LOG_LIB_ENT         contextLib,
    IN CPSS_LOG_TYPE_ENT        logType,
    IN GT_CHAR_PTR              namePtr,
    IN void                   * fieldPtr,
    INOUT PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC     * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_FIELD_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC *, valPtr);
    PRV_CPSS_LOG_UNUSED_MAC(inOutParamInfoPtr);
    PRV_CPSS_LOG_STC_ENUM_MAC(valPtr, fieldName, CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, data, CPSS_DXCH_PACKET_ANALYZER_MAX_FIELD_LENGTH_CNS, GT_U32);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, msk, CPSS_DXCH_PACKET_ANALYZER_MAX_FIELD_LENGTH_CNS, GT_U32);
    prvCpssLogStcLogEnd(contextLib, logType);
}
void prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_GROUP_ATTRIBUTES_STC_PTR
(
    IN CPSS_LOG_LIB_ENT         contextLib,
    IN CPSS_LOG_TYPE_ENT        logType,
    IN GT_CHAR_PTR              namePtr,
    IN void                   * fieldPtr,
    INOUT PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC     * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_FIELD_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_GROUP_ATTRIBUTES_STC *, valPtr);
    PRV_CPSS_LOG_UNUSED_MAC(inOutParamInfoPtr);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, groupNameArr, CPSS_DXCH_PACKET_ANALYZER_MAX_NAME_LENGTH_CNS, GT_CHAR);
    prvCpssLogStcLogEnd(contextLib, logType);
}
void prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_INTERNAL_FIELD_VALUE_STC_PTR
(
    IN CPSS_LOG_LIB_ENT         contextLib,
    IN CPSS_LOG_TYPE_ENT        logType,
    IN GT_CHAR_PTR              namePtr,
    IN void                   * fieldPtr,
    INOUT PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC     * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_FIELD_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_INTERNAL_FIELD_VALUE_STC *, valPtr);
    PRV_CPSS_LOG_UNUSED_MAC(inOutParamInfoPtr);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, fieldName, CPSS_DXCH_PACKET_ANALYZER_MAX_STR_LEN_CNS, GT_CHAR);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, data, CPSS_DXCH_PACKET_ANALYZER_MAX_FIELD_LENGTH_CNS, GT_U32);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, msk, CPSS_DXCH_PACKET_ANALYZER_MAX_FIELD_LENGTH_CNS, GT_U32);
    prvCpssLogStcLogEnd(contextLib, logType);
}
void prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_KEY_ATTRIBUTES_STC_PTR
(
    IN CPSS_LOG_LIB_ENT         contextLib,
    IN CPSS_LOG_TYPE_ENT        logType,
    IN GT_CHAR_PTR              namePtr,
    IN void                   * fieldPtr,
    INOUT PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC     * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_FIELD_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_KEY_ATTRIBUTES_STC *, valPtr);
    PRV_CPSS_LOG_UNUSED_MAC(inOutParamInfoPtr);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, keyNameArr, CPSS_DXCH_PACKET_ANALYZER_MAX_NAME_LENGTH_CNS, GT_CHAR);
    prvCpssLogStcLogEnd(contextLib, logType);
}
void prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_RULE_ATTRIBUTES_STC_PTR
(
    IN CPSS_LOG_LIB_ENT         contextLib,
    IN CPSS_LOG_TYPE_ENT        logType,
    IN GT_CHAR_PTR              namePtr,
    IN void                   * fieldPtr,
    INOUT PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC     * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_FIELD_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_RULE_ATTRIBUTES_STC *, valPtr);
    PRV_CPSS_LOG_UNUSED_MAC(inOutParamInfoPtr);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, ruleNameArr, CPSS_DXCH_PACKET_ANALYZER_MAX_NAME_LENGTH_CNS, GT_CHAR);
    prvCpssLogStcLogEnd(contextLib, logType);
}
void prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_STC_PTR
(
    IN CPSS_LOG_LIB_ENT         contextLib,
    IN CPSS_LOG_TYPE_ENT        logType,
    IN GT_CHAR_PTR              namePtr,
    IN void                   * fieldPtr,
    INOUT PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC     * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_FIELD_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_STC *, valPtr);
    PRV_CPSS_LOG_UNUSED_MAC(inOutParamInfoPtr);
    PRV_CPSS_LOG_STC_NUMBER_MAC(valPtr, device);
    PRV_CPSS_LOG_STC_ENUM_MAC(valPtr, type, CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_TYPE_ENT);
    PRV_CPSS_LOG_STC_NUMBER_MAC(valPtr, tile);
    PRV_CPSS_LOG_STC_NUMBER_MAC(valPtr, pipe);
    PRV_CPSS_LOG_STC_NUMBER_MAC(valPtr, dp);
    PRV_CPSS_LOG_STC_NUMBER_MAC(valPtr, portNum);
    prvCpssLogStcLogEnd(contextLib, logType);
}
void prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_STAGE_INTERFACE_STC_PTR
(
    IN CPSS_LOG_LIB_ENT         contextLib,
    IN CPSS_LOG_TYPE_ENT        logType,
    IN GT_CHAR_PTR              namePtr,
    IN void                   * fieldPtr,
    INOUT PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC     * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_FIELD_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_STAGE_INTERFACE_STC *, valPtr);
    PRV_CPSS_LOG_UNUSED_MAC(inOutParamInfoPtr);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, instanceId, CPSS_DXCH_PACKET_ANALYZER_MAX_STR_LEN_CNS, GT_CHAR);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, interfaceId, CPSS_DXCH_PACKET_ANALYZER_MAX_STR_LEN_CNS, GT_CHAR);
    PRV_CPSS_LOG_STC_NUMBER_MAC(valPtr, interfaceIndex);
    prvCpssLogStcLogEnd(contextLib, logType);
}
void prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC_PTR
(
    IN CPSS_LOG_LIB_ENT         contextLib,
    IN CPSS_LOG_TYPE_ENT        logType,
    IN GT_CHAR_PTR              namePtr,
    IN void                   * fieldPtr,
    INOUT PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC     * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_FIELD_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC *, valPtr);
    PRV_CPSS_LOG_UNUSED_MAC(inOutParamInfoPtr);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, udfNameArr, CPSS_DXCH_PACKET_ANALYZER_MAX_NAME_LENGTH_CNS, GT_CHAR);
    prvCpssLogStcLogEnd(contextLib, logType);
}
void prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC_PTR
(
    IN CPSS_LOG_LIB_ENT         contextLib,
    IN CPSS_LOG_TYPE_ENT        logType,
    IN GT_CHAR_PTR              namePtr,
    IN void                   * fieldPtr,
    INOUT PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC     * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_FIELD_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC *, valPtr);
    PRV_CPSS_LOG_UNUSED_MAC(inOutParamInfoPtr);
    PRV_CPSS_LOG_STC_TYPE_ARRAY_MAC(valPtr, udsNameArr, CPSS_DXCH_PACKET_ANALYZER_MAX_NAME_LENGTH_CNS, GT_CHAR);
    prvCpssLogStcLogEnd(contextLib, logType);
}
void prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_COUNTER_INTERRUPT_THRESH_STC_PTR
(
    IN CPSS_LOG_LIB_ENT         contextLib,
    IN CPSS_LOG_TYPE_ENT        logType,
    IN GT_CHAR_PTR              namePtr,
    IN void                   * fieldPtr,
    INOUT PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC     * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_FIELD_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_COUNTER_INTERRUPT_THRESH_STC *, valPtr);
    PRV_CPSS_LOG_UNUSED_MAC(inOutParamInfoPtr);
    PRV_CPSS_LOG_STC_NUMBER_MAC(valPtr, lsb);
    PRV_CPSS_LOG_STC_NUMBER_MAC(valPtr, middle);
    PRV_CPSS_LOG_STC_NUMBER_MAC(valPtr, msb);
    prvCpssLogStcLogEnd(contextLib, logType);
}


/********* parameters log functions *********/

void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_ACTION_STC_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_PARAM_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_ACTION_STC*, paramVal);
    prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_ACTION_STC_PTR(contextLib, logType, namePtr, paramVal, inOutParamInfoPtr);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_SET_PARAM_VAL_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT, paramVal);
    PRV_CPSS_LOG_ENUM_MAC(namePtr, paramVal, CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_SET_PARAM_VAL_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT*, paramVal);
    if (paramVal == NULL)
    {
        PRV_CPSS_LOG_AND_HISTORY_PARAM_MAC(contextLib, logType, "%s = NULL\n", namePtr);
        return;
    }
    PRV_CPSS_LOG_ENUM_MAC(namePtr, *paramVal, CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_SET_PARAM_VAL_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT, paramVal);
    PRV_CPSS_LOG_ENUM_MAC(namePtr, paramVal, CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_SET_PARAM_VAL_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT*, paramVal);
    if (paramVal == NULL)
    {
        PRV_CPSS_LOG_AND_HISTORY_PARAM_MAC(contextLib, logType, "%s = NULL\n", namePtr);
        return;
    }
    PRV_CPSS_LOG_ENUM_MAC(namePtr, *paramVal, CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_FIELD_NAME_STC_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_PARAM_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_NAME_STC*, paramVal);
    prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_FIELD_NAME_STC_PTR(contextLib, logType, namePtr, paramVal, inOutParamInfoPtr);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_PARAM_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC*, paramVal);
    prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR(contextLib, logType, namePtr, paramVal, inOutParamInfoPtr);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_GROUP_ATTRIBUTES_STC_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_PARAM_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_GROUP_ATTRIBUTES_STC*, paramVal);
    prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_GROUP_ATTRIBUTES_STC_PTR(contextLib, logType, namePtr, paramVal, inOutParamInfoPtr);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_INTERNAL_FIELD_VALUE_STC_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_PARAM_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_INTERNAL_FIELD_VALUE_STC*, paramVal);
    prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_INTERNAL_FIELD_VALUE_STC_PTR(contextLib, logType, namePtr, paramVal, inOutParamInfoPtr);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_KEY_ATTRIBUTES_STC_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_PARAM_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_KEY_ATTRIBUTES_STC*, paramVal);
    prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_KEY_ATTRIBUTES_STC_PTR(contextLib, logType, namePtr, paramVal, inOutParamInfoPtr);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_SET_PARAM_VAL_MAC(CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT, paramVal);
    PRV_CPSS_LOG_ENUM_MAC(namePtr, paramVal, CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_SET_PARAM_VAL_MAC(CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT*, paramVal);
    if (paramVal == NULL)
    {
        PRV_CPSS_LOG_AND_HISTORY_PARAM_MAC(contextLib, logType, "%s = NULL\n", namePtr);
        return;
    }
    PRV_CPSS_LOG_ENUM_MAC(namePtr, *paramVal, CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_RULE_ATTRIBUTES_STC_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_PARAM_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_RULE_ATTRIBUTES_STC*, paramVal);
    prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_RULE_ATTRIBUTES_STC_PTR(contextLib, logType, namePtr, paramVal, inOutParamInfoPtr);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_STC_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_PARAM_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_STC*, paramVal);
    prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_STC_PTR(contextLib, logType, namePtr, paramVal, inOutParamInfoPtr);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_STAGE_INTERFACE_STC_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_PARAM_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_STAGE_INTERFACE_STC*, paramVal);
    prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_STAGE_INTERFACE_STC_PTR(contextLib, logType, namePtr, paramVal, inOutParamInfoPtr);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_PARAM_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC*, paramVal);
    prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC_PTR(contextLib, logType, namePtr, paramVal, inOutParamInfoPtr);
}
void prvCpssLogParamFunc_CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC_PTR(
    IN CPSS_LOG_LIB_ENT            contextLib,
    IN CPSS_LOG_TYPE_ENT           logType,
    IN GT_CHAR_PTR                 namePtr,
    IN va_list                   * argsPtr,
    IN GT_BOOL                     skipLog,
    IN PRV_CPSS_LOG_PARAM_ENTRY_INFO_STC   * inOutParamInfoPtr
)
{
    PRV_CPSS_LOG_START_PARAM_STC_MAC(CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC*, paramVal);
    prvCpssLogParamFuncStc_CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC_PTR(contextLib, logType, namePtr, paramVal, inOutParamInfoPtr);
}


/********* API fields DB *********/

const PRV_CPSS_LOG_FUNC_PARAM_STC DX_INOUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR_sampleFieldsValueArr = {
     "sampleFieldsValueArr", PRV_CPSS_LOG_PARAM_INOUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_INOUT_GT_U32_PTR_numOfApplicStagesPtr = {
     "numOfApplicStagesPtr", PRV_CPSS_LOG_PARAM_INOUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_INOUT_GT_U32_PTR_numOfFieldsPtr = {
     "numOfFieldsPtr", PRV_CPSS_LOG_PARAM_INOUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_INOUT_GT_U32_PTR_numOfMatchedStagesPtr = {
     "numOfMatchedStagesPtr", PRV_CPSS_LOG_PARAM_INOUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_INOUT_GT_U32_PTR_numOfMuxStagesPtr = {
     "numOfMuxStagesPtr", PRV_CPSS_LOG_PARAM_INOUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_INOUT_GT_U32_PTR_numOfSampleFieldsPtr = {
     "numOfSampleFieldsPtr", PRV_CPSS_LOG_PARAM_INOUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_INOUT_GT_U32_PTR_numOfStagesPtr = {
     "numOfStagesPtr", PRV_CPSS_LOG_PARAM_INOUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_INOUT_GT_U32_PTR_numOfValidStagesPtr = {
     "numOfValidStagesPtr", PRV_CPSS_LOG_PARAM_INOUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_ACTION_STC_PTR_actionPtr = {
     "actionPtr", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_ACTION_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT_fieldMode = {
     "fieldMode", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_PTR_fieldsArr = {
     "fieldsArr", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_fieldName = {
     "fieldName", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_udfId = {
     "udfId", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_NAME_STC_PTR_fieldNamePtr = {
     "fieldNamePtr", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_NAME_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR_fieldsValueArr = {
     "fieldsValueArr", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_GROUP_ATTRIBUTES_STC_PTR_groupAttrPtr = {
     "groupAttrPtr", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_GROUP_ATTRIBUTES_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_KEY_ATTRIBUTES_STC_PTR_keyAttrPtr = {
     "keyAttrPtr", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_KEY_ATTRIBUTES_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_stagesArr = {
     "stagesArr", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_stageId = {
     "stageId", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_MAC(CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_udsId = {
     "udsId", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_MAC(CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_RULE_ATTRIBUTES_STC_PTR_ruleAttrPtr = {
     "ruleAttrPtr", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_RULE_ATTRIBUTES_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_STC_PTR_searchAttributePtr = {
     "searchAttributePtr", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_STAGE_INTERFACE_STC_PTR_interfaceAttrPtr = {
     "interfaceAttrPtr", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_STAGE_INTERFACE_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC_PTR_udfAttrPtr = {
     "udfAttrPtr", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC_PTR_udsAttrPtr = {
     "udsAttrPtr", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_GT_U32_actionId = {
     "actionId", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_GT_U32_groupId = {
     "groupId", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_GT_U32_keyId = {
     "keyId", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_GT_U32_managerId = {
     "managerId", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_GT_U32_numOfFields = {
     "numOfFields", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_IN_GT_U32_numOfStages = {
     "numOfStages", PRV_CPSS_LOG_PARAM_IN_E,  PRV_CPSS_LOG_FUNC_TYPE_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_ACTION_STC_PTR_actionPtr = {
     "actionPtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_ACTION_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT_PTR_fieldModePtr = {
     "fieldModePtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_PTR_fieldsArr = {
     "fieldsArr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_PTR_udfIdPtr = {
     "udfIdPtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_NAME_STC_PTR_fieldNamePtr = {
     "fieldNamePtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_NAME_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR_fieldsValueArr = {
     "fieldsValueArr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR_sampleFieldsValueArr = {
     "sampleFieldsValueArr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_INTERNAL_FIELD_VALUE_STC_PTR_sampleFieldsValueArr = {
     "sampleFieldsValueArr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_INTERNAL_FIELD_VALUE_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_KEY_ATTRIBUTES_STC_PTR_keyAttrPtr = {
     "keyAttrPtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_KEY_ATTRIBUTES_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_applicStagesListArr = {
     "applicStagesListArr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_matchedStagesArr = {
     "matchedStagesArr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_muxStagesListArr = {
     "muxStagesListArr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_stagesArr = {
     "stagesArr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_udsIdPtr = {
     "udsIdPtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_validStagesListArr = {
     "validStagesListArr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_RULE_ATTRIBUTES_STC_PTR_ruleAttrPtr = {
     "ruleAttrPtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_RULE_ATTRIBUTES_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_STAGE_INTERFACE_STC_PTR_interfaceAttrPtr = {
     "interfaceAttrPtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_STAGE_INTERFACE_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC_PTR_udfAttrPtr = {
     "udfAttrPtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC_PTR_udsAttrPtr = {
     "udsAttrPtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_GT_BOOL_PTR_deviceStatePtr = {
     "deviceStatePtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(GT_BOOL)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_GT_U32_PTR_actionIdPtr = {
     "actionIdPtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_GT_U32_PTR_keyIdPtr = {
     "keyIdPtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_GT_U32_PTR_numOfHitsPtr = {
     "numOfHitsPtr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(GT_U32)
};
const PRV_CPSS_LOG_FUNC_PARAM_STC DX_OUT_GT_U8_PTR_devicesArr = {
     "devicesArr", PRV_CPSS_LOG_PARAM_OUT_E,  PRV_CPSS_LOG_FUNC_TYPE_PTR_MAC(GT_U8)
};


/********* API prototypes DB *********/

const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerManagerCreate_PARAMS[] =  {
    &DX_IN_GT_U32_managerId
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerFieldStagesGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_fieldName,
    &DX_INOUT_GT_U32_PTR_numOfStagesPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_stagesArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerFieldSizeGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_fieldName,
    &DX_OUT_GT_U32_PTR_lengthPtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerUserDefinedFieldInfoGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_udfId,
    &DX_OUT_GT_BOOL_PTR_validPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC_PTR_udfAttrPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_NAME_STC_PTR_fieldNamePtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerMuxStageBind_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_stageId
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerStageFieldOverlappingFieldsGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_stageId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_fieldName,
    &DX_INOUT_GT_U32_PTR_numOfFieldsPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_PTR_fieldsArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerStageFieldsGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_stageId,
    &DX_INOUT_GT_U32_PTR_numOfFieldsPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_PTR_fieldsArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerMuxStagesGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_stageId,
    &DX_INOUT_GT_U32_PTR_numOfMuxStagesPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_muxStagesListArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerUserDefinedStageInfoGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_udsId,
    &DX_OUT_GT_BOOL_PTR_validPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC_PTR_udsAttrPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_STAGE_INTERFACE_STC_PTR_interfaceAttrPtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerUserDefinedFieldDelete_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC_PTR_udfAttrPtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerUserDefinedFieldAdd_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC_PTR_udfAttrPtr,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_NAME_STC_PTR_fieldNamePtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_PTR_udfIdPtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerUserDefinedFieldGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_UDF_ATTRIBUTES_STC_PTR_udfAttrPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_PTR_udfIdPtr,
    &DX_OUT_GT_BOOL_PTR_validPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_NAME_STC_PTR_fieldNamePtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerUserDefinedStageDelete_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC_PTR_udsAttrPtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerUserDefinedStageAdd_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC_PTR_udsAttrPtr,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_STAGE_INTERFACE_STC_PTR_interfaceAttrPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_udsIdPtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerUserDefinedStageGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_UDS_ATTRIBUTES_STC_PTR_udsAttrPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_udsIdPtr,
    &DX_OUT_GT_BOOL_PTR_validPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_STAGE_INTERFACE_STC_PTR_interfaceAttrPtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerManagerEnableSet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_BOOL_enable
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerActionDelete_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_actionId
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerActionCreate_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_actionId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_ACTION_STC_PTR_actionPtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerActionSamplingEnableSet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_actionId,
    &DX_IN_GT_BOOL_enable
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerActionGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_actionId,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_ACTION_STC_PTR_actionPtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerGroupDelete_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_groupId
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerGroupCreate_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_groupId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_GROUP_ATTRIBUTES_STC_PTR_groupAttrPtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerGroupActivateEnableSet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_groupId,
    &DX_IN_GT_BOOL_enable
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerLogicalKeyDelete_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_keyId
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerLogicalKeyCreate_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_keyId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_KEY_ATTRIBUTES_STC_PTR_keyAttrPtr,
    &DX_IN_GT_U32_numOfStages,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_stagesArr,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT_fieldMode,
    &DX_IN_GT_U32_numOfFields,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_PTR_fieldsArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerLogicalKeyFieldsPerStageGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_keyId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_stageId,
    &DX_INOUT_GT_U32_PTR_numOfFieldsPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_PTR_fieldsArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerGroupRuleAdd_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_keyId,
    &DX_IN_GT_U32_groupId,
    &DX_IN_GT_U32_ruleId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_RULE_ATTRIBUTES_STC_PTR_ruleAttrPtr,
    &DX_IN_GT_U32_numOfFields,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR_fieldsValueArr,
    &DX_IN_GT_U32_actionId
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerLogicalKeyFieldsAdd_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_keyId,
    &DX_IN_GT_U32_numOfFields,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_ENT_PTR_fieldsArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerLogicalKeyStagesGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_keyId,
    &DX_INOUT_GT_U32_PTR_numOfStagesPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_stagesArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerLogicalKeyInfoGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_keyId,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_KEY_ATTRIBUTES_STC_PTR_keyAttrPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_ASSIGNMENT_MODE_ENT_PTR_fieldModePtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerGroupRuleDelete_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_ruleId,
    &DX_IN_GT_U32_groupId
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerRuleMatchDataAllFieldsByAttributeGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_ruleId,
    &DX_IN_GT_U32_groupId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_stageId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_STC_PTR_searchAttributePtr,
    &DX_OUT_GT_U32_PTR_numOfHitsPtr,
    &DX_INOUT_GT_U32_PTR_numOfSampleFieldsPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR_sampleFieldsValueArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerStageMatchDataAllInternalFieldsByAttributesGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_ruleId,
    &DX_IN_GT_U32_groupId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_stageId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_SEARCH_ATTRIBUTE_STC_PTR_searchAttributePtr,
    &DX_OUT_GT_U32_PTR_numOfHitsPtr,
    &DX_INOUT_GT_U32_PTR_numOfSampleFieldsPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_INTERNAL_FIELD_VALUE_STC_PTR_sampleFieldsValueArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerStageMatchDataGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_ruleId,
    &DX_IN_GT_U32_groupId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_stageId,
    &DX_OUT_GT_U32_PTR_numOfHitsPtr,
    &DX_INOUT_GT_U32_PTR_numOfSampleFieldsPtr,
    &DX_INOUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR_sampleFieldsValueArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerStageMatchDataAllFieldsGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_ruleId,
    &DX_IN_GT_U32_groupId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_stageId,
    &DX_OUT_GT_U32_PTR_numOfHitsPtr,
    &DX_INOUT_GT_U32_PTR_numOfSampleFieldsPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR_sampleFieldsValueArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerStageMatchDataAllInternalFieldsGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_ruleId,
    &DX_IN_GT_U32_groupId,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_stageId,
    &DX_OUT_GT_U32_PTR_numOfHitsPtr,
    &DX_INOUT_GT_U32_PTR_numOfSampleFieldsPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_INTERNAL_FIELD_VALUE_STC_PTR_sampleFieldsValueArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerGroupRuleUpdate_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_ruleId,
    &DX_IN_GT_U32_groupId,
    &DX_IN_GT_U32_numOfFields,
    &DX_IN_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR_fieldsValueArr,
    &DX_IN_GT_U32_actionId
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerRuleMatchStagesGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_ruleId,
    &DX_IN_GT_U32_groupId,
    &DX_INOUT_GT_U32_PTR_numOfMatchedStagesPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_matchedStagesArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerGroupRuleGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U32_ruleId,
    &DX_IN_GT_U32_groupId,
    &DX_OUT_GT_U32_PTR_keyIdPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_RULE_ATTRIBUTES_STC_PTR_ruleAttrPtr,
    &DX_INOUT_GT_U32_PTR_numOfFieldsPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_FIELD_VALUE_STC_PTR_fieldsValueArr,
    &DX_OUT_GT_U32_PTR_actionIdPtr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerManagerDeviceAdd_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_IN_GT_U8_devNum
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerStagesGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_INOUT_GT_U32_PTR_numOfApplicStagesPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_applicStagesListArr,
    &DX_INOUT_GT_U32_PTR_numOfValidStagesPtr,
    &DX_OUT_CPSS_DXCH_PACKET_ANALYZER_LOOKUP_STAGES_ENT_PTR_validStagesListArr
};
const PRV_CPSS_LOG_FUNC_PARAM_STC * const cpssDxChPacketAnalyzerManagerDevicesGet_PARAMS[] =  {
    &DX_IN_GT_U32_managerId,
    &DX_OUT_GT_BOOL_PTR_deviceStatePtr,
    &DX_INOUT_GT_U32_PTR_numOfDevicesPtr,
    &DX_OUT_GT_U8_PTR_devicesArr
};


/********* lib API DB *********/

static const PRV_CPSS_LOG_FUNC_ENTRY_STC prvCpssDxChPacketAnalyzerLogLibDb[] = {
    {"cpssDxChPacketAnalyzerManagerCreate", 1, cpssDxChPacketAnalyzerManagerCreate_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerManagerDelete", 1, cpssDxChPacketAnalyzerManagerCreate_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerManagerDeviceAdd", 2, cpssDxChPacketAnalyzerManagerDeviceAdd_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerManagerDeviceRemove", 2, cpssDxChPacketAnalyzerManagerDeviceAdd_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerManagerEnableSet", 2, cpssDxChPacketAnalyzerManagerEnableSet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerManagerDevicesGet", 4, cpssDxChPacketAnalyzerManagerDevicesGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerManagerResetToDefaults", 1, cpssDxChPacketAnalyzerManagerCreate_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerFieldSizeGet", 3, cpssDxChPacketAnalyzerFieldSizeGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerLogicalKeyCreate", 8, cpssDxChPacketAnalyzerLogicalKeyCreate_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerLogicalKeyFieldsAdd", 4, cpssDxChPacketAnalyzerLogicalKeyFieldsAdd_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerLogicalKeyFieldsRemove", 4, cpssDxChPacketAnalyzerLogicalKeyFieldsAdd_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerLogicalKeyDelete", 2, cpssDxChPacketAnalyzerLogicalKeyDelete_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerLogicalKeyInfoGet", 4, cpssDxChPacketAnalyzerLogicalKeyInfoGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerLogicalKeyStagesGet", 4, cpssDxChPacketAnalyzerLogicalKeyStagesGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerLogicalKeyFieldsPerStageGet", 5, cpssDxChPacketAnalyzerLogicalKeyFieldsPerStageGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerStagesGet", 5, cpssDxChPacketAnalyzerStagesGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerMuxStagesGet", 4, cpssDxChPacketAnalyzerMuxStagesGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerGroupCreate", 3, cpssDxChPacketAnalyzerGroupCreate_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerGroupDelete", 2, cpssDxChPacketAnalyzerGroupDelete_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerGroupRuleAdd", 8, cpssDxChPacketAnalyzerGroupRuleAdd_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerGroupRuleUpdate", 6, cpssDxChPacketAnalyzerGroupRuleUpdate_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerGroupRuleDelete", 3, cpssDxChPacketAnalyzerGroupRuleDelete_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerGroupRuleGet", 8, cpssDxChPacketAnalyzerGroupRuleGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerActionCreate", 3, cpssDxChPacketAnalyzerActionCreate_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerActionUpdate", 3, cpssDxChPacketAnalyzerActionCreate_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerActionDelete", 2, cpssDxChPacketAnalyzerActionDelete_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerActionGet", 3, cpssDxChPacketAnalyzerActionGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerSampledDataCountersClear", 3, cpssDxChPacketAnalyzerGroupRuleDelete_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerActionSamplingEnableSet", 3, cpssDxChPacketAnalyzerActionSamplingEnableSet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerGroupActivateEnableSet", 3, cpssDxChPacketAnalyzerGroupActivateEnableSet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerRuleMatchStagesGet", 5, cpssDxChPacketAnalyzerRuleMatchStagesGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerStageMatchDataGet", 7, cpssDxChPacketAnalyzerStageMatchDataGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerStageMatchDataAllFieldsGet", 7, cpssDxChPacketAnalyzerStageMatchDataAllFieldsGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerStageMatchDataAllInternalFieldsGet", 7, cpssDxChPacketAnalyzerStageMatchDataAllInternalFieldsGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerStageMatchDataAllInternalFieldsByAttributesGet", 8, cpssDxChPacketAnalyzerStageMatchDataAllInternalFieldsByAttributesGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerStageFieldsGet", 4, cpssDxChPacketAnalyzerStageFieldsGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerFieldStagesGet", 4, cpssDxChPacketAnalyzerFieldStagesGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerMuxStageBind", 2, cpssDxChPacketAnalyzerMuxStageBind_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerMuxStageUnbind", 2, cpssDxChPacketAnalyzerMuxStageBind_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerUserDefinedFieldAdd", 4, cpssDxChPacketAnalyzerUserDefinedFieldAdd_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerUserDefinedFieldDelete", 2, cpssDxChPacketAnalyzerUserDefinedFieldDelete_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerUserDefinedFieldGet", 5, cpssDxChPacketAnalyzerUserDefinedFieldGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerUserDefinedFieldInfoGet", 5, cpssDxChPacketAnalyzerUserDefinedFieldInfoGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerUserDefinedStageAdd", 4, cpssDxChPacketAnalyzerUserDefinedStageAdd_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerUserDefinedStageDelete", 2, cpssDxChPacketAnalyzerUserDefinedStageDelete_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerUserDefinedStageGet", 5, cpssDxChPacketAnalyzerUserDefinedStageGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerUserDefinedStageInfoGet", 5, cpssDxChPacketAnalyzerUserDefinedStageInfoGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerRuleMatchDataAllFieldsByAttributeGet", 8, cpssDxChPacketAnalyzerRuleMatchDataAllFieldsByAttributeGet_PARAMS, NULL},
    {"cpssDxChPacketAnalyzerStageFieldOverlappingFieldsGet", 5, cpssDxChPacketAnalyzerStageFieldOverlappingFieldsGet_PARAMS, NULL},
};

/******** DB Access Function ********/
void prvCpssLogParamLibDbGet_DX_CPSS_LOG_LIB_PACKET_ANALYZER(
    OUT const PRV_CPSS_LOG_FUNC_ENTRY_STC ** logFuncDbPtrPtr,
    OUT GT_U32 * logFuncDbSizePtr
)
{
    *logFuncDbPtrPtr = prvCpssDxChPacketAnalyzerLogLibDb;
    *logFuncDbSizePtr = sizeof(prvCpssDxChPacketAnalyzerLogLibDb) / sizeof(PRV_CPSS_LOG_FUNC_ENTRY_STC);
}

