/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,       *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
* wraplCpssDxChHwAccees.c
*
* DESCRIPTION:
*       HW access low level functions wrapper
*
* DEPENDENCIES:
*
* COMMENTS:
*
* FILE REVISION NUMBER:
*       $Revision: 14 $
*******************************************************************************/

#include <cpss/common/cpssTypes.h>
#include <cpss/common/config/cpssGenCfg.h>
#include <cpss/generic/version/cpssGenStream.h>
#include <generic/private/prvWraplGeneral.h>
#include <cpss/dxCh/dxChxGen/config/private/prvCpssDxChInfo.h>
#include <extUtils/luaCLI/luaCLIEngine_genWrapper.h>
#include <cpss/common/private/globalShared/prvCpssGlobalDb.h>
#include <cpss/common/private/globalShared/prvCpssGlobalDbInterface.h>

#define VOC_ENUM_MAC(enum_val) {#enum_val, enum_val}
#define VOC_END_MAC {NULL, 0}


typedef struct
{
    char* name;
    GT_U32 val;
} VOC_STC;

static VOC_STC tabNameVoc[] =
{
      VOC_ENUM_MAC(CPSS_DXCH_TABLE_VLAN_PORT_PROTOCOL_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_PORT_VLAN_QOS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_TRUNK_MEMBERS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_STATISTICAL_RATE_LIMIT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_CPU_CODE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_PCL_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_QOS_PROFILE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_REMARKING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_STG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_VLAN_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_MULTICAST_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_ROUTE_HA_MAC_SA_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_ROUTE_HA_ARP_DA_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_FDB_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_POLICER_E)
    , VOC_ENUM_MAC(CPSS_DXCH_TABLE_POLICER_COUNTERS_E)
    , VOC_ENUM_MAC(CPSS_DXCH2_TABLE_EGRESS_PCL_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH2_TABLE_TUNNEL_START_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH2_TABLE_QOS_PROFILE_TO_ROUTE_BLOCK_E)
    , VOC_ENUM_MAC(CPSS_DXCH2_TABLE_ROUTE_ACCESS_MATRIX_E)
    , VOC_ENUM_MAC(CPSS_DXCH2_LTT_TT_ACTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH2_UC_MC_ROUTE_NEXT_HOP_E)
    , VOC_ENUM_MAC(CPSS_DXCH2_ROUTE_NEXT_HOP_AGE_E)
    , VOC_ENUM_MAC(CPSS_DXCH3_TABLE_MAC2ME_E)
    , VOC_ENUM_MAC(CPSS_DXCH3_TABLE_INGRESS_VLAN_TRANSLATION_E)
    , VOC_ENUM_MAC(CPSS_DXCH3_TABLE_EGRESS_VLAN_TRANSLATION_E)
    , VOC_ENUM_MAC(CPSS_DXCH3_TABLE_VRF_ID_E)
    , VOC_ENUM_MAC(CPSS_DXCH3_LTT_TT_ACTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH_XCAT_TABLE_INGRESS_PCL_LOOKUP1_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_XCAT_TABLE_INGRESS_PCL_UDB_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_XCAT_TABLE_LOGICAL_TARGET_MAPPING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_XCAT_TABLE_BCN_PROFILES_E)
    , VOC_ENUM_MAC(CPSS_DXCH_XCAT_TABLE_EGRESS_POLICER_REMARKING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_XCAT_TABLE_EQ_VLAN_MAPPING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_XCAT_TABLE_EQ_LP_EGRESS_VLAN_MEMBER_E)
    , VOC_ENUM_MAC(CPSS_DXCH_XCAT_TABLE_MLL_L2MLL_VIDX_ENABLE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_XCAT_TABLE_MLL_L2MLL_POINTER_MAPPING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_XCAT2_TABLE_INGRESS_PCL_LOOKUP01_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_TRUNK_HASH_MASK_CRC_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_VLAN_INGRESS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_VLAN_EGRESS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_STG_INGRESS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_STG_EGRESS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_PORT_ISOLATION_L2_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_PORT_ISOLATION_L3_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_TXQ_SOURCE_ID_MEMBERS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_TXQ_NON_TRUNK_MEMBERS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_TXQ_DESIGNATED_PORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_TXQ_EGRESS_STC_E)
    , VOC_ENUM_MAC(CPSS_DXCH_LION_TABLE_ROUTER_VLAN_URPF_STC_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TTI_PHYSICAL_PORT_ATTRIBUTE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_PRE_TTI_LOOKUP_INGRESS_EPORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_POST_TTI_LOOKUP_INGRESS_EPORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_BRIDGE_INGRESS_EPORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_BRIDGE_INGRESS_EPORT_LEARN_PRIO_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_BRIDGE_SOURCE_TRUNK_ATTRIBUTE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_BRIDGE_PHYSICAL_PORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_BRIDGE_PHYSICAL_PORT_RATE_LIMIT_COUNTERS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EQ_INGRESS_EPORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EQ_INGRESS_STC_PHYSICAL_PORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EQ_INGRESS_MIRROR_PHYSICAL_PORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EQ_TRUNK_LTT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EQ_L2_ECMP_LTT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EQ_L2_ECMP_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EQ_EPORT_TO_PHYSICAL_PORT_TARGET_MAPPING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EQ_TO_CPU_RATE_LIMITER_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EQ_TX_PROTECTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EQ_EPORT_TO_LOC_MAPPING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EQ_PROTECTION_LOC_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_LPM_MEM_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_IPV4_VRF_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_IPV6_VRF_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_FCOE_VRF_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_ECMP_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_EFT_FAST_STACK_FAILOVER_SECONDARY_TARGET_PORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_EGRESS_EPORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_EGRESS_VLAN_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_TARGET_PORT_MAPPER_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_CPU_CODE_TO_LOOPBACK_MAPPER_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_FWD_FROM_CPU_TO_LOOPBACK_MAPPER_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_EGRESS_EPORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_DEVICE_MAP_TABLE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_HA_EGRESS_EPORT_1_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_HA_EGRESS_EPORT_2_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_HA_PHYSICAL_PORT_1_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_HA_PHYSICAL_PORT_2_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_HA_QOS_PROFILE_TO_EXP_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_HA_EPCL_UDB_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_HA_PTP_DOMAIN_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_HA_GENERIC_TS_PROFILE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_HA_GLOBAL_MAC_SA_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_IP_MLL_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_L2_MLL_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_L2_MLL_LTT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_ADJACENCY_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_E_ATTRIBUTES_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_REMARKING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_HIERARCHICAL_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_METERING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_E_ATTRIBUTES_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_REMARKING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_METERING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_POLICER_E_ATTRIBUTES_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_POLICER_METERING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_IPVX_INGRESS_EPORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_IPVX_EVLAN_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_IPVX_ROUTER_NEXTHOP_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_IPVX_ROUTER_NEXTHOP_AGE_BITS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_IPVX_ROUTER_ACCESS_MATRIX_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_IPVX_ROUTER_QOS_PROFILE_OFFSETS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_KEEPALIVE_AGING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_MEG_EXCEPTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_SOURCE_INTERFACE_EXCEPTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_INVALID_KEEPALIVE_HASH_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_KEEPALIVE_EXCESS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_EXCEPTION_SUMMARY_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_RDI_STATUS_CHANGE_EXCEPTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_TX_PERIOD_EXCEPTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_OPCODE_PACKET_COMMAND_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_KEEPALIVE_AGING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_MEG_EXCEPTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_SOURCE_INTERFACE_EXCEPTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_INVALID_KEEPALIVE_HASH_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_KEEPALIVE_EXCESS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_EXCEPTION_SUMMARY_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_RDI_STATUS_CHANGE_EXCEPTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_TX_PERIOD_EXCEPTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_OPCODE_PACKET_COMMAND_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_OAM_LM_OFFSET_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TTI_QOS_MAP_DSCP_TO_QOS_PROFILE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TTI_QOS_MAP_UP_CFI_TO_QOS_PROFILE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TTI_QOS_MAP_EXP_TO_QOS_PROFILE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TTI_QOS_MAP_DSCP_TO_DSCP_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TTI_UDB_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TTI_PTP_COMMAND_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_IPCL0_UDB_SELECT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_IPCL1_UDB_SELECT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_IPCL2_UDB_SELECT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TCAM_PCL_TTI_ACTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_ERMRK_TIMESTAMP_CFG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_ERMRK_PTP_LOCAL_ACTION_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_ERMRK_PTP_TARGET_PORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_ERMRK_PTP_SOURCE_PORT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_ERMRK_QOS_DSCP_MAP_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_ERMRK_QOS_TC_DP_MAP_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TCAM_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_BRIDGE_PORT_MEMBERS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_INGRESS_SPAN_STATE_GROUP_INDEX_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_VLAN_ATTRIBUTES_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_VLAN_SPANNING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_VLAN_MAPPER_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_NON_TRUNK_MEMBERS2_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_EPORT_FILTER_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_EPCL_UDB_SELECT_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_BMA_PORT_MAPPING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_BMA_MULTICAST_COUNTERS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TAIL_DROP_MAX_QUEUE_LIMITS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TAIL_DROP_EQ_QUEUE_LIMITS_DP0_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TAIL_DROP_DQ_QUEUE_BUF_LIMITS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TAIL_DROP_DQ_QUEUE_DESC_LIMITS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TAIL_DROP_EQ_QUEUE_LIMITS_DP1_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TAIL_DROP_EQ_QUEUE_LIMITS_DP2_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TAIL_DROP_COUNTERS_Q_MAIN_BUFF_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TAIL_DROP_COUNTERS_Q_MAIN_MC_BUFF_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TXQ_LINK_LIST_COUNTERS_Q_MAIN_DESC_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_PFC_MODE_PROFILE_TC_XOFF_THRESHOLDS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_PFC_MODE_PROFILE_TC_XON_THRESHOLDS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_PFC_LLFC_COUNTERS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_DROP_DROP_MASKING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_DROP_QUEUE_PROFILE_ID_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_QMAP_CPU_CODE_TO_TC_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_QMAP_TARGET_DEV_TO_INDEX_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_QMAP_POLICING_ENABLE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_QMAP_QUEUE_ID_SELECTOR_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_INGR_GLUE_L1_PKT_LEN_OFFSET_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_EGR_GLUE_AGING_QUEUE_PROFILE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_EGR_GLUE_AGING_PROFILE_THESHOLDS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_EGR_GLUE_TARGET_INTERFACE_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_FCU_ETH_DMA_TO_TM_PORT_MAPPING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_FCU_ILK_DMA_TO_TM_PORT_MAPPING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_FCU_TC_PORT_TO_CNODE_PORT_MAPPING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_FCU_PORT_INGRESS_TIMERS_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_FCU_INGRESS_TIMERS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_TM_FCU_PORT_TO_PHYSICAL_PORT_MAPPING_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_TABLE_CN_SAMPLE_INTERVALS_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_15_TABLE_INGRESS_POLICER_0_METERING_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_15_TABLE_INGRESS_POLICER_1_METERING_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_15_TABLE_EGRESS_POLICER_METERING_CONFIG_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_15_TABLE_INGRESS_POLICER_0_METERING_CONFORM_SIGN_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_15_TABLE_INGRESS_POLICER_1_METERING_CONFORM_SIGN_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_15_TABLE_EGRESS_POLICER_METERING_CONFORM_SIGN_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_TABLE_EGF_QAG_PORT_TARGET_ATTRIBUTES_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_TABLE_TTI_PHYSICAL_PORT_ATTRIBUTE_2_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_TABLE_EQ_TX_PROTECTION_LOC_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_TABLE_EGF_QAG_TC_DP_MAPPER_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_1_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_2_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_3_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_4_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_5_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_LAST_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_1_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_2_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_3_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_4_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_5_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_LAST_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_1_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_2_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_3_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_4_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_5_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_LAST_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_EQ_INGRESS_STC_PHYSICAL_PORT_PIPE_1_E)
    , VOC_ENUM_MAC(CPSS_DXCH_SIP5_20_TABLE_LPM_MEM_PIPE_1_E)
    , VOC_END_MAC
}; /*tabNameVoc*/

/* if not found returns 0xFFFFFFFF */
static GT_U32 searchInVoc(VOC_STC *voc, char* name)
{
    VOC_STC *p;
    for (p = voc; (p->name != NULL); p++)
    {
        if (cpssOsStrCmp(p->name, name) == 0) return p->val;
    }
    return 0xFFFFFFFF;
}

/*******************************************************************************
* wrlPrvCpssDxChWriteTableEntryField
*
* DESCRIPTION:
*       Wrapps prvCpssDxChWriteTableEntryField, does not support special values.
*
* APPLICABLE DEVICES:
*       all devices.
*
* NOT APPLICABLE DEVICES:
*       none
*
* INPUTS:
*       L                     - lua state
*
* OUTPUTS:
*       Return code of called API.
* RETURNS:
*       1;
*
* COMMENTS:
*
*******************************************************************************/
int wrlPrvCpssDxChWriteTableEntryField
(
    IN lua_State *L
)
{
    GT_STATUS               rc;
    GT_U8                   devNum;
    char*                   tableName;
    CPSS_DXCH_TABLE_ENT tableType;
    GT_U32                  entryIndex;
    GT_U32                  fieldWordNum;
    GT_U32                  fieldOffset;
    GT_U32                  fieldLength;
    GT_U32                  fieldValue;

    rc = GT_OK;
    tableName = "******";
    PARAM_NUMBER(rc, devNum, 1, GT_U8);
    if (lua_type(L, 2) != LUA_TSTRING)
        rc = GT_BAD_PARAM;
    else
        tableName = (char*)lua_tostring(L, 2);
    PARAM_NUMBER(rc, entryIndex,   3, GT_U32);
    PARAM_NUMBER(rc, fieldWordNum, 4, GT_U32);
    PARAM_NUMBER(rc, fieldOffset , 5, GT_U32);
    PARAM_NUMBER(rc, fieldLength , 6, GT_U32);
    PARAM_NUMBER(rc, fieldValue,   7, GT_U32);

    if (rc != GT_OK)
    {
        lua_pushinteger(L, rc);
        return 1;
    }

    tableType = searchInVoc(tabNameVoc, tableName);
    if (tableType == 0xFFFFFFFF)
    {
        rc = GT_BAD_PARAM;
    }
    else
    {
        rc = prvCpssDxChWriteTableEntryField(
            devNum, tableType, entryIndex,
            fieldWordNum, fieldOffset, fieldLength, fieldValue);
    }

    lua_pushinteger(L, rc);
    return 1;
}
