/*******************************************************************************
Copyright (C) 2014-2016, Marvell International Ltd. and its affiliates
If you received this File from Marvell and you have entered into a commercial
license agreement (a "Commercial License") with Marvell, the File is licensed
to you under the terms of the applicable Commercial License.
*******************************************************************************/

/********************************************************************
This file is a placeholder of AVAGO defined file.
********************************************************************/

#ifndef MV_HWS_AVAGO_SERDES_H
#define MV_HWS_AVAGO_SERDES_H

/* Global variables */
#define aapl_default_server                         mvHws_aapl_default_server
#define aapl_default_port                           mvHws_aapl_default_port
#define aapl_sigint_detected                        mvHws_aapl_sigint_detected
#define q03                                         mvHws_q03
#define q04                                         mvHws_q04
#define q05                                         mvHws_q05
#define q06                                         mvHws_q06
#define q10                                         mvHws_q10
#define q12                                         mvHws_q12
#define q15                                         mvHws_q15
#define q17                                         mvHws_q17
#define avago_chip_id                               mvHws_avago_chip_id

/* Function definitions */
/* Aacs server */
#define avago_aacs_server                           mvHws_avago_aacs_server
#define avago_aacs_server_options                   mvHws_avago_aacs_server_options
#define avago_aacs_process_cmd                      mvHws_avago_aacs_process_cmd
#define aapl_telnet_thread                          mvHws_aapl_telnet_thread
#define ate_vec_command                             mvHws_ate_vec_command

/* Aapl core */
#define aapl_construct                              mvHws_aapl_construct
#define aapl_destruct                               mvHws_aapl_destruct
#define aapl_init                                   mvHws_aapl_init
#define avago_addr_init                             mvHws_avago_addr_init
#define avago_addr_init_broadcast                   mvHws_avago_addr_init_broadcast
#define aapl_get_ip_info                            mvHws_aapl_get_ip_info
#define aapl_get_return_code                        mvHws_aapl_get_return_code
#define aapl_get_firmware_rev                       mvHws_aapl_get_firmware_rev
#define aapl_get_firmware_build                     mvHws_aapl_get_firmware_build
#define aapl_get_chips                              mvHws_aapl_get_chips
#define aapl_get_max_sbus_addr                      mvHws_aapl_get_max_sbus_addr
#define aapl_get_jtag_idcode                        mvHws_aapl_get_jtag_idcode
#define aapl_get_chip_name                          mvHws_aapl_get_chip_name
#define aapl_get_chip_rev_str                       mvHws_aapl_get_chip_rev_str
#define aapl_get_lsb_rev                            mvHws_aapl_get_lsb_rev
#define aapl_get_ip_rev                             mvHws_aapl_get_ip_rev
#define aapl_set_ip_type                            mvHws_aapl_set_ip_type
#define aapl_get_ip_type                            mvHws_aapl_get_ip_type
#define aapl_bind_set                               mvHws_aapl_bind_set
#define aapl_bind_get                               mvHws_aapl_bind_get
#define aapl_get_process_id                         mvHws_aapl_get_process_id
#define aapl_get_process_id_str                     mvHws_aapl_get_process_id_str
#define aapl_get_spico_running_flag                 mvHws_aapl_get_spico_running_flag
#define aapl_set_spico_running_flag                 mvHws_aapl_set_spico_running_flag
#define aapl_send                                   mvHws_aapl_send
#define aapl_recv                                   mvHws_aapl_recv
#define aapl_check_capabilities                     mvHws_aapl_check_capabilities
#define aapl_set_chip                               mvHws_aapl_set_chip
#define aapl_set_chip_by_addr                       mvHws_aapl_set_chip_by_addr
#define aapl_check_sdrev                            mvHws_aapl_check_sdrev
#define aapl_get_sdrev                              mvHws_aapl_get_sdrev
#define aapl_get_interrupt_rev                      mvHws_aapl_get_interrupt_rev
#define aapl_get_addr_list                          mvHws_aapl_get_addr_list
#define avago_aacs_flush                            mvHws_avago_aacs_flush
#define avago_aacs_open_fn                          mvHws_avago_aacs_open_fn
#define avago_aacs_close_fn                         mvHws_avago_aacs_close_fn
#if !defined(MV_HWS_REDUCED_BUILD_EXT_CM3)
#define avago_aacs_send_command                     mvHws_avago_aacs_send_command
#define avago_aacs_send_command_options             mvHws_avago_aacs_send_command_options
#define avago_aacs_send_command_int                 mvHws_avago_aacs_send_command_int
#define avago_aacs_send_command_options_int         mvHws_avago_aacs_send_command_options_int
#endif
#define aapl_aacs_sbus_fn                           mvHws_aapl_aacs_sbus_fn
#define aapl_register_sbus_fn                       mvHws_aapl_register_sbus_fn
#define aapl_register_mdio_fn                       mvHws_aapl_register_mdio_fn
#define aapl_register_i2c_fn                        mvHws_aapl_register_i2c_fn
#define aapl_register_jtag_fn                       mvHws_aapl_register_jtag_fn
#define aapl_register_bit_banged_jtag_fn            mvHws_aapl_register_bit_banged_jtag_fn
#define aapl_register_spico_int_fn                  mvHws_aapl_register_spico_int_fn
#define aapl_register_parallel_serdes_int_fn        mvHws_aapl_register_parallel_serdes_int_fn
#define aapl_register_jtag_idcode_fn                mvHws_aapl_register_jtag_idcode_fn
#define aapl_register_user_supplied_functions       mvHws_aapl_register_user_supplied_functions
#define avago_get_tap_gen                           mvHws_avago_get_tap_gen
#define aapl_connect                                mvHws_aapl_connect
#define aapl_close_connection                       mvHws_aapl_close_connection
#define aapl_close_connection2                      mvHws_aapl_close_connection2
#define aapl_reconnect                              mvHws_aapl_reconnect
#define aapl_connection_status                      mvHws_aapl_connection_status
#define aapl_is_i2c_communication_method            mvHws_aapl_is_i2c_communication_method
#define aapl_is_mdio_communication_method           mvHws_aapl_is_mdio_communication_method
#define aapl_is_sbus_communication_method           mvHws_aapl_is_sbus_communication_method
#define aapl_is_aacs_communication_method           mvHws_aapl_is_aacs_communication_method
#define aapl_is_jtag_communication_method           mvHws_aapl_is_jtag_communication_method
#define aapl_is_octal_p1                            mvHws_aapl_is_octal_p1
#define avago_system_chip_setup                     mvHws_avago_system_chip_setup
#define aapl_set_async_cancel_flag                  mvHws_aapl_set_async_cancel_flag
#define aapl_get_async_cancel_flag                  mvHws_aapl_get_async_cancel_flag
#define aapl_tcp_strerr                             mvHws_aapl_tcp_strerr
#define avago_jtag                                  mvHws_avago_jtag
#define avago_jtag_options                          mvHws_avago_jtag_options
#define avago_jtag_rd_len                           mvHws_avago_jtag_rd_len
#define avago_jtag_rd                               mvHws_avago_jtag_rd
#define avago_jtag_set_bit                          mvHws_avago_jtag_set_bit
#define avago_jtag_scan                             mvHws_avago_jtag_scan
#define avago_jtag_scan_options                     mvHws_avago_jtag_scan_options
#define avago_jtag_reset                            mvHws_avago_jtag_reset
#define aapl_check_ip_type                          mvHws_aapl_check_ip_type
#define aapl_check_ip_type_exists                   mvHws_aapl_check_ip_type_exists
#define aapl_check_process                          mvHws_aapl_check_process
#define aapl_check_firmware_rev                     mvHws_aapl_check_firmware_rev
#define aapl_check_firmware_build                   mvHws_aapl_check_firmware_build
#define aapl_check_broadcast_address                mvHws_aapl_check_broadcast_address
#define avago_struct_to_addr                        mvHws_avago_struct_to_addr
#define avago_addr_to_struct                        mvHws_avago_addr_to_struct
#define avago_make_sbus_controller_addr             mvHws_avago_make_sbus_controller_addr
#define avago_make_sbus_master_addr                 mvHws_avago_make_sbus_master_addr
#define avago_make_sbus_controller_addr             mvHws_avago_make_sbus_controller_addr
#define avago_make_serdes_broadcast_addr            mvHws_avago_make_serdes_broadcast_addr
#define avago_make_sbus_addr                        mvHws_avago_make_sbus_addr
#define avago_make_sbus_lane_addr                   mvHws_avago_make_sbus_lane_addr
#define aapl_broadcast_first                        mvHws_aapl_broadcast_first
#define aapl_broadcast_next                         mvHws_aapl_broadcast_next
#define aapl_str_to_addr                            mvHws_aapl_str_to_addr
#define avago_make_addr3                            mvHws_avago_make_addr3
#define avago_make_addr4                            mvHws_avago_make_addr4
#define avago_addr_new                              mvHws_avago_addr_new
#define avago_addr_new_from_struct                  mvHws_avago_addr_new_from_struct
#define avago_addr_delete                           mvHws_avago_addr_delete
#define avago_group_expand_broadcast                mvHws_avago_group_expand_broadcast
#define avago_group_setup                           mvHws_avago_group_setup
#define avago_group_clear                           mvHws_avago_group_clear
#define avago_group_get_next                        mvHws_avago_group_get_next
#define avago_group_get_addr                        mvHws_avago_group_get_addr
#define avago_group_debug                           mvHws_avago_group_debug
#define aapl_sigint_check                           mvHws_aapl_sigint_check
#define aapl_register_ate_vec_fn                    mvHws_aapl_register_ate_vec_fn
#define aapl_register_hard_sbus_reset_fn            mvHws_aapl_register_hard_sbus_reset_fn

/* Aapl library */
#define ms_sleep                                    mvHws_ms_sleept
#define aapl_hex_2_bin                              mvHws_aapl_hex_2_bint
#define aapl_strcasecmp                             mvHws_aapl_strcasecmpt
#define aapl_strncasecmp                            mvHws_aapl_strncasecmpt
#define aapl_strdup                                 mvHws_aapl_strdupt
#define aapl_str_rep                                mvHws_aapl_str_rept
#define aapl_strtok_r                               mvHws_aapl_strtok_rt
#define aapl_local_strftime                         mvHws_aapl_local_strftimet

/* Avsp */
#define avsp_supervisor_enable                      mvHws_avsp_supervisor_enable
#define avsp_supervisor_status                      mvHws_avsp_supervisor_status
#define avsp_supervisor_clear_interr_io             mvHws_avsp_supervisor_clear_interr_io
#define avsp_supervisor_get_interr_io               mvHws_avsp_supervisor_get_interr_io
#define avsp_supervisor_config_init                 mvHws_avsp_supervisor_config_init
#define avsp_supervisor_config_construct            mvHws_avsp_supervisor_config_construct
#define avsp_supervisor_config_destruct             mvHws_avsp_supervisor_config_destruct
#define avsp_supervisor_set_config                  mvHws_avsp_supervisor_set_config
#define avsp_get_name_list                          mvHws_avsp_get_name_list
#define avsp_upload_firmware                        mvHws_avsp_upload_firmware
#define avsp_upload_firmware_file                   mvHws_avsp_upload_firmware_file
#define avsp_get_self_healing                       mvHws_avsp_get_self_healing
#define avsp_set_self_healing                       mvHws_avsp_set_self_healing
#define avsp_get_refclk_divisor                     mvHws_avsp_get_refclk_divisor
#define avsp_5410_get_mode                          mvHws_avsp_5410_get_mode
#define avsp_5410_set_mode                          mvHws_avsp_5410_set_mode
#define avsp_5410_control_logic_reset_direct        mvHws_avsp_5410_control_logic_reset_direct

/* Diag core */
#define avago_diag_sbus_dump                        mvHws_avago_diag_sbus_dump
#define avago_spico_diag                            mvHws_avago_spico_diag
#define read_spico_file                             mvHws_read_spico_file
#define avago_spico_diag_line                       mvHws_avago_spico_diag_line
#define avago_spico_single_step                     mvHws_avago_spico_single_step
#define avago_serdes_restore                        mvHws_avago_serdes_restore
#define avago_diag_config_construct                 mvHws_avago_diag_config_construct
#define avago_diag_config_destruct                  mvHws_avago_diag_config_destruct
#define avago_diag                                  mvHws_avago_diag
#define avago_serdes_diag                           mvHws_avago_serdes_diag
#define avago_serdes_mem_dump                       mvHws_avago_serdes_mem_dump
#define avago_serdes_state_dump                     mvHws_avago_serdes_state_dump
#define avago_serdes_get_state_dump                 mvHws_avago_serdes_get_state_dump
#define avago_serdes_print_state_table_options      mvHws_avago_serdes_print_state_table_options
#define avago_device_info_options                   mvHws_avago_device_info_options

/* Eye */
#define aapl_str_to_eye_type                        mvHws_aapl_str_to_eye_type
#define aapl_eye_type_to_str                        mvHws_aapl_eye_type_to_str
#define avago_serdes_eye_config_construct           mvHws_avago_serdes_eye_config_construct
#define avago_serdes_eye_data_construct             mvHws_avago_serdes_eye_data_construct
#define avago_serdes_eye_config_destruct            mvHws_avago_serdes_eye_config_destruct
#define avago_serdes_eye_data_destruct              mvHws_avago_serdes_eye_data_destruct
#define avago_serdes_eye_get                        mvHws_avago_serdes_eye_get
#define avago_serdes_eye_data_read_file             mvHws_avago_serdes_eye_data_read_file
#define avago_serdes_eye_data_write_file            mvHws_avago_serdes_eye_data_write_file
#define avago_serdes_eye_hbtc_extrapolate           mvHws_avago_serdes_eye_hbtc_extrapolate
#define avago_serdes_eye_vbtc_extrapolate           mvHws_avago_serdes_eye_vbtc_extrapolate
#define avago_serdes_eye_get_default_avdd           mvHws_avago_serdes_eye_get_default_avdd
#define avago_serdes_eye_data_read_phase            mvHws_avago_serdes_eye_data_read_phase
#define avago_serdes_eye_plot_write                 mvHws_avago_serdes_eye_plot_write
#define avago_serdes_eye_gradient_plot_write        mvHws_avago_serdes_eye_gradient_plot_write
#define avago_serdes_eye_contour_plot_write         mvHws_avago_serdes_eye_contour_plot_write
#define avago_serdes_eye_hbtc_write                 mvHws_avago_serdes_eye_hbtc_write
#define avago_serdes_eye_vbtc_write                 mvHws_avago_serdes_eye_vbtc_write
#define avago_serdes_eye_btc_write                  mvHws_avago_serdes_eye_btc_write
#define avago_serdes_eye_data_write                 mvHws_avago_serdes_eye_data_write
#define avago_serdes_eye_plot_log_print             mvHws_avago_serdes_eye_plot_log_print
#define avago_serdes_eye_hbtc_log_print             mvHws_avago_serdes_eye_hbtc_log_print
#define avago_serdes_eye_vbtc_log_print             mvHws_avago_serdes_eye_vbtc_log_print
#define avago_serdes_eye_btc_log_print              mvHws_avago_serdes_eye_btc_log_print
#define avago_serdes_eye_errors_get                 mvHws_avago_serdes_eye_errors_get
#define avago_serdes_eye_bits_get                   mvHws_avago_serdes_eye_bits_get
#define avago_serdes_eye_grad_get                   mvHws_avago_serdes_eye_grad_get
#define avago_serdes_eye_qval_get                   mvHws_avago_serdes_eye_qval_get
#define avago_serdes_eye_plot_format                mvHws_avago_serdes_eye_plot_format
#define avago_serdes_eye_gradient_plot_format       mvHws_avago_serdes_eye_gradient_plot_format
#define avago_serdes_eye_contour_plot_format        mvHws_avago_serdes_eye_contour_plot_format
#define avago_serdes_eye_hbtc_format                mvHws_avago_serdes_eye_hbtc_format
#define avago_serdes_eye_vbtc_format                mvHws_avago_serdes_eye_vbtc_format
#define avago_serdes_eye_btc_format                 mvHws_avago_serdes_eye_btc_format
#define avago_hardware_info_format                  mvHws_avago_hardware_info_format
#define allocate_eye_arrays                         mvHws_allocate_eye_arrays
#define sbm_eye_gather                              mvHws_sbm_eye_gather

/* Eye math */
#define avago_interpolate                           mvHws_avago_interpolate
#define avago_calc_BER                              mvHws_avago_calc_BER
#define avago_qfunc                                 mvHws_avago_qfunc
#define avago_qfuncinv                              mvHws_avago_qfuncinv
#define avago_qfuncinv_half                         mvHws_avago_qfuncinv_half
#define avago_least_sqr                             mvHws_avago_least_sqr
#define aapl_iround                                 mvHws_aapl_iround
#define avago_matrix_construct                      mvHws_avago_matrix_construct
#define avago_matrix_destruct                       mvHws_avago_matrix_destruct
#define avago_matrix_transpose                      mvHws_avago_matrix_transpose
#define avago_matrix_multiply                       mvHws_avago_matrix_multiply
#define avago_matrix_subtract                       mvHws_avago_matrix_subtract
#define avago_matrix_construct_prbs_inverse         mvHws_avago_matrix_construct_prbs_inverse
#define avago_matrix_print                          mvHws_avago_matrix_print

/* Gpio Mdio */
#define avago_gpio_mdio_open_fn                     mvHws_avago_gpio_mdio_open_fn
#define avago_gpio_mdio_close_fn                    mvHws_avago_gpio_mdio_close_fn
#define avago_gpio_mdio_fn                          mvHws_avago_gpio_mdio_fn

/* I2C */
#define avago_i2c_sbus_fn                           mvHws_avago_i2c_sbus_fn
#define avago_system_i2c_open_fn                    mvHws_avago_system_i2c_open_fn
#define avago_system_i2c_close_fn                   mvHws_avago_system_i2c_close_fn
#define avago_i2c_read                              mvHws_avago_i2c_read
#define avago_i2c_write                             mvHws_avago_i2c_write
#define avago_aacs_i2c_write_fn                     mvHws_avago_aacs_i2c_write_fn
#define avago_aacs_i2c_read_fn                      mvHws_avago_aacs_i2c_read_fn
#define avago_system_i2c_write_fn                   mvHws_avago_system_i2c_write_fn
#define avago_system_i2c_read_fn                    mvHws_avago_system_i2c_read_fn

/* Logging */
#define aapl_log_add                                mvHws_aapl_log_add
#define aapl_buf_add                                mvHws_aapl_buf_add
#define aapl_log_get                                mvHws_aapl_log_get
#define aapl_log_clear                              mvHws_aapl_log_clear
#define aapl_start_file_logging                     mvHws_aapl_start_file_logging
#define aapl_stop_file_logging                      mvHws_aapl_stop_file_logging
#define aapl_built_in_logging_fn                    mvHws_aapl_built_in_logging_fn
#define aapl_register_logging_fn                    mvHws_aapl_register_logging_fn
#define name_to_index                               mvHws_name_to_index
#define value_to_index                              mvHws_value_to_index
#define aapl_addr_to_str                            mvHws_aapl_addr_to_str
#define aapl_bigint_to_str                          mvHws_aapl_bigint_to_str
#define aapl_bool_to_str                            mvHws_aapl_bool_to_str
#define aapl_comm_method_to_str                     mvHws_aapl_comm_method_to_str
#define aapl_cmp_data_to_str                        mvHws_aapl_cmp_data_to_str
#define aapl_cmp_mode_to_str                        mvHws_aapl_cmp_mode_to_str
#define aapl_data_sel_to_str                        mvHws_aapl_data_sel_to_str
#define aapl_dfe_status_to_str                      mvHws_aapl_dfe_status_to_str
#define aapl_dfe_tune_mode_to_str                   mvHws_aapl_dfe_tune_mode_to_str
#define aapl_enable_to_str                          mvHws_aapl_enable_to_str
#define aapl_line_encoding_to_str                   mvHws_aapl_line_encoding_to_str
#define aapl_ip_type_to_str                         mvHws_aapl_ip_type_to_str
#define aapl_log_type_to_str                        mvHws_aapl_log_type_to_str
#define aapl_mem_type_to_str                        mvHws_aapl_mem_type_to_str
#define aapl_onoff_to_str                           mvHws_aapl_onoff_to_str
#define aapl_pll_clk_to_str                         mvHws_aapl_pll_clk_to_str
#define aapl_process_id_to_str                      mvHws_aapl_process_id_to_str
#define aapl_rx_clock_cdc_to_str                    mvHws_aapl_rx_clock_cdc_to_str
#define aapl_rx_clock_to_str                        mvHws_aapl_rx_clock_to_str
#define aapl_term_to_str                            mvHws_aapl_term_to_str
#define aapl_spico_clk_to_str                       mvHws_aapl_spico_clk_to_str
#define aapl_str_to_addr                            mvHws_aapl_str_to_addr
#define aapl_str_to_cmp_data                        mvHws_aapl_str_to_cmp_data
#define aapl_str_to_cmp_mode                        mvHws_aapl_str_to_cmp_mode
#define aapl_str_to_comm_method                     mvHws_aapl_str_to_comm_method
#define aapl_str_to_data_sel                        mvHws_aapl_str_to_data_sel
#define aapl_str_to_dfe_tune_mode                   mvHws_aapl_str_to_dfe_tune_mode
#define aapl_str_to_line_encoding                   mvHws_aapl_str_to_line_encoding
#define aapl_str_to_ip_type                         mvHws_aapl_str_to_ip_type
#define aapl_str_to_mem_type                        mvHws_aapl_str_to_mem_type
#define aapl_str_to_pll_clk                         mvHws_aapl_str_to_pll_clk
#define aapl_str_to_rx_clock                        mvHws_aapl_str_to_rx_clock
#define aapl_str_to_rx_clock_cdc                    mvHws_aapl_str_to_rx_clock_cdc
#define aapl_str_to_term                            mvHws_aapl_str_to_term
#define aapl_str_to_spico_clk                       mvHws_aapl_str_to_spico_clk
#define aapl_user_supplied_log_func_ptr             mvHws_aapl_user_supplied_log_func_ptr

/* Mdio */
#define avago_mdio                                  mvHws_avago_mdio
#define avago_mdio_wr                               mvHws_avago_mdio_wr
#define avago_mdio_rd                               mvHws_avago_mdio_rd
#define avago_aacs_mdio_fn                          mvHws_avago_aacs_mdio_fn
#define avago_mdio_sbus_fn                          mvHws_avago_mdio_sbus_fn

/* Means */
#define avago_serdes_dfe_los                        mvHws_avago_serdes_dfe_los
#define avago_serdes_dfe_running                    mvHws_avago_serdes_dfe_running
#define avago_serdes_dfe_pause                      mvHws_avago_serdes_dfe_pause
#define avago_serdes_dfe_wait                       mvHws_avago_serdes_dfe_wait
#define avago_serdes_dfe_wait_timeout               mvHws_avago_serdes_dfe_wait_timeout
#define avago_serdes_dfe_resume                     mvHws_avago_serdes_dfe_resume
#define avago_serdes_get_dac_range                  mvHws_avago_serdes_get_dac_range
#define avago_serdes_get_phase_multiplier           mvHws_avago_serdes_get_phase_multiplier
#define avago_serdes_power_down_phase_interpolator  mvHws_avago_serdes_power_down_phase_interpolator

/* PMD */
#define avago_serdes_pmd_init                       mvHws_avago_serdes_pmd_init
#define avago_serdes_pmd_train                      mvHws_avago_serdes_pmd_train
#define avago_serdes_pmd_status                     mvHws_avago_serdes_pmd_status
#define avago_serdes_pmd_config_construct           mvHws_avago_serdes_pmd_config_construct
#define avago_serdes_pmd_config_destruct            mvHws_avago_serdes_pmd_config_destruct
#define avago_serdes_pmd_debug_construct            mvHws_avago_serdes_pmd_debug_construct
#define avago_serdes_pmd_debug_destruct             mvHws_avago_serdes_pmd_debug_destruct
#define avago_serdes_pmd_debug                      mvHws_avago_serdes_pmd_debug
#define avago_serdes_pmd_debug_print                mvHws_avago_serdes_pmd_debug_print
#define avago_serdes_pmd_debug_print_repeat         mvHws_avago_serdes_pmd_debug_print_repeat
#define aapl_pmd_clause_to_str                      mvHws_aapl_pmd_clause_to_str
#define aapl_pmd_train_mode_to_str                  mvHws_aapl_pmd_train_mode_to_str
#define aapl_str_to_pmd_clause                      mvHws_aapl_str_to_pmd_clause
#define aapl_str_to_pmd_train_mode                  mvHws_aapl_str_to_pmd_train_mode
#define avago_serdes_pmd_wait                       mvHws_avago_serdes_pmd_wait

/* Pmro */
#define avago_pmro_get_metric                       mvHws_avago_pmro_get_metric

/* Sbm */
#define avago_sbm_get_sbus_clock_divider            mvHws_avago_sbm_get_sbus_clock_divider
#define avago_sbm_set_sbus_clock_divider            mvHws_avago_sbm_set_sbus_clock_divider

/* Sbus */
#define avago_sbus                                  mvHws_avago_sbus
#define avago_sbus_open                             mvHws_avago_sbus_open
#define avago_sbus_close                            mvHws_avago_sbus_close
#define avago_sbus_rd_array                         mvHws_avago_sbus_rd_array
#define avago_sbus_rd                               mvHws_avago_sbus_rd
#define avago_sbus_wr                               mvHws_avago_sbus_wr
#define avago_sbus_wr_flush                         mvHws_avago_sbus_wr_flush
#define avago_sbus_rmw                              mvHws_avago_sbus_rmw
#define avago_sbus_reset                            mvHws_avago_sbus_reset
#define avago_sbm_get_temperature                   mvHws_avago_sbm_get_temperature
#define user_supplied_sbus_function                 mvHws_user_supplied_sbus_function
#define avago_diag_sbus_rw_test                     mvHws_avago_diag_sbus_rw_test
#define aapl_sbus_thread_worker                     mvHws_aapl_sbus_thread_worker
#define avago_jtag_sbus_fn                          mvHws_avago_jtag_sbus_fn
#define avago_offline_sbus_fn                       mvHws_avago_offline_sbus_fn
#define avago_offline_open_fn                       mvHws_avago_offline_open_fn
#define avago_offline_close_fn                      mvHws_avago_offline_close_fn
#define aapl_set_sbus_tap_reset_sel                 mvHws_aapl_set_sbus_tap_reset_sel
#define user_supplied_sbus_soft_reset               mvHws_user_supplied_sbus_soft_reset
#define recovery_process                            mvHws_recovery_process
#define avago_hard_sbus_reset_fn                    mvHws_avago_hard_sbus_reset_fn

/* Sensor */
#if !defined(MV_HWS_REDUCED_BUILD_EXT_CM3) || defined(RAVEN_DEV_SUPPORT)
#define avago_sensor_start_temperature              mvHws_avago_sensor_start_temperature
#define avago_sensor_wait_temperature               mvHws_avago_sensor_wait_temperature
#define avago_sensor_get_temperature                mvHws_avago_sensor_get_temperature
#define avago_sensor_start_voltage                  mvHws_avago_sensor_start_voltage
#define avago_sensor_wait_voltage                   mvHws_avago_sensor_wait_voltage
#define avago_sensor_get_voltage                    mvHws_avago_sensor_get_voltage
#endif

/* Serdes core */
#define avago_serdes_set_error_timer                mvHws_avago_serdes_set_error_timer
#define avago_serdes_get_lsb_rev                    mvHws_avago_serdes_get_lsb_rev
#define avago_serdes_mem_rd                         mvHws_avago_serdes_mem_rd
#define avago_serdes_mem_wr                         mvHws_avago_serdes_mem_wr
#define avago_serdes_mem_rmw                        mvHws_avago_serdes_mem_rmw
#define aapl_get_pcs_architecture                   mvHws_aapl_get_pcs_architecture
#define avago_serdes_width_to_bits                  mvHws_avago_serdes_width_to_bits
#define avago_serdes_bits_to_width                  mvHws_avago_serdes_bits_to_width
#define avago_serdes_get_rx_register                mvHws_avago_serdes_get_rx_register
#define aapl_serdes_get_int30_bits                  mvHws_aapl_serdes_get_int30_bits
#define avago_serdes_get_ei_limits                  mvHws_avago_serdes_get_ei_limits
#define avago_serdes_get_tx_data_sel                mvHws_avago_serdes_get_tx_data_sel
#define avago_serdes_set_tx_data_sel                mvHws_avago_serdes_set_tx_data_sel
#define avago_serdes_get_tx_user_data               mvHws_avago_serdes_get_tx_user_data
#define avago_serdes_set_tx_user_data               mvHws_avago_serdes_set_tx_user_data
#define avago_serdes_get_tx_rx_ready                mvHws_avago_serdes_get_tx_rx_ready
#define avago_serdes_set_tx_rx_enable               mvHws_avago_serdes_set_tx_rx_enable
#define avago_serdes_get_burst_mode                 mvHws_avago_serdes_get_burst_mode
#define avago_serdes_get_tx_output_enable           mvHws_avago_serdes_get_tx_output_enable
#define avago_serdes_set_tx_output_enable           mvHws_avago_serdes_set_tx_output_enable
#define avago_serdes_get_tx_invert                  mvHws_avago_serdes_get_tx_invert
#define avago_serdes_set_tx_invert                  mvHws_avago_serdes_set_tx_invert
#define avago_serdes_set_tx_datapath_encoding       mvHws_avago_serdes_set_tx_datapath_encoding
#define avago_serdes_get_tx_datapath_encoding       mvHws_avago_serdes_get_tx_datapath_encoding
#define avago_serdes_tx_inject_error                mvHws_avago_serdes_tx_inject_error
#define avago_serdes_rx_inject_error                mvHws_avago_serdes_rx_inject_error
#define avago_serdes_get_tx_rx_width                mvHws_avago_serdes_get_tx_rx_width
#define avago_serdes_set_tx_rx_width                mvHws_avago_serdes_set_tx_rx_width
#define avago_serdes_get_tx_line_encoding           mvHws_avago_serdes_get_tx_line_encoding
#define avago_serdes_get_rx_line_encoding           mvHws_avago_serdes_get_rx_line_encoding
#define avago_serdes_get_tx_rx_line_encoding        mvHws_avago_serdes_get_tx_rx_line_encoding
#define avago_serdes_set_tx_rx_width_pam            mvHws_avago_serdes_set_tx_rx_width_pam
#define avago_serdes_tx_eq_init                     mvHws_avago_serdes_tx_eq_init
#define avago_serdes_get_tx_eq                      mvHws_avago_serdes_get_tx_eq
#define avago_serdes_set_tx_eq                      mvHws_avago_serdes_set_tx_eq
#define avago_serdes_get_rx_cmp_data                mvHws_avago_serdes_get_rx_cmp_data
#define avago_serdes_set_rx_cmp_data                mvHws_avago_serdes_set_rx_cmp_data
#define avago_serdes_get_rx_input_loopback          mvHws_avago_serdes_get_rx_input_loopback
#define avago_serdes_set_rx_input_loopback          mvHws_avago_serdes_set_rx_input_loopback
#define avago_serdes_get_rx_invert                  mvHws_avago_serdes_get_rx_invert
#define avago_serdes_set_rx_invert                  mvHws_avago_serdes_set_rx_invert
#define avago_serdes_get_rx_datapath                mvHws_avago_serdes_get_rx_datapath
#define avago_serdes_set_rx_datapath                mvHws_avago_serdes_set_rx_datapath
#define avago_serdes_get_tx_datapath                mvHws_avago_serdes_get_tx_datapath
#define avago_serdes_set_tx_datapath                mvHws_avago_serdes_set_tx_datapath
#define avago_serdes_set_rx_datapath_encoding       mvHws_avago_serdes_set_rx_datapath_encoding
#define avago_serdes_get_rx_datapath_encoding       mvHws_avago_serdes_get_rx_datapath_encoding
#define avago_serdes_get_rx_data                    mvHws_avago_serdes_get_rx_data
#define avago_serdes_get_rx_live_data               mvHws_avago_serdes_get_rx_live_data
#define avago_serdes_get_rx_cmp_mode                mvHws_avago_serdes_get_rx_cmp_mode
#define avago_serdes_set_rx_cmp_mode                mvHws_avago_serdes_set_rx_cmp_mode
#define avago_serdes_get_rx_term                    mvHws_avago_serdes_get_rx_term
#define avago_serdes_set_rx_term                    mvHws_avago_serdes_set_rx_term
#define avago_serdes_get_spico_clk_src              mvHws_avago_serdes_get_spico_clk_src
#define avago_serdes_set_spico_clk_src              mvHws_avago_serdes_set_spico_clk_src
#define avago_serdes_get_tx_pll_clk_src             mvHws_avago_serdes_get_tx_pll_clk_src
#define avago_serdes_set_tx_pll_clk_src             mvHws_avago_serdes_set_tx_pll_clk_src
#define avago_serdes_get_electrical_idle            mvHws_avago_serdes_get_electrical_idle
#define avago_serdes_get_signal_ok_enable           mvHws_avago_serdes_get_signal_ok_enable
#define avago_serdes_get_signal_ok_threshold        mvHws_avago_serdes_get_signal_ok_threshold
#define avago_serdes_get_signal_ok                  mvHws_avago_serdes_get_signal_ok
#define avago_serdes_initialize_signal_ok           mvHws_avago_serdes_initialize_signal_ok
#define avago_serdes_launch_ei_calibration          mvHws_avago_serdes_launch_ei_calibration
#define avago_serdes_get_ei_calibration_status      mvHws_avago_serdes_get_ei_calibration_status
#define avago_serdes_get_ei_calibration_threshold   mvHws_avago_serdes_get_ei_calibration_threshold
#define avago_serdes_set_ei_calibration_threshold   mvHws_avago_serdes_set_ei_calibration_threshold
#define avago_serdes_get_frequency_lock             mvHws_avago_serdes_get_frequency_lock
#define avago_serdes_get_frequency_lock_time        mvHws_avago_serdes_get_frequency_lock_time
#define avago_serdes_get_signal_ok_live             mvHws_avago_serdes_get_signal_ok_live
#define avago_serdes_get_errors                     mvHws_avago_serdes_get_errors
#define avago_serdes_error_reset                    mvHws_avago_serdes_error_reset
#define avago_serdes_count_errors_start             mvHws_avago_serdes_count_errors_start
#define avago_serdes_count_errors_wait              mvHws_avago_serdes_count_errors_wait
#define avago_serdes_count_errors                   mvHws_avago_serdes_count_errors
#define avago_serdes_set_error_timer                mvHws_avago_serdes_set_error_timer
#define avago_serdes_get_error_flag                 mvHws_avago_serdes_get_error_flag
#define avago_serdes_error_flag_reset               mvHws_avago_serdes_error_flag_reset
#ifndef MV_HWS_REDUCED_BUILD_EXT_CM3
#define avago_serdes_aux_counter_disable            mvHws_avago_serdes_aux_counter_disable
#define avago_serdes_aux_counter_start              mvHws_avago_serdes_aux_counter_start
#endif /* MV_HWS_REDUCED_BUILD_EXT_CM3 */
#define avago_serdes_aux_counter_read               mvHws_avago_serdes_aux_counter_read
#define avago_serdes_enable_core_to_cntl            mvHws_avago_serdes_enable_core_to_cntl
#define avago_serdes_slip_bits                      mvHws_avago_serdes_slip_bits
#define avago_serdes_slip_rx_phase                  mvHws_avago_serdes_slip_rx_phase
#define avago_serdes_slip_tx_phase                  mvHws_avago_serdes_slip_tx_phase
#define avago_serdes_enable_core_bit_slip           mvHws_avago_serdes_enable_core_bit_slip
#define avago_serdes_enable_low_power_mode          mvHws_avago_serdes_enable_low_power_mode
#define avago_serdes_enable_pcs_fifo_clock          mvHws_avago_serdes_enable_pcs_fifo_clock
#define avago_serdes_init_config_construct          mvHws_avago_serdes_init_config_construct
#define avago_serdes_init_config_destruct           mvHws_avago_serdes_init_config_destruct
#define avago_serdes_init_config                    mvHws_avago_serdes_init_config
#define avago_serdes_init                           mvHws_avago_serdes_init
#define avago_serdes_base_init                      mvHws_avago_serdes_base_init
#define avago_serdes_tx_init                        mvHws_avago_serdes_tx_init
#define avago_serdes_rx_init                        mvHws_avago_serdes_rx_init
#define avago_serdes_loopback_test                  mvHws_avago_serdes_loopback_test
#define avago_parallel_serdes_base_init             mvHws_avago_parallel_serdes_base_init
#define avago_parallel_serdes_get_signal_ok         mvHws_avago_parallel_serdes_get_signal_ok
#define avago_parallel_serdes_init                  mvHws_avago_parallel_serdes_init
#define avago_parallel_serdes_initialize_signal_ok  mvHws_avago_parallel_serdes_initialize_signal_ok
#define avago_parallel_serdes_mem_rd                mvHws_avago_parallel_serdes_mem_rd
#define avago_parallel_serdes_set_rx_datapath       mvHws_avago_parallel_serdes_set_rx_datapath
#define avago_parallel_serdes_set_tx_datapath       mvHws_avago_parallel_serdes_set_tx_datapath
#define avago_parallel_serdes_set_tx_rx_enable      mvHws_avago_parallel_serdes_set_tx_rx_enable
#define avago_parallel_serdes_set_tx_rx_width_pam   mvHws_avago_parallel_serdes_set_tx_rx_width_pam
#define avago_parallel_verify_addr_list             mvHws_avago_parallel_verify_addr_list
#define avago_serdes_pon_set_rate_select            mvHws_avago_serdes_pon_set_rate_select
#define avago_serdes_pon_get_rate_select            mvHws_avago_serdes_pon_get_rate_select
#define avago_serdes_init_quick                     mvHws_avago_serdes_init_quick
#define avago_serdes_tune_init                      mvHws_avago_serdes_tune_init
#define avago_serdes_tune                           mvHws_avago_serdes_tune
#define avago_serdes_eye_get_simple_metric          mvHws_avago_serdes_eye_get_simple_metric
#define avago_serdes_get_rx_register_clock          mvHws_avago_serdes_get_rx_register_clock
#define divider_lookup28nm                          mvHws_divider_lookup28nm
#define avago_serdes_set_rx_data_clock              mvHws_avago_serdes_set_rx_data_clock
#define avago_serdes_set_rx_dfe_clock               mvHws_avago_serdes_set_rx_dfe_clock
#define avago_serdes_set_rx_edge_clock              mvHws_avago_serdes_set_rx_edge_clock
#define avago_serdes_set_rx_test_clock              mvHws_avago_serdes_set_rx_test_clock
#define avago_serdes_set_rx_cdc_clock               mvHws_avago_serdes_set_rx_cdc_clock
#define avago_serdes_rx_clock_apply                 mvHws_avago_serdes_rx_clock_apply
#define avago_serdes_rx_clock_print                 mvHws_avago_serdes_rx_clock_print
#define avago_serdes_rx_clock_read                  mvHws_avago_serdes_rx_clock_read
#define avago_serdes_rx_clock_write                 mvHws_avago_serdes_rx_clock_write
#define avago_serdes_get_fine_frequency_lock        mvHws_avago_serdes_get_fine_frequency_lock
#define avago_serdes_set_fine_frequency_lock        mvHws_avago_serdes_set_fine_frequency_lock
#define avago_serdes_hal_get                        mvHws_avago_serdes_hal_get
#define avago_serdes_hal_set                        mvHws_avago_serdes_hal_set
#define avago_serdes_hal_func                       mvHws_avago_serdes_hal_func
#define avago_serdes_parallel_count_errors          mvHws_avago_serdes_parallel_count_errors
#define avago_serdes_get_default_width              mvHws_avago_serdes_get_default_width

/* Serdes dfe */
#define avago_serdes_get_dfe_state                  mvHws_avago_serdes_get_dfe_state
#define avago_serdes_print_dfe                      mvHws_avago_serdes_print_dfe
#define avago_serdes_dfe_state_to_str               mvHws_avago_serdes_dfe_state_to_str
#define avago_serdes_get_dfe_status                 mvHws_avago_serdes_get_dfe_status
#define avago_parallel_serdes_get_dfe_status        mvHws_avago_parallel_serdes_get_dfe_status
#define avago_parallel_serdes_interpret_dfe_status  mvHws_avago_parallel_serdes_interpret_dfe_status
#define avago_parallel_serdes_dfe_tune              mvHws_avago_parallel_serdes_dfe_tune
#define avago_serdes_interpret_dfe_status           mvHws_avago_serdes_interpret_dfe_status
#define serdes_dfe_update_ctle                      mvHws_serdes_dfe_update_ctle
#define serdes_dfe_update_gain                      mvHws_serdes_dfe_update_gain

/* Spico */
#define avago_spico_status                          mvHws_avago_spico_status
#define avago_spico_running                         mvHws_avago_spico_running
#define avago_spico_reset                           mvHws_avago_spico_reset
#define avago_spico_get_pc                          mvHws_avago_spico_get_pc
#define avago_spico_get_state                       mvHws_avago_spico_get_state
#define avago_spico_upload_swap_imag                mvHws_avago_spico_upload_swap_imag
#define avago_spico_upload                          mvHws_avago_spico_upload
#define avago_parallel_spico_upload                 mvHws_avago_parallel_spico_upload
#define avago_spico_wait_for_upload                 mvHws_avago_spico_wait_for_upload
#define avago_twi_wait_for_complete                 mvHws_avago_twi_wait_for_complete
#define avago_load_rom_from_file                    mvHws_avago_load_rom_from_file
#define avago_find_swap_file                        mvHws_avago_find_swap_file
#define avago_spico_upload_file                     mvHws_avago_spico_upload_file
#define avago_parallel_spico_upload_file            mvHws_avago_parallel_spico_upload_file
#define avago_spico_int                             mvHws_avago_spico_int
#define avago_spico_int_check                       mvHws_avago_spico_int_check
#define avago_parallel_serdes_int                   mvHws_avago_parallel_serdes_int
#define avago_parallel_serdes_int_check             mvHws_avago_parallel_serdes_int_check
#define avago_serdes_spico_int_sbus_fn              mvHws_avago_serdes_spico_int_sbus_fn
#define avago_parallel_serdes_int_sbus_fn           mvHws_avago_parallel_serdes_int_sbus_fn
#define avago_parallel_core_serdes_int_sbus_fn      mvHws_avago_parallel_core_serdes_int_sbus_fn
#define avago_spico_broadcast_int                   mvHws_avago_spico_broadcast_int
#define avago_spico_broadcast_int_w_mask            mvHws_avago_spico_broadcast_int_w_mask
#define avago_spico_int_array                       mvHws_avago_spico_int_array
#define avago_firmware_get_engineering_id           mvHws_avago_firmware_get_engineering_id
#define avago_firmware_get_rev                      mvHws_avago_firmware_get_rev
#define avago_firmware_get_build_id                 mvHws_avago_firmware_get_build_id
#define avago_spico_crc                             mvHws_avago_spico_crc
#define avago_parallel_serdes_crc                   mvHws_avago_parallel_serdes_crc
#define avago_spico_ram_bist                        mvHws_avago_spico_ram_bist
#define aapl_crc_one_byte                           mvHws_aapl_crc_one_byte
#define aapl_crc_rom                                mvHws_aapl_crc_rom
#define avago_spico_halt                            mvHws_avago_spico_halt
#define avago_spico_resume                          mvHws_avago_spico_resume
#define spico_int_array_nobatch                     mvHws_spico_int_array_nobatch
#define spico_int_array_batch                       mvHws_spico_int_array_batch
#define spico_int_02_retry                          mvHws_spico_int_02_retry
#define avago_spico_upload                          mvHws_avago_spico_upload
#define avago_spico_upload_swap_image               mvHws_avago_spico_upload_swap_image
#define avago_spico_upload_file                     mvHws_avago_spico_upload_file
#define avago_spico_wait_for_upload                 mvHws_avago_spico_wait_for_upload
#define avago_firmware_upload                       mvHws_avago_firmware_upload
#define avago_firmware_upload_file                  mvHws_avago_firmware_upload_file
#define aapl_addr_selects_fw_device                 mvHws_aapl_addr_selects_fw_device
#define aapl_sbm_rom_has_sdi                        mvHws_aapl_sbm_rom_has_sdi
#define merge_sdi_files                             mvHws_merge_sdi_files
#define aapl_read_file                              mvHws_aapl_read_file

#endif /* defined MV_HWS_AVAGO_SERDES_H */

