/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE IS A REFERENCE CODE FOR MARVELL SWITCH PRODUCTS.  IT IS PROVIDED   *
* "AS IS" WITH NO WARRANTIES, EXPRESSED, IMPLIED OR OTHERWISE, REGARDING ITS   *
* ACCURACY, COMPLETENESS OR PERFORMANCE.                                       *
* CUSTOMERS ARE FREE TO MODIFY IT AND USE IT ONLY IN THEIR PRODUCTION          *
* SOFTWARE RELEASES WITH MARVELL SWITCH CHIPSETS.                              *
*******************************************************************************/
/**
********************************************************************************
* @file gtDbDxBoardSpecific_DataIntegrityTables.c
*
* @brief Board specific data integrity table configuration for Dx devices.
*
*/

#include <cpss/dxCh/dxChxGen/cpssHwInit/cpssDxChTables.h>


CPSS_DXCH_LOGICAL_TABLES_SHADOW_STC dataIntegrityTblForAldrin2Customized[] =
{
    {CPSS_DXCH_LOGICAL_TABLE_VLAN_E, CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_EPORT_E, CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_PHYSICAL_PORT_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_STG_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_QOS_PROFILE_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_TRUNK_MEMBERS_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_PFC_MODE_PROFILE_TC_THRESHOLDS_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_QUEUE_LIMITS_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_INGRESS_PCL_CONFIG_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_PCL_UDB_CONFIG_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_PCL_UDB_SELECT_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_DEFAULT_EPORT_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_FDB_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_TCAM_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_TCAM_ACTION_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_EGRESS_DEVICE_MAP_TABLE_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_TRUNK_HASH_MASK_CRC_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_BRIDGE_SOURCE_TRUNK_ATTRIBUTE_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},

    {CPSS_DXCH_LOGICAL_TABLE_TTI_UDB_CONFIG_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},

    {CPSS_DXCH_LOGICAL_TABLE_TXQ_DESIGNATED_PORT_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_EGRESS_TC_DP_MAPPER_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_MULTICAST_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_CPU_CODE_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_EGRESS_E_VLAN_MAPPER_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},

    {CPSS_DXCH_LOGICAL_TABLE_L2_ECMP_LTT_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_TXQ_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_EGRESS_PCL_CONFIG_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_PORT_MAX_BUFFER_FILL_LEVEL_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_QUEUE_MAX_BUFFER_FILL_LEVEL_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E},
    {CPSS_DXCH_LOGICAL_TABLE_EGRESS_PROFILE_CONFIG_E,CPSS_DXCH_SHADOW_TYPE_CPSS_E}
};

GT_U32 dataIntegrityTblForAldrin2CustomizedSize = sizeof(dataIntegrityTblForAldrin2Customized)/sizeof(CPSS_DXCH_LOGICAL_TABLES_SHADOW_STC);
