/*
 *  ppa_fw_accelerator_commands.h
 *
 *  PPA fw accelerator commands definitions
 *
 */

#include "ppa_fw_defs.h"

/**************************************************************************
 * Function prototypes
 * ************************************************************************/
void load_accelerator_commands();

/**************************************************************************
 * Accelerator Instruction: Base addresses
 * ************************************************************************/
#define ACCEL_CMDS_CFG_BASE_ADDR   0xB0
#define ACCEL_CMDS_ALIAS_BASE_ADDR 0x1000
#define ACCEL_CMDS_TRIG_BASE_ADDR (ACCEL_CMDS_ALIAS_BASE_ADDR + ACCEL_CMDS_CFG_BASE_ADDR)

/**************************************************************************
 * Accelerator Instruction: Command bits map
 * ************************************************************************/
#define ACCEL_CMD_BYTE_COPY             (0)
#define ACCEL_CMD_BIT_COPY              (1 << 26)
#define ACCEL_CMD_SRC_BYTE(val)         (val)
#define ACCEL_CMD_SRC_BYTE_TYPE(val)    (val << 7)
#define ACCEL_CMD_DST_BYTE(val)         (val << 8)
#define ACCEL_CMD_DST_BYTE_TYPE(val)    (val << 15)
#define ACCEL_CMD_LEN(val)              ((val-1) << 16)
#define ACCEL_CMD_SRC_BIT(val)          (val << 20)
#define ACCEL_CMD_DST_BIT(val)          (val << 23)
#define PKT                             (1)
#define NO_PKT                          (0)


#define BUILD_ACCELERATOR_COMMAND_H2H_COPY_BYTE(length,dest,src)   (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(length)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(dest)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(src))
#define BUILD_ACCELERATOR_COMMAND_C2H_COPY_BYTE(length,dest,src)   (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(length)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(dest)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(src))


/**************************************************************************
 * Accelerator commands types data
 * ************************************************************************/

/*************** Thread 1 (E2U) *******************/
#define COPY_BYTES_THR1_E2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_8_VALUE              (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(12)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb8c94 */
#define COPY_BITS_THR1_E2U_CFG_srcPortEntry__PCID_LEN12_TO_CFG_etag__E_CID_base_VALUE                                            (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(16)) /* 0x60b0210 */
#define COPY_BITS_THR1_E2U_CFG_targetPortEntry__TPID_LEN16_TO_PKT_etag__TPID_VALUE                                               (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(24)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0x40f9814 */
#define COPY_BYTES_THR1_E2U_CFG_etag__E_PCP_LEN6_TO_PKT_etag__E_PCP_VALUE                                                        (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(6)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(26)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0x59a00 */
#define COPY_BITS_THR1_E2U_DESC_nonQcn_desc__up0_LEN4_TO_CFG_etag__E_PCP_VALUE                                                   (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(72)) /* 0x4030048 */
#define COPY_BITS_THR1_E2U_CFG_srcPortEntry__Uplink_Port_LEN1_TO_CFG_etag__IPL_Direction_VALUE                                   (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(19)) /* 0x4400213 */

/*************** Thread 2 (U2E) *******************/
#define COPY_BYTES_THR2_U2E_PKT_mac_da_47_32_PLUS8_LEN12_TO_MACSHIFTRIGHT_12_VALUE      (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(32)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(28)) /* 0xba09c */
#define COPY_BYTES_THR2_U2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_8_VALUE             (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(28)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9c94 */

/*************** Thread 3 (U2C) *******************/
#define COPY_BYTES_THR3_U2C_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_8_VALUE                                (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(28)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9c94 */
#define COPY_BITS_THR3_U2C_CFG_cfgReservedSpace__reserved_0_LEN1_TO_PKT_etag__IPL_Direction_VALUE                                (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(36)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(28)) /* 0x400a41c */

/*************** Thread 4 (ET2U) *******************/
#define COPY_BITS_THR4_ET2U_CFG_srcPortEntry__src_port_num_LEN4_TO_CFG_DSA_fwd__SrcPort_4_0_PLUS1_VALUE    (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(1)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(1)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(17)) /* 0x4c30111 */
#define COPY_BITS_THR4_ET2U_PKT_vlan__vid_LEN12_TO_CFG_DSA_fwd__vid_VALUE                                  (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x64b02a2 */
#define COPY_BITS_THR4_ET2U_PKT_vlan__up_LEN3_TO_CFG_DSA_fwd__up_VALUE                                     (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x40202a2 */
#define COPY_BITS_THR4_ET2U_PKT_vlan__cfi_LEN1_TO_CFG_DSA_fwd__cfi_VALUE                                   (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(7)|ACCEL_CMD_SRC_BIT(3)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(1)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x7b001a2 */
#define COPY_BYTES_THR4_ET2U_CFG_DSA_fwd__tagCommand_LEN4_TO_PKT_DSA_fwd__tagCommand_VALUE                 (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(32)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0x3a000 */

/*************** Thread 5 (EU2U) *******************/
#define COPY_BITS_THR5_EU2U_CFG_srcPortEntry__src_port_num_LEN4_TO_CFG_DSA_fwd__SrcPort_4_0_PLUS1_VALUE    (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(1)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(1)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(17)) /* 0x4c30111 */
#define COPY_BYTES_THR5_EU2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_4_VALUE                                (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(16)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9094 */
#define COPY_BYTES_THR5_EU2U_CFG_DSA_fwd__tagCommand_LEN4_TO_PKT_DSA_fwd__tagCommand_VALUE                 (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(28)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0x39c00 */
#define COPY_BITS_THR5_EU2U_CFG_cfgReservedSpace__reserved_0_LEN12_TO_CFG_DSA_fwd__vid_VALUE               (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(28)) /* 0x60b021c */

/*************** Thread 6 (U2E) *******************/
#define COPY_BYTES_THR6_U2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_8_VALUE                                                      (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(28)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9c94 */
#define COPY_BITS_THR6_U2E_PKT_extDSA_fwd_w0__vid_LEN12_TO_CFG_vlan__vid_VALUE                                                   (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(6)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x64b06a2 */
#define COPY_BITS_THR6_U2E_PKT_extDSA_fwd_w0__up_LEN3_TO_CFG_vlan__up_VALUE                                                      (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(6)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x40206a2 */
#define COPY_BITS_THR6_U2E_PKT_extDSA_fwd_w0__cfi_LEN1_TO_CFG_vlan__cfi_VALUE                                                    (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(7)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(6)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(33)) /* 0x5f006a1 */
#define COPY_BITS_THR6_U2E_CFG_targetPortEntry__TPID_LEN16_TO_CFG_vlan__TPID_VALUE                                               (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(4)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0x40f0414 */
#define COPY_BYTES_THR6_U2E_CFG_vlan__TPID_LEN4_TO_PKT_vlan__TPID_VALUE                                                          (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(36)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(4)) /* 0x3a404 */
#define COPY_BYTES_THR6_U2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_4_VALUE                                     (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(24)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9894 */

/*************** THR7_Mrr2E *******************/
#define COPY_BYTES_THR7_Mrr2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_4_VALUE                   (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(24)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9894 */
#define COPY_BITS_THR7_Mrr2E_PKT_DSA_from_cpu__Extend_LEN1_TO_DESC_nonQcn_desc__fw_drop_VALUE   (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(3)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(81)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x5b051a2 */

/*************** THR8_E_V2U *******************/
#define COPY_BYTES_THR8_E_V2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_12_VALUE                                       (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(8)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb8894 */
#define COPY_BITS_THR8_E_V2U_PKT_vlan__vid_LEN12_TO_CFG_eDSA_fwd_w0__eVLAN_11_0_VALUE                               (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x64b02a2 */
#define COPY_BITS_THR8_E_V2U_PKT_vlan__up_LEN3_TO_CFG_eDSA_fwd_w0__UP_VALUE                                         (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x40202a2 */
#define COPY_BITS_THR8_E_V2U_PKT_vlan__cfi_LEN1_TO_CFG_eDSA_fwd_w0__CFI_VALUE                                       (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(7)|ACCEL_CMD_SRC_BIT(3)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(1)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x7b001a2 */
#define COPY_BITS_THR8_E_V2U_CFG_srcPortEntry__src_ePort_13_7_LEN7_TO_CFG_eDSA_fwd_w2__Src_ePort_16_7_PLUS3_VALUE   (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(6)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(7)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(16)) /* 0x7060a10 */
#define COPY_BITS_THR8_E_V2U_CFG_srcPortEntry__src_ePort_6_5_LEN2_TO_CFG_eDSA_fwd_w1__Src_ePort_6_5_VALUE           (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(1)|ACCEL_CMD_SRC_BIT(7)|ACCEL_CMD_LEN(2)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(4)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(16)) /* 0x4f10410 */
#define COPY_BITS_THR8_E_V2U_CFG_srcPortEntry__src_ePort_4_0_LEN5_TO_CFG_eDSA_fwd_w0__Src_ePort_4_0_VALUE           (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(1)|ACCEL_CMD_LEN(5)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(1)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(17)) /* 0x4140111 */
#define COPY_BITS_THR8_E_V2U_DESC_nonQcn_desc__tc_LEN3_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS2_VALUE            (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(6)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(5)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(78)) /* 0x702054e */
#define COPY_BITS_THR8_E_V2U_DESC_nonQcn_desc__dp_1_LEN2_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS5_VALUE          (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(1)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(2)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(6)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(72)) /* 0x4c10648 */
#define COPY_BYTES_THR8_E_V2U_CFG_eDSA_fwd_w0__TagCommand_LEN16_TO_PKT_eDSA_fwd_w0__TagCommand_VALUE                (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(20)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0xf9400 */

/*************** THR9_E2U *******************/
#define COPY_BYTES_THR9_E2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_16_VALUE                                         (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(4)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb8494 */
#define COPY_BITS_THR9_E2U_CFG_srcPortEntry__src_ePort_13_7_LEN7_TO_CFG_eDSA_fwd_w2__Src_ePort_16_7_PLUS3_VALUE     (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(6)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(7)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(16)) /* 0x7060a10 */
#define COPY_BITS_THR9_E2U_CFG_srcPortEntry__src_ePort_6_5_LEN2_TO_CFG_eDSA_fwd_w1__Src_ePort_6_5_VALUE             (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(1)|ACCEL_CMD_SRC_BIT(7)|ACCEL_CMD_LEN(2)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(4)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(16)) /* 0x4f10410 */
#define COPY_BITS_THR9_E2U_CFG_srcPortEntry__src_ePort_4_0_LEN5_TO_CFG_eDSA_fwd_w0__Src_ePort_4_0_VALUE             (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(1)|ACCEL_CMD_LEN(5)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(1)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(17)) /* 0x4140111 */
#define COPY_BITS_THR9_E2U_DESC_nonQcn_desc__tc_LEN3_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS2_VALUE              (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(6)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(5)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(78)) /* 0x702054e */
#define COPY_BITS_THR9_E2U_DESC_nonQcn_desc__dp_1_LEN2_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS5_VALUE            (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(1)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(2)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(6)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(72)) /* 0x4c10648 */
#define COPY_BYTES_THR9_E2U_CFG_eDSA_fwd_w0__TagCommand_LEN16_TO_PKT_eDSA_fwd_w0__TagCommand_VALUE                  (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(16)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0xf9000 */

/*************** THR10_C_V2U *******************/
#define COPY_BYTES_THR10_C_V2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_4_VALUE                                   (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(16)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9094 */
#define COPY_BITS_THR10_C_V2U_CFG_srcPortEntry__reserved2_LEN9_TO_CFG_eDSA_fwd_w2__Src_ePort_16_7_PLUS1_VALUE   (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(9)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(18)) /* 0x6080a12 */
#define COPY_BITS_THR10_C_V2U_CFG_srcPortEntry__reserved2_PLUS9_LEN2_TO_CFG_eDSA_fwd_w1__Src_ePort_6_5_VALUE    (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(1)|ACCEL_CMD_SRC_BIT(1)|ACCEL_CMD_LEN(2)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(4)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(19)) /* 0x4910413 */
#define COPY_BITS_THR10_C_V2U_CFG_srcPortEntry__reserved2_PLUS11_LEN5_TO_CFG_eDSA_fwd_w0__Src_ePort_4_0_VALUE   (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(3)|ACCEL_CMD_LEN(5)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(1)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(19)) /* 0x4340113 */
#define COPY_BITS_THR10_C_V2U_PKT_vlan__vid_LEN12_TO_CFG_eDSA_fwd_w0__eVLAN_11_0_VALUE                          (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(42)) /* 0x64b02aa */
#define COPY_BITS_THR10_C_V2U_PKT_vlan__up_LEN3_TO_CFG_eDSA_fwd_w0__UP_VALUE                                    (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(42)) /* 0x40202aa */
#define COPY_BITS_THR10_C_V2U_PKT_vlan__cfi_LEN1_TO_CFG_eDSA_fwd_w0__CFI_VALUE                                  (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(7)|ACCEL_CMD_SRC_BIT(3)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(1)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(42)) /* 0x7b001aa */
#define COPY_BITS_THR10_C_V2U_DESC_nonQcn_desc__tc_LEN3_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS2_VALUE       (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(6)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(5)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(78)) /* 0x702054e */
#define COPY_BITS_THR10_C_V2U_DESC_nonQcn_desc__dp_1_LEN2_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS5_VALUE     (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(1)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(2)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(6)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(72)) /* 0x4c10648 */
#define COPY_BYTES_THR10_C_V2U_CFG_eDSA_fwd_w0__TagCommand_LEN16_TO_PKT_eDSA_fwd_w0__TagCommand_VALUE           (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(28)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0xf9c00 */
#define COPY_BITS_THR10_C_V2U_CFG_cfgReservedSpace__reserved_0_LEN1_TO_CFG_eDSA_fwd_w2__Src_ePort_16_7_VALUE    (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(28)) /* 0x5800a1c */

/*************** THR11_C2U *******************/
#define COPY_BYTES_THR11_C2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_8_VALUE                                     (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(12)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb8c94 */
#define COPY_BITS_THR11_C2U_CFG_srcPortEntry__reserved2_LEN9_TO_CFG_eDSA_fwd_w2__Src_ePort_16_7_PLUS1_VALUE     (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(9)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(18)) /* 0x6080a12 */
#define COPY_BITS_THR11_C2U_CFG_srcPortEntry__reserved2_PLUS9_LEN2_TO_CFG_eDSA_fwd_w1__Src_ePort_6_5_VALUE      (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(1)|ACCEL_CMD_SRC_BIT(1)|ACCEL_CMD_LEN(2)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(4)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(19)) /* 0x4910413 */
#define COPY_BITS_THR11_C2U_CFG_srcPortEntry__reserved2_PLUS11_LEN5_TO_CFG_eDSA_fwd_w0__Src_ePort_4_0_VALUE     (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(3)|ACCEL_CMD_LEN(5)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(1)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(19)) /* 0x4340113 */
#define COPY_BITS_THR11_C2U_DESC_nonQcn_desc__tc_LEN3_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS2_VALUE         (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(6)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(5)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(78)) /* 0x702054e */
#define COPY_BITS_THR11_C2U_DESC_nonQcn_desc__dp_1_LEN2_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS5_VALUE       (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(1)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(2)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(6)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(72)) /* 0x4c10648 */
#define COPY_BYTES_THR11_C2U_CFG_eDSA_fwd_w0__TagCommand_LEN16_TO_PKT_eDSA_fwd_w0__TagCommand_VALUE             (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(24)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0xf9800 */
#define COPY_BITS_THR11_C2U_CFG_cfgReservedSpace__reserved_0_LEN1_TO_CFG_eDSA_fwd_w2__Src_ePort_16_7_VALUE      (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(28)) /* 0x5800a1c */

/*************** THR12_U_UC2C *******************/
#define COPY_BYTES_THR12_U_UC2C_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_16_VALUE                                    (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(36)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xba494 */
#define COPY_BITS_THR12_U_UC2C_DESC_nonQcn_desc__tc_LEN3_TO_CFG_etag__E_PCP_VALUE                                                (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(78)) /* 0x402004e */
#define COPY_BITS_THR12_U_UC2C_DESC_nonQcn_desc__dp_0_LEN1_TO_CFG_etag__E_DEI_VALUE                                              (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(5)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(72)) /* 0x5d00048 */
#define COPY_BITS_THR12_U_UC2C_PKT_eDSA_fwd_w0__eVLAN_11_0_LEN12_TO_CFG_vlan__vid_VALUE                             (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x64b0aa2 */
#define COPY_BITS_THR12_U_UC2C_PKT_eDSA_fwd_w0__UP_LEN3_TO_CFG_vlan__up_VALUE                                       (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x4020aa2 */
#define COPY_BITS_THR12_U_UC2C_PKT_eDSA_fwd_w0__CFI_LEN1_TO_CFG_vlan__cfi_VALUE                                     (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(7)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(33)) /* 0x5f00aa1 */
#define COPY_BYTES_THR12_U_UC2C_CFG_etag__E_PCP_LEN6_TO_PKT_etag__E_PCP_VALUE                                                    (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(6)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(38)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0x5a600 */
#define COPY_BYTES_THR12_U_UC2C_CFG_vlan__TPID_LEN4_TO_PKT_vlan__TPID_VALUE                                                      (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(44)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(8)) /* 0x3ac08 */
#define COPY_BYTES_THR12_U_UC2C_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_4_VALUE                                                  (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(24)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9894 */
#define COPY_BITS_THR12_U_UC2C_CFG_srcPortEntry__reserved1_PLUS4_LEN12_TO_CFG_etag__E_CID_base_VALUE                             (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(18)) /* 0x64b0212 */
#define COPY_BITS_THR12_U_UC2C_CFG_targetPortEntry__TPID_LEN16_TO_PKT_etag__TPID_VALUE                                           (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(36)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0x40fa414 */

/*************** Thread 13 (U_MC2C) *******************/
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w3__eVIDX_15_12_LEN4_TO_CFG_etag_u_mc2c__eVIDX_full_VALUE                            (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(45)) /* 0x40302ad */
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w1__eVIDX_11_0_LEN12_TO_CFG_etag_u_mc2c__eVIDX_full_PLUS4_VALUE                      (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(38)) /* 0x64b02a6 */
#define COPY_BITS_THR13_U_MC2C_DESC_nonQcn_desc__tc_LEN3_TO_CFG_etag_u_mc2c__E_PCP_VALUE                                         (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(78)) /* 0x402004e */
#define COPY_BITS_THR13_U_MC2C_DESC_nonQcn_desc__dp_0_LEN1_TO_CFG_etag_u_mc2c__E_DEI_VALUE                                       (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(5)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(72)) /* 0x5d00048 */
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w2__Src_ePort_16_7_LEN10_TO_CFG_src_ePort__src_ePort_full_VALUE         (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(3)|ACCEL_CMD_LEN(10)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(12)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(42)) /* 0x4390caa */
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w1__Src_ePort_6_5_LEN2_TO_CFG_src_ePort__src_ePort_full_PLUS10_VALUE    (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(2)|ACCEL_CMD_SRC_BIT(1)|ACCEL_CMD_LEN(2)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(13)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(36)) /* 0x5110da4 */
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w0__Src_ePort_4_0_LEN5_TO_CFG_src_ePort__src_ePort_full_PLUS12_VALUE    (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(5)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(13)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(33)) /* 0x6040da1 */
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w0__eVLAN_11_0_LEN12_TO_CFG_vlan_eDSA__eVLAN_VALUE                      (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x64b0aa2 */
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w0__UP_LEN3_TO_CFG_vlan_eDSA__up_VALUE                                  (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x4020aa2 */
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w0__CFI_LEN1_TO_CFG_vlan_eDSA__cfi_VALUE                                (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(7)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(33)) /* 0x5f00aa1 */
#define COPY_BYTES_THR13_U_MC2C_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_4_VALUE                                     (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(24)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9894 */
#define COPY_BYTES_THR13_U_MC2C_CFG_etag_u_mc2c__E_PCP_LEN6_TO_PKT_etag_u_mc2c__E_PCP_VALUE                                      (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(6)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(38)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0x5a600 */
#define COPY_BYTES_THR13_U_MC2C_CFG_vlan_eDSA__TPID_LEN4_TO_PKT_vlan_eDSA__TPID_VALUE                                            (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(44)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(8)) /* 0x3ac08 */
#define COPY_BITS_THR13_U_MC2C_CFG_cfgReservedSpace__reserved_0_LEN12_TO_CFG_etag_u_mc2c__Ingress_E_CID_base_VALUE               (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(28)) /* 0x60b001c */
#define COPY_BITS_THR13_U_MC2C_CFG_srcPortEntry__reserved1_PLUS4_LEN12_TO_CFG_etag_u_mc2c__Ingress_E_CID_base_VALUE              (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(18)) /* 0x64b0012 */
#define COPY_BITS_THR13_U_MC2C_CFG_targetPortEntry__TPID_LEN16_TO_PKT_etag_u_mc2c__TPID_VALUE                                    (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(36)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0x40fa414 */

/*************** THR14_U_MR2C *******************/
#define COPY_BYTES_THR14_U_MR2C_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_16_VALUE                                    (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(36)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xba494 */
#define COPY_BITS_THR14_U_MR2C_DESC_nonQcn_desc__tc_LEN3_TO_CFG_etag__E_PCP_VALUE                                                (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(78)) /* 0x402004e */
#define COPY_BITS_THR14_U_MR2C_DESC_nonQcn_desc__dp_0_LEN1_TO_CFG_etag__E_DEI_VALUE                                              (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(5)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(72)) /* 0x5d00048 */
#define COPY_BITS_THR14_U_MR2C_PKT_eDSA_w0_ToAnalyzer__eVLAN_11_0_LEN12_TO_CFG_vlan__vid_VALUE                      (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x64b0aa2 */
#define COPY_BITS_THR14_U_MR2C_PKT_eDSA_w0_ToAnalyzer__UP_LEN3_TO_CFG_vlan__up_VALUE                                (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x4020aa2 */
#define COPY_BITS_THR14_U_MR2C_PKT_eDSA_w0_ToAnalyzer__CFI_LEN1_TO_CFG_vlan__cfi_VALUE                              (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(7)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(10)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(33)) /* 0x5f00aa1 */
#define COPY_BITS_THR14_U_MR2C_CFG_targetPortEntry__TPID_LEN16_TO_PKT_etag__TPID_VALUE                                           (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(36)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0x40fa414 */
#define COPY_BYTES_THR14_U_MR2C_CFG_etag__E_PCP_LEN6_TO_PKT_etag__E_PCP_VALUE                                                    (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(6)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(38)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0x5a600 */
#define COPY_BYTES_THR14_U_MR2C_CFG_vlan__TPID_LEN4_TO_PKT_vlan__TPID_VALUE                                                      (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(44)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(8)) /* 0x3ac08 */
#define COPY_BYTES_THR14_U_MR2C_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_4_VALUE                                                  (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(24)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9894 */
#define COPY_BITS_THR14_U_MR2C_CFG_srcPortEntry__reserved1_PLUS4_LEN12_TO_CFG_etag__E_CID_base_VALUE                             (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(18)) /* 0x64b0212 */

/*************** Thread 15 (QCN) *******************/
#define COPY_BITS_THR15_QCN_CFG_targetPortEntry__zero_0_LEN10_TO_PKT_qcn_tag__Version_VALUE                         (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(10)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(42)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0x409aa14 */
#define COPY_BYTES_THR15_QCN_CFG_targetPortEntry__zero_0_LEN12_TO_PKT_qcn_tag__CPID_63_32_VALUE                     (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(44)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xbac14 */
#define COPY_BYTES_THR15_QCN_CFG_targetPortEntry__zero_0_LEN9_TO_PKT_qcn_tag__Encapsulated_priority_VALUE           (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(9)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(56)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0x8b814 */
#define COPY_BYTES_THR15_QCN_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_6_VALUE                                         (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(14)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb8e94 */
#define COPY_BITS_THR15_QCN_DESC_Qcn_desc__congested_port_number_LEN5_TO_CFG_qcn_ha_table__DSA_w0_SrcPort_4_0_VALUE (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(5)|ACCEL_CMD_LEN(5)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(7)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(70)) /* */
#define COPY_BITS_THR15_QCN_DESC_Qcn_desc__qcn_q_fb_LEN6_TO_PKT_qcn_tag__qFb_VALUE                                  (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(2)|ACCEL_CMD_SRC_BIT(7)|ACCEL_CMD_LEN(6)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(43)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(69)) /* 0x575ab45 */
#define COPY_BITS_THR15_QCN_DESC_Qcn_desc__congested_queue_number_LEN3_TO_PKT_qcn_tag__CPID_2_0_VALUE               (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(5)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(51)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(69)) /* 0x6c2b345 */
#define COPY_BYTES_THR15_QCN_CFG_qcn_ha_table__sa_mac_47_32_LEN16_TO_PKT_mac_header__mac_sa_47_32_VALUE             (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(26)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0xf9a00 */

/*************** THR16_U2E *******************/
#define COPY_BYTES_THR16_U2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_12_VALUE                                                      (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(32)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xba094 */
#define COPY_BITS_THR16_U2E_PKT_eDSA_fwd_w0__eVLAN_11_0_LEN12_TO_CFG_vlan__vid_VALUE                                               (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x64b02a2 */
#define COPY_BITS_THR16_U2E_PKT_eDSA_fwd_w0__UP_LEN3_TO_CFG_vlan__up_VALUE                                                         (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(34)) /* 0x40202a2 */
#define COPY_BITS_THR16_U2E_PKT_eDSA_fwd_w0__CFI_LEN1_TO_CFG_vlan__cfi_VALUE                                                       (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(7)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(33)) /* 0x5f002a1 */
#define COPY_BITS_THR16_U2E_CFG_targetPortEntry__TPID_LEN16_TO_CFG_vlan__TPID_VALUE                                                (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0x40f0014 */
#define COPY_BYTES_THR16_U2E_CFG_vlan__TPID_LEN4_TO_PKT_vlan__TPID_VALUE                                                           (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(44)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0x3ac00 */
#define COPY_BYTES_THR16_U2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_16_VALUE                                                      (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(36)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xba494 */
#define COPY_BITS_THR16_U2E_PKT_eDSA_fwd_w0__Src_ePort_4_0_LEN5_TO_CFG_cfgReservedSpaceWithSrc_ePort__Src_ePortFull_PLUS27_VALUE   (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(5)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(31)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(33)) /* 0x5841fa1 */
#define COPY_BITS_THR16_U2E_PKT_eDSA_fwd_w1__Src_ePort_6_5_LEN2_TO_CFG_cfgReservedSpaceWithSrc_ePort__Src_ePortFull_PLUS25_VALUE   (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(1)|ACCEL_CMD_SRC_BIT(1)|ACCEL_CMD_LEN(2)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(31)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(36)) /* 0x4911fa4 */
#define COPY_BITS_THR16_U2E_PKT_eDSA_fwd_w2__Src_ePort_16_7_LEN10_TO_CFG_cfgReservedSpaceWithSrc_ePort__Src_ePortFull_PLUS15_VALUE (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(7)|ACCEL_CMD_SRC_BIT(3)|ACCEL_CMD_LEN(10)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(29)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(42)) /* 0x7b91daa */
#define COPY_BITS_THR16_U2E_CFG_targetPortEntry__trg_ePort_10_0_LEN11_TO_CFG_HA_Table_Target_ePort__Target_ePortFull_PLUS3_VALUE   (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(3)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(11)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(4)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(24)) /* 0x58a0418 */
#define COPY_BITS_THR16_U2E_CFG_targetPortEntry__trg_ePort_13_11_LEN3_TO_CFG_HA_Table_Target_ePort__Target_ePortFull_VALUE         (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(5)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(4)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(23)) /* 0x4520417 */

/*************** THR19_E2U_UNTAGGED *******************/
#define COPY_BYTES_THR19_E2U_Untagged_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_12_VALUE                                            (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(8)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb8894 */
#define COPY_BITS_THR19_E2U_Untagged_CFG_srcPortEntry__PCID_LEN12_TO_CFG_HA_Table_Upstream_Ports__E_CID_base_VALUE               (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(16)) /* 0x60b0210 */
#define COPY_BITS_THR19_E2U_Untagged_DESC_nonQcn_desc__up0_LEN4_TO_CFG_HA_Table_Upstream_Ports__E_PCP_VALUE                      (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(72)) /* 0x4030048 */
#define COPY_BITS_THR19_E2U_Untagged_CFG_srcPortEntry__Uplink_Port_LEN1_TO_CFG_HA_Table_Upstream_Ports__IPL_Direction_VALUE      (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(19)) /* 0x4400213 */
#define COPY_BITS_THR19_E2U_Untagged_CFG_targetPortEntry__TPID_LEN16_TO_PKT_etag__TPID_VALUE                                     (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(20)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0x40f9414 */
#define COPY_BYTES_THR19_E2U_Untagged_CFG_HA_Table_Upstream_Ports__E_PCP_LEN8_TO_PKT_etag__E_PCP_VALUE                           (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(8)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(22)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0x79600 */
#define COPY_BITS_THR19_E2U_Untagged_CFG_srcPortEntry__Default_VLAN_Tag_LEN16_TO_PKT_vlan__up_VALUE                              (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(30)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(17)) /* 0x44f9e11 */

/*************** THR20_U2E_M4 *******************/
#define COPY_BYTES_THR20_U2E_M4_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_12_VALUE                                                 (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(32)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xba094 */
#define COPY_BYTES_THR20_U2E_M4_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_8_VALUE                                                  (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(28)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9c94 */

/*************** THR21_U2E_M8 *******************/
#define COPY_BYTES_THR21_U2E_M8_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_12_VALUE                                                 (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(32)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xba094 */
#define COPY_BYTES_THR21_U2E_M8_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_8_VALUE                                                  (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(28)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9c94 */

/*************** THR23_EVB_E2U *******************/
#define COPY_BYTES_THR23_EVB_E2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_4_VALUE                                                  (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(16)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9094 */
#define COPY_BITS_THR23_EVB_E2U_DESC_nonQcn_desc__up0_LEN4_TO_CFG_vlan__up_VALUE                                                 (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(72)) /* 0x4030248 */
#define COPY_BITS_THR23_EVB_E2U_CFG_srcPortEntry__PVID_LEN12_TO_CFG_vlan__vid_VALUE                                              (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(2)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(16)) /* 0x60b0210 */
#define COPY_BITS_THR23_EVB_E2U_CFG_targetPortEntry__TPID_LEN16_TO_CFG_vlan__TPID_VALUE                                          (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0x40f0014 */
#define COPY_BYTES_THR23_EVB_E2U_CFG_vlan__TPID_LEN4_TO_PKT_vlan__TPID_VALUE                                                     (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(28)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0x39c00 */

/*************** THR24_EVB_U2E *******************/
#define COPY_BYTES_THR24_EVB_U2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_4_VALUE                                                 (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(24)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb9894 */

/*************** THR25_EVB_QCN *******************/
#define COPY_BYTES_THR25_EVB_QCN_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_6_VALUE                                                  (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(14)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb8e94 */
#define COPY_BYTES_THR25_EVB_QCN_CFG_evb_qcn_ha_table__sa_mac_47_32_LEN6_TO_PKT_mac_header__mac_sa_47_32_VALUE                   (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(6)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(26)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0x59a00 */
#define COPY_BITS_THR25_EVB_QCN_CFG_targetPortEntry__TPID_LEN16_TO_PKT_vlan__TPID_VALUE                                          (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(32)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0x40fa014 */
#define COPY_BYTES_THR25_EVB_QCN_CFG_evb_qcn_ha_table__EtherType_LEN10_TO_PKT_qcn_tag__EtherType_VALUE                           (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(10)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(36)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(6)) /* 0x9a406 */
#define COPY_BYTES_THR25_EVB_QCN_CFG_evb_qcn_ha_table__reserved_0_LEN8_TO_PKT_qcn_tag__EtherType_PLUS10_VALUE                    (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(8)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(46)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(8)) /* 0x7ae08 */
#define COPY_BYTES_THR25_EVB_QCN_CFG_evb_qcn_ha_table__reserved_0_LEN7_TO_PKT_qcn_tag__EtherType_PLUS18_VALUE                    (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(7)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(54)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(8)) /* 0x6b608 */
#define COPY_BITS_THR25_EVB_QCN_DESC_Qcn_desc__qcn_q_fb_LEN6_TO_PKT_qcn_tag__qFb_VALUE                                           (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(2)|ACCEL_CMD_SRC_BIT(7)|ACCEL_CMD_LEN(6)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(39)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(69)) /* 0x575a745 */
#define COPY_BITS_THR25_EVB_QCN_DESC_Qcn_desc__congested_queue_number_LEN3_TO_PKT_qcn_tag__CPID_2_0_VALUE                        (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(5)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(47)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(69)) /* 0x6c2af45 */

/*************** THR27_PRE_DA_E2U *******************/
#define COPY_BYTES_THR27_PRE_DA_E2U_CFG_srcPortEntry__reserved_0_LEN2_TO_PKT_pre_da_tag__reserved_VALUE                          (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(2)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(18)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(16)) /* 0x19210 */

/*************** THR45_VariableCyclesLengthWithAcclCmd *******************/
#define COPY_BITS_THR45_VariableCyclesLengthWithAcclCmd_CFG_targetPortEntry__reserved_LEN3_TO_CFG_HA_Table_reserved_space__reserved_2_VALUE (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(5)|ACCEL_CMD_LEN(3)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(8)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(23)) /* 0x4520817 */
#define COPY_BYTES_THR45_VariableCyclesLengthWithAcclCmd_PKT_mac_da_47_32_LEN6_TO_MACSHIFTLEFT_6_VALUE                                      (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(6)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(14)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0x58e94 */

/*************** THR47_Add20Bytes *******************/
#define COPY_BYTES_THR47_Add20Bytes_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_20_VALUE                                                 (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(0)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xb8094 */
#define COPY_BYTES_THR47_Add20Bytes_CFG_HA_Table_reserved_space__reserved_0_LEN16_TO_PKT_HA_Table_reserved_space__reserved_0_VALUE  (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(16)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(12)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(0)) /* 0xf8c00 */
#define COPY_BYTES_THR47_Add20Bytes_CFG_srcPortEntry__PVID_LEN4_TO_PKT_srcPortEntry__PVID_VALUE                                     (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(4)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(28)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(16)) /* 0x39c10 */

/*************** THR48_Remove20Bytes *******************/
#define COPY_BYTES_THR48_Remove20Bytes_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_20_VALUE                                          (ACCEL_CMD_BYTE_COPY|ACCEL_CMD_LEN(12)|ACCEL_CMD_DST_BYTE_TYPE(PKT)|ACCEL_CMD_DST_BYTE(40)|ACCEL_CMD_SRC_BYTE_TYPE(PKT)|ACCEL_CMD_SRC_BYTE(20)) /* 0xba894 */

/*************** PTP *******************/
#define COPY_BITS_PTP_CFG_cfgReservedSpace__reserved_0_LEN1_TO_DESC_nonQcn_desc__mac_timestamping_en_VALUE                       (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(82)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(28)) /* 0x600521c */
#define COPY_BITS_PTP_DESC_nonQcn_desc__is_ptp_LEN1_TO_DESC_nonQcn_desc__mac_timestamping_en_VALUE                               (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(82)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(68)) /* 0x6005244 */
#define COPY_BITS_PTP_CFG_cfgReservedSpace__reserved_0_LEN1_TO_DESC_nonQcn_desc__ptp_egress_tai_sel_VALUE                        (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(90)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(28)) /* 0x6005a1c */
#define COPY_BITS_PTP_CFG_cfgReservedSpace__reserved_0_LEN1_TO_DESC_nonQcn_desc__ptp_timestamp_queue_select_VALUE                (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(5)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(90)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(28)) /* 0x6805a1c */
#define COPY_BITS_PTP_CFG_cfgReservedSpace__reserved_0_LEN1_TO_DESC_nonQcn_desc__ptp_timestamp_queue_entry_id_VALUE              (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(6)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(82)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(28)) /* 0x700521c */
#define COPY_BITS_PTP_DESC_nonQcn_desc__is_ptp_LEN1_TO_DESC_nonQcn_desc__ptp_dispatching_en_VALUE                                (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(0)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(82)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(68)) /* 0x4005244 */
#define COPY_BITS_PTP_CFG_cfgReservedSpace__reserved_0_LEN1_TO_DESC_nonQcn_desc__ptp_cf_wraparound_check_en_VALUE                (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(5)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(82)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(28)) /* 0x680521c */
#define COPY_BITS_PTP_CFG_targetPortEntry__Egress_Pipe_Delay_LEN10_TO_DESC_nonQcn_desc__egress_pipe_delay_PLUS10_VALUE           (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(2)|ACCEL_CMD_SRC_BIT(4)|ACCEL_CMD_LEN(10)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(85)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(25)) /* 0x5495519 */
#define COPY_BITS_PTP_CFG_targetPortEntry__Egress_Pipe_Delay_PLUS10_LEN10_TO_DESC_nonQcn_desc__egress_pipe_delay_PLUS20_VALUE    (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(4)|ACCEL_CMD_SRC_BIT(6)|ACCEL_CMD_LEN(10)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(86)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(26)) /* 0x669561a */
#define COPY_BITS_PTP_DESC_nonQcn_desc__timestamp_Sec_LEN2_TO_DESC_nonQcn_desc__ingress_timestamp_seconds_VALUE                  (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(6)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(2)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(87)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(64)) /* 0x7015740 */
#define COPY_BITS_PTP_DESC_nonQcn_desc__is_ptp_LEN1_TO_DESC_nonQcn_desc__udp_checksum_update_en_VALUE                            (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(7)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(91)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(68)) /* 0x7805b44 */
#define COPY_BITS_PTP_DESC_nonQcn_desc__is_ptp_LEN1_TO_DESC_nonQcn_desc__ptp_cf_wraparound_check_en_VALUE                        (ACCEL_CMD_BIT_COPY|ACCEL_CMD_DST_BIT(5)|ACCEL_CMD_SRC_BIT(0)|ACCEL_CMD_LEN(1)|ACCEL_CMD_DST_BYTE_TYPE(NO_PKT)|ACCEL_CMD_DST_BYTE(82)|ACCEL_CMD_SRC_BYTE_TYPE(NO_PKT)|ACCEL_CMD_SRC_BYTE(68)) /* 0x6805244 */

/**************************************************************************
 * Accelerator commands offsets
 **************************************************************************/
/*************** Thread 1 (E2U) *******************/
#define COPY_BYTES_THR1_E2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_8_OFFSET                                                      (0x0)
#define COPY_BITS_THR1_E2U_CFG_srcPortEntry__PCID_LEN12_TO_CFG_etag__E_CID_base_OFFSET                                           (0x4)
#define COPY_BITS_THR1_E2U_CFG_targetPortEntry__TPID_LEN16_TO_PKT_etag__TPID_OFFSET                                              (0x8)
#define COPY_BYTES_THR1_E2U_CFG_etag__E_PCP_LEN6_TO_PKT_etag__E_PCP_OFFSET                                                       (0xc)
#define COPY_BITS_THR1_E2U_DESC_nonQcn_desc__up0_LEN4_TO_CFG_etag__E_PCP_OFFSET                                                  (0x10)
#define COPY_BITS_THR1_E2U_CFG_srcPortEntry__Uplink_Port_LEN1_TO_CFG_etag__IPL_Direction_OFFSET                                  (0x14)
/*************** Thread 2 (U2E) *******************/
#define COPY_BYTES_THR2_U2E_PKT_mac_da_47_32_PLUS8_LEN12_TO_MACSHIFTRIGHT_12_OFFSET                                              (0x18)
#define COPY_BYTES_THR2_U2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_8_OFFSET                                                     (0x1c)
/*************** Thread 3 (U2C) *******************/
#define COPY_BYTES_THR3_U2C_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_8_OFFSET                                                     (0x20)
#define COPY_BITS_THR3_U2C_CFG_cfgReservedSpace__reserved_0_LEN1_TO_PKT_etag__IPL_Direction_OFFSET                               (0x24)
/*************** Thread 4 (ET2U) *******************/
#define COPY_BITS_THR4_ET2U_CFG_srcPortEntry__src_port_num_LEN4_TO_CFG_DSA_fwd__SrcPort_4_0_PLUS1_OFFSET                         (0x28)
#define COPY_BITS_THR4_ET2U_PKT_vlan__vid_LEN12_TO_CFG_DSA_fwd__vid_OFFSET                                                       (0x2c)
#define COPY_BITS_THR4_ET2U_PKT_vlan__up_LEN3_TO_CFG_DSA_fwd__up_OFFSET                                                          (0x30)
#define COPY_BITS_THR4_ET2U_PKT_vlan__cfi_LEN1_TO_CFG_DSA_fwd__cfi_OFFSET                                                        (0x34)
#define COPY_BYTES_THR4_ET2U_CFG_DSA_fwd__tagCommand_LEN4_TO_PKT_DSA_fwd__tagCommand_OFFSET                                      (0x38)
/*************** Thread 5 (EU2U) *******************/
#define COPY_BITS_THR5_EU2U_CFG_srcPortEntry__src_port_num_LEN4_TO_CFG_DSA_fwd__SrcPort_4_0_PLUS1_OFFSET                         (0x3c)
#define COPY_BYTES_THR5_EU2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_4_OFFSET                                                     (0x40)
#define COPY_BYTES_THR5_EU2U_CFG_DSA_fwd__tagCommand_LEN4_TO_PKT_DSA_fwd__tagCommand_OFFSET                                      (0x44)
#define COPY_BITS_THR5_EU2U_CFG_cfgReservedSpace__reserved_0_LEN12_TO_CFG_DSA_fwd__vid_OFFSET                                    (0x48)
/*************** Thread 6 (U2E) *******************/
#define COPY_BYTES_THR6_U2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_8_OFFSET                                                     (0x4c)
#define COPY_BITS_THR6_U2E_PKT_extDSA_fwd_w0__vid_LEN12_TO_CFG_vlan__vid_OFFSET                                                  (0x50)
#define COPY_BITS_THR6_U2E_PKT_extDSA_fwd_w0__up_LEN3_TO_CFG_vlan__up_OFFSET                                                     (0x54)
#define COPY_BITS_THR6_U2E_PKT_extDSA_fwd_w0__cfi_LEN1_TO_CFG_vlan__cfi_OFFSET                                                   (0x58)
#define COPY_BITS_THR6_U2E_CFG_targetPortEntry__TPID_LEN16_TO_CFG_vlan__TPID_OFFSET                                              (0x5c)
#define COPY_BYTES_THR6_U2E_CFG_vlan__TPID_LEN4_TO_PKT_vlan__TPID_OFFSET                                                         (0x60)
#define COPY_BYTES_THR6_U2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_4_OFFSET                                                     (0x64)

/*************** THR7_Mrr2E *******************/
#define COPY_BYTES_THR7_Mrr2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_4_OFFSET                                                   (0x68)
#define COPY_BITS_THR7_Mrr2E_PKT_DSA_from_cpu__Extend_LEN1_TO_DESC_nonQcn_desc__fw_drop_OFFSET                                   (0x6c)

/*************** THR8_E_V2U *******************/
#define COPY_BYTES_THR8_E_V2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_12_OFFSET                                                   (0x70)
#define COPY_BITS_THR8_E_V2U_PKT_vlan__vid_LEN12_TO_CFG_eDSA_fwd_w0__eVLAN_11_0_OFFSET                                           (0x74)
#define COPY_BITS_THR8_E_V2U_PKT_vlan__up_LEN3_TO_CFG_eDSA_fwd_w0__UP_OFFSET                                                     (0x78)
#define COPY_BITS_THR8_E_V2U_PKT_vlan__cfi_LEN1_TO_CFG_eDSA_fwd_w0__CFI_OFFSET                                                   (0x7c)
#define COPY_BITS_THR8_E_V2U_CFG_srcPortEntry__src_ePort_13_7_LEN7_TO_CFG_eDSA_fwd_w2__Src_ePort_16_7_PLUS3_OFFSET               (0x80)
#define COPY_BITS_THR8_E_V2U_CFG_srcPortEntry__src_ePort_6_5_LEN2_TO_CFG_eDSA_fwd_w1__Src_ePort_6_5_OFFSET                       (0x84)
#define COPY_BITS_THR8_E_V2U_CFG_srcPortEntry__src_ePort_4_0_LEN5_TO_CFG_eDSA_fwd_w0__Src_ePort_4_0_OFFSET                       (0x88)
#define COPY_BITS_THR8_E_V2U_DESC_nonQcn_desc__tc_LEN3_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS2_OFFSET                        (0x8c)
#define COPY_BITS_THR8_E_V2U_DESC_nonQcn_desc__dp_1_LEN2_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS5_OFFSET                      (0x90)
#define COPY_BYTES_THR8_E_V2U_CFG_eDSA_fwd_w0__TagCommand_LEN16_TO_PKT_eDSA_fwd_w0__TagCommand_OFFSET                            (0x94)

/*************** THR9_E2U *******************/
#define COPY_BYTES_THR9_E2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_16_OFFSET                                                     (0x98)
#define COPY_BITS_THR9_E2U_CFG_srcPortEntry__src_ePort_13_7_LEN7_TO_CFG_eDSA_fwd_w2__Src_ePort_16_7_PLUS3_OFFSET                 (0x9c)
#define COPY_BITS_THR9_E2U_CFG_srcPortEntry__src_ePort_6_5_LEN2_TO_CFG_eDSA_fwd_w1__Src_ePort_6_5_OFFSET                         (0xa0)
#define COPY_BITS_THR9_E2U_CFG_srcPortEntry__src_ePort_4_0_LEN5_TO_CFG_eDSA_fwd_w0__Src_ePort_4_0_OFFSET                         (0xa4)
#define COPY_BITS_THR9_E2U_DESC_nonQcn_desc__tc_LEN3_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS2_OFFSET                          (0xa8)
#define COPY_BITS_THR9_E2U_DESC_nonQcn_desc__dp_1_LEN2_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS5_OFFSET                        (0xac)
#define COPY_BYTES_THR9_E2U_CFG_eDSA_fwd_w0__TagCommand_LEN16_TO_PKT_eDSA_fwd_w0__TagCommand_OFFSET                              (0xb0)

/*************** THR10_C_V2U *******************/
#define COPY_BYTES_THR10_C_V2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_4_OFFSET                                                   (0xb4)
#define COPY_BITS_THR10_C_V2U_CFG_srcPortEntry__reserved2_LEN9_TO_CFG_eDSA_fwd_w2__Src_ePort_16_7_PLUS1_OFFSET                   (0xb8)
#define COPY_BITS_THR10_C_V2U_CFG_srcPortEntry__reserved2_PLUS9_LEN2_TO_CFG_eDSA_fwd_w1__Src_ePort_6_5_OFFSET                    (0xbc)
#define COPY_BITS_THR10_C_V2U_CFG_srcPortEntry__reserved2_PLUS11_LEN5_TO_CFG_eDSA_fwd_w0__Src_ePort_4_0_OFFSET                   (0xc0)
#define COPY_BITS_THR10_C_V2U_PKT_vlan__vid_LEN12_TO_CFG_eDSA_fwd_w0__eVLAN_11_0_OFFSET                                          (0xc4)
#define COPY_BITS_THR10_C_V2U_PKT_vlan__up_LEN3_TO_CFG_eDSA_fwd_w0__UP_OFFSET                                                    (0xc8)
#define COPY_BITS_THR10_C_V2U_PKT_vlan__cfi_LEN1_TO_CFG_eDSA_fwd_w0__CFI_OFFSET                                                  (0xcc)
#define COPY_BITS_THR10_C_V2U_DESC_nonQcn_desc__tc_LEN3_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS2_OFFSET                       (0xd0)
#define COPY_BITS_THR10_C_V2U_DESC_nonQcn_desc__dp_1_LEN2_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS5_OFFSET                     (0xd4)
#define COPY_BYTES_THR10_C_V2U_CFG_eDSA_fwd_w0__TagCommand_LEN16_TO_PKT_eDSA_fwd_w0__TagCommand_OFFSET                           (0xd8)
#define COPY_BITS_THR10_C_V2U_CFG_cfgReservedSpace__reserved_0_LEN1_TO_CFG_eDSA_fwd_w2__Src_ePort_16_7_OFFSET                    (0xdc)

/*************** THR11_C2U *******************/
#define COPY_BYTES_THR11_C2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_8_OFFSET                                                     (0xe0)
#define COPY_BITS_THR11_C2U_CFG_srcPortEntry__reserved2_LEN9_TO_CFG_eDSA_fwd_w2__Src_ePort_16_7_PLUS1_OFFSET                     (0xe4)
#define COPY_BITS_THR11_C2U_CFG_srcPortEntry__reserved2_PLUS9_LEN2_TO_CFG_eDSA_fwd_w1__Src_ePort_6_5_OFFSET                      (0xe8)
#define COPY_BITS_THR11_C2U_CFG_srcPortEntry__reserved2_PLUS11_LEN5_TO_CFG_eDSA_fwd_w0__Src_ePort_4_0_OFFSET                     (0xec)
#define COPY_BITS_THR11_C2U_DESC_nonQcn_desc__tc_LEN3_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS2_OFFSET                         (0xf0)
#define COPY_BITS_THR11_C2U_DESC_nonQcn_desc__dp_1_LEN2_TO_CFG_eDSA_fwd_w1__GlobalQoS_Profile_PLUS5_OFFSET                       (0xf4)
#define COPY_BYTES_THR11_C2U_CFG_eDSA_fwd_w0__TagCommand_LEN16_TO_PKT_eDSA_fwd_w0__TagCommand_OFFSET                             (0xf8)
#define COPY_BITS_THR11_C2U_CFG_cfgReservedSpace__reserved_0_LEN1_TO_CFG_eDSA_fwd_w2__Src_ePort_16_7_OFFSET                      (0xfc)

/*************** THR12_U_UC2C *******************/
#define COPY_BYTES_THR12_U_UC2C_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_16_OFFSET                                                (0x100)
#define COPY_BITS_THR12_U_UC2C_DESC_nonQcn_desc__tc_LEN3_TO_CFG_etag__E_PCP_OFFSET                                               (0x104)
#define COPY_BITS_THR12_U_UC2C_DESC_nonQcn_desc__dp_0_LEN1_TO_CFG_etag__E_DEI_OFFSET                                             (0x108)
#define COPY_BITS_THR12_U_UC2C_PKT_eDSA_fwd_w0__eVLAN_11_0_LEN12_TO_CFG_vlan__vid_OFFSET                                         (0x10c)
#define COPY_BITS_THR12_U_UC2C_PKT_eDSA_fwd_w0__UP_LEN3_TO_CFG_vlan__up_OFFSET                                                   (0x110)
#define COPY_BITS_THR12_U_UC2C_PKT_eDSA_fwd_w0__CFI_LEN1_TO_CFG_vlan__cfi_OFFSET                                                 (0x114)
#define COPY_BYTES_THR12_U_UC2C_CFG_etag__E_PCP_LEN6_TO_PKT_etag__E_PCP_OFFSET                                                   (0x118)
#define COPY_BYTES_THR12_U_UC2C_CFG_vlan__TPID_LEN4_TO_PKT_vlan__TPID_OFFSET                                                     (0x11c)
#define COPY_BYTES_THR12_U_UC2C_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_4_OFFSET                                                 (0x120)
#define COPY_BITS_THR12_U_UC2C_CFG_srcPortEntry__reserved1_PLUS4_LEN12_TO_CFG_etag__E_CID_base_OFFSET                            (0x124)
#define COPY_BITS_THR12_U_UC2C_CFG_targetPortEntry__TPID_LEN16_TO_PKT_etag__TPID_OFFSET                                          (0x128)

/*************** THR13_U_MC2C *******************/
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w3__eVIDX_15_12_LEN4_TO_CFG_etag_u_mc2c__eVIDX_full_OFFSET                           (0x12c)
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w1__eVIDX_11_0_LEN12_TO_CFG_etag_u_mc2c__eVIDX_full_PLUS4_OFFSET                     (0x130)
#define COPY_BITS_THR13_U_MC2C_DESC_nonQcn_desc__tc_LEN3_TO_CFG_etag_u_mc2c__E_PCP_OFFSET                                        (0x134)
#define COPY_BITS_THR13_U_MC2C_DESC_nonQcn_desc__dp_0_LEN1_TO_CFG_etag_u_mc2c__E_DEI_OFFSET                                      (0x138)
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w2__Src_ePort_16_7_LEN10_TO_CFG_src_ePort__src_ePort_full_OFFSET                     (0x13c)
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w1__Src_ePort_6_5_LEN2_TO_CFG_src_ePort__src_ePort_full_PLUS10_OFFSET                (0x140)
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w0__Src_ePort_4_0_LEN5_TO_CFG_src_ePort__src_ePort_full_PLUS12_OFFSET                (0x144)
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w0__eVLAN_11_0_LEN12_TO_CFG_vlan_eDSA__eVLAN_OFFSET                                  (0x148)
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w0__UP_LEN3_TO_CFG_vlan_eDSA__up_OFFSET                                              (0x14c)
#define COPY_BITS_THR13_U_MC2C_PKT_eDSA_fwd_w0__CFI_LEN1_TO_CFG_vlan_eDSA__cfi_OFFSET                                            (0x150)
#define COPY_BYTES_THR13_U_MC2C_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_4_OFFSET                                                 (0x154)
#define COPY_BYTES_THR13_U_MC2C_CFG_etag_u_mc2c__E_PCP_LEN6_TO_PKT_etag_u_mc2c__E_PCP_OFFSET                                     (0x158)
#define COPY_BYTES_THR13_U_MC2C_CFG_vlan_eDSA__TPID_LEN4_TO_PKT_vlan_eDSA__TPID_OFFSET                                           (0x15c)
#define COPY_BITS_THR13_U_MC2C_CFG_cfgReservedSpace__reserved_0_LEN12_TO_CFG_etag_u_mc2c__Ingress_E_CID_base_OFFSET              (0x160)
#define COPY_BITS_THR13_U_MC2C_CFG_srcPortEntry__reserved1_PLUS4_LEN12_TO_CFG_etag_u_mc2c__Ingress_E_CID_base_OFFSET             (0x164)
#define COPY_BITS_THR13_U_MC2C_CFG_targetPortEntry__TPID_LEN16_TO_PKT_etag_u_mc2c__TPID_OFFSET                                   (0x168)

/*************** THR14_U_MR2C *******************/
#define COPY_BYTES_THR14_U_MR2C_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_16_OFFSET                                                (0x16c)
#define COPY_BITS_THR14_U_MR2C_DESC_nonQcn_desc__tc_LEN3_TO_CFG_etag__E_PCP_OFFSET                                               (0x170)
#define COPY_BITS_THR14_U_MR2C_DESC_nonQcn_desc__dp_0_LEN1_TO_CFG_etag__E_DEI_OFFSET                                             (0x174)
#define COPY_BITS_THR14_U_MR2C_PKT_eDSA_w0_ToAnalyzer__eVLAN_11_0_LEN12_TO_CFG_vlan__vid_OFFSET                                  (0x178)
#define COPY_BITS_THR14_U_MR2C_PKT_eDSA_w0_ToAnalyzer__UP_LEN3_TO_CFG_vlan__up_OFFSET                                            (0x17c)
#define COPY_BITS_THR14_U_MR2C_PKT_eDSA_w0_ToAnalyzer__CFI_LEN1_TO_CFG_vlan__cfi_OFFSET                                          (0x180)
#define COPY_BITS_THR14_U_MR2C_CFG_targetPortEntry__TPID_LEN16_TO_PKT_etag__TPID_OFFSET                                          (0x184)
#define COPY_BYTES_THR14_U_MR2C_CFG_etag__E_PCP_LEN6_TO_PKT_etag__E_PCP_OFFSET                                                   (0x188)
#define COPY_BYTES_THR14_U_MR2C_CFG_vlan__TPID_LEN4_TO_PKT_vlan__TPID_OFFSET                                                     (0x18c)
#define COPY_BYTES_THR14_U_MR2C_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_4_OFFSET                                                 (0x190)
#define COPY_BITS_THR14_U_MR2C_CFG_srcPortEntry__reserved1_PLUS4_LEN12_TO_CFG_etag__E_CID_base_OFFSET                            (0x194)

/*************** THR15_QCN *******************/
#define COPY_BITS_THR15_QCN_CFG_targetPortEntry__zero_0_LEN10_TO_PKT_qcn_tag__Version_OFFSET                                     (0x198)
#define COPY_BYTES_THR15_QCN_CFG_targetPortEntry__zero_0_LEN12_TO_PKT_qcn_tag__CPID_63_32_OFFSET                                 (0x19c)
#define COPY_BYTES_THR15_QCN_CFG_targetPortEntry__zero_0_LEN9_TO_PKT_qcn_tag__Encapsulated_priority_OFFSET                       (0x1a0)
#define COPY_BYTES_THR15_QCN_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_6_OFFSET                                                     (0x1a4)
#define COPY_BITS_THR15_QCN_DESC_Qcn_desc__congested_port_number_LEN5_TO_CFG_qcn_ha_table__DSA_w0_SrcPort_4_0_OFFSET             (0x1a8)
#define COPY_BITS_THR15_QCN_DESC_Qcn_desc__qcn_q_fb_LEN6_TO_PKT_qcn_tag__qFb_OFFSET                                              (0x1ac)
#define COPY_BITS_THR15_QCN_DESC_Qcn_desc__congested_queue_number_LEN3_TO_PKT_qcn_tag__CPID_2_0_OFFSET                           (0x1b0)
#define COPY_BYTES_THR15_QCN_CFG_qcn_ha_table__sa_mac_47_32_LEN16_TO_PKT_mac_header__mac_sa_47_32_OFFSET                         (0x1b4)

/*************** THR16_U2E *******************/
#define COPY_BYTES_THR16_U2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_12_OFFSET                                                   (0x1b8)
#define COPY_BITS_THR16_U2E_PKT_eDSA_fwd_w0__eVLAN_11_0_LEN12_TO_CFG_vlan__vid_OFFSET                                            (0x1bc)
#define COPY_BITS_THR16_U2E_PKT_eDSA_fwd_w0__UP_LEN3_TO_CFG_vlan__up_OFFSET                                                      (0x1c0)
#define COPY_BITS_THR16_U2E_PKT_eDSA_fwd_w0__CFI_LEN1_TO_CFG_vlan__cfi_OFFSET                                                    (0x1c4)
#define COPY_BITS_THR16_U2E_CFG_targetPortEntry__TPID_LEN16_TO_CFG_vlan__TPID_OFFSET                                             (0x1c8)
#define COPY_BYTES_THR16_U2E_CFG_vlan__TPID_LEN4_TO_PKT_vlan__TPID_OFFSET                                                        (0x1cc)
#define COPY_BYTES_THR16_U2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_16_OFFSET                                                   (0x1d0)
#define COPY_BITS_THR16_U2E_PKT_eDSA_fwd_w0__Src_ePort_4_0_LEN5_TO_CFG_cfgReservedSpaceWithSrc_ePort__Src_ePortFull_PLUS27_OFFSET (0x1d4)
#define COPY_BITS_THR16_U2E_PKT_eDSA_fwd_w1__Src_ePort_6_5_LEN2_TO_CFG_cfgReservedSpaceWithSrc_ePort__Src_ePortFull_PLUS25_OFFSET (0x1d8)
#define COPY_BITS_THR16_U2E_PKT_eDSA_fwd_w2__Src_ePort_16_7_LEN10_TO_CFG_cfgReservedSpaceWithSrc_ePort__Src_ePortFull_PLUS15_OFFSET (0x1dc)
#define COPY_BITS_THR16_U2E_CFG_targetPortEntry__trg_ePort_10_0_LEN11_TO_CFG_HA_Table_Target_ePort__Target_ePortFull_PLUS3_OFFSET (0x1e0)
#define COPY_BITS_THR16_U2E_CFG_targetPortEntry__trg_ePort_13_11_LEN3_TO_CFG_HA_Table_Target_ePort__Target_ePortFull_OFFSET      (0x1e4)

/*************** THR19_E2U_Untagged *******************/
#define COPY_BYTES_THR19_E2U_Untagged_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_12_OFFSET                                           (0x1e8)
#define COPY_BITS_THR19_E2U_Untagged_CFG_srcPortEntry__PCID_LEN12_TO_CFG_HA_Table_Upstream_Ports__E_CID_base_OFFSET              (0x1ec)
#define COPY_BITS_THR19_E2U_Untagged_DESC_nonQcn_desc__up0_LEN4_TO_CFG_HA_Table_Upstream_Ports__E_PCP_OFFSET                     (0x1f0)
#define COPY_BITS_THR19_E2U_Untagged_CFG_srcPortEntry__Uplink_Port_LEN1_TO_CFG_HA_Table_Upstream_Ports__IPL_Direction_OFFSET     (0x1f4)
#define COPY_BITS_THR19_E2U_Untagged_CFG_targetPortEntry__TPID_LEN16_TO_PKT_etag__TPID_OFFSET                                    (0x1f8)
#define COPY_BYTES_THR19_E2U_Untagged_CFG_HA_Table_Upstream_Ports__E_PCP_LEN8_TO_PKT_etag__E_PCP_OFFSET                          (0x1fc)
#define COPY_BITS_THR19_E2U_Untagged_CFG_srcPortEntry__Default_VLAN_Tag_LEN16_TO_PKT_vlan__up_OFFSET                             (0x200)

/*************** THR20_U2E_M4 *******************/
#define COPY_BYTES_THR20_U2E_M4_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_12_OFFSET                                                (0x204)
#define COPY_BYTES_THR20_U2E_M4_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_8_OFFSET                                                 (0x208)

/*************** THR21_U2E_M8 *******************/
#define COPY_BYTES_THR21_U2E_M8_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_12_OFFSET                                                (0x20c)
#define COPY_BYTES_THR21_U2E_M8_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_8_OFFSET                                                 (0x210)

/*************** THR23_EVB_E2U *******************/
#define COPY_BYTES_THR23_EVB_E2U_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_4_OFFSET                                                 (0x214)
#define COPY_BITS_THR23_EVB_E2U_DESC_nonQcn_desc__up0_LEN4_TO_CFG_vlan__up_OFFSET                                                (0x218)
#define COPY_BITS_THR23_EVB_E2U_CFG_srcPortEntry__PVID_LEN12_TO_CFG_vlan__vid_OFFSET                                             (0x21c)
#define COPY_BITS_THR23_EVB_E2U_CFG_targetPortEntry__TPID_LEN16_TO_CFG_vlan__TPID_OFFSET                                         (0x220)
#define COPY_BYTES_THR23_EVB_E2U_CFG_vlan__TPID_LEN4_TO_PKT_vlan__TPID_OFFSET                                                    (0x224)

/*************** THR24_EVB_U2E *******************/
#define COPY_BYTES_THR24_EVB_U2E_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_4_OFFSET                                                (0x228)

/*************** THR25_EVB_QCN *******************/
#define COPY_BYTES_THR25_EVB_QCN_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_6_OFFSET                                                 (0x22c)
#define COPY_BYTES_THR25_EVB_QCN_CFG_evb_qcn_ha_table__sa_mac_47_32_LEN6_TO_PKT_mac_header__mac_sa_47_32_OFFSET                  (0x230)
#define COPY_BITS_THR25_EVB_QCN_CFG_targetPortEntry__TPID_LEN16_TO_PKT_vlan__TPID_OFFSET                                         (0x234)
#define COPY_BYTES_THR25_EVB_QCN_CFG_evb_qcn_ha_table__EtherType_LEN10_TO_PKT_qcn_tag__EtherType_OFFSET                          (0x238)
#define COPY_BYTES_THR25_EVB_QCN_CFG_evb_qcn_ha_table__reserved_0_LEN8_TO_PKT_qcn_tag__EtherType_PLUS10_OFFSET                   (0x23c)
#define COPY_BYTES_THR25_EVB_QCN_CFG_evb_qcn_ha_table__reserved_0_LEN7_TO_PKT_qcn_tag__EtherType_PLUS18_OFFSET                   (0x240)
#define COPY_BITS_THR25_EVB_QCN_DESC_Qcn_desc__qcn_q_fb_LEN6_TO_PKT_qcn_tag__qFb_OFFSET                                          (0x244)
#define COPY_BITS_THR25_EVB_QCN_DESC_Qcn_desc__congested_queue_number_LEN3_TO_PKT_qcn_tag__CPID_2_0_OFFSET                       (0x248)

/*************** THR27_PRE_DA_E2U *******************/
#define COPY_BYTES_THR27_PRE_DA_E2U_CFG_srcPortEntry__reserved_0_LEN2_TO_PKT_pre_da_tag__reserved_OFFSET                         (0x24c)

/*************** THR45_VariableCyclesLengthWithAcclCmd *******************/
#define COPY_BITS_THR45_VariableCyclesLengthWithAcclCmd_CFG_targetPortEntry__reserved_LEN3_TO_CFG_HA_Table_reserved_space__reserved_2_OFFSET (0x250)
#define COPY_BYTES_THR45_VariableCyclesLengthWithAcclCmd_PKT_mac_da_47_32_LEN6_TO_MACSHIFTLEFT_6_OFFSET                          (0x254)

/*************** THR47_Add20Bytes *******************/
#define COPY_BYTES_THR47_Add20Bytes_PKT_mac_da_47_32_LEN12_TO_MACSHIFTLEFT_20_OFFSET                                             (0x258)
#define COPY_BYTES_THR47_Add20Bytes_CFG_HA_Table_reserved_space__reserved_0_LEN16_TO_PKT_HA_Table_reserved_space__reserved_0_OFFSET (0x25c)
#define COPY_BYTES_THR47_Add20Bytes_CFG_srcPortEntry__PVID_LEN4_TO_PKT_srcPortEntry__PVID_OFFSET                                 (0x260)

/*************** THR48_Remove20Bytes *******************/
#define COPY_BYTES_THR48_Remove20Bytes_PKT_mac_da_47_32_LEN12_TO_MACSHIFTRIGHT_20_OFFSET                                         (0x264)

/*************** PTP *******************/
#define COPY_BITS_PTP_CFG_cfgReservedSpace__reserved_0_LEN1_TO_DESC_nonQcn_desc__mac_timestamping_en_OFFSET                      (0x268)
#define COPY_BITS_PTP_DESC_nonQcn_desc__is_ptp_LEN1_TO_DESC_nonQcn_desc__mac_timestamping_en_OFFSET                              (0x26c)
#define COPY_BITS_PTP_CFG_cfgReservedSpace__reserved_0_LEN1_TO_DESC_nonQcn_desc__ptp_egress_tai_sel_OFFSET                       (0x270)
#define COPY_BITS_PTP_CFG_cfgReservedSpace__reserved_0_LEN1_TO_DESC_nonQcn_desc__ptp_timestamp_queue_select_OFFSET               (0x274)
#define COPY_BITS_PTP_CFG_cfgReservedSpace__reserved_0_LEN1_TO_DESC_nonQcn_desc__ptp_timestamp_queue_entry_id_OFFSET             (0x278)
#define COPY_BITS_PTP_DESC_nonQcn_desc__is_ptp_LEN1_TO_DESC_nonQcn_desc__ptp_dispatching_en_OFFSET                               (0x27c)
#define COPY_BITS_PTP_CFG_cfgReservedSpace__reserved_0_LEN1_TO_DESC_nonQcn_desc__ptp_cf_wraparound_check_en_OFFSET               (0x280)
#define COPY_BITS_PTP_CFG_targetPortEntry__Egress_Pipe_Delay_LEN10_TO_DESC_nonQcn_desc__egress_pipe_delay_PLUS10_OFFSET          (0x284)
#define COPY_BITS_PTP_CFG_targetPortEntry__Egress_Pipe_Delay_PLUS10_LEN10_TO_DESC_nonQcn_desc__egress_pipe_delay_PLUS20_OFFSET   (0x288)
#define COPY_BITS_PTP_DESC_nonQcn_desc__timestamp_Sec_LEN2_TO_DESC_nonQcn_desc__ingress_timestamp_seconds_OFFSET                 (0x28c)
#define COPY_BITS_PTP_DESC_nonQcn_desc__is_ptp_LEN1_TO_DESC_nonQcn_desc__udp_checksum_update_en_OFFSET                           (0x290)
#define COPY_BITS_PTP_DESC_nonQcn_desc__is_ptp_LEN1_TO_DESC_nonQcn_desc__ptp_cf_wraparound_check_en_OFFSET                       (0x294)

/*************** Last Entry *******************/
#define ACCELERATOR_COMMAND_OFFSET_LAST_ENTRY                                                                                    (0x294)

/**************************************************************************
 * Accelerator command Trigger and load macros
 **************************************************************************/
/* Trigger the accelerator by writing dummy value to the Accelerator Instruction Trigger area */
#define ACCEL_CMD_TRIG(offset,value)	PPA_FW_SP_WRITE(ACCEL_CMDS_TRIG_BASE_ADDR + offset,value)
/* Load the accelerator command data into SP memory */
#define ACCEL_CMD_LOAD(offset,value)	PPA_FW_SP_WRITE(ACCEL_CMDS_CFG_BASE_ADDR + offset,value)

