#!/usr/bin/env python
# enumDict.py
#
#/*******************************************************************************
#* Copyright (c) 2021 Marvell. All rights reserved. The following file is       *
#* subject to the limited use license agreement by and between Marvell and you, *
#* your employer or other entity on behalf of whom you act. In the absence of   *
#* such license agreement the following file is subject to Marvell`s standard   *
#* Limited Use License Agreement.                                               *
#*******************************************************************************/
#* This file is auto generated file                                            */
#* Last Modification Time :  Fri Apr 28 14:33:19 2017                          */
#*******************************************************************************/
#* @file enumDict.py
#

# Dictionary for enum
enumDictionaries = {
   'hashField' :
    {
        'XP_ETHERNET_MAC_DA' : 0,
        'XP_ETHERNET_MAC_SA' : 1,
        'XP_ETHERNET_E_TAG_TPID' : 2,
        'XP_ETHERNET_E_TAG_E_PCP' : 3,
        'XP_ETHERNET_E_TAG_E_DEI' : 4,
        'XP_ETHERNET_E_TAG_INGRESS_E_CID_BASE' : 5,
        'XP_ETHERNET_E_TAG_RESERVED' : 6,
        'XP_ETHERNET_E_TAG_GRP' : 7,
        'XP_ETHERNET_E_TAG_E_CID_BASE' : 8,
        'XP_ETHERNET_E_TAG_INGRESS_E_CID_EXT' : 9,
        'XP_ETHERNET_E_TAG_E_CID_EXT' : 10,
        'XP_ETHERNET_O_TAG_TPID' : 11,
        'XP_ETHERNET_O_TAG_PCP' : 12,
        'XP_ETHERNET_O_TAG_DEI' : 13,
        'XP_ETHERNET_O_TAG_VID' : 14,
        'XP_ETHERNET_S_TAG_TPID' : 15,
        'XP_ETHERNET_S_TAG_PCP' : 16,
        'XP_ETHERNET_S_TAG_DEI' : 17,
        'XP_ETHERNET_S_TAG_VID' : 18,
        'XP_ETHERNET_C_TAG_TPID' : 19,
        'XP_ETHERNET_C_TAG_PCP' : 20,
        'XP_ETHERNET_C_TAG_DEI' : 21,
        'XP_ETHERNET_C_TAG_VID' : 22,
        'XP_ETHERNET_ETHERTYPE' : 23,
        'XP_TU_ETHER_MAC_DA' : 24,
        'XP_TU_ETHER_MAC_SA' : 25,
        'XP_TU_ETHER_S_TAG_TPID' : 26,
        'XP_TU_ETHER_S_TAG_PCP' : 27,
        'XP_TU_ETHER_S_TAG_DEI' : 28,
        'XP_TU_ETHER_S_TAG_VID' : 29,
        'XP_TU_ETHER_C_TAG_TPID' : 30,
        'XP_TU_ETHER_C_TAG_PCP' : 31,
        'XP_TU_ETHER_C_TAG_DEI' : 32,
        'XP_TU_ETHER_C_TAG_VID' : 33,
        'XP_TU_ETHER_ETHERTYPE' : 34,
        'XP_ULL_ETHERNET_MAC_DA' : 35,
        'XP_ULL_ETHERNET_MAC_SA' : 36,
        'XP_ULL_ETHERNET_C_TAG_TPID' : 37,
        'XP_ULL_ETHERNET_C_TAG_PCP' : 38,
        'XP_ULL_ETHERNET_C_TAG_DEI' : 39,
        'XP_ULL_ETHERNET_C_TAG_VID' : 40,
        'XP_ULL_ETHERNET_ETHERTYPE' : 41,
        'XP_PBB_MAC_DA' : 42,
        'XP_PBB_MAC_SA' : 43,
        'XP_PBB_E_TAG_TPID' : 44,
        'XP_PBB_E_TAG_E_PCP' : 45,
        'XP_PBB_E_TAG_E_DEI' : 46,
        'XP_PBB_E_TAG_INGRESS_E_CID_BASE' : 47,
        'XP_PBB_E_TAG_RESERVED' : 48,
        'XP_PBB_E_TAG_GRP' : 49,
        'XP_PBB_E_TAG_E_CID_BASE' : 50,
        'XP_PBB_E_TAG_INGRESS_E_CID_EXT' : 51,
        'XP_PBB_E_TAG_E_CID_EXT' : 52,
        'XP_PBB_O_TAG_TPID' : 53,
        'XP_PBB_O_TAG_PCP' : 54,
        'XP_PBB_O_TAG_DEI' : 55,
        'XP_PBB_O_TAG_VID' : 56,
        'XP_PBB_B_TAG_TPID' : 57,
        'XP_PBB_B_TAG_PCP' : 58,
        'XP_PBB_B_TAG_DEI' : 59,
        'XP_PBB_B_TAG_VID' : 60,
        'XP_PBB_I_SID_TPID' : 61,
        'XP_PBB_I_SID_I_PCP' : 62,
        'XP_PBB_I_SID_I_DEI' : 63,
        'XP_PBB_I_SID_UCA' : 64,
        'XP_PBB_I_SID_RESERVED' : 65,
        'XP_PBB_I_SID' : 66,
        'XP_ARP_HTYPE' : 67,
        'XP_ARP_PTYPE' : 68,
        'XP_ARP_HLEN' : 69,
        'XP_ARP_PLEN' : 70,
        'XP_ARP_OPER' : 71,
        'XP_ARP_SHA' : 72,
        'XP_ARP_SPA' : 73,
        'XP_ARP_SHA_2' : 74,
        'XP_ARP_SPA_2' : 75,
        'XP_IPV4_VERSION' : 76,
        'XP_IPV4_IHL' : 77,
        'XP_IPV4_DSCP' : 78,
        'XP_IPV4_ECN' : 79,
        'XP_IPV4_TOTAL_LENGTH' : 80,
        'XP_IPV4_IDENTIFICATION' : 81,
        'XP_IPV4_RESERVED_1' : 82,
        'XP_IPV4_DF' : 83,
        'XP_IPV4_MF' : 84,
        'XP_IPV4_FRAGMENT_OFFSET' : 85,
        'XP_IPV4_TIME_TO_LIVE' : 86,
        'XP_IPV4_PROTOCOL' : 87,
        'XP_IPV4_HEADER_CHECKSUM' : 88,
        'XP_IPV4_SOURCE_IP_ADDRESS' : 89,
        'XP_IPV4_DESTINATION_IP_ADDRESS' : 90,
        'XP_IPV4_OPTIONS' : 91,
        'XP_IPV6_VERSION' : 92,
        'XP_IPV6_ECN' : 93,
        'XP_IPV6_FLOW_LABEL' : 94,
        'XP_IPV6_PAYLOAD_LENGTH' : 95,
        'XP_IPV6_NEXT_HEADER' : 96,
        'XP_IPV6_TIME_TO_LIVE' : 97,
        'XP_IPV6_SPLIT_SOURCE_IP_ADDRESS' : 98,
        'XP_IPV6_SPLIT_DESTINATION_IP_ADDRESS' : 99,
        'XP_MPLS_LABEL0' : 100,
        'XP_MPLS_EXP0' : 101,
        'XP_MPLS_BS0' : 102,
        'XP_MPLS_TTL0' : 103,
        'XP_MPLS_LABEL1' : 104,
        'XP_MPLS_EXP1' : 105,
        'XP_MPLS_BS1' : 106,
        'XP_MPLS_TTL1' : 107,
        'XP_MPLS_LABEL2' : 108,
        'XP_MPLS_EXP2' : 109,
        'XP_MPLS_BS2' : 110,
        'XP_MPLS_TTL2' : 111,
        'XP_MPLS_LABEL3' : 112,
        'XP_MPLS_EXP3' : 113,
        'XP_MPLS_BS3' : 114,
        'XP_MPLS_TTL3' : 115,
        'XP_MPLS_CONTROL_WORD' : 116,
        'XP_GRE_C' : 117,
        'XP_GRE_R' : 118,
        'XP_GRE_K' : 119,
        'XP_GRE_S' : 120,
        'XP_GRE_VERSION' : 121,
        'XP_GRE_PROTOCOL' : 122,
        'XP_GRE_CHECKSUM' : 123,
        'XP_GRE_RESERVED_2' : 124,
        'XP_GRE_KEY' : 125,
        'XP_GRE_SEQ_NUM' : 126,
        'XP_ICMP_TYPE' : 127,
        'XP_ICMP_CODE' : 128,
        'XP_ICMP_CHECKSUM' : 129,
        'XP_ICMP_MESSAGE_SPECIFIC_INFO' : 130,
        'XP_IGMP_VERSIONORTYPE' : 131,
        'XP_IGMP_MAX_RESPONSE_TIME' : 132,
        'XP_IGMP_CHECKSUM' : 133,
        'XP_IGMP_GROUP_ADDRESS' : 134,
        'XP_ICMPV6_TYPE' : 135,
        'XP_ICMPV6_CODE' : 136,
        'XP_ICMPV6_CHECKSUM' : 137,
        'XP_ICMPV6_MESSAGE_BODY' : 138,
        'XP_UDP_SOURCE_PORT' : 139,
        'XP_UDP_DESTINATION_PORT' : 140,
        'XP_UDP_LENGTH' : 141,
        'XP_UDP_CHECKSUM' : 142,
        'XP_TCP_SOURCE_PORT' : 143,
        'XP_TCP_DESTINATION_PORT' : 144,
        'XP_TCP_SEQUENCE_NUMBER' : 145,
        'XP_TCP_ACK_NUMBER' : 146,
        'XP_TCP_OFFSET' : 147,
        'XP_TCP_RESERVED' : 148,
        'XP_TCP_FLAGS' : 149,
        'XP_TCP_WINDOW' : 150,
        'XP_TCP_CHECKSUM' : 151,
        'XP_TCP_URGENT_POINTER' : 152,
        'XP_TCP_TCP_OPTIONS' : 153,
        'XP_FCOE_VERSION' : 154,
        'XP_FCOE_RESERVED' : 155,
        'XP_FCOE_SOF' : 156,
        'XP_FCOE_R_CTL' : 157,
        'XP_FCOE_D_ID' : 158,
        'XP_FCOE_CS_CTL_PRIORITY' : 159,
        'XP_FCOE_S_ID' : 160,
        'XP_FCOE_TYPE' : 161,
        'XP_FCOE_F_CTL' : 162,
        'XP_FCOE_SEQ_ID' : 163,
        'XP_FCOE_DF_CTL' : 164,
        'XP_FCOE_SEQ_CNT' : 165,
        'XP_FCOE_SPLIT_OX_ID' : 166,
        'XP_FCOE_SPLIT_RX_ID' : 167,
        'XP_FCOE_SPLIT_PARAMETER' : 168,
        'XP_CNM_CNM_VER' : 169,
        'XP_CNM_QFEEDBACK' : 170,
        'XP_CNM_CPID' : 171,
        'XP_CNM_CNMQOFFSET' : 172,
        'XP_CNM_CNMQDELTA' : 173,
        'XP_CNM_ENCAP_PRIORITY' : 174,
        'XP_CNM_ENCAP_DA' : 175,
        'XP_CNM_ENCAP_LEN' : 176,
        'XP_GENEVE_VERSION' : 177,
        'XP_GENEVE_OPTIONSLEN' : 178,
        'XP_GENEVE_OAMFRAME' : 179,
        'XP_GENEVE_CRITICALFLAG' : 180,
        'XP_GENEVE_RESERVED_1' : 181,
        'XP_GENEVE_PROTOCOL' : 182,
        'XP_GENEVE_VNI' : 183,
        'XP_GENEVE_RESERVED_2' : 184,
        'XP_GENEVE_OPTIONCLASS' : 185,
        'XP_GENEVE_TYPE' : 186,
        'XP_GENEVE_RESERVED_3' : 187,
        'XP_GENEVE_OPTLEN' : 188,
        'XP_GENEVE_RESERVED_4' : 189,
        'XP_GENEVE_FLOWID' : 190,
        'XP_GENEVE_OPTIONCLASS_2' : 191,
        'XP_GENEVE_TYPE_2' : 192,
        'XP_GENEVE_RESERVED_5' : 193,
        'XP_GENEVE_OPTLEN_2' : 194,
        'XP_GENEVE_RESERVED_6' : 195,
        'XP_GENEVE_TEMPLATEID' : 196,
        'XP_GRE_NOLAYER_C' : 197,
        'XP_GRE_NOLAYER_R' : 198,
        'XP_GRE_NOLAYER_K' : 199,
        'XP_GRE_NOLAYER_S' : 200,
        'XP_GRE_NOLAYER_VERSION' : 201,
        'XP_GRE_NOLAYER_PROTOCOL' : 202,
        'XP_GRE_NOLAYER_CHECKSUM' : 203,
        'XP_GRE_NOLAYER_RESERVED_2' : 204,
        'XP_GRE_NOLAYER_KEY' : 205,
        'XP_GRE_NOLAYER_SEQ_NUM' : 206,
        'XP_UDPVXLANNSH_SOURCE_PORT' : 207,
        'XP_UDPVXLANNSH_DESTINATION_PORT' : 208,
        'XP_UDPVXLANNSH_LENGTH' : 209,
        'XP_UDPVXLANNSH_CHECKSUM' : 210,
        'XP_UDPVXLANNSH_FLAGS' : 211,
        'XP_UDPVXLANNSH_RESERVED_1' : 212,
        'XP_UDPVXLANNSH_NEXTPROTOCOL' : 213,
        'XP_UDPVXLANNSH_VNI' : 214,
        'XP_UDPVXLANNSH_RESEVED_2' : 215,
        'XP_UDPVXLANNSH_FLAGS_1' : 216,
        'XP_UDPVXLANNSH_NSH_LENGTH' : 217,
        'XP_UDPVXLANNSH_MD_TYPE' : 218,
        'XP_UDPVXLANNSH_NSHNEXTPROTOCOL' : 219,
        'XP_UDPVXLANNSH_SERVICEPATHID' : 220,
        'XP_UDPVXLANNSH_SERVICEINDEX' : 221,
        'XP_UDPVXLANNSH_SOURCEISLANDID' : 222,
        'XP_UDPVXLANNSH_DESTISLANDID' : 223,
        'XP_UDPVXLANNSH_RESERVED_3' : 224,
        'XP_NSH_FLAGS_1' : 225,
        'XP_NSH_NSH_LENGTH' : 226,
        'XP_NSH_MD_TYPE' : 227,
        'XP_NSH_NSHNEXTPROTOCOL' : 228,
        'XP_NSH_SERVICEPATHID' : 229,
        'XP_NSH_SERVICEINDEX' : 230,
        'XP_NSH_SOURCEISLANDID' : 231,
        'XP_NSH_DESTISLANDID' : 232,
        'XP_NSH_RESERVED_3' : 233,
        'XP_TUNNEL_IPV6_SPLIT_SOURCE_IP_ADDRESS' : 234,
        'XP_TUNNEL_IPV6_SPLIT_DESTINATION_IP_ADDRESS' : 235,
        'XP_TUNNEL_IPV6_ICMPV6_SOURCE_IP_ADDRESS' : 236,
        'XP_TUNNEL_IPV6_ICMPV6_DESTINATION_IP_ADDRESS' : 237,
        'XP_TUNNEL_IPV6_UDP_SOURCE_IP_ADDRESS' : 238,
        'XP_TUNNEL_IPV6_UDP_DESTINATION_IP_ADDRESS' : 239,
        'XP_TUNNEL_IPV6_TCP_SOURCE_IP_ADDRESS' : 240,
        'XP_TUNNEL_IPV6_TCP_DESTINATION_IP_ADDRESS' : 241,
        'XP_UDPVXLAN_SOURCE_PORT' : 242,
        'XP_UDPVXLAN_DESTINATION_PORT' : 243,
        'XP_UDPVXLAN_LENGTH' : 244,
        'XP_UDPVXLAN_CHECKSUM' : 245,
        'XP_UDPVXLAN_FLAGS' : 246,
        'XP_UDPVXLAN_RESERVED_1' : 247,
        'XP_UDPVXLAN_NEXTPROTOCOL' : 248,
        'XP_UDPVXLAN_VNI' : 249,
        'XP_UDPVXLAN_RESEVED_2' : 250,
        'XP_SRH_SRH_NEXT_HEADER' : 251,
        'XP_SRH_HDR_EXT_LEN' : 252,
        'XP_SRH_ROUTE_TYPE' : 253,
        'XP_SRH_SEGMENT_LEFT' : 254,
        'XP_SRH_FIRST_SEGMENT' : 255,
        'XP_SRH_FLAGS' : 256,
        'XP_SRH_RESERVED' : 257,
        'XP_SRH_IP0_DIP0' : 258,
        'XP_SRH_IP0_DIP1' : 259,
        'XP_SRH_IP1_DIP0' : 260,
        'XP_SRH_IP2_DIP1' : 261,
        'XP_SRH_IP2_DIP2' : 262,
        'XP_NUM_HASH_FIELDS' : 263
    },
   'pktCmd' :
    {
        'XP_PKTCMD_DROP' : 0,
        'XP_PKTCMD_FWD' : 1,
        'XP_PKTCMD_TRAP' : 2,
        'XP_PKTCMD_FWD_MIRROR' : 3,
    },
   'portFrameType' :
    {
        'FRAMETYPE_ALL' : 0,
        'FRAMETYPE_UN_PRI' : 1,
        'FRAMETYPE_TAG' : 2,
    },
   'portConfigFieldList' :
    {
        'XPS_PORT_FIELD_NUM_MIN' : 0,
        'XPS_PORT_DEFAULT_EXP' : 1,
        'XPS_PORT_DEFAULT_DSCP' : 2,
        'XPS_PORT_DEFAULT_DEI' : 3,
        'XPS_PORT_DEFAULT_PCP' : 4,
        'XPS_PORT_DEFAULT_DP' : 5,
        'XPS_PORT_DEFAULT_TC' : 6,
        'XPS_PORT_MPLS_QOS_EN' : 7,
        'XPS_POST_IP_QOS_EN' : 8,
        'XPS_PORT_LAYER2_QOS_EN' : 9,
        'XPS_PORT_EGRESS_FILTER_ID' : 10,
        'XPS_PORT_SET_INGRESS_VIF' : 11,
        'XPS_PORT_SET_BRIDGE_DOMAIN' : 12,
        'XPS_PORT_ACCEPTED_FRAME_TYPE' : 13,
        'XPS_PORT_BYPASS_TUNNEL_VIF' : 14,
        'XPS_PORT_BYPASS_ACLSPBR' : 15,
        'XPS_PORT_SAMPLER_EN' : 16,
        'XPS_PORT_POLICER_EN' : 17,
        'XPS_PORT_STATE' : 18,
        'XPS_PORT_SET_EGRESS_PORT_FILTER' : 19,
        'XPS_PORT_MAC_SAMISSCMD' : 20,
        'XPS_PORT_BUM_POLICER_EN' : 21,
        'XPS_PORT_ACL_EN' : 22,
        'XPS_PORT_DEBUG_EN' : 23,
        'XPS_PORT_ACL_ID' : 24,
        'XPS_PORT_PRIVATE_WIRE_EN' : 25,
        'XPS_PORT_ADD_PORT_BASED_TAG' : 26,
        'XPS_PORT_RESERVED2' : 27,
        'XPS_PORT_BRIDGE_DOMAIN' : 28,
        'XPS_PORT_EVIF' : 29,
        'XPS_PORT_MIRROR_BITMASK' : 30,
        'XPS_PORT_INGRESS_VIF' : 31,
        'XPS_PORT_PVID_MODE_ALLPKT' : 32,
        'XPS_PORT_PVID' : 33,
        'XPS_PORT_MPLS_QOS_PROFILE_IDX' : 34,
        'XPS_PORT_IP_QOS_PROFILE_IDX' : 35,
        'XPS_PORT_L2QOS_PROFILE_IDX' : 36,
        'XPS_PORT_ETAG_EXISTS' : 37,
    },
   'countMode' :
    {
        'COUNT_MODE_NONE' : 0,
        'COUNT_MODE_CNT' : 1,
        'COUNT_MODE_POL' : 2,
        'COUNT_MODE_CNT_POL' : 3,
        'COUNT_MODE_SMP' : 4,
        'COUNT_MODE_CNT_SMP' : 5,
        'COUNT_MODE_POL_SMP' : 6,
        'COUNT_MODE_CNT_POL_SMP' : 7,
    },
   'l2EncapType' :
    {
        'XP_L2_ENCAP_DOT1Q_UNTAGGED' : 0,
        'XP_L2_ENCAP_DOT1Q_TAGGED' : 1,
        'XP_L2_ENCAP_DOT1Q_PRIOTAGGED' : 2,
        'XP_L2_ENCAP_QINQ_UNTAGGED' : 3,
        'XP_L2_ENCAP_QINQ_CTAGGED' : 4,
        'XP_L2_ENCAP_QINQ_STAGGED' : 5,
        'XP_L2_ENCAP_VXLAN' : 6,
        'XP_L2_ENCAP_NVGRE' : 7,
        'XP_L2_ENCAP_PBB' : 8,
        'XP_L2_ENCAP_GENEVE' : 9,
        'XP_L2_ENCAP_MPLS' : 10,
        'XP_L2_ENCAP_NO_OP' : 11,
        'XP_L2_ENCAP_INVALID' : -1,
    },
   'vlanBridgeMcMode' :
    {
        'MC_BRIDGE_MODE_DISABLED' : 0,
        'MC_BRIDGE_MODE_FDB' : 1,
    },
   'vlanStgState' :
    {
        'SPAN_STATE_DISABLE' : 0,
        'SPAN_STATE_LEARN' : 1,
        'SPAN_STATE_FORWARD' : 2,
        'SPAN_STATE_BLOCK' : 3,
    },
   'bdCountMode' :
    {
        'BD_COUNT_MODE_NONE' : 0,
        'BD_COUNT_MODE_ROUTED_AND_SWITCHED' : 1,
        'BD_COUNT_MODE_ONLY_ROUTED' : 2,
    },
   'ipPrefixType' :
    {
        'XP_PREFIX_TYPE_IPV4' : 0,
        'XP_PREFIX_TYPE_IPV6' : 1,
    },
   'initType' :
    {
        'INIT_UNKNOWN' : 0,
        'INIT_COLD' : 1,
        'INIT_WARM' : 2,
        'INIT_WARM_SYNC_TO_HW' : 3,
        'INIT_WARM_SYNC_TO_SHADOW' : 4,
    },
   'macConfigMode' :
    {
        'MAC_MODE_SGMII' : 0,
        'MAC_MODE_MIX_4_CHANNEL_10G' : 1,
        'MAC_MODE_1GB' : 2,
        'MAC_MODE_2X40GB' : 4,
        'MAC_MODE_4X25GB' : 7,
        'MAC_MODE_2X50GB' : 8,
        'MAC_MODE_1000BASE_R' : 10,
        'MAC_MODE_1000BASE_X' : 11,
        'MAC_MODE_MIX_SGMII' : 12,
        'MAC_MODE_MIX_1000BASE_R' : 13,
        'MAC_MODE_4X10GB' : 3,
        'MAC_MODE_1X10GB' : 9,
        'MAC_MODE_1X40GB' : 5,
        'MAC_MODE_1X50GB' : 14,
        'MAC_MODE_1X100GB' : 6,
    },
   'rxConfigMode' :
    {
        'INTR' : 0,
        'POLL' : 1,
    },
   'salType' :
    {
        'XP_SAL_HW_TYPE' : 0,
        'XP_SAL_WM_TYPE' : 1,
        'XP_SAL_KERN_TYPE' : 2,
        'XP_SAL_KERN_WM_TYPE' : 3,
        'XP_SAL_MAX_OS_TYPE' : 4,
        'XP_SAL_OTHER_OS_TYPE' : 5,
    },
   'callbackMethodType' :
    {
        'PD_SEND' : 0,
        'PD_RECV' : 1,
        'PD_ERR' : 2,
        'PD_ALL' : 3,
    },
   'txMode' :
    {
        'SYNC_TX' : 0,
        'ASYNC_TX' : 1,
    },
   'AGE_MODE' :
    {
        'XP_AGE_MODE_AUTO' : 0,
        'XP_AGE_MODE_TRIGGER' : 1,
        'XP_AGE_MODE_INVALID' : 2,
    },
   'cpuRxPktCbType' :
    {
        'XP_L2_LEARN' : 0,
        'XP_OPENFLOW' : 3,
        'XP_TUNNEL' : 1,
        'XP_NAT' : 2,
        'XP_DEFAULT_HANDLER' : 4,
        'XP_PTP_INGRESS_TRAP' : 5,
    },
   'fecMode' :
    {
        'RS_FEC_MODE' : 0,
        'FC_FEC_MODE' : 1,
        'MAX_FEC_MODE' : 2,
    },
   'serdesDfeTuneMode' :
    {
        'DFE_ICAL' : 0,
        'DFE_PCAL' : 1,
        'DFE_START_ADAPTIVE' : 2,
        'DFE_STOP_ADAPTIVE' : 3,
        'DFE_ENABLE_RR' : 4,
        'DFE_DISABLE_RR' : 5,
    },
   'speed' :
    {
        'SPEED_10MB' : 0,
        'SPEED_100MB' : 1,
        'SPEED_1GB' : 2,
        'SPEED_1GB_PCS' : 3,
        'SPEED_2_5GB' : 4,
        'SPEED_10GB' : 5,
        'SPEED_40GB' : 6,
        'SPEED_100GB' : 7,
        'SPEED_25GB' : 8,
        'SPEED_50GB' : 9,
    },
   'eventType' :
    {
        'LINK_UP' : 0,
        'LINK_DOWN' : 1,
        'FAULT_DETECTED' : 2,
        'FAULT_NOT_DETECTED' : 3,
        'SERDES_SIG_DETECTED' : 4,
        'SERDES_SIG_NOT_DETECTED' : 5,
        'TX_UNDER_RUN' : 6,
        'TX_JABBER' : 7,
        'TX_TIMESTAMPS_FIFO_OVER_FLOW' : 8,
        'TX_TIMESTAMPS_FIFO_AVAILABLE' : 9,
        'FEC_ALIGNMENT_MAKER_LOST_LANE0' : 10,
        'FEC_ALIGNMENT_MAKER_LOST_LANE1' : 11,
        'FEC_ALIGNMENT_MAKER_LOST_LANE2' : 12,
        'FEC_ALIGNMENT_MAKER_LOST_LANE3' : 13,
        'FEC_UNCORRECTABLE_FRM' : 14,
        'FEC_DESKEW_LOST' : 15,
        'FEC_BER_OVER_THRESHOLD' : 16,
        'HSMCPCS_BLOCK_LOCK' : 17,
        'HSMCPCS_FAULT' : 18,
        'HSMCPCS_TX_GEARBOX_FIFO_ERROR' : 19,
        'HSMCPCS_DEBUG_DESKEW_OVERFLOW' : 20,
        'UMAC_COMMON_INT_END' : 21,
        'UMAC_A0_INT_START' : 22,
        'TX_BASE_PAGE_STARTED' : 23,
        'TX_NEXT_PAGE_STARTED' : 24,
        'RX_BASE_PAGE_STARTED' : 25,
        'RX_NEXT_PAGE_STARTED' : 26,
        'BPAN_COMPLETED' : 27,
        'UMAC_A0_INT_END' : 28,
        'UMAC_B0_INT_START' : 29,
        'HSMCPCS_DECODER_TRAP' : 30,
        'HSMCPCS_LOSS_OF_SYNC' : 31,
        'HSMCPCS_LOSS_OF_BLOCK_LOCK' : 32,
        'HSMCPCS_HIGH_BER_EVENT' : 33,
        'HSMCPCS_ERROR_BLOCK' : 34,
        'LSMCPCS_AN_DONE' : 35,
        'FC_FEC_BLOCK_LOCK_GAINED' : 36,
        'FC_FEC_BLOCK_LOCK_LOST' : 37,
        'FC_FEC_UNCORRECTED_CODEWORD' : 38,
        'FC_FEC_BAD_CODEWORD' : 39,
        'FC_FEC_TOO_MANY_REQUESTED' : 40,
        'BPAN_INT' : 41,
        'TX_IDLE' : 42,
        'RX_FIFO_ERR' : 43,
        'TX_FIFO_OVERFLOW_ERR' : 44,
        'TX_DCNT_VIOLATION_ERR' : 45,
        'TX_FIFO_SOF_EOF_VIOLATION_ERR' : 46,
        'RX_LOCAL_FAULT' : 47,
        'RX_REMOTE_FAULT' : 48,
        'RX_CRC_ERROR' : 49,
        'UMAC_B0_INT_END' : 50,
    },
   'interruptType' :
    {
        'XP_TXQ_CNT_STATS_INTR' : 0,
        'XP_TXQ_CNT_LEN_INTR' : 1,
        'XP_TXQ_TBWRAPPER_INTR' : 2,
        'XP_TXQ_TBM_INTR' : 3,
        'XP_TXQ_AQM_INTR' : 4,
        'XP_TXQ_EQ_INTR' : 5,
        'XP_TXQ_DQ_INTR' : 6,
        'XP_SEARCH_RSLT_NTWK_INTR' : 7,
        'XP_SEARCH_REQ_NTWK_INTR' : 8,
        'XP_SEARCH_AGE_INTR' : 9,
        'XP_SEARCH_POOLL_INTR' : 10,
        'XP_SEARCH_POOLA_INTR' : 11,
        'XP_SEARCH_POOLT_INTR' : 12,
        'XP_SEARCH_MEM_INTR' : 13,
        'XP_SEARCH_SE_INTR' : 14,
        'XP_SDE1_LDE_INTR' : 15,
        'XP_SDE1_ISME_INTR' : 16,
        'XP_SDE1_URW_INTR' : 17,
        'XP_SDE1_MME_INTR' : 18,
        'XP_SDE1_MRE_INTR' : 19,
        'XP_SDE1_HDBF_INTR' : 20,
        'XP_SDE1_ACM_INTR' : 21,
        'XP_SDE1_PARSER_INTR' : 22,
        'XP_SDE0_MEM_INTR' : 23,
        'XP_SDE0_LDE_INTR' : 24,
        'XP_SDE0_ISME_INTR' : 25,
        'XP_SDE0_URW_INTR' : 26,
        'XP_SDE0_MME_INTR' : 27,
        'XP_SDE0_MRE_INTR' : 28,
        'XP_SDE0_HDBF_INTR' : 29,
        'XP_SDE0_ACM_INTR' : 30,
        'XP_SDE0_PARSER_INTR' : 31,
        'XP_DP_BM_INTR' : 32,
        'XP_DP_PM_INTR' : 33,
        'XP_DP_TXDMA_INTR' : 34,
        'XP_DP_SDMA_INTR' : 35,
        'XP_DP_RXDMA_INTR' : 36,
        'XP_DP_IBUFFER_INTR' : 37,
        'XP_PTG_INTR' : 38,
        'XP_DMAC_INTR' : 39,
        'XP_PTP_INTR' : 40,
        'XP_MGMT_INTR' : 41,
    },
   'ACM_CONFIG_MODE' :
    {
        'XP_ACM_NONE' : 0,
        'XP_ACM_COUNTING' : 1,
        'XP_ACM_SAMPLING' : 2,
        'XP_ACM_POLICING' : 3,
    },
   'acmClient' :
    {
        'XP_ACM_UNKNOWN' : 0,
        'XP_ACM_OPENFLOW_0' : 1,
        'XP_ACM_OPENFLOW_1' : 2,
        'XP_ACM_OPENFLOW_2' : 3,
        'XP_ACM_OPENFLOW_3' : 4,
        'XP_ACM_OPENFLOW_4' : 5,
        'XP_ACM_OPENFLOW_5' : 6,
        'XP_ACM_OPENFLOW_6' : 7,
        'XP_ACM_OPENFLOW_7' : 8,
        'XP_ACM_OPENFLOW_8' : 9,
        'XP_ACM_OPENFLOW_9' : 10,
        'XP_ACM_OPENFLOW_10' : 11,
        'XP_ACM_OPENFLOW_11' : 12,
        'XP_ACM_OPENFLOW_12' : 13,
        'XP_ACM_OPENFLOW_13' : 14,
        'XP_ACM_OPENFLOW_14' : 15,
        'XP_ACM_OPENFLOW_15' : 16,
        'XP_ACM_OPENFLOW_16' : 17,
        'XP_ACM_OPENFLOW_17' : 18,
        'XP_ACM_OPENFLOW_18' : 19,
        'XP_ACM_OPENFLOW_19' : 20,
        'XP_ACM_OPENFLOW_20' : 21,
        'XP_ACM_OPENFLOW_21' : 22,
        'XP_ACM_OPENFLOW_22' : 23,
        'XP_ACM_OPENFLOW_23' : 24,
        'XP_ACM_OPENFLOW_MAX' : 31,
        'XP_ACM_ING_PORT_POLICER' : 32,
        'XP_ACM_ING_PORT_SAMPLER' : 64,
        'XP_ACM_VNI_COUNTER' : 128,
        'XP_ACM_ING_BD_COUNTER' : 256,
        'XP_ACM_VLAN_BUM_POLICER' : 512,
        'XP_ACM_IACL_POLICER' : 1024,
        'XP_ACM_IPACL_COUNTER' : 2048,
        'XP_ACM_IBACL_COUNTER' : 4096,
        'XP_ACM_IRACL_COUNTER' : 8192,
        'XP_ACM_EACL_POLICER' : 16384,
        'XP_ACM_EACL_COUNTER' : 32768,
        'XP_ACM_EGR_BD_COUNTER' : 65536,
        'XP_ACM_DROP_RSN_COUNTER' : 131072,
        'XP_ACM_PORT_RANGE' : 262144,
        'XP_ACM_PORT_VLAN' : 524288,
        'XP_ACM_TUNNEL_COUNTER' : 1048576,
        'XP_ACM_COPP_POLICER' : 2097152,
    },
   'packetInterface' :
    {
        'XP_DMA' : 0,
        'XP_ETHER' : 1,
        'XP_NETDEV_DMA' : 2,
        'XP_DMA_TAP' : 3,
        'XP_NETDEV_DMA_TAP' : 4,
    },
   'policingResultType' :
    {
        'XP_POL_RESULT_EXP' : 0,
        'XP_POL_RESULT_DSCP' : 1,
        'XP_POL_RESULT_DEI' : 2,
        'XP_POL_RESULT_PCP' : 3,
        'XP_POL_RESULT_TC' : 4,
        'XP_POL_RESULT_DP' : 5,
    },
   'PROFILE_TYPE' :
    {
        'XP_RESERVED_PROFILE' : 0,
        'XP_DEFAULT_SINGLE_PIPE_PROFILE' : 0,
        'XP_DEFAULT_TWO_PIPE_PROFILE' : 1,
        'XP_ROUTE_CENTRIC_SINGLE_PIPE_PROFILE' : 2,
        'XP_OPENFLOW_HYBRID_SINGLE_PIPE_PROFILE' : 3,
        'XP_TUNNEL_CENTRIC_SINGLE_PIPE_PROFILE' : 7,
        'XP_ACL_WCM_PROFILE' : 9,
        'XP_SEGMENT_ROUTE_SINGLE_PIPE_PROFILE' : 14,
    },
   'skuMode' :
    {
        'SKU_128X10' : 0,
        'SKU_32X40' : 1,
        'SKU_64X40' : 2,
        'SKU_32X100' : 3,
        'SKU_128X25' : 4,
        'SKU_64X50' : 5,
        'SKU_MIX' : 6,
        'SKU_32X100G_SP' : 7,
        'SKU_128X1' : 8,
        'SKU_48X25_6X100' : 9,
        'SKU_48X10_6X100' : 10,
        'SKU_48X25_6X100_C' : 11,
        'SKU_48X10_6X100_C' : 12,
        'SKU_72X25' : 13,
        'SKU_72X10' : 14,
        'SKU_18X40' : 18,
        'SKU_36X40' : 19,
        'SKU_18X100' : 20,
        'SKU_32X50' : 21,
        'SKU_72X1' : 22,
        'SKU_48X25_6X100_78072' : 23,
        'SKU_48X25_6X100_78072_EVB' : 24,
        'SKU_48X10_6X100_78072' : 25,
        'SKU_48X10_6X100_78072_EVB' : 26,
    },
   'nlMsgType' :
    {
        'XPNL_CREATE_NETDEV_INTF_MSG' : 1,
        'XPNL_DELETE_NETDEV_INTF_MSG' : 2,
        'XPNL_TXHEADER_MSG' : 3,
        'XPNL_TRAP_CONFIG_MSG' : 4,
        'XPNL_CB_FD_REG_MSG' : 5,
        'XPNL_INTF_ID' : 32767,
        'XPNL_INTF_NAME' : 32768,
        'XPNL_TXHEADER' : 32769,
        'XPNL_TRAP_ID' : 32770,
        'XPNL_REASONCODE' : 32771,
        'XPNL_CHANNEL' : 32772,
        'XPNL_FD' : 32773,
    },
   'ofPortNo' :
    {
        'XP_OFPP_MAX' : 4294967040,
        'XP_OFPP_IN_PORT' : 4294967288,
        'XP_OFPP_TABLE' : 4294967289,
        'XP_OFPP_NORMAL' : 4294967290,
        'XP_OFPP_FLOOD' : 4294967291,
        'XP_OFPP_ALL' : 4294967292,
        'XP_OFPP_CONTROLLER' : 4294967293,
        'XP_OFPP_LOCAL' : 4294967294,
        'XP_OFPP_ANY' : 4294967295,
    },
   'ofActionType' :
    {
        'XP_OFPAT_OUTPUT' : 0,
        'XP_OFPAT_POP_VLAN' : 6,
        'XP_OFPAT_GROUP' : 10,
        'XP_OFPAT_SET_NW_TTL' : 11,
        'XP_OFPAT_DEC_NW_TTL' : 12,
        'XP_OFPAT_SET_FIELD' : 13,
        'XP_OFPAT_SET_MPLS_TTL' : 15,
        'XP_OFPAT_DEC_MPLS_TTL' : 16,
        'XP_OFPAT_PUSH_MPLS' : 19,
        'XP_OFPAT_POP_MPLS' : 20,
    },
   'oxmType' :
    {
        'XP_OFPXMT_OFB_IN_PORT' : 0,
        'XP_OFPXMT_OFB_IN_PHY_PORT' : 1,
        'XP_OFPXMT_OFB_METADATA' : 2,
        'XP_OFPXMT_OFB_ETH_DST' : 3,
        'XP_OFPXMT_OFB_ETH_SRC' : 4,
        'XP_OFPXMT_OFB_ETH_TYPE' : 5,
        'XP_OFPXMT_OFB_VLAN_VID' : 6,
        'XP_OFPXMT_OFB_VLAN_PCP' : 7,
        'XP_OFPXMT_OFB_IP_PROTO' : 10,
        'XP_OFPXMT_OFB_IPV4_SRC' : 11,
        'XP_OFPXMT_OFB_IPV4_DST' : 12,
        'XP_OFPXMT_OFB_TCP_SRC' : 13,
        'XP_OFPXMT_OFB_TCP_DST' : 14,
        'XP_OFPXMT_OFB_UDP_SRC' : 15,
        'XP_OFPXMT_OFB_UDP_DST' : 16,
        'XP_OFPXMT_OFB_SCTP_SRC' : 17,
        'XP_OFPXMT_OFB_SCTP_DST' : 18,
        'XP_OFPXMT_OFB_MPLS_LABEL' : 34,
        'XP_OFPXMT_OFB_MPLS_TC' : 35,
        'XP_OFPXMT_OFB_MPLS_BOS' : 36,
    },
   'ofMatchPktType' :
    {
        'XP_MATCH_PKT_ANY' : 0,
        'XP_MATCH_PKT_UNTAGGED' : 1,
        'XP_MATCH_PKT_TAGGED' : 2,
        'XP_MATCH_PKT_MASK' : 3,
    },
   'ofGroupType' :
    {
        'XP_OFPGT_ALL' : 0,
        'XP_OFPGT_SELECT' : 1,
        'XP_OFPGT_INDIRECT' : 2,
        'XP_OFPGT_FF' : 3,
    },
   'ofFlowType' :
    {
        'XP_OFPFT_STANDARD_FLOW' : 0,
        'XP_OFPFT_HIDDEN_HIGH_FLOW' : 1,
        'XP_OFPFT_HIDDEN_LOW_FLOW' : 2,
    },
   'ofPacketInReason' :
    {
        'XP_OFPR_TABLE_MISS' : 0,
        'XP_OFPR_APPLY_ACTION' : 1,
        'XP_OFPR_INVALID_TTL' : 2,
        'XP_OFPR_ACTION_SET' : 3,
        'XP_OFPR_GROUP' : 4,
        'XP_OFPR_PACKET_OUT' : 5,
        'XP_OFPR_PORT_LOCAL' : 7,
    },
   'ofTableType' :
    {
        'XP_OF_HASH_TABLE' : 0,
        'XP_OF_TCAM_TABLE' : 1,
        'XP_OF_TABLE_NUM' : 2,
    },
   'interfaceType' :
    {
        'XPS_PORT' : 0,
        'XPS_EXTENDED_PORT' : 1,
        'XPS_LAG' : 2,
        'XPS_TUNNEL_MPLS' : 3,
        'XPS_TUNNEL_VXLAN' : 4,
        'XPS_TUNNEL_NVGRE' : 5,
        'XPS_TUNNEL_GENEVE' : 6,
        'XPS_TUNNEL_PBB' : 7,
        'XPS_TUNNEL_GRE' : 8,
        'XPS_TUNNEL_VPN_GRE' : 9,
        'XPS_TUNNEL_VPN_GRE_LOOSE' : 10,
        'XPS_TUNNEL_GRE_ERSPAN2' : 11,
        'XPS_TUNNEL_IP_IN_IP' : 12,
        'XPS_L2_MCAST_GROUP' : 13,
        'XPS_L3_MCAST_GROUP' : 14,
        'XPS_PORT_ROUTER' : 15,
        'XPS_SUBINTERFACE_ROUTER' : 16,
        'XPS_VLAN_ROUTER' : 17,
        'XPS_TUNNEL_ROUTER' : 18,
        'XPS_VPN_ROUTER' : 19,
        'XPS_PORT_CONTROL_VIF' : 20,
        'XPS_AC' : 21,
    },
   'qosMapPfl' :
    {
        'QOSMAP_PROFILE_TRUST' : 0,
        'QOSMAP_PROFILE_1' : 1,
        'QOSMAP_PROFILE_2' : 2,
        'QOSMAP_PROFILE_3' : 3,
        'QOSMAP_PROFILE_4' : 4,
        'QOSMAP_PROFILE_5' : 5,
        'QOSMAP_PROFILE_6' : 6,
        'QOSMAP_PROFILE_7' : 7,
    },
   'aclType' :
    {
        'XP_ACL_IACL0' : 0,
        'XP_ACL_IACL1' : 1,
        'XP_ACL_IACL2' : 2,
        'XP_ACL_EACL' : 3,
        'XP_ACML_TOTAL_TYPE' : 4,
    },
   'iaclType' :
    {
        'XP_IACL0' : 0,
        'XP_IACL1' : 1,
        'XP_IACL2' : 2,
        'XP_IACL_TOTAL_TYPE' : 3,
    },
   'iaclV4KeyFlds' :
    {
        'XP_IACL_KEY_TYPE_V4' : 0,
        'XP_IACL_ID' : 1,
        'XP_IACL_MAC_DA' : 2,
        'XP_IACL_MAC_SA' : 3,
        'XP_IACL_V4_ETHER_TYPE' : 4,
        'XP_IACL_CTAG_VID_DEI_PCP' : 5,
        'XP_IACL_STAG_VID_DEI_PCP' : 6,
        'XP_IACL_SIP_V4' : 7,
        'XP_IACL_DIP_V4' : 8,
        'XP_IACL_L4_DEST_PORT' : 9,
        'XP_IACL_L4_SRC_PORT' : 10,
        'XP_IACL_IVIF' : 11,
        'XP_IACL_ICMP_CODE' : 12,
        'XP_IACL_ICMP_MSG_TYPE' : 13,
        'XP_IACL_PROTOCOL' : 14,
        'XP_IACL_DSCP_ECN' : 15,
        'XP_IACL_BD' : 16,
        'XP_IACL_TTL' : 17,
        'XP_IACL_PKTLEN' : 18,
        'XP_IACL_TCP_FLAGS' : 19,
        'XP_IACL_VRF_ID' : 20,
        'XP_IACL_TAG_FRAGMENT_INFO' : 21,
    },
   'iaclV6KeyFlds' :
    {
        'XP_IACL_KEY_TYPE_V6' : 0,
        'XP_IACL_V6_ID' : 1,
        'XP_IACL_DIP_V6' : 2,
        'XP_IACL_SIP_V6' : 3,
        'XP_IACL_NXT_HDR' : 4,
        'XP_IACL_L4_V6_DEST_PORT' : 5,
        'XP_IACL_L4_V6_SRC_PORT' : 6,
        'XP_IACL_ICMP_V6_CODE' : 7,
        'XP_IACL_ICMP_V6_MSG_TYPE' : 8,
        'XP_IACL_HOP_LIMIT' : 9,
        'XP_IACL_V6_PROTOCOL' : 10,
        'XP_IACL_V6_TCP_FLAGS' : 11,
        'XP_IACL_V6_PKTLEN' : 12,
        'XP_IACL_TC_ROUTERMAC' : 13,
    },
   'iaclV4MplsKeyFlds' :
    {
        'XP_IACL_KEY_TYPE_MPLS_V4' : 0,
        'XP_IACL_MPLS_V4_ID' : 1,
        'XP_IACL_MPLS_V4_DIP' : 2,
        'XP_IACL_MPLS_V4_SIP' : 3,
        'XP_IACL_MPLS_V4_L4_DEST_PORT' : 4,
        'XP_IACL_MPLS_V4_L4_SRC_PORT' : 5,
        'XP_IACL_MPLS_V4_IVIF' : 6,
        'XP_IACL_MPLS_V4_ICMP_CODE' : 7,
        'XP_IACL_MPLS_V4_ICMP_MSG_TYPE' : 8,
        'XP_IACL_MPLS_V4_PROTOCOL' : 9,
        'XP_IACL_MPLS_V4_DSCP_ECN' : 10,
        'XP_IACL_MPLS_V4_BD' : 11,
        'XP_IACL_MPLS_V4_TCP_FLAGS' : 12,
        'XP_IACL_MPLS_V4_TTL' : 13,
        'XP_IACL_MPLS_V4_PKTLEN_LABEL_EXP' : 14,
    },
   'eaclV4KeyFlds' :
    {
        'XP_EACL_KEY_TYPE_V4' : 0,
        'XP_EACL_MAC_DA' : 1,
        'XP_EACL_MAC_SA' : 2,
        'XP_EACL_DIP_V4' : 3,
        'XP_EACL_SIP_V4' : 4,
        'XP_EACL_L4_DEST_PORT' : 5,
        'XP_EACL_L4_SRC_PORT' : 6,
        'XP_EACL_V4_ETHER_TYPE' : 17,
        'XP_EACL_ICMP_MSG_TYPE' : 8,
        'XP_EACL_PROTOCOL' : 9,
        'XP_EACL_EGRESS_BD' : 10,
        'XP_EACL_EGRESS_VIF' : 11,
        'XP_EACL_VI' : 12,
        'XP_EACL_DSCP_PCP_EXP' : 13,
        'XP_EACL_TCP_FLAGS_RSNCODE' : 14,
        'XP_EACL_TC_DP' : 15,
    },
   'eaclV6KeyFlds' :
    {
        'XP_EACL_KEY_TYPE_V6' : 0,
        'XP_EACL_DIP_V6' : 1,
        'XP_EACL_SIP_V6' : 2,
        'XP_EACL_L4_V6_DEST_PORT' : 3,
        'XP_EACL_L4_V6_SRC_PORT' : 4,
        'XP_EACL_V6_ETHER_TYPE' : 5,
        'XP_EACL_ICMP_V6_MSG_TYPE' : 6,
        'XP_EACL_V6_EGRESS_BD' : 7,
        'XP_EACL_V6_EGRESS_VIF' : 8,
        'XP_EACL_V6_RSNCODE_TC_DP' : 9,
    },
   'iaclKeyType' :
    {
        'XP_IACL_V4_TYPE' : 0,
        'XP_IACL_V6_TYPE' : 1,
        'XP_IACL_V4_MPLS_TYPE' : 2,
    },
   'iaclEncapType' :
    {
        'XP_IACL_ENCAP_TAGGED' : 0,
        'XP_IACL_ENCAP_UNTAGGED' : 1,
        'XP_IACL_ENCAP_IP_TUNNEL' : 2,
        'XP_IACL_ENCAP_NONE' : 3,
    },
   'cpuTypes' :
    {
        'XP_MCPU' : 0,
        'XP_SCPU' : 1,
    },
   'scpuTaskList' :
    {
       'PACKET_DRIVER_TX' : 0,
       'PACKET_DRIVER_RX' : 1,
       'IPC_SIGNAL' : 2,
       'POLL_AGE_FIFO' : 3,
       'GET_STATISTICS' : 4,
       'SEND_LED_STREAM' : 5,
       'ALL_SCPU_TASKS' : 6
    },
   'dalType' :
    {
        'XPS_DAL_HARDWARE' : 0,
        'XPS_DAL_WHITEMODEL' : 1,
    },
    'slaveResetIdList' :
    {
        'XP_SLAVE_RST_PTP' : 0,
        'XP_SLAVE_RST_PTG_0' : 1,
        'XP_SLAVE_RST_PTG_1' : 2,
        'XP_SLAVE_RST_PTG_2' : 3,
        'XP_SLAVE_RST_PTG_3' : 4,
        'XP_SLAVE_RST_PTG_4' : 5,
        'XP_SLAVE_RST_PTG_5' : 6,
        'XP_SLAVE_RST_PTG_6' : 7,
        'XP_SLAVE_RST_PTG_7' : 8,
        'XP_SLAVE_RST_PTG_8' : 9,
        'XP_SLAVE_RST_PTG_9' : 10,
        'XP_SLAVE_RST_PTG_10': 11,
        'XP_SLAVE_RST_PTG_11' : 12,
        'XP_SLAVE_RST_PTG_12' : 13,
        'XP_SLAVE_RST_PTG_13' : 14,
        'XP_SLAVE_RST_PTG_14' : 15,
        'XP_SLAVE_RST_PTG_15' : 16,
        'XP_SLAVE_RST_PTG_16' : 17,
        'XP_SLAVE_RST_PTG_17' : 18,
        'XP_SLAVE_RST_PTG_18' : 19,
        'XP_SLAVE_RST_PTG_19' : 20,
        'XP_SLAVE_RST_PTG_20' : 21,
        'XP_SLAVE_RST_PTG_21' : 22,
        'XP_SLAVE_RST_PTG_22' : 23,
        'XP_SLAVE_RST_PTG_23' : 24,
        'XP_SLAVE_RST_PTG_24' : 25,
        'XP_SLAVE_RST_PTG_25' : 26,
        'XP_SLAVE_RST_PTG_26' : 27,
        'XP_SLAVE_RST_PTG_27' : 28,
        'XP_SLAVE_RST_PTG_28' : 29,
        'XP_SLAVE_RST_PTG_29' : 30,
        'XP_SLAVE_RST_PTG_30' : 31,
        'XP_SLAVE_RST_PTG_31' : 32,
        'XP_SLAVE_RST_EPTG_0' : 33,
        'XP_SLAVE_RST_IBUFFER_0' : 34,
        'XP_SLAVE_RST_IBUFFER_1' : 35,
        'XP_SLAVE_RST_IBUFFER_2' : 36,
        'XP_SLAVE_RST_IBUFFER_3' : 37,
        'XP_SLAVE_RST_DP_RXDMA_0' : 38,
        'XP_SLAVE_RST_DP_RXDMA_1' : 39,
        'XP_SLAVE_RST_DP_RXDMA_2' : 40,
        'XP_SLAVE_RST_DP_RXDMA_3' : 41,
        'XP_SLAVE_RST_DP_SDMA_0' : 42,
        'XP_SLAVE_RST_DP_SDMA_1' : 43,
        'XP_SLAVE_RST_DP_TXDMA_0' : 44,
        'XP_SLAVE_RST_DP_TXDMA_1' : 45,
        'XP_SLAVE_RST_DP_TXDMA_2' : 46,
        'XP_SLAVE_RST_DP_TXDMA_3' : 47,
        'XP_SLAVE_RST_OBUFFER_0' : 48,
        'XP_SLAVE_RST_OBUFFER_1' : 49,
        'XP_SLAVE_RST_OBUFFER_2' : 50,
        'XP_SLAVE_RST_OBUFFER_3' : 51,
        'XP_SLAVE_RST_IOBUFFER_0' : 52,
        'XP_SLAVE_RST_IOBUFFER_1' : 53,
        'XP_SLAVE_RST_DP_PM_0' : 54,
        'XP_SLAVE_RST_DP_PM_1' : 55,
        'XP_SLAVE_RST_DP_PM_2' : 56,
        'XP_SLAVE_RST_DP_PM_3' : 57,
        'XP_SLAVE_RST_DP_PM_4' : 58,
        'XP_SLAVE_RST_DP_PM_5' : 59,
        'XP_SLAVE_RST_DP_PM_6' : 60,
        'XP_SLAVE_RST_DP_PM_7' : 61,
        'XP_SLAVE_RST_DP_PM_8' : 62,
        'XP_SLAVE_RST_DP_PM_9': 63,
        'XP_SLAVE_RST_DP_PM_10' : 64,
        'XP_SLAVE_RST_DP_PM_11': 65,
        'XP_SLAVE_RST_DP_PM_12' : 66,
        'XP_SLAVE_RST_DP_PM_13' : 67,
        'XP_SLAVE_RST_DP_PM_14' : 68,
        'XP_SLAVE_RST_DP_PM_15' : 69,
        'XP_SLAVE_RST_BM_0' : 70,
        'XP_SLAVE_RST_BM_1' : 71,
        'XP_SLAVE_RST_BM_2' : 72,
        'XP_SLAVE_RST_BM_3' : 73,
        'XP_SLAVE_RST_SDE_DECODER_0' : 74,
        'XP_SLAVE_RST_SDE_DECODER_1' : 75,
        'XP_SLAVE_RST_SDE_PARSER_0' : 76,
        'XP_SLAVE_RST_SDE_PARSER_1' : 77,
        'XP_SLAVE_RST_SDE_ACM_0' : 78,
        'XP_SLAVE_RST_SDE_ACM_1' : 79,
        'XP_SLAVE_RST_SDE_HDBF_0' : 80,
        'XP_SLAVE_RST_SDE_HDBF_1' : 81,
        'XP_SLAVE_RST_SDE_MRE_0' : 82,
        'XP_SLAVE_RST_SDE_MRE_1' : 83,
        'XP_SLAVE_RST_SDE_MME_0' : 84,
        'XP_SLAVE_RST_SDE_MME_1' : 85,
        'XP_SLAVE_RST_SDE_FR_0' : 86,
        'XP_SLAVE_RST_SDE_FR_1' : 87,
        'XP_SLAVE_RST_SDE_FM_0' : 88,
        'XP_SLAVE_RST_SDE_FM_1': 89,
        'XP_SLAVE_RST_PKTTKR_0' : 90,
        'XP_SLAVE_RST_PKTTKR_1' : 91,
        'XP_SLAVE_RST_SDE_URW_0' : 92,
        'XP_SLAVE_RST_SDE_URW_1' : 93,
        'XP_SLAVE_RST_SDE_URW_2' : 94,
        'XP_SLAVE_RST_SDE_URW_3' : 95,
        'XP_SLAVE_RST_SDE_URW_4' : 96,
        'XP_SLAVE_RST_SDE_URW_5' : 97,
        'XP_SLAVE_RST_SDE_URW_6' : 98,
        'XP_SLAVE_RST_SDE_URW_7' : 99,
        'XP_SLAVE_RST_SDE_ISME_0' : 100,
        'XP_SLAVE_RST_SDE_ISME_1' : 101,
        'XP_SLAVE_RST_SDE_ISME_2' : 102,
        'XP_SLAVE_RST_SDE_ISME_3' : 103,
        'XP_SLAVE_RST_SDE_ISME_4' : 104,
        'XP_SLAVE_RST_SDE_ISME_5' : 105,
        'XP_SLAVE_RST_SDE_LDE_0' : 106,
        'XP_SLAVE_RST_SDE_LDE_1' : 107,
        'XP_SLAVE_RST_SDE_LDE_2' : 108,
        'XP_SLAVE_RST_SDE_LDE_3' : 109,
        'XP_SLAVE_RST_SDE_LDE_4' : 110,
        'XP_SLAVE_RST_SDE_LDE_5' : 111,
        'XP_SLAVE_RST_SDE_LDE_6': 112,
        'XP_SLAVE_RST_SDE_LDE_7' : 113,
        'XP_SLAVE_RST_SDE_LDE_8' : 114,
        'XP_SLAVE_RST_SDE_LDE_9' : 115,
        'XP_SLAVE_RST_SDE_LDE_10' : 116,
        'XP_SLAVE_RST_SDE_LDE_11' : 117,
        'XP_SLAVE_RST_SDE_LDE_12' : 118,
        'XP_SLAVE_RST_SDE_LDE_13' : 119,
        'XP_SLAVE_RST_SDE_LDE_14' : 120,
        'XP_SLAVE_RST_SDE_LDE_15' : 121,
        'XP_SLAVE_RST_SDE_LDE_16' : 122,
        'XP_SLAVE_RST_SDE_LDE_17' : 123,
        'XP_SLAVE_RST_SDE_LDE_18' : 124,
        'XP_SLAVE_RST_SDE_LDE_19' : 125,
        'XP_SLAVE_RST_SDE_LDE_20' : 126,
        'XP_SLAVE_RST_SDE_LDE_21' : 127,
        'XP_SLAVE_RST_SDE_LDE_22' : 128,
        'XP_SLAVE_RST_SDE_LDE_23' : 129,
        'XP_SLAVE_RST_SDE_MEM_0' : 130,
        'XP_SLAVE_RST_SDE_MEM_1' : 131,
        'XP_SLAVE_RST_SEARCH_POOL_T0_0' : 132,
        'XP_SLAVE_RST_SEARCH_POOL_T0_1' : 133,
        'XP_SLAVE_RST_SEARCH_POOL_T1_0' : 134,
        'XP_SLAVE_RST_SEARCH_POOL_T1_1' : 135,
        'XP_SLAVE_RST_SEARCH_POOL_A0_0' : 136,
        'XP_SLAVE_RST_SEARCH_POOL_A0_1' : 137,
        'XP_SLAVE_RST_SEARCH_POOL_A1_0' : 138,
        'XP_SLAVE_RST_SEARCH_POOL_A1_1' : 139,
        'XP_SLAVE_RST_SEARCH_POOL_L0_0' : 140,
        'XP_SLAVE_RST_SEARCH_POOL_L0_1' : 141,
        'XP_SLAVE_RST_SEARCH_POOL_L0_2' : 142,
        'XP_SLAVE_RST_SEARCH_POOL_L0_3' : 143,
        'XP_SLAVE_RST_SEARCH_POOL_L0_4' : 144,
        'XP_SLAVE_RST_SEARCH_POOL_L0_5' : 145,
        'XP_SLAVE_RST_SEARCH_POOL_L0_6' : 146,
        'XP_SLAVE_RST_SEARCH_POOL_L0_7' : 147,
        'XP_SLAVE_RST_SEARCH_POOL_L0_8' : 148,
        'XP_SLAVE_RST_SEARCH_POOL_L0_9' : 149,
        'XP_SLAVE_RST_SEARCH_POOL_L0_10' : 150,
        'XP_SLAVE_RST_SEARCH_POOL_L0_11' : 151,
        'XP_SLAVE_RST_SEARCH_POOL_L1_0' : 152,
        'XP_SLAVE_RST_SEARCH_POOL_L1_1' : 153,
        'XP_SLAVE_RST_SEARCH_POOL_C0_0' : 154,
        'XP_SLAVE_RST_SEARCH_POOL_C0_1' : 155,
        'XP_SLAVE_RST_SEARCH_POOL_C1_0' : 156,
        'XP_SLAVE_RST_SEARCH_POOL_C1_1' : 157,
        'XP_SLAVE_RST_SEARCH_SE_0' : 158,
        'XP_SLAVE_RST_SEARCH_SE_1' : 159,
        'XP_SLAVE_RST_SEARCH_MEM_0' : 160,
        'XP_SLAVE_RST_SEARCH_AGE_0' : 161,
        'XP_SLAVE_RST_SEARCH_AGE_1' : 162,
        'XP_SLAVE_RST_SEARCH_REQNETWK_0' : 163,
        'XP_SLAVE_RST_SEARCH_REQNETWK_1' : 164,
        'XP_SLAVE_RST_SEARCH_RSLTNETWK_0' : 165,
        'XP_SLAVE_RST_SEARCH_RSLTNETWK_1' : 166,
        'XP_SLAVE_RST_TXQ_DQ_0' : 167,
        'XP_SLAVE_RST_TXQ_EQ_0' : 168,
        'XP_SLAVE_RST_TXQ_EQ_DQ_0' : 169,
        'XP_SLAVE_RST_TXQ_EQ_DQ_1' : 170,
        'XP_SLAVE_RST_TXQ_EQ_DQ_2' : 171,
        'XP_SLAVE_RST_TXQ_EQ_DQ_3' : 172,
        'XP_SLAVE_RST_TXQ_AQM_0' : 173,
        'XP_SLAVE_RST_TXQ_AQM_1' : 174,
        'XP_SLAVE_RST_TXQ_AQM_2' : 175,
        'XP_SLAVE_RST_TXQ_AQM_3' : 176,
        'XP_SLAVE_RST_TXQ_TBM_0' : 177,
        'XP_SLAVE_RST_TXQ_TBM_1' : 178,
        'XP_SLAVE_RST_TXQ_TBM_2' : 179,
        'XP_SLAVE_RST_TXQ_TBM_3' : 180,
        'XP_SLAVE_RST_TXQ_TBWRAPPER_0' : 181,
        'XP_SLAVE_RST_TXQ_CNT_LEN_0' : 182,
        'XP_SLAVE_RST_TXQ_CNT_STATS_0' : 183 ,
    }
}


#/*****************************************************************************************************/
# Print enum
#/*****************************************************************************************************/
def printEnumDict(enumname):
    global enumDictionaries
    count = 0
    for key,value in enumDictionaries.items():
        if key == enumname:
            for keys,values in sorted(enumDictionaries[key].iteritems(), key = lambda (k, v) : (v, k)):
                if(count % 3) == 0:
                    print
                print " %10d : %-40s " %(values, keys),
                count += 1
    print


#/*****************************************************************************************************/
# Auto completion
#/*****************************************************************************************************/
def autoCompletion(line, text, tempDict):
    global enumDictionaries
    for key,value in sorted(tempDict.iteritems()):
        if len(line.split()) == key:
            return [i for i in enumDictionaries[value].keys() if i.startswith(text.upper())]
        elif line[len(line) - 1 ] != ' ' and len(line.split()) - 1 == key:
            return [i for i in enumDictionaries[value].keys() if i.startswith(text.upper())]
    return []
