{
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   0, 32,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},   0  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   1, 33,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},   1  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   2, 34,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},   2  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   3, 35,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},   3  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   4, 40,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},   4  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   5, 41,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},   5  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   6, 42,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},   6  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   7, 43,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},   7  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   8, 48,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},   8  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   9, 49,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},   9  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  10, 50,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  10  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  11, 51,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  11  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  12, 56,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  12  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  13, 57,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  13  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  14, 58,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  14  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  15, 59,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  15  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  16, 64,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  16  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  17, 65,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  17  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  18, 66,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  18  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  19, 67,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  19  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  20, 72,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  20  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  21, 73,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  21  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  22, 74,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  22  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  23, 75,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  23  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  24, 80,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  24  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  25, 81,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  25  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  26, 82,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  26  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  27, 83,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  27  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  28, 88,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  28  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  29, 89,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  29  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  30, 90,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  30  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  31, 91,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  31  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  32, 96,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  32  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  33, 97,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  33  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  34, 98,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  34  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  35, 99,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  35  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  36, 104, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  36  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  37, 105, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  37  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  38, 106, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  38  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  39, 107, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  39  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  40, 112, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  40  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  41, 113, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  41  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  42, 114, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  42  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  43, 115, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  43  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  44, 120, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  44  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  45, 121, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  45  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  46, 122, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  46  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  47, 123, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  47  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  48, 128, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  48  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  49, 129, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  49  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  50, 130, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  50  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  51, 131, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  51  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  52, 136, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  52  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  53, 137, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  53  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  54, 138, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  54  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  55, 139, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  55  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  56, 144, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  56  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  57, 145, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  57  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  58, 146, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  58  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  59, 147, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  59  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  60, 152, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  60  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  64, 153, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  64  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  65, 154, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  65  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  66, 155, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  66  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  67, 160, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  67  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  68, 161, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  68  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  69, 162, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  69  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  70, 163, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  70  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  71, 168, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  71  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  72, 169, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  72  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  73, 170, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  73  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  74, 171, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  74  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  75, 176, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  75  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  76, 177, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  76  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  77, 178, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  77  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  78, 179, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  78  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  79, 184, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  79  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  80, 185, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  80  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  81, 186, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  81  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  82, 187, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  82  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  83, 192, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  83  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  84, 193, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  84  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  85, 194, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  85  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  86, 195, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  86  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  87, 200, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  87  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  88, 201, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  88  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  89, 202, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  89  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  90, 203, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  90  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  91, 208, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  91  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  92, 209, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  92  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  93, 210, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  93  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  94, 211, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  94  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  95, 216, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  95  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  96, 217, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  96  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  97, 218, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  97  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  98, 219, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  98  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  99, 224, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  99  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 100, 225, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 100  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 101, 226, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 101  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 102, 227, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 102  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 103, 232, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 103  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 104, 233, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 104  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 105, 234, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 105  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 106, 235, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 106  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 107, 240, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 107  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 108, 241, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 108  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 109, 242, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 109  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 110, 243, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 110  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 111, 248, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 111  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 112, 249, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 112  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 113, 250, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 113  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 114, 251, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 114  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 115,  0,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 115  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 116,  1,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 116  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 117,  2,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 117  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 118,  3,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 118  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 119,  8,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 119  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 120,  9,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 120  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 121, 10,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 121  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 122, 11,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 122  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 123, 16,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 123  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 124, 17,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 124  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 125, 18,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 125  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 126, 19,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 126  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 127, 24,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 127  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 128, 25,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 128  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 129, 26,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 129  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 130, 27,  0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 130  }},

    //10G CPU port
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 131, 258, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 131  }},

    // CPU PORT
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {63, 273, 0, PROFILE_INTERFACE_MODE_KR_E, 10 }},

    /* simulation */
    {.profileType = PROFILE_TYPE_SIM_INIFILE_E, .profileValue.sim_inifile = "-i ./iniFiles/falcon_12_8_A0_wm.ini"},
    {.profileType = PROFILE_TYPE_HW_SKU_E, .profileValue.hwTableSizes = &hw_sku_profiles_falcon[2]},

    /* last */
    {.profileType = PROFILE_TYPE_LAST_E, .profileValue.no_param = 0}

};
