{
    /* port mapping  for aldrin copied from aldrinDefaultMap (gtDbDxBobcat2.c) also base on cpssTypes.h mapping for C81F11AB
     * macNum is same as interface num in the mapping array*/
    /*                                                                  portNum macNum  txQNum  interfaceMode                       interfaceSpeed */
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {0,     ALDRIN2_MAC_AND_TXQ_PORT_MAC(0),            PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {1,     ALDRIN2_MAC_AND_TXQ_PORT_MAC(1),            PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {2,     ALDRIN2_MAC_AND_TXQ_PORT_MAC(2),            PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {3,     ALDRIN2_MAC_AND_TXQ_PORT_MAC(3),            PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {4,     ALDRIN2_MAC_AND_TXQ_PORT_MAC(4),            PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {5,     ALDRIN2_MAC_AND_TXQ_PORT_MAC(5),            PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {6,     ALDRIN2_MAC_AND_TXQ_PORT_MAC(6),            PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {7,     ALDRIN2_MAC_AND_TXQ_PORT_MAC(7),            PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {8,     ALDRIN2_MAC_AND_TXQ_PORT_MAC(8),            PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {9,     ALDRIN2_MAC_AND_TXQ_PORT_MAC(9),            PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {10,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(10),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {11,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(11),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {12,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(12),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {13,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(13),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {14,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(14),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {15,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(15),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {16,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(16),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {17,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(17),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {18,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(18),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {19,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(19),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {20,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(20),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {21,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(21),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {22,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(22),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {23,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(23),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {24,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(24),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {25,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(25),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {26,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(26),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {27,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(27),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {28,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(28),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {29,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(29),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {30,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(30),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {31,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(31),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {32,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(32),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {33,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(33),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {34,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(34),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {35,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(35),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {36,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(36),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {37,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(37),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {38,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(38),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {39,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(39),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {40,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(40),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {41,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(41),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {42,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(42),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {43,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(43),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {44,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(44),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {45,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(45),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {46,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(46),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {47,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(47),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {48,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(48),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {49,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(49),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {50,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(50),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {51,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(51),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {52,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(52),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {53,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(53),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {54,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(54),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {55,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(55),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {56,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(56),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {57,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(57),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {58,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(58),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
#if 0 // NOT VALID                                                                                             
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {59,    9,          PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {60,    10,         PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {61,    1,          PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {62,    2,          PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {63,    3,          PROFILE_INTERFACE_MODE_KR_E,        10}},
#endif // NOT VALID                                                                                                           
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {64,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(59),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {65,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(60),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {66,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(61),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {67,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(62),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {68,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(63),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {69,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(64),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {70,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(65),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {71,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(66),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {72,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(67),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {73,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(68),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {74,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(69),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {75,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(70),           PROFILE_INTERFACE_MODE_KR_E,        10000}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {76,    ALDRIN2_MAC_AND_TXQ_PORT_MAC(71),           PROFILE_INTERFACE_MODE_KR_E,        10000}},

    /* simulation */
    //      {.profileType = PROFILE_TYPE_SIM_INIFILE_E, .profileValue.sim_inifile = "-e aldrin_x2_pss_wm.ini"         },
    {.profileType = PROFILE_TYPE_SIM_INIFILE_E, .profileValue.sim_inifile = "-e aldrin2_A0_pss_wm.ini"        },
    {.profileType = PROFILE_TYPE_HW_SKU_E, .profileValue.hwTableSizes = &hw_sku_profiles_ald[0]},
    /* last */
    {.profileType = PROFILE_TYPE_LAST_E,        .profileValue.no_param = 0 }
};
