{
    /*                                                               portNum          macNum  txQNum            interfaceMode      interfaceSpeed       */
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  0, ALDRIN2_MAC_AND_TXQ_PORT_MAC( 0), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0},  0 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  1, ALDRIN2_MAC_AND_TXQ_PORT_MAC( 1), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0},  1 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  2, ALDRIN2_MAC_AND_TXQ_PORT_MAC( 2), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0},  2 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  3, ALDRIN2_MAC_AND_TXQ_PORT_MAC( 3), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0},  3 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  4, ALDRIN2_MAC_AND_TXQ_PORT_MAC( 4), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0},  4 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  5, ALDRIN2_MAC_AND_TXQ_PORT_MAC( 5), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0},  5 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  6, ALDRIN2_MAC_AND_TXQ_PORT_MAC( 6), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0},  6 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  7, ALDRIN2_MAC_AND_TXQ_PORT_MAC( 7), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0},  7 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  8, ALDRIN2_MAC_AND_TXQ_PORT_MAC( 8), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0},  8 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  9, ALDRIN2_MAC_AND_TXQ_PORT_MAC( 9), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0},  9 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 10, ALDRIN2_MAC_AND_TXQ_PORT_MAC(10), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 10 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 11, ALDRIN2_MAC_AND_TXQ_PORT_MAC(11), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 11 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 12, ALDRIN2_MAC_AND_TXQ_PORT_MAC(12), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 12 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 13, ALDRIN2_MAC_AND_TXQ_PORT_MAC(13), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 13 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 14, ALDRIN2_MAC_AND_TXQ_PORT_MAC(14), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 14 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 15, ALDRIN2_MAC_AND_TXQ_PORT_MAC(15), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 15 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 16, ALDRIN2_MAC_AND_TXQ_PORT_MAC(16), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 16 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 17, ALDRIN2_MAC_AND_TXQ_PORT_MAC(17), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 17 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 18, ALDRIN2_MAC_AND_TXQ_PORT_MAC(18), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 18 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 19, ALDRIN2_MAC_AND_TXQ_PORT_MAC(19), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 19 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 20, ALDRIN2_MAC_AND_TXQ_PORT_MAC(20), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 20 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 21, ALDRIN2_MAC_AND_TXQ_PORT_MAC(21), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 21 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 22, ALDRIN2_MAC_AND_TXQ_PORT_MAC(22), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 22 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 23, ALDRIN2_MAC_AND_TXQ_PORT_MAC(23), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 23 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 28, ALDRIN2_MAC_AND_TXQ_PORT_MAC(28), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 28 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 29, ALDRIN2_MAC_AND_TXQ_PORT_MAC(29), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 29 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 30, ALDRIN2_MAC_AND_TXQ_PORT_MAC(30), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 30 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 31, ALDRIN2_MAC_AND_TXQ_PORT_MAC(31), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 31 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 36, ALDRIN2_MAC_AND_TXQ_PORT_MAC(36), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 36 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 37, ALDRIN2_MAC_AND_TXQ_PORT_MAC(37), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 37 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 38, ALDRIN2_MAC_AND_TXQ_PORT_MAC(38), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 38 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 39, ALDRIN2_MAC_AND_TXQ_PORT_MAC(39), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 39 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 44, ALDRIN2_MAC_AND_TXQ_PORT_MAC(44), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 44 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 45, ALDRIN2_MAC_AND_TXQ_PORT_MAC(45), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 45 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 46, ALDRIN2_MAC_AND_TXQ_PORT_MAC(46), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 46 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 47, ALDRIN2_MAC_AND_TXQ_PORT_MAC(47), PROFILE_INTERFACE_MODE_SR_LR_E, 10, .phyInfo = {0, 0, 0, 0}, 47 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 52, ALDRIN2_MAC_AND_TXQ_PORT_MAC(52), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 52 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 53, ALDRIN2_MAC_AND_TXQ_PORT_MAC(53), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 53 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 54, ALDRIN2_MAC_AND_TXQ_PORT_MAC(54), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 54 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 55, ALDRIN2_MAC_AND_TXQ_PORT_MAC(55), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 55 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 65, ALDRIN2_MAC_AND_TXQ_PORT_MAC(60), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 65 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 66, ALDRIN2_MAC_AND_TXQ_PORT_MAC(61), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 66 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 67, ALDRIN2_MAC_AND_TXQ_PORT_MAC(62), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 67 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 68, ALDRIN2_MAC_AND_TXQ_PORT_MAC(63), PROFILE_INTERFACE_MODE_1000BASE_X_E, 10, .phyInfo = {0, 0, 0, 0}, 68 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 69, ALDRIN2_MAC_AND_TXQ_PORT_MAC(68), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 69 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 70, ALDRIN2_MAC_AND_TXQ_PORT_MAC(69), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 70 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 71, ALDRIN2_MAC_AND_TXQ_PORT_MAC(70), PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 71 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 72, ALDRIN2_MAC_AND_TXQ_PORT_MAC(71), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 72 }},

   
    //CPU SDMA PORTs
     {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E, .profileValue.portMap = { 63, 0, 99, PROFILE_INTERFACE_MODE_KR_E, 10 }},
    
    /* Polarity                                                                lane   invTx    invRx */
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  0, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  1, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  2, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  3, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  4, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  5, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  6, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  7, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  8, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  9, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 10, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 11, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 12, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 13, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 14, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 15, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 16, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 17, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 18, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 19, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 20, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 21, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 22, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 23, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 28, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 29, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 30, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 31, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 36, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 37, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 38, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 39, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 44, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 45, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 46, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 47, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 52, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 53, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 54, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 55, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 60, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 61, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 62, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 63, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 68, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 69, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 70, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 71, GT_FALSE, GT_FALSE }},
    /* simulation */
    {.profileType = PROFILE_TYPE_SIM_INIFILE_E, .profileValue.sim_inifile  = "-i iniFiles/aldrin2_xl_fujitsu_large.ini" },
    {.profileType = PROFILE_TYPE_HW_SKU_E,      .profileValue.hwTableSizes = &hw_sku_profiles_aldrin2_fl[0] },
    /* last */
    {.profileType = PROFILE_TYPE_LAST_E,        .profileValue.no_param = 0 }
};
