{
    /*                                                               portNum          macNum  txQNum            interfaceMode      interfaceSpeed       */
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  0, ALDRIN2_MAC_AND_TXQ_PORT_MAC(69), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  0 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  1, ALDRIN2_MAC_AND_TXQ_PORT_MAC(68), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  1 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  2, ALDRIN2_MAC_AND_TXQ_PORT_MAC(67), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  2 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  3, ALDRIN2_MAC_AND_TXQ_PORT_MAC(66), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  3 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  4, ALDRIN2_MAC_AND_TXQ_PORT_MAC(65), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  4 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  5, ALDRIN2_MAC_AND_TXQ_PORT_MAC(64), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  5 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  6, ALDRIN2_MAC_AND_TXQ_PORT_MAC(63), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  6 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  7, ALDRIN2_MAC_AND_TXQ_PORT_MAC(62), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  7 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  8, ALDRIN2_MAC_AND_TXQ_PORT_MAC(61), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  8 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {  9, ALDRIN2_MAC_AND_TXQ_PORT_MAC(60), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0},  9 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 10, ALDRIN2_MAC_AND_TXQ_PORT_MAC(59), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 10 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 11, ALDRIN2_MAC_AND_TXQ_PORT_MAC(58), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 11 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 12, ALDRIN2_MAC_AND_TXQ_PORT_MAC(56), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 12 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 13, ALDRIN2_MAC_AND_TXQ_PORT_MAC(55), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 13 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 14, ALDRIN2_MAC_AND_TXQ_PORT_MAC(54), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 14 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 15, ALDRIN2_MAC_AND_TXQ_PORT_MAC(53), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 15 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 16, ALDRIN2_MAC_AND_TXQ_PORT_MAC(52), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 16 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 17, ALDRIN2_MAC_AND_TXQ_PORT_MAC(51), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 17 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 18, ALDRIN2_MAC_AND_TXQ_PORT_MAC(50), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 18 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 19, ALDRIN2_MAC_AND_TXQ_PORT_MAC(49), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 19 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 20, ALDRIN2_MAC_AND_TXQ_PORT_MAC(48), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 20 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 21, ALDRIN2_MAC_AND_TXQ_PORT_MAC(47), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 21 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 22, ALDRIN2_MAC_AND_TXQ_PORT_MAC(46), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 22 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 23, ALDRIN2_MAC_AND_TXQ_PORT_MAC(45), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 23 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 24, ALDRIN2_MAC_AND_TXQ_PORT_MAC(44), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 24 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 25, ALDRIN2_MAC_AND_TXQ_PORT_MAC(43), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 25 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 26, ALDRIN2_MAC_AND_TXQ_PORT_MAC(42), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 26 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 27, ALDRIN2_MAC_AND_TXQ_PORT_MAC(41), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 27 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 28, ALDRIN2_MAC_AND_TXQ_PORT_MAC(40), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 28 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 29, ALDRIN2_MAC_AND_TXQ_PORT_MAC(39), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 29 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 30, ALDRIN2_MAC_AND_TXQ_PORT_MAC(38), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 30 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 31, ALDRIN2_MAC_AND_TXQ_PORT_MAC(37), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 31 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 32, ALDRIN2_MAC_AND_TXQ_PORT_MAC(36), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 32 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 33, ALDRIN2_MAC_AND_TXQ_PORT_MAC(35), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 33 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 34, ALDRIN2_MAC_AND_TXQ_PORT_MAC(34), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 34 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 35, ALDRIN2_MAC_AND_TXQ_PORT_MAC(33), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 35 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 36, ALDRIN2_MAC_AND_TXQ_PORT_MAC(32), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 36 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 37, ALDRIN2_MAC_AND_TXQ_PORT_MAC(31), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 37 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 38, ALDRIN2_MAC_AND_TXQ_PORT_MAC(30), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 38 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 39, ALDRIN2_MAC_AND_TXQ_PORT_MAC(29), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 39 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 40, ALDRIN2_MAC_AND_TXQ_PORT_MAC(28), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 40 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 41, ALDRIN2_MAC_AND_TXQ_PORT_MAC(27), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 41 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 42, ALDRIN2_MAC_AND_TXQ_PORT_MAC(26), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 42 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 43, ALDRIN2_MAC_AND_TXQ_PORT_MAC(25), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 43 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 44, ALDRIN2_MAC_AND_TXQ_PORT_MAC(24), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 44 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 45, ALDRIN2_MAC_AND_TXQ_PORT_MAC(23), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 45 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 46, ALDRIN2_MAC_AND_TXQ_PORT_MAC(22), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 46 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = { 47, ALDRIN2_MAC_AND_TXQ_PORT_MAC(21), PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 47 }},

    //CPU SDMA PORTs
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E, .profileValue.portMap = { 63, 0, 99, PROFILE_INTERFACE_MODE_KR_E, 10 }},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E, .profileValue.portMap = { 64, 0, 49, PROFILE_INTERFACE_MODE_KR_E, 10 }},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E, .profileValue.portMap = { 65, 0, 74, PROFILE_INTERFACE_MODE_KR_E, 10 }},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E, .profileValue.portMap = { 66, 0, 23, PROFILE_INTERFACE_MODE_KR_E, 10 }},

    /* Polarity                                                                lane   invTx    invRx */
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 69,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 68,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 67, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 66,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 65, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 64,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 63, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 62,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 61, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 60,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 59, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 58,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 56,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 55,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 54,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 53,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 52,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 51,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 50,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 49, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 48, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 47,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 46, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 45, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 44,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 43, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 42,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 41, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 40,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 39, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 38,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 37, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 36,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 35, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 34,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 33, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 32,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 31, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 30,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 29, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 28,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 27, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 26,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 25,  GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 24, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 23, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 22, GT_FALSE, GT_FALSE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 21, GT_FALSE, GT_FALSE }},

    /* simulation */
    {.profileType = PROFILE_TYPE_SIM_INIFILE_E, .profileValue.sim_inifile  = "-i iniFiles/aldrin2_A0_pss_wm.ini" },
    {.profileType = PROFILE_TYPE_HW_SKU_E,      .profileValue.hwTableSizes = &hw_sku_profiles_aldrin2_xl[0] },
    /* last */
    {.profileType = PROFILE_TYPE_LAST_E,        .profileValue.no_param = 0 }
};
