{
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {1,  1,    0, PROFILE_INTERFACE_MODE_QSGMII_E, 10,   .phyInfo = {1, 0x11, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 1  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {2,  0,    1, PROFILE_INTERFACE_MODE_QSGMII_E, 10,   .phyInfo = {1, 0x10, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 2  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {3,  3,    2, PROFILE_INTERFACE_MODE_QSGMII_E, 10,   .phyInfo = {1, 0x13, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 3  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {4,  2,    3, PROFILE_INTERFACE_MODE_QSGMII_E, 10,   .phyInfo = {1, 0x12, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 4  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {5,  5,    4, PROFILE_INTERFACE_MODE_QSGMII_E, 10,   .phyInfo = {1, 0x15, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 5  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {6,  4,    5, PROFILE_INTERFACE_MODE_QSGMII_E, 10,   .phyInfo = {1, 0x14, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 6  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {7,  7,    6, PROFILE_INTERFACE_MODE_QSGMII_E, 10,   .phyInfo = {1, 0x17, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 7  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {8,  6,    7, PROFILE_INTERFACE_MODE_QSGMII_E, 10,   .phyInfo = {1, 0x16, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 8  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {9,  9,    8, PROFILE_INTERFACE_MODE_QSGMII_E, 10,   .phyInfo = {1, 0x19, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 9  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {10,  8,    9, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x18, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 10  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {11,  11,  10, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x1b, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 11  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {12,  10,  11, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x1a, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 12  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {13,  13,  12, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x1d, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 13  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {14,  12,  13, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x1c, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 14  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {15,  15,  14, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x1f, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 15  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {16,  14,  15, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x1e, CPSS_PHY_SMI_INTERFACE_0_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 16  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {17,  17,  16, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x11, CPSS_PHY_SMI_INTERFACE_1_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 17  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {18,  16,  17, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x10, CPSS_PHY_SMI_INTERFACE_1_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 18  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {19,  19,  18, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x13, CPSS_PHY_SMI_INTERFACE_1_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 19  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {20,  18,  19, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x12, CPSS_PHY_SMI_INTERFACE_1_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 20  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {21,  21,  20, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x15, CPSS_PHY_SMI_INTERFACE_1_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 21  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {22,  20,  21, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x14, CPSS_PHY_SMI_INTERFACE_1_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 22  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {23,  23,  22, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x17, CPSS_PHY_SMI_INTERFACE_1_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 23  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {24,  22,  23, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x16, CPSS_PHY_SMI_INTERFACE_1_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 24  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {25,  25,  24, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x11, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 25  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {26,  24,  25, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x10, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 26  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {27,  27,  26, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x13, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 27  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {28,  26,  27, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x12, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 28  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {29,  29,  28, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x15, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 29  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {30,  28,  29, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x14, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 30  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {31,  31,  30, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x17, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 31  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {32,  30,  31, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x16, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 32  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {33,  33,  32, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x19, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 33  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {34,  32,  33, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x18, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 34  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {35,  35,  34, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x1b, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 35  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {36,  34,  35, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x1a, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 36  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {37,  37,  36, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x1d, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 37  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {38,  36,  37, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x1c, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 38  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {39,  39,  38, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x1f, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 39  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {40,  38,  39, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x1e, CPSS_PHY_SMI_INTERFACE_2_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 40  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {41,  41,  40, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x11, CPSS_PHY_SMI_INTERFACE_3_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 41  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {42,  40,  41, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x10, CPSS_PHY_SMI_INTERFACE_3_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 42  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {43,  43,  42, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x13, CPSS_PHY_SMI_INTERFACE_3_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 43  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {44,  42,  43, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x12, CPSS_PHY_SMI_INTERFACE_3_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 44  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {45,  45,  44, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x15, CPSS_PHY_SMI_INTERFACE_3_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 45  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {46,  44,  45, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x14, CPSS_PHY_SMI_INTERFACE_3_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 46  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {47,  47,  46, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x17, CPSS_PHY_SMI_INTERFACE_3_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 47  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {48,  46,  47, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {1, 0x16, CPSS_PHY_SMI_INTERFACE_3_E, CPSS_PHY_XSMI_INTERFACE_MAX_E}, 48  }},
    /*SFP*/
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {56,  58,  56, PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 48  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {57,  59,  57, PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 49  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {58,  56,  58, PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 50  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {59,  57,  59, PROFILE_INTERFACE_MODE_SR_LR_E, 100, .phyInfo = {0, 0, 0, 0}, 51  }},
#if 0
    /*QSFP 40g. 4x10G*/
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {64,  65,  64, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 64   }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {65,  66,  65, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 65   }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {66,  64,  66, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 66   }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {67,  67,  67, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 67   }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {68,  69,  68, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 68   }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {69,  70,  69, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 69   }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {70,  68,  70, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 70   }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {71,  71,  71, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 71   }},
#endif
    /*1g */
    //{.profileType = PROFILE_TYPE_PORT_MAP_E, .profileValue.portMap = {90,  62,  62, PROFILE_INTERFACE_MODE_QSGMII_E, 10,  .phyInfo = {0, 0, 0, 0}, 60  }},

    // CPU PORT
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {63,    127,    63,  PROFILE_INTERFACE_MODE_KR_E,        10}},

    /* Polarity                                                                 laneNum  invertTx    invertRx*/
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 25,     GT_FALSE,   GT_TRUE   }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 24,     GT_TRUE,    GT_TRUE   }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 27,     GT_FALSE,   GT_TRUE   }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 26,     GT_TRUE,    GT_TRUE   }},

    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 34,     GT_FALSE,   GT_TRUE   }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 33,     GT_TRUE,   GT_TRUE   }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 35,     GT_TRUE,   GT_TRUE   }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 32,     GT_TRUE,   GT_TRUE   }},

    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 30,     GT_TRUE,   GT_FALSE   }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 29,     GT_FALSE,   GT_FALSE   }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 31,     GT_FALSE,   GT_FALSE   }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 29,     GT_TRUE,   GT_TRUE   }},
    /* simulation */
    //{.profileType = PROFILE_TYPE_SIM_INIFILE_E, .profileValue.sim_inifile = "-i ./iniFiles/bobk_caelum_A1_pss_wm.ini"},
    {.profileType = PROFILE_TYPE_SIM_INIFILE_E, .profileValue.sim_inifile = "-i ./iniFiles/bobk_caelum_pss_wm.ini"},
    {.profileType = PROFILE_TYPE_HW_SKU_E, .profileValue.hwTableSizes = &hw_sku_profiles_cygnus[0]},

    /* last */
    {.profileType = PROFILE_TYPE_LAST_E, .profileValue.no_param = 0}

};
