{
#if 1
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   0,    0, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   1,    1, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   2,    2, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   3,    3, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  18,   18, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  20,   20, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  32,   32, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  35,   35, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  36,   36, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  54,   54, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  55,   55, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  56,   56, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  57,   57, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  58,   58, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  64,   64, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  65,   66, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  66,   68, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  67,   70, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  68,   72, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  69,   74, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  70,   76, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  71,   78, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  72,   80, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  73,   82, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  74,   84, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  75,   86, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  76,   88, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  77,   90, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  78,   92, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  79,   94, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  80,   96, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  81,   98, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  82,  100, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  83,  102, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  84,  104, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  85,  106, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  86,  108, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  87,  110, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  88,  112, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  89,  114, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  90,  116, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  91,  118, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  92,  120, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  93,  122, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  94,  124, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  95,  126, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  96,  128, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  97,  130, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  98,  132, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  99,  134, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 100,  136, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 101,  138, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 102,  140, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 103,  142, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 104,  144, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 105,  146, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 106,  148, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 107,  150, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 108,  152, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 109,  154, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 110,  176, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 111,  180, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 112,  184, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 113,  188, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 114,  192, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 115,  196, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 116,  200, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 117,  204, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 118,  208, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 119,  212, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},

    /*CPU TODO*/
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {63,    259,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {121,   261,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {122,   262,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {123,   263,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {124,   268,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {125,   269,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {126,   270,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {127,   271,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},

#else /*TODO revisit for txq*/
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 0,  0, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 1,  1, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 2,  2, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 3,  3, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 4,  4, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 5,  5, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 6,  6, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 7,  7, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 8,  8, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 9,  9, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {10, 10, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {11, 11, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {12, 12, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {13, 13, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {14, 14, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {15, 15, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {16, 16, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {17, 17, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {18, 18, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {19, 19, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {20, 20, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {21, 21, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {22, 22, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {23, 23, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {24, 24, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {25, 25, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {26, 26, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {27, 27, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {28, 28, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {29, 29, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {30, 30, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {31, 31, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {32, 32, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {33, 33, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {34, 34, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {35, 35, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {36, 36, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {37, 37, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {38, 38, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {39, 39, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {40, 40, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {41, 41, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {42, 42, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {43, 43, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {44, 44, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {45, 45, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {46, 46, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {47, 47, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {48, 48, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {49, 49, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {50, 50, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {51, 51, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {52, 52, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {53, 53, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {54, 54, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {55, 55, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {56, 56, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {57, 57, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {58, 58, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {64, 59, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {65, 60, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {66, 61, 8,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    /*TODO xps port allocator is overlapping with CPU ports*/
    //{.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {67, 62, 8 ,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    //{.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {68, 63, 8 ,  PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    /*TODO handle this 10g port*/
    //{.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {69, 64, 0 ,  PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}}},

    /*CPU TODO*/
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {63,    259,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {121,   261,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {122,   262,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {123,   263,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
#endif
    /* simulation */
    {.profileType = PROFILE_TYPE_SIM_INIFILE_E, .profileValue.sim_inifile = "-i ./iniFiles/falcon_3_2_A0_wm.ini"},
    {.profileType = PROFILE_TYPE_HW_SKU_E, .profileValue.hwTableSizes = &hw_sku_profiles_falcon[2]},

    /* last */
    {.profileType = PROFILE_TYPE_LAST_E, .profileValue.no_param = 0}

}; // falcon_3_2_profile
