{
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  0,     0, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  1,     1, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  2,     2, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  3,     3, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  4,     4, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  5,     5, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  6,     6, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  7,     7, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  8,     8, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  9,     9, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 10,    10, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 11,    11, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 12,    12, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 13,    13, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 14,    14, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 15,    15, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 16,    16, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 17,    17, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 18,    18, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 19,    19, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 20,    20, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 21,    21, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 22,    22, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 23,    23, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 24,    24, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 25,    25, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 26,    26, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 27,    27, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 28,    28, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 29,    29, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 30,    30, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 31,    31, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 32,    32, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 33,    33, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 34,    34, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 35,    35, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 36,    36, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 37,    37, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 38,    38, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 39,    39, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 40,    40, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 41,    41, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 42,    42, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 43,    43, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 44,    44, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 45,    45, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 46,    46, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 47,    47, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 48,    48, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 49,    49, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 50,    50, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 51,    51, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 52,    52, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 53,    53, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 54,    54, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 55,    55, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 56,    56, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 57,    57, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 58,    58, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   64,    59, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   65,    60, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   66,    61, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   67,    62, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   68,    63, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   69,    64, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   70,    65, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   71,    66, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   72,    67, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   73,    68, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   74,    69, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   75,    70, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   76,    71, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   77,    72, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   78,    73, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   79,    74, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   80,    75, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   81,    76, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   82,    77, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   83,    78, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   84,    79, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   85,    80, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   86,    81, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   87,    82, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   88,    83, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   89,    84, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   90,    85, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   91,    86, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   92,    87, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   93,    88, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   94,    89, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   95,    90, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   96,    91, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   97,    92, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   98,    93, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {   99,    94, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  100,    95, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  101,    96, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  102,    97, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  103,    98, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  104,    99, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  105,   100, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  106,   101, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  107,   102, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  108,   103, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  109,   104, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  110,   105, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  111,   106, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  112,   107, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  113,   108, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  114,   109, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  115,   110, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  116,   111, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  117,   112, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  118,   113, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = {  119,   114, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 120,   115, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 121,   116, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 122,   117, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 123,   118, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 124,   119, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 125,   120, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 126,   121, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 127,   122, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 128,   123, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 129,   124, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 130,   125, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 131,   126, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 132,   127, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 133,   128, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 134,   129, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 135,   130, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 136,   131, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 137,   132, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 138,   133, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 139,   134, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 141,   135, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 142,   136, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 143,   137, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 144,   138, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 145,   139, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 146,   141, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 147,   142, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 148,   143, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 149,   144, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 150,   145, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 151,   146, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 152,   147, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 153,   148, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 154,   149, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 155,   150, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 156,   151, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 157,   152, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 158,   153, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 159,   154, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 160,   155, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 161,   156, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 162,   157, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 163,   158, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 164,   159, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 165,   160, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 166,   161, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 167,   162, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 168,   163, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 169,   164, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 170,   165, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 171,   166, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 172,   167, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 173,   168, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 174,   169, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 175,   170, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 176,   171, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 177,   172, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 178,   173, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 179,   174, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 180,   175, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 181,   176, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 182,   177, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 183,   178, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 184,   179, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 185,   180, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 186,   181, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 187,   182, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 188,   183, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 189,   184, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 190,   185, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 191,   186, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 192,   187, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 193,   188, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 194,   189, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 195,   190, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 196,   191, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 197,   192, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 198,   193, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 199,   194, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 200,   195, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 201,   196, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 202,   197, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 203,   198, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 204,   199, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 205,   200, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 206,   201, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 207,   202, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 208,   203, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 209,   204, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 210,   205, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 211,   206, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 212,   207, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 213,   208, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 214,   209, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 215,   210, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 216,   211, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 217,   212, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 218,   213, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 219,   214, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 220,   215, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 221,   216, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 222,   217, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 223,   218, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 224,   219, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 225,   220, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 226,   221, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 227,   222, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 228,   223, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 229,   224, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 230,   225, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 231,   226, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 232,   227, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 233,   228, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 234,   229, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 235,   230, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 236,   231, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 237,   232, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 238,   233, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 239,   234, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 240,   235, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 241,   236, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 242,   237, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 243,   238, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 244,   239, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 245,   240, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 246,   241, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 247,   242, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 248,   243, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 249,   244, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 250,   245, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 251,   246, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 252,   247, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 253,   248, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 254,   249, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 255,   250, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 256,   251, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 257,   252, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 258,   253, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 259,   254, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 260,   255, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}}},

#if 0
    //10G CPU Ports
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 261,   256, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}}},
#endif

    // CPU PORT
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {63,    259,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {264,   260,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {265,   261,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {266,   262,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {267,   263,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {268,   264,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {269,   265,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {270,   266,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {271,   267,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {272,   268,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {273,   269,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {274,   270,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {275,   271,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {276,   272,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {277,   273,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},

    /* Polarity                                                                 laneNum  invertTx    invertRx*/
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 0,    GT_TRUE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 1,    GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 2,    GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 3,    GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 4,    GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 5,    GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 6,    GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 7,    GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 8,    GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 9,    GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 10,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 11,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 12,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 13,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 14,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 15,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 16,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 17,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 18,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 19,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 20,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 21,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 22,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 23,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 24,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 25,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 26,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 27,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 28,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 29,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 30,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 31,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 32,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 33,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 34,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 35,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 36,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 37,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 38,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 39,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 40,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 41,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 42,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 43,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 44,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 45,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 46,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 47,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 48,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 49,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 50,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 51,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 52,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 53,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 54,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 55,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 56,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 57,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 58,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 59,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 60,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 61,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 62,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 63,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 64,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 65,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 66,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 67,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 68,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 69,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 70,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 71,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 72,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 73,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 74,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 75,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 76,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 77,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 78,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 79,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 80,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 81,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 82,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 83,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 84,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 85,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 86,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 87,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 88,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 89,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 90,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 91,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 92,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 93,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 94,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 95,   GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 96,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 97,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 98,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 99,   GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 100,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 101,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 102,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 103,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 104,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 105,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 106,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 107,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 108,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 109,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 110,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 111,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 112,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 113,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 114,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 115,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 116,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 117,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 118,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 119,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 120,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 121,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 122,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 123,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 124,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 125,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 126,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 127,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 128,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 129,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 130,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 131,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 132,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 133,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 134,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 135,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 136,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 137,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 138,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 139,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 140,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 141,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 142,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 143,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 144,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 145,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 146,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 147,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 148,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 149,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 150,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 151,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 152,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 153,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 154,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 155,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 156,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 157,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 158,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 159,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 160,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 161,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 162,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 163,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 164,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 165,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 166,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 167,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 168,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 169,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 170,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 171,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 172,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 173,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 174,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 175,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 176,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 177,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 178,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 179,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 180,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 181,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 182,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 183,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 184,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 185,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 186,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 187,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 188,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 189,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 190,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 191,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 192,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 193,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 194,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 195,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 196,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 197,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 198,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 199,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 200,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 201,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 202,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 203,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 204,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 205,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 206,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 207,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 208,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 209,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 210,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 211,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 212,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 213,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 214,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 215,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 216,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 217,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 218,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 219,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 220,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 221,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 222,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 223,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 224,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 225,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 226,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 227,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 228,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 229,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 230,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 231,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 232,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 233,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 234,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 235,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 236,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 237,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 238,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 239,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 240,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 241,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 242,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 243,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 244,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 245,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 246,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 247,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 248,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 249,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 250,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 251,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 252,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 253,  GT_FALSE,   GT_TRUE  } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 254,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 255,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 256,  GT_FALSE,   GT_FALSE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = { 257,  GT_FALSE,   GT_FALSE } },

    /* simulation */
    {.profileType = PROFILE_TYPE_SIM_INIFILE_E, .profileValue.sim_inifile = "-i ./iniFiles/falcon_12_8_A0_wm.ini"},
    {.profileType = PROFILE_TYPE_HW_SKU_E, .profileValue.hwTableSizes = &hw_sku_profiles_falcon[3]},

    /* last */
    {.profileType = PROFILE_TYPE_LAST_E, .profileValue.no_param = 0}

}; // falcon_belly2belly_profile
