/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,       *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
* cpssFalconTxqPfccRegFile.h
*
* DESCRIPTION:
*      Describe TXQ PFCC registers (Automaticly generated from CIDER)
*
* DEPENDENCIES:
*       None.
*
* FILE REVISION NUMBER:
*       $Revision: 1 $
*
*******************************************************************************/
#ifndef _TXQ_PFCC_REGFILE_H_
#define _TXQ_PFCC_REGFILE_H_

/* start of register global_pfcc_cfg*/

#define      TXQ_PFCC_GLOBAL_PFCC_CFG_MASTER_EN_FIELD_OFFSET            0
#define      TXQ_PFCC_GLOBAL_PFCC_CFG_LAST_PFCC_ENTRY_IDX_FIELD_OFFSET          1
#define      TXQ_PFCC_GLOBAL_PFCC_CFG_PFCC_EN_FIELD_OFFSET          10
#define      TXQ_PFCC_GLOBAL_PFCC_CFG_DEBUG_ENABLE_FIELD_OFFSET         11
#define      TXQ_PFCC_GLOBAL_PFCC_CFG_GLOBAL_TC_POOL_OVRD_FIELD_OFFSET          12


#define      TXQ_PFCC_GLOBAL_PFCC_CFG_MASTER_EN_FIELD_SIZE          1
#define      TXQ_PFCC_GLOBAL_PFCC_CFG_LAST_PFCC_ENTRY_IDX_FIELD_SIZE            9
#define      TXQ_PFCC_GLOBAL_PFCC_CFG_PFCC_EN_FIELD_SIZE            1
#define      TXQ_PFCC_GLOBAL_PFCC_CFG_DEBUG_ENABLE_FIELD_SIZE           1
#define      TXQ_PFCC_GLOBAL_PFCC_CFG_GLOBAL_TC_POOL_OVRD_FIELD_SIZE            1

/* end of global_pfcc_cfg*/


/* start of register pool_CFG*/

#define      TXQ_PFCC_POOL_CFG_POOL_TC_EN_VEC_FIELD_OFFSET          0
#define      TXQ_PFCC_POOL_CFG_POOL_1_TC_EN_VEC_FIELD_OFFSET            8
#define      TXQ_PFCC_POOL_CFG_POOL_2_TC_EN_VEC_FIELD_OFFSET            16
#define      TXQ_PFCC_POOL_CFG_POOL_3_TC_EN_VEC_FIELD_OFFSET            24


#define      TXQ_PFCC_POOL_CFG_POOL_TC_EN_VEC_FIELD_SIZE            8
#define      TXQ_PFCC_POOL_CFG_POOL_1_TC_EN_VEC_FIELD_SIZE          8
#define      TXQ_PFCC_POOL_CFG_POOL_2_TC_EN_VEC_FIELD_SIZE          8
#define      TXQ_PFCC_POOL_CFG_POOL_3_TC_EN_VEC_FIELD_SIZE          8

/* end of pool_CFG*/


/* start of register PFCC_metal_fix*/

#define      TXQ_PFCC_PFCC_METAL_FIX_PFCC_METAL_FIX_FIELD_OFFSET            0


#define      TXQ_PFCC_PFCC_METAL_FIX_PFCC_METAL_FIX_FIELD_SIZE          32

/* end of PFCC_metal_fix*/


/* start of register TC_to_pool_CFG*/

#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_TO_POOL_MAPPING_FIELD_OFFSET            0
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_1_TO_POOL_MAPPING_FIELD_OFFSET          3
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_2_TO_POOL_MAPPING_FIELD_OFFSET          6
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_3_TO_POOL_MAPPING_FIELD_OFFSET          9
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_4_TO_POOL_MAPPING_FIELD_OFFSET          12
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_5_TO_POOL_MAPPING_FIELD_OFFSET          15
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_6_TO_POOL_MAPPING_FIELD_OFFSET          18
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_7_TO_POOL_MAPPING_FIELD_OFFSET          21
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_POOL_OCCUPIED_BUFFERS_MODE_FIELD_OFFSET         24
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_1_POOL_OCCUPIED_BUFFERS_MODE_FIELD_OFFSET           25
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_2_POOL_OCCUPIED_BUFFERS_MODE_FIELD_OFFSET           26
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_3_POOL_OCCUPIED_BUFFERS_MODE_FIELD_OFFSET           27
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_4_POOL_OCCUPIED_BUFFERS_MODE_FIELD_OFFSET           28
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_5_POOL_OCCUPIED_BUFFERS_MODE_FIELD_OFFSET           29
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_6_POOL_OCCUPIED_BUFFERS_MODE_FIELD_OFFSET           30
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_7_POOL_OCCUPIED_BUFFERS_MODE_FIELD_OFFSET           31


#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_TO_POOL_MAPPING_FIELD_SIZE          3
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_1_TO_POOL_MAPPING_FIELD_SIZE            3
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_2_TO_POOL_MAPPING_FIELD_SIZE            3
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_3_TO_POOL_MAPPING_FIELD_SIZE            3
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_4_TO_POOL_MAPPING_FIELD_SIZE            3
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_5_TO_POOL_MAPPING_FIELD_SIZE            3
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_6_TO_POOL_MAPPING_FIELD_SIZE            3
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_7_TO_POOL_MAPPING_FIELD_SIZE            3
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_POOL_OCCUPIED_BUFFERS_MODE_FIELD_SIZE           1
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_1_POOL_OCCUPIED_BUFFERS_MODE_FIELD_SIZE         1
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_2_POOL_OCCUPIED_BUFFERS_MODE_FIELD_SIZE         1
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_3_POOL_OCCUPIED_BUFFERS_MODE_FIELD_SIZE         1
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_4_POOL_OCCUPIED_BUFFERS_MODE_FIELD_SIZE         1
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_5_POOL_OCCUPIED_BUFFERS_MODE_FIELD_SIZE         1
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_6_POOL_OCCUPIED_BUFFERS_MODE_FIELD_SIZE         1
#define      TXQ_PFCC_TC_TO_POOL_CFG_TC_7_POOL_OCCUPIED_BUFFERS_MODE_FIELD_SIZE         1

/* end of TC_to_pool_CFG*/

/* start of register PFCC_Interrupt_Cause*/

#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_PFCC_INTSUM_FIELD_OFFSET         0
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_ILLEGAL_ADDRESS_ACCESS_FIELD_OFFSET          1
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_ZERO_BUBBLES_INT_FIELD_OFFSET            2
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_POOL_COUNTER_OVERFLOW_FIELD_OFFSET           3
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_POOL_1_COUNTER_OVERFLOW_FIELD_OFFSET         4
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_POOL_2_COUNTER_OVERFLOW_FIELD_OFFSET         5
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_POOL_3_COUNTER_OVERFLOW_FIELD_OFFSET         6
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_SRC_PORT_COUNTER_OVERFLOW_FIELD_OFFSET           7


#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_PFCC_INTSUM_FIELD_SIZE           1
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_ILLEGAL_ADDRESS_ACCESS_FIELD_SIZE            1
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_ZERO_BUBBLES_INT_FIELD_SIZE          1
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_POOL_COUNTER_OVERFLOW_FIELD_SIZE         1
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_POOL_1_COUNTER_OVERFLOW_FIELD_SIZE           1
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_POOL_2_COUNTER_OVERFLOW_FIELD_SIZE           1
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_POOL_3_COUNTER_OVERFLOW_FIELD_SIZE           1
#define      TXQ_PFCC_PFCC_INTERRUPT_CAUSE_SRC_PORT_COUNTER_OVERFLOW_FIELD_SIZE         1

/* end of PFCC_Interrupt_Cause*/


/* start of register PFCC_Interrupt_Mask*/

#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK1_FIELD_OFFSET           1
#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK2_FIELD_OFFSET           2
#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK3_FIELD_OFFSET           3
#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK4_FIELD_OFFSET           4
#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK5_FIELD_OFFSET           5
#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK6_FIELD_OFFSET           6
#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK7_FIELD_OFFSET           7


#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK1_FIELD_SIZE         1
#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK2_FIELD_SIZE         1
#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK3_FIELD_SIZE         1
#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK4_FIELD_SIZE         1
#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK5_FIELD_SIZE         1
#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK6_FIELD_SIZE         1
#define      TXQ_PFCC_PFCC_INTERRUPT_MASK_PFCC_INTERRUPT_CAUSE_MASK7_FIELD_SIZE         1

/* end of PFCC_Interrupt_Mask*/


/* start of register Address_Violation*/

#define      TXQ_PFCC_ADDRESS_VIOLATION_ADDRESS_VIOLATION_FIELD_OFFSET          0


#define      TXQ_PFCC_ADDRESS_VIOLATION_ADDRESS_VIOLATION_FIELD_SIZE            32

/* end of Address_Violation*/


/* start of table entry Global_status_counters*/

#define      TXQ_PFCC_GLOBAL_STATUS_COUNTERS_TC_COUNTER_VAL_FIELD_OFFSET            0


#define      TXQ_PFCC_GLOBAL_STATUS_COUNTERS_TC_COUNTER_VAL_FIELD_SIZE          20

/* end of Global_status_counters*/


/* start of table entry Pool_counter*/

#define      TXQ_PFCC_POOL_COUNTER_POOL_COUNTER_STATUS_FIELD_OFFSET         0


#define      TXQ_PFCC_POOL_COUNTER_POOL_COUNTER_STATUS_FIELD_SIZE           20

/* end of Pool_counter*/


/* start of register PFCC_Cycle_Counter*/

#define      TXQ_PFCC_PFCC_CYCLE_COUNTER_PFCC_CYCLE_COUNTER_STATUS_FIELD_OFFSET         0


#define      TXQ_PFCC_PFCC_CYCLE_COUNTER_PFCC_CYCLE_COUNTER_STATUS_FIELD_SIZE           32

/* end of PFCC_Cycle_Counter*/


/* start of register Aggregation_Request_Gen_SM_State*/

#define      TXQ_PFCC_AGGREGATION_REQUEST_GEN_SM_STATE_AGG_GEN_CURR_STATE_STATUS_FIELD_OFFSET           0


#define      TXQ_PFCC_AGGREGATION_REQUEST_GEN_SM_STATE_AGG_GEN_CURR_STATE_STATUS_FIELD_SIZE         3

/* end of Aggregation_Request_Gen_SM_State*/


/* start of register Source_Port_Index_For_Read*/

#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_REQUESTED_TO_READ_FIELD_OFFSET         0
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_COUNTER_FOR_DEBUG_VALID_FIELD_OFFSET            9
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_1_COUNTER_FOR_DEBUG_VALID_FIELD_OFFSET          10
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_2_COUNTER_FOR_DEBUG_VALID_FIELD_OFFSET          11
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_3_COUNTER_FOR_DEBUG_VALID_FIELD_OFFSET          12
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_4_COUNTER_FOR_DEBUG_VALID_FIELD_OFFSET          13
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_5_COUNTER_FOR_DEBUG_VALID_FIELD_OFFSET          14
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_6_COUNTER_FOR_DEBUG_VALID_FIELD_OFFSET          15
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_7_COUNTER_FOR_DEBUG_VALID_FIELD_OFFSET          16
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_COUNTER_FOR_DEBUG_VALID_FIELD_OFFSET           17


#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_REQUESTED_TO_READ_FIELD_SIZE           9
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_COUNTER_FOR_DEBUG_VALID_FIELD_SIZE          1
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_1_COUNTER_FOR_DEBUG_VALID_FIELD_SIZE            1
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_2_COUNTER_FOR_DEBUG_VALID_FIELD_SIZE            1
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_3_COUNTER_FOR_DEBUG_VALID_FIELD_SIZE            1
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_4_COUNTER_FOR_DEBUG_VALID_FIELD_SIZE            1
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_5_COUNTER_FOR_DEBUG_VALID_FIELD_SIZE            1
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_6_COUNTER_FOR_DEBUG_VALID_FIELD_SIZE            1
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_TC_7_COUNTER_FOR_DEBUG_VALID_FIELD_SIZE            1
#define      TXQ_PFCC_SOURCE_PORT_REQUESTED_FOR_READ_SOURCE_PORT_COUNTER_FOR_DEBUG_VALID_FIELD_SIZE         1

/* end of Source_Port_Index_For_Read*/


/* start of table entry Source_Port_Counter_value*/

#define      TXQ_PFCC_SOURCE_PORT_COUNTER_VALUE_SOURCE_PORT_TC_COUNTER_VALUE_FOR_DEBUG_FIELD_OFFSET         0


#define      TXQ_PFCC_SOURCE_PORT_COUNTER_VALUE_SOURCE_PORT_TC_COUNTER_VALUE_FOR_DEBUG_FIELD_SIZE           20

/* end of Source_Port_Counter_value*/


/* start of register Source_Port_Counter*/

#define      TXQ_PFCC_SOURCE_PORT_COUNTER_SOURCE_PORT_COUNTER_VALUE_FOR_DEBUG_FIELD_OFFSET          0


#define      TXQ_PFCC_SOURCE_PORT_COUNTER_SOURCE_PORT_COUNTER_VALUE_FOR_DEBUG_FIELD_SIZE            20

/* end of Source_Port_Counter*/

/* start of table entry Global_HR_status_counters*/

#define      TXQ_PFCC_GLOBAL_HR_STATUS_COUNTERS_GLOBAL_TC_HR_COUNTER_VALUE_FIELD_OFFSET         0


#define      TXQ_PFCC_GLOBAL_HR_STATUS_COUNTERS_GLOBAL_TC_HR_COUNTER_VALUE_FIELD_SIZE           20

/* end of Global_HR_status_counters*/


/* start of table entry Pool_HR_Counter_Max_Peak*/

#define      TXQ_PFCC_POOL_HR_COUNTER_MAX_PEAK_POOL_HR_COUNTER_MAX_VAL_FIELD_OFFSET         0


#define      TXQ_PFCC_POOL_HR_COUNTER_MAX_PEAK_POOL_HR_COUNTER_MAX_VAL_FIELD_SIZE           20

/* end of Pool_HR_Counter_Max_Peak*/


/* start of table entry Global_TC_HR_Counter_Max_Peak*/

#define      TXQ_PFCC_GLOBAL_TC_HR_COUNTER_MAX_PEAK_GLOBAL_TC_HR_COUNTER_MAX_VAL_FIELD_OFFSET           0


#define      TXQ_PFCC_GLOBAL_TC_HR_COUNTER_MAX_PEAK_GLOBAL_TC_HR_COUNTER_MAX_VAL_FIELD_SIZE         20

/* end of Global_TC_HR_Counter_Max_Peak*/


/* start of register pb_occupancy_status*/

#define      TXQ_PFCC_PB_OCCUPANCY_STATUS_PB_OCCUPANCY_STATUS_FIELD_OFFSET          0


#define      TXQ_PFCC_PB_OCCUPANCY_STATUS_PB_OCCUPANCY_STATUS_FIELD_SIZE            10

/* end of pb_occupancy_status*/


/* start of table entry Pool_HR_counter_statue*/

#define      TXQ_PFCC_POOL_HR_COUNTER_STATUS_POOL_HR_COUNTER_VALUE_FIELD_OFFSET         0


#define      TXQ_PFCC_POOL_HR_COUNTER_STATUS_POOL_HR_COUNTER_VALUE_FIELD_SIZE           20

/* end of Pool_HR_counter_statue*/


/* start of table entry pfcc_CFG*/

#define      TXQ_PFCC_PFCC_CFG_ENTRY_TYPE_FIELD_OFFSET          0
#define      TXQ_PFCC_PFCC_CFG_PORT_FIELD_OFFSET            2
#define      TXQ_PFCC_PFCC_CFG_NUM_OF_BUBBLES_FIELD_OFFSET          3
#define      TXQ_PFCC_PFCC_CFG_TC_FIELD_OFFSET          3
#define      TXQ_PFCC_PFCC_CFG_TC_BIT_VEC_EN_FIELD_OFFSET           11
#define      TXQ_PFCC_PFCC_CFG_PFC_MESSAGE_TRIGGER_FIELD_OFFSET         19


#define      TXQ_PFCC_PFCC_CFG_ENTRY_TYPE_FIELD_SIZE            2
#define      TXQ_PFCC_PFCC_CFG_PORT_FIELD_SIZE          9
#define      TXQ_PFCC_PFCC_CFG_NUM_OF_BUBBLES_FIELD_SIZE            10
#define      TXQ_PFCC_PFCC_CFG_TC_FIELD_SIZE            3
#define      TXQ_PFCC_PFCC_CFG_TC_BIT_VEC_EN_FIELD_SIZE         8
#define      TXQ_PFCC_PFCC_CFG_PFC_MESSAGE_TRIGGER_FIELD_SIZE           1

/* end of pfcc_CFG*/


/* manual - start of table entry Pool_counter_status*/

#define      TXQ_PFCC_COUNTER_STATUS_POOL_VALUE_FIELD_OFFSET         0


#define      TXQ_PFCC_COUNTER_STATUS_POOL_VALUE_FIELD_SIZE           20

/* end of Pool_counter_status*/


#endif
