var modules =
[
    [ "SAI - Entry point specific API definitions.", "group___s_a_i.html", "group___s_a_i" ],
    [ "SAI - ACL specific API definitions", "group___s_a_i_a_c_l.html", "group___s_a_i_a_c_l" ],
    [ "SAI - BFD specific public APIs and data structures", "group___s_a_i_b_f_d.html", "group___s_a_i_b_f_d" ],
    [ "SAI - Bridge specific API definitions", "group___s_a_i_b_r_i_d_g_e.html", "group___s_a_i_b_r_i_d_g_e" ],
    [ "SAI - Buffer specific API definitions", "group___s_a_i_b_u_f_f_e_r.html", "group___s_a_i_b_u_f_f_e_r" ],
    [ "SAI - Counter specific API definitions", "group___s_a_i_c_o_u_n_t_e_r.html", "group___s_a_i_c_o_u_n_t_e_r" ],
    [ "SAI - Debug counter specific API definitions", "group___s_a_i_d_e_b_u_g_c_o_u_n_t_e_r.html", "group___s_a_i_d_e_b_u_g_c_o_u_n_t_e_r" ],
    [ "SAI - DTEL specific API definitions", "group___s_a_i_d_t_e_l.html", "group___s_a_i_d_t_e_l" ],
    [ "SAI - FDB specific API definitions", "group___s_a_i_f_d_b.html", "group___s_a_i_f_d_b" ],
    [ "SAI - Hash specific API definitions.", "group___s_a_i_h_a_s_h.html", "group___s_a_i_h_a_s_h" ],
    [ "SAI - Host Interface specific API definitions", "group___s_a_i_h_o_s_t_i_n_t_f.html", "group___s_a_i_h_o_s_t_i_n_t_f" ],
    [ "SAI - IPMC specific API definitions", "group___s_a_i_i_p_m_c.html", "group___s_a_i_i_p_m_c" ],
    [ "SAI - IPMC group specific API definitions", "group___s_a_i_i_p_m_c_g_r_o_u_p.html", "group___s_a_i_i_p_m_c_g_r_o_u_p" ],
    [ "SAI - Isolation group specific API definitions", "group___s_a_i_i_s_o_l_a_t_i_o_n_g_r_o_u_p.html", "group___s_a_i_i_s_o_l_a_t_i_o_n_g_r_o_u_p" ],
    [ "SAI - L2MC specific API definitions", "group___s_a_i_l2_m_c.html", "group___s_a_i_l2_m_c" ],
    [ "SAI - L2MC group specific API definitions", "group___s_a_i_l2_m_c_g_r_o_u_p.html", "group___s_a_i_l2_m_c_g_r_o_u_p" ],
    [ "SAI - LAG specific API definitions", "group___s_a_i_l_a_g.html", "group___s_a_i_l_a_g" ],
    [ "SAI - MACsec specific API definitions", "group___s_a_i_m_a_c_s_e_c.html", "group___s_a_i_m_a_c_s_e_c" ],
    [ "SAI - Multicast FDB specific API definitions", "group___s_a_i_m_c_f_d_b.html", "group___s_a_i_m_c_f_d_b" ],
    [ "SAI - Mirror specific public APIs and data structures", "group___s_a_i_m_i_r_r_o_r.html", "group___s_a_i_m_i_r_r_o_r" ],
    [ "SAI - MPLS specific API definitions", "group___s_a_i_m_p_l_s.html", "group___s_a_i_m_p_l_s" ],
    [ "SAI - Network Address Translation (NAT) specific API definitions", "group___s_a_i_n_a_t.html", "group___s_a_i_n_a_t" ],
    [ "SAI - Neighbor specific API definitions.", "group___s_a_i_n_e_i_g_h_b_o_r.html", "group___s_a_i_n_e_i_g_h_b_o_r" ],
    [ "SAI - Next hop specific API definitions.", "group___s_a_i_n_e_x_t_h_o_p.html", "group___s_a_i_n_e_x_t_h_o_p" ],
    [ "SAI - Next hop group specific API definitions", "group___s_a_i_n_e_x_t_h_o_p_g_r_o_u_p.html", "group___s_a_i_n_e_x_t_h_o_p_g_r_o_u_p" ],
    [ "SAI - Object API definitions.", "group___s_a_i_o_b_j_e_c_t.html", "group___s_a_i_o_b_j_e_c_t" ],
    [ "SAI - QOS Policer specific API definitions", "group___s_a_i_p_o_l_i_c_e_r.html", "group___s_a_i_p_o_l_i_c_e_r" ],
    [ "SAI - Port specific API definitions", "group___s_a_i_p_o_r_t.html", "group___s_a_i_p_o_r_t" ],
    [ "SAI - QOS Maps specific API definitions.", "group___s_a_i_q_o_s_m_a_p_s.html", "group___s_a_i_q_o_s_m_a_p_s" ],
    [ "SAI - QOS Queue specific API definitions.", "group___s_a_i_q_u_e_u_e.html", "group___s_a_i_q_u_e_u_e" ],
    [ "SAI - Route specific API definitions", "group___s_a_i_r_o_u_t_e.html", "group___s_a_i_r_o_u_t_e" ],
    [ "SAI - Router interface specific API definitions", "group___s_a_i_r_o_u_t_e_r_i_n_t_f.html", "group___s_a_i_r_o_u_t_e_r_i_n_t_f" ],
    [ "SAI - RPF group specific API definitions", "group___s_a_i_r_p_f_g_r_o_u_p.html", "group___s_a_i_r_p_f_g_r_o_u_p" ],
    [ "SAI - Samplepacket specific public APIs and data structures", "group___s_a_i_s_a_m_p_l_e_p_a_c_k_e_t.html", "group___s_a_i_s_a_m_p_l_e_p_a_c_k_e_t" ],
    [ "SAI - QOS scheduler specific API definitions", "group___s_a_i_s_c_h_e_d_u_l_e_r.html", "group___s_a_i_s_c_h_e_d_u_l_e_r" ],
    [ "SAI - QOS scheduler group specific API definitions", "group___s_a_i_s_c_h_e_d_u_l_e_r_g_r_o_u_p.html", "group___s_a_i_s_c_h_e_d_u_l_e_r_g_r_o_u_p" ],
    [ "SAI - Segment Route specific API definitions", "group___s_a_i_s_e_g_m_e_n_t_r_o_u_t_e.html", "group___s_a_i_s_e_g_m_e_n_t_r_o_u_t_e" ],
    [ "SAI - Status codes definitions", "group___s_a_i_s_t_a_t_u_s.html", "group___s_a_i_s_t_a_t_u_s" ],
    [ "SAI - STP specific public APIs and data structures", "group___s_a_i_s_t_p.html", "group___s_a_i_s_t_p" ],
    [ "SAI - Switch specific API definitions", "group___s_a_i_s_w_i_t_c_h.html", "group___s_a_i_s_w_i_t_c_h" ],
    [ "SAI - System Port specific API definitions", "group___s_a_i_s_y_s_t_e_m_p_o_r_t.html", "group___s_a_i_s_y_s_t_e_m_p_o_r_t" ],
    [ "SAI - Telemetry and monitoring specific API definitions", "group___s_a_i_t_a_m.html", "group___s_a_i_t_a_m" ],
    [ "SAI - Next hop specific API definitions", "group___s_a_i_t_u_n_n_e_l.html", "group___s_a_i_t_u_n_n_e_l" ],
    [ "SAI - Types definitions", "group___s_a_i_t_y_p_e_s.html", "group___s_a_i_t_y_p_e_s" ],
    [ "SAI - User Defined Field specific API definitions", "group___s_a_i_u_d_f.html", "group___s_a_i_u_d_f" ],
    [ "SAI - Router specific API definitions", "group___s_a_i_r_o_u_t_e_r.html", "group___s_a_i_r_o_u_t_e_r" ],
    [ "SAI - VLAN specific API definitions", "group___s_a_i_v_l_a_n.html", "group___s_a_i_v_l_a_n" ],
    [ "SAI - QOS WRED specific API definitions", "group___s_a_i_w_r_e_d.html", "group___s_a_i_w_r_e_d" ]
];