{
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 0,    0,   0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0},  0  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 1,    1,   0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0},  1  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 2,    2,   0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0},  2  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 3,    3,   0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0},  3  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 4,    4,   0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0},  4  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 5,    5,   0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0},  5  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 6,    6,   0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0},  6  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 7,    7,   0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0},  7  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 8,    8,   0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0},  8  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 9,    9,   0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0},  9  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 10,   10,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 10  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 11,   11,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 11  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 12,   12,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 12  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 13,   13,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 13  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 14,   14,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 14  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 15,   15,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 15  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 16,   16,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 16  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 17,   17,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 17  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 18,   18,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 18  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 19,   19,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 19  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 20,   20,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 20  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 21,   21,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 21  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 22,   22,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 22  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 23,   23,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 23  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 24,   24,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 24  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 25,   25,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 25  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 26,   26,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 26  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 27,   27,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 27  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 28,   28,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 28  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 29,   29,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 29  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 30,   30,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 30  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 31,   31,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 31  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 32,   32,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 32  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 33,   33,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 33  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 34,   34,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 34  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 35,   35,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 35  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 36,   36,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 36  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 37,   37,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 37  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 38,   38,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 38  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 39,   39,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 39  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 40,   40,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 40  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 41,   41,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 41  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 42,   42,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 42  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 43,   43,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 43  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 44,   44,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 44  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 45,   45,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 45  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 46,   46,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 46  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 47,   47,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 47  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 48,   48,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 48  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 49,   49,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 49  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 50,   50,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 50  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 51,   51,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 51  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 52,   52,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 52  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 53,   53,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 53  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 54,   54,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 54  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 55,   55,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 55  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 56,   56,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 56  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 57,   57,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 57  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 58,   58,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 58  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 59,   59,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 59  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 60,   60,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 60  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 64,   61,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 64  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 65,   62,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 65  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 66,   63,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 66  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 67,   64,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 67  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 68,   65,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 68  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 69,   66,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 69  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 70,   67,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 70  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 71,   68,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 71  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 72,   69,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 72  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 73,   70,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 73  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 74,   71,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 74  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 75,   72,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 75  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 76,   73,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 76  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 77,   74,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 77  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 78,   75,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 78  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 79,   76,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 79  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 80,   77,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 80  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 81,   78,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 81  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 82,   79,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 82  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 83,   80,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 83  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 84,   81,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 84  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 85,   82,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 85  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 86,   83,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 86  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 87,   84,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 87  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 88,   85,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 88  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 89,   86,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 89  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 90,   87,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 90  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 91,   88,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 91  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 92,   89,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 92  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 93,   90,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 93  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 94,   91,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 94  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 95,   92,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 95  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 96,   93,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 96  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 97,   94,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 97  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 98,   95,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 98  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 99,   96,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 99  }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 100,  97,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 100 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 101,  98,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 101 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 102,  99,  0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 102 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 103,  100, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 103 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 104,  101, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 104 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 105,  102, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 105 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 106,  103, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 106 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 107,  104, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 107 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 108,  105, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 108 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 109,  106, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 109 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 110,  107, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 110 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 111,  108, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 111 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 112,  109, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 112 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 113,  110, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 113 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 114,  111, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 114 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 115,  112, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 115 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 116,  113, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 116 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 117,  114, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 117 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 118,  115, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 118 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 119,  116, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 119 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 120,  117, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 120 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 121,  118, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 121 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 122,  119, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 122 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 123,  120, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 123 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 124,  121, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 124 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 125,  122, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 125 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 126,  123, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 126 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 127,  124, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 127 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 128,  125, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 128 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 129,  126, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 129 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 130,  127, 0, PROFILE_INTERFACE_MODE_KR_E, 500, .phyInfo = {0, 0, 0, 0}, 130 }},

    //10G CPU Ports
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 131, 128, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 131 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 132, 135, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 132 }},

    // CPU PORT
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {63,     136,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {133,    137,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {134,    138,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {135,    139,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},

    /* simulation */
    {.profileType = PROFILE_TYPE_SIM_INIFILE_E, .profileValue.sim_inifile = "-i ./iniFiles/falcon_6_4_A0_wm.ini"},
    {.profileType = PROFILE_TYPE_HW_SKU_E, .profileValue.hwTableSizes = &hw_sku_profiles_falcon[2]},

    /* last */
    {.profileType = PROFILE_TYPE_LAST_E, .profileValue.no_param = 0}

};
