// 6.4T 64x25G R1 Port Profile (FALCON64x25G)
{
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 0,  0,   0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0},  0 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 1,  1,   0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0},  1 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 2,  2,   0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0},  2 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 3,  3,   0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0},  3 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 4,  8,   0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0},  4 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 5,  9,   0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0},  5 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 6, 10,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 6 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 7, 11,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 7 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 8, 16,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 8 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 9, 17,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 9 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 10, 18,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 10 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 11, 19,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 11 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 12, 24,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 12 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 13, 25,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 13 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 14, 26,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 14 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 15, 27,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 15 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 16, 32,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 16 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 17, 33,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 17 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 18, 34,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 18 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 19, 35,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 19 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 20, 40,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 20 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 21, 41,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 21 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 22, 42,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 22 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 23, 43,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 23 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 24, 48,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 24 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 25, 49,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 25 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 26, 50,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 26 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 27, 51,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 27 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 28, 56,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 28 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 29, 57,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 29 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 30, 58,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 30 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 31, 59,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 31 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 32, 64,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 32 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 33, 65,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 33 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 34, 66,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 34 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 35, 67,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 35 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 36, 72,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 36 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 37, 73,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 37 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 38, 74,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 38 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 39, 75,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 39 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 40, 80,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 40 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 41, 81,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 41 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 42, 82,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 42 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 43, 83,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 43 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 44, 88,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 44 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 45, 89,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 45 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 46, 90,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 46 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 47, 91,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 47 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 48, 96,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 48 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 49, 97,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 49 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 50, 98,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 50 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 51, 99,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 51 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 52, 104, 0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 52 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 53, 105, 0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 53 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 54, 106, 0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 54 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 55, 107, 0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 55 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 56, 112, 0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 56 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 57, 113, 0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 57 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 58, 114, 0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 58 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 59, 115, 0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 59 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 60, 120, 0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 60 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 64, 121, 0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 64 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 65, 122, 0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 65 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 66, 123, 0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 66 }},

    //10G CPU Ports
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 67, 128, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 67}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 68, 135, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 68}},

    // CPU PORT
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {63,    136,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {69,    137,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {70,    138,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {71,    139,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},

    /* simulation */
    {.profileType = PROFILE_TYPE_SIM_INIFILE_E, .profileValue.sim_inifile = "-i ./iniFiles/falcon_6_4_A0_wm.ini"},
    {.profileType = PROFILE_TYPE_HW_SKU_E, .profileValue.hwTableSizes = &hw_sku_profiles_falcon[1]},

    /* last */
    {.profileType = PROFILE_TYPE_LAST_E, .profileValue.no_param = 0}

};
