/*******************************************************************************
*              (c), Copyright 2018, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,       *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
*/
/**
********************************************************************************
* @file cpssAppPlatformProfileDecl.h
*
* @brief CPSS Application platform - file to declare all profiles to be used in
*        cpssAppPlatform/src/profiles/mainProfiles
* @version   1
********************************************************************************
*/

#ifndef __CPSS_APP_PROFILE_DECL_H
#define __CPSS_APP_PROFILE_DECL_H

#include "cpssAppPlatformProfile.h"

extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC DB_98EX5520_6ZQSFP_48SFP_BOARD_INFO;
extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC DB_98EX5520_6ZQSFP_48SFP_PP_MAP_INFO;
extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC DB_98EX5520_6ZQSFP_48SFP_LED_INFO;
extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC DB_98EX5520_6ZQSFP_48SFP_CASCADE_PROFILE;

extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC DB_98EX5520_6ZQSFP_48SFP_PP_MAP_INFO_1;
extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC DB_98EX5520_6ZQSFP_48SFP_PP_MAP_INFO_0;
extern CPSS_APP_PLATFORM_PP_PROFILE_STC DB_98EX5520_PP_INFO;
extern CPSS_APP_PLATFORM_PP_PROFILE_STC DB_98EX5520_PP_INFO_AP;

extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_PORT_MANAGER_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_DB_98EX5520_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_DB_98EX5520_GEN_EVENT_AP_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_DB_98EX5520_GEN_EVENT_INFO;

/* Falcon */
extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC WM_FALCON_12_8_R0_1_PP_MAP_INFO;
extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC WM_FALCON_12_8_R0_1_BOARD_INFO;
extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC WM_FALCON_6_4_BOARD_INFO;

extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC WM_FALCON_12_8_Belly2Belly_1_BOARD_INFO;

extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC WM_FALCON_12_8_Z2_PP_MAP_INFO;
extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC WM_FALCON_12_8_Z2_BOARD_INFO;

extern CPSS_APP_PLATFORM_PP_PROFILE_STC    WM_FALCON_12_8_Z2_PP_INFO;
extern CPSS_APP_PLATFORM_PP_PROFILE_STC    WM_FALCON_12_8_R0_1_PP_INFO;
extern CPSS_APP_PLATFORM_PP_PROFILE_STC    WM_FALCON_12_8_R0_1_BELLY2BELLY_PP_INFO;
extern CPSS_APP_PLATFORM_PP_PROFILE_STC    WM_FALCON_6_4_PP_INFO;

extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_WM_FALCON_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_WM_FALCON_GEN_EVENT_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_WM_FALCON_6_4_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC LINK_WM_FALCON_6_4_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RX_WM_FALCON_6_4_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_WM_NOPORTS_FALCON_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_WM_FALCON_BELLY2BELLY_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_WM_NOPORTS_FALCON_BELLY2BELLY_INFO;

/* ALDRIN */
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_DB_ALDRIN_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_DB_ALDRIN_GEN_EVENT_INFO;
extern CPSS_APP_PLATFORM_PP_PROFILE_STC DB_ALDRIN_PP_INFO;
/* ALDRIN B2B*/
extern CPSS_APP_PLATFORM_PP_PROFILE_STC B2B_0_ALDRIN_PP_INFO;
extern CPSS_APP_PLATFORM_PP_PROFILE_STC B2B_1_ALDRIN_PP_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_TRAFFIC_B2B_0_ALDRIN_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_TRAFFIC_B2B_1_ALDRIN_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_EVENTS_B2B_ALDRIN_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_ALDRIN_B2B_GEN_EVENT_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_PORT_MANAGER_INFO_ALDRIN_B2B;

/* AC5X */
extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC WM_AC5X_BOARD_INFO;
extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC DB_AC5X_8SFP_BOARD_INFO;
extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC RD_AC5X_32SFP_BOARD_INFO;
extern CPSS_APP_PLATFORM_BOARD_PROFILE_STC WM_AC5X_PP_MAP_INFO;

extern CPSS_APP_PLATFORM_PP_PROFILE_STC    WM_AC5X_PP_INFO;
extern CPSS_APP_PLATFORM_PP_PROFILE_STC    WM_AC5X_INT_CPU_PP_INFO;

extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_PORT_MANAGER_INFO_AC5X;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_WM_AC5X_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_WM_NOPORTS_AC5X_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_DB_AC5X_8SFP_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_RD_AC5X_32SFP_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_DB_AC5X_8SFP_NOPORTS_INFO;
extern CPSS_APP_PLATFORM_RUNTIME_PROFILE_STC RUNTIME_WM_AC5X_GEN_EVENT_INFO;

#endif /* __CPSS_APP_PROFILE_DECL_H */
