/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsAc5xPcs25Units.h
*
* @brief Hawk port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsAc5xPcs25Units_H
#define __mvHwsAc5xPcs25Units_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  PCS25_UNITS_PORT_SPEED_ABILITY_C10GETH_E,
  /*1*/  PCS25_UNITS_PORT_SPEED_ABILITY_C10PASS_TS_E,
  /*2*/  PCS25_UNITS_PORT_SPEED_ABILITY_C40G_E,
  /*3*/  PCS25_UNITS_PORT_SPEED_ABILITY_C100G_E,
  /*4*/  PCS25_UNITS_PORT_SPEED_ABILITY_C25G_E,
  /*5*/  PCS25_UNITS_PORT_CONTROL2_PCS_TYPE_E,
  /*6*/  PCS25_UNITS_PORT_BASER_TEST_ERR_CNT_COUNTER_E,
  /*7*/  PCS25_UNITS_PORT_VL2_1_M2_E,
  /*8*/  PCS25_UNITS_PORT_VENDOR_LAYENCY_RX_PATH_LATENCY_E,
  /*9*/  PCS25_UNITS_PORT_VENDOR_LAYENCY_TX_PATH_LATENCY_E,
  /*10*/  PCS25_UNITS_PORT_BER_HIGH_ORDER_CNT_BER_COUNTER_E,
  /*11*/  PCS25_UNITS_PORT_VENDOR_CORE_REV_REVISION_E,
  /*12*/  PCS25_UNITS_PORT_VENDOR_GB_SHIFT_GB_SHIFT_E,
  /*13*/  PCS25_UNITS_PORT_PKG_ID0_IDENTIFIER_E,
  /*14*/  PCS25_UNITS_PORT_SEED_A0_SEED_E,
  /*15*/  PCS25_UNITS_PORT_SEED_A2_SEED_E,
  /*16*/  PCS25_UNITS_PORT_BASER_TEST_CONTROL_DATA_PATTERN_SEL_E,
  /*17*/  PCS25_UNITS_PORT_BASER_TEST_CONTROL_SELECT_SQUARE_E,
  /*18*/  PCS25_UNITS_PORT_BASER_TEST_CONTROL_RX_TESTPATTERN_E,
  /*19*/  PCS25_UNITS_PORT_BASER_TEST_CONTROL_TX_TESTPATTERN_E,
  /*20*/  PCS25_UNITS_PORT_BASER_TEST_CONTROL_SELECT_RANDOM_E,
  /*21*/  PCS25_UNITS_PORT_VENDOR_SCRATCH_SCRATCH_E,
  /*22*/  PCS25_UNITS_PORT_VENDOR_PCS_MODE_ENA_CLAUSE49_E,
  /*23*/  PCS25_UNITS_PORT_VENDOR_PCS_MODE_DISABLE_MLD_E,
  /*24*/  PCS25_UNITS_PORT_VENDOR_PCS_MODE_HI_BER25_E,
  /*25*/  PCS25_UNITS_PORT_VENDOR_PCS_MODE_ST_ENA_CLAUSE49_E,
  /*26*/  PCS25_UNITS_PORT_VENDOR_PCS_MODE_ST_DISABLE_MLD_E,
  /*27*/  PCS25_UNITS_PORT_MULTILANE_ALIGN_STAT3_LANE0_ALIGNMENT_MARKER_LOCK_E,
  /*28*/  PCS25_UNITS_PORT_MULTILANE_ALIGN_STAT3_LANE1_ALIGNMENT_MARKER_LOCK_E,
  /*29*/  PCS25_UNITS_PORT_MULTILANE_ALIGN_STAT3_LANE2_ALIGNMENT_MARKER_LOCK_E,
  /*30*/  PCS25_UNITS_PORT_MULTILANE_ALIGN_STAT3_LANE3_ALIGNMENT_MARKER_LOCK_E,
  /*31*/  PCS25_UNITS_PORT_BASER_STATUS1_BLOCK_LOCK_E,
  /*32*/  PCS25_UNITS_PORT_BASER_STATUS1_HIGH_BER_E,
  /*33*/  PCS25_UNITS_PORT_BASER_STATUS1_RECEIVE_LINK_E,
  /*34*/  PCS25_UNITS_PORT_BASER_STATUS2_ERRORED_CNT_E,
  /*35*/  PCS25_UNITS_PORT_BASER_STATUS2_BER_COUNTER_E,
  /*36*/  PCS25_UNITS_PORT_BASER_STATUS2_HIGH_BER_E,
  /*37*/  PCS25_UNITS_PORT_BASER_STATUS2_BLOCK_LOCK_E,
  /*38*/  PCS25_UNITS_PORT_SEED_B2_SEED_E,
  /*39*/  PCS25_UNITS_PORT_VL3_0_M0_E,
  /*40*/  PCS25_UNITS_PORT_VL3_0_M1_E,
  /*41*/  PCS25_UNITS_PORT_DEVICES_IN_PKG2_CLAUSE22_E,
  /*42*/  PCS25_UNITS_PORT_DEVICES_IN_PKG2_DEVICE1_E,
  /*43*/  PCS25_UNITS_PORT_DEVICES_IN_PKG2_DEVICE2_E,
  /*44*/  PCS25_UNITS_PORT_PKG_ID1_IDENTIFIER_E,
  /*45*/  PCS25_UNITS_PORT_SEED_A1_SEED_E,
  /*46*/  PCS25_UNITS_PORT_SEED_B1_SEED_E,
  /*47*/  PCS25_UNITS_PORT_ERR_BLK_HIGH_ORDER_CNT_ERRORED_BLOCKS_COUNTER_E,
  /*48*/  PCS25_UNITS_PORT_ERR_BLK_HIGH_ORDER_CNT_HIGH_ORDER_PRESENT_E,
  /*49*/  PCS25_UNITS_PORT_VL_INTVL_ALIGNMENT_MARKERS_INTERVAL_E,
  /*50*/  PCS25_UNITS_PORT_STATUS2_C10GBASE_R_E,
  /*51*/  PCS25_UNITS_PORT_STATUS2_C10GBASE_X_E,
  /*52*/  PCS25_UNITS_PORT_STATUS2_C10GBASE_W_E,
  /*53*/  PCS25_UNITS_PORT_STATUS2_C10GBASE_T_E,
  /*54*/  PCS25_UNITS_PORT_STATUS2_C40GBASE_R_E,
  /*55*/  PCS25_UNITS_PORT_STATUS2_C100GBASE_R_E,
  /*56*/  PCS25_UNITS_PORT_STATUS2_C25GBASE_R_E,
  /*57*/  PCS25_UNITS_PORT_STATUS2_RECEIVE_FAULT_E,
  /*58*/  PCS25_UNITS_PORT_STATUS2_TRANSMIT_FAULT_E,
  /*59*/  PCS25_UNITS_PORT_STATUS2_DEVICE_PRESENT_E,
  /*60*/  PCS25_UNITS_PORT_SEED_A3_SEED_E,
  /*61*/  PCS25_UNITS_PORT_SEED_B3_SEED_E,
  /*62*/  PCS25_UNITS_PORT_VENDOR_TX_LANE_THRESH_TX_FIFO_ALMOST_FULL_THRESHOLD_E,
  /*63*/  PCS25_UNITS_PORT_VL0_1_M2_E,
  /*64*/  PCS25_UNITS_PORT_VL1_0_M0_E,
  /*65*/  PCS25_UNITS_PORT_VL1_0_M1_E,
  /*66*/  PCS25_UNITS_PORT_VL2_0_M0_E,
  /*67*/  PCS25_UNITS_PORT_VL2_0_M1_E,
  /*68*/  PCS25_UNITS_PORT_STATUS1_LOW_POWER_ABILITY_E,
  /*69*/  PCS25_UNITS_PORT_STATUS1_PCS_RECEIVE_LINK_E,
  /*70*/  PCS25_UNITS_PORT_STATUS1_FAULT_E,
  /*71*/  PCS25_UNITS_PORT_STATUS1_RX_LPI_ACTIVE_E,
  /*72*/  PCS25_UNITS_PORT_STATUS1_TX_LPI_ACTIVE_E,
  /*73*/  PCS25_UNITS_PORT_STATUS1_RX_LPI_E,
  /*74*/  PCS25_UNITS_PORT_STATUS1_TX_LPI_E,
  /*75*/  PCS25_UNITS_PORT_DEVICE_ID1_IDENTIFIER1_E,
  /*76*/  PCS25_UNITS_PORT_VL0_0_M0_E,
  /*77*/  PCS25_UNITS_PORT_VL0_0_M1_E,
  /*78*/  PCS25_UNITS_PORT_VL3_1_M2_E,
  /*79*/  PCS25_UNITS_PORT_CONTROL1_PORT_SPEED_SELECTION_E,
  /*80*/  PCS25_UNITS_PORT_CONTROL1_PORT_SPEED_ALWAYS1_E,
  /*81*/  PCS25_UNITS_PORT_CONTROL1_PORT_LOW_POWER_E,
  /*82*/  PCS25_UNITS_PORT_CONTROL1_PORT_SPEED_SELECT_ALWAYS1_E,
  /*83*/  PCS25_UNITS_PORT_CONTROL1_PORT_LOOPBACK_E,
  /*84*/  PCS25_UNITS_PORT_CONTROL1_PORT_RESET_E,
  /*85*/  PCS25_UNITS_PORT_DEVICE_ID0_IDENTIFIER0_E,
  /*86*/  PCS25_UNITS_PORT_DEVICES_IN_PKG1_CLAUSE22_E,
  /*87*/  PCS25_UNITS_PORT_DEVICES_IN_PKG1_PMD_PMA_E,
  /*88*/  PCS25_UNITS_PORT_DEVICES_IN_PKG1_WIS_PRES_E,
  /*89*/  PCS25_UNITS_PORT_DEVICES_IN_PKG1_PCS_PRES_E,
  /*90*/  PCS25_UNITS_PORT_DEVICES_IN_PKG1_PHY_XS_E,
  /*91*/  PCS25_UNITS_PORT_DEVICES_IN_PKG1_DTE_XS_E,
  /*92*/  PCS25_UNITS_PORT_DEVICES_IN_PKG1_TC_PRES_E,
  /*93*/  PCS25_UNITS_PORT_SEED_B0_SEED_E,
  /*94*/  PCS25_UNITS_PORT_MULTILANE_ALIGN_STAT1_LANE_ALIGN_STATUS_E,
  /*95*/  PCS25_UNITS_PORT_VL1_1_M2_E,
    PCS25_UNITS_REGISTER_LAST_E /* should be last */
} MV_HWS_PCS25_UNIT_FIELDS_E;


#ifdef __cplusplus
}
#endif

#endif /* __mvHwsMtiPcs25RegDb_H */

