/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsIronmanMtip10GMacBRUnits.h
*
* @brief IronmanL port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsIronmanMtip10GMacBRUnits_H
#define __mvHwsIronmanMtip10GMacBRUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  IRONMAN_MTIP_MAC_10G_BR_REVISION_CORE_REVISION_E,
  /*1*/  IRONMAN_MTIP_MAC_10G_BR_REVISION_CORE_VERSION_E,
  /*2*/  IRONMAN_MTIP_MAC_10G_BR_REVISION_CUSTOMER_REVISION_E,
  /*3*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_TX_ENA_E,
  /*4*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_RX_ENA_E,
  /*5*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_HD_ENA_E,
  /*6*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_CRC_FWD_E,
  /*7*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_PAUSE_FWD_E,
  /*8*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_PAUSE_IGNORE_E,
  /*9*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_LOOPBACK_EN_E,
  /*10*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_TX_PAD_EN_E,
  /*11*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_SW_RESET_E,
  /*12*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_CNTL_FRAME_ENA_E,
  /*13*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PHY_TXENA_E,
  /*14*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_SEND_IDLE_E,
  /*15*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_PAUSE_MASK_P_E,
  /*16*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_PAUSE_MASK_E_E,
  /*17*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_PFC_MODE_E,
  /*18*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_PAUSE_PFC_COMP_E,
  /*19*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_RX_SFD_ANY_E,
  /*20*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_TX_FLUSH_E,
  /*21*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_TX_LOWP_ENA_E,
  /*22*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_REG_LOWP_RXEMPTY_E,
  /*23*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_FLT_TX_STOP_E,
  /*24*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_TX_FIFO_RESET_E,
  /*25*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_FLT_HDL_DIS_E,
  /*26*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_TX_PAUSE_DIS_E,
  /*27*/  IRONMAN_MTIP_MAC_10G_BR_COMMAND_CONFIG_PMAC_RX_PAUSE_DIS_E,
  /*28*/  IRONMAN_MTIP_MAC_10G_BR_PMAC_ADDR_0_MAC_ADDRESS_0_E,
  /*29*/  IRONMAN_MTIP_MAC_10G_BR_PMAC_ADDR_1_MAC_ADDRESS_1_E,
  /*30*/  IRONMAN_MTIP_MAC_10G_BR_PMAC_FRM_LENGTH_FRM_LENGTH_E,
  /*31*/  IRONMAN_MTIP_MAC_10G_BR_PMAC_FRM_LENGTH_TX_MTU_E,
  /*32*/  IRONMAN_MTIP_MAC_10G_BR_PMAC_TX_FIFO_SECTIONS_TX_SECTION_FULL_E,
  /*33*/  IRONMAN_MTIP_MAC_10G_BR_PMAC_TX_FIFO_SECTIONS_TX_SECTION_EMPTY_E,
  /*34*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_PCH_ENA_E,
  /*35*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_CRC_REVERSE_E,
  /*36*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_TX_FORCE_1S_PTP_E,
  /*37*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_TX_PTP_DIS_E,
  /*38*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_TX_TS_CAP_DIS_E,
  /*39*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_TX_TSID_OVR_E,
  /*40*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_TX_NOTS_PCH_MODE_E,
  /*41*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_TX_TS_PCH_MODE_E,
  /*42*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_RX_KEEP_PCH_E,
  /*43*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_RX_PTP_DIS_E,
  /*44*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_RX_NOPTP_USE_FRC_E,
  /*45*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_RX_CRCERR_USE_FRC_E,
  /*46*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_RX_SUBPORT_CHK_DIS_E,
  /*47*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_RX_CRC_CHK_DIS_E,
  /*48*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_RX_BADCRC_DISCARD_E,
  /*49*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_RX_NOPCH_CRC_DIS_E,
  /*50*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_RX_FWD_IDLE_E,
  /*51*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_RX_FWD_RSVD_E,
  /*52*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_RX_DROP_FE_E,
  /*53*/  IRONMAN_MTIP_MAC_10G_BR_USX_PCH_CONTROL_SUBPORT_E,
  /*54*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_RX_LOC_FAULT_E,
  /*55*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_RX_REM_FAULT_E,
  /*56*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_PHY_LOS_E,
  /*57*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_RX_LOWP_E,
  /*58*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_PMAC_TX_EMPTY_E,
  /*59*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_PMAC_RX_EMPTY_E,
  /*60*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_RX_LINT_FAULT_E,
  /*61*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_TX_IS_IDLE_E,
  /*62*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_TX_MERGE_ISIDLE_E,
  /*63*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_EMAC_TX_EMPTY_E,
  /*64*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_EMAC_RX_EMPTY_E,
  /*65*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_AVB_FIFO_OVR_E,
  /*66*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_PCH_RX_SUBPORT_ERR_E,
  /*67*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_PCH_RX_CRC_ERR_E,
  /*68*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_PCH_RX_UNSUP_E,
  /*69*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_PCH_RX_FRM_DROP_E,
  /*70*/  IRONMAN_MTIP_MAC_10G_BR_STATUS_PCH_RX_SUBPORT_E,
  /*71*/  IRONMAN_MTIP_MAC_10G_BR_TX_IPG_LENGTH_TXIPG_DIC_DISABLE_E,
  /*72*/  IRONMAN_MTIP_MAC_10G_BR_TX_IPG_LENGTH_TXIPG_RESERVED1_E,
  /*73*/  IRONMAN_MTIP_MAC_10G_BR_TX_IPG_LENGTH_TXIPG_RESERVED2_E,
  /*74*/  IRONMAN_MTIP_MAC_10G_BR_TX_IPG_LENGTH_TXIPG_E,
  /*75*/  IRONMAN_MTIP_MAC_10G_BR_TX_IPG_LENGTH_COMPENSATION_HI_E,
  /*76*/  IRONMAN_MTIP_MAC_10G_BR_TX_IPG_LENGTH_COMPENSATION_E,
  /*77*/  IRONMAN_MTIP_MAC_10G_BR_CRC_MODE_DIS_RX_CRC_CHK_E,
  /*78*/  IRONMAN_MTIP_MAC_10G_BR_CRC_MODE_MCRC_INVERT_E,
  /*79*/  IRONMAN_MTIP_MAC_10G_BR_XIF_MODE_XGMII_E,
  /*80*/  IRONMAN_MTIP_MAC_10G_BR_XIF_MODE_PAUSETIMERX8_E,
  /*81*/  IRONMAN_MTIP_MAC_10G_BR_XIF_MODE_ONESTEP_ENA_E,
  /*82*/  IRONMAN_MTIP_MAC_10G_BR_XIF_MODE_EMAC_RX_PAUSE_BYPASS_E,
  /*83*/  IRONMAN_MTIP_MAC_10G_BR_XIF_MODE_PMAC_RX_PAUSE_BYPASS_E,
  /*84*/  IRONMAN_MTIP_MAC_10G_BR_XIF_MODE_TX_MAC_RS_ERR_E,
  /*85*/  IRONMAN_MTIP_MAC_10G_BR_XIF_MODE_TS_BINARY_MODE_E,
  /*86*/  IRONMAN_MTIP_MAC_10G_BR_XIF_MODE_PFC_PULSE_MODE_E,
  /*87*/  IRONMAN_MTIP_MAC_10G_BR_XIF_MODE_TS_SFD_ENA_E,
  /*88*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_TX_PREEMPT_EN_E,
  /*89*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_TX_VERIF_DIS_E,
  /*90*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_TX_ADDFRAGSIZE_E,
  /*91*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_TX_VERIFY_TIME_E,
  /*92*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_TX_PAUSE_PRI_EN_E,
  /*93*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_TX_FRAG_PAUSE_EN_E,
  /*94*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_TX_NON_EMPTY_PREEMPT_EN_E,
  /*95*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_TX_ALLOW_PMAC_IF_NVERIF_E,
  /*96*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_TX_ALLOW_EMAC_IF_NVERIF_E,
  /*97*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_BR_COUNT_CLR_ON_RD_E,
  /*98*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_BR_COUNT_SAT_E,
  /*99*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_RX_STRICT_PREAMBLE_E,
  /*100*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_PMAC_TO_EMAC_STATS_E,
  /*101*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_RX_BR_SMD_DIS_E,
  /*102*/  IRONMAN_MTIP_MAC_10G_BR_BR_CONTROL_RX_BR_STRICT_FRM_ENA_E,
  /*103*/  IRONMAN_MTIP_MAC_10G_BR_BR_STATUS_TX_VERIFY_STATUS_E,
  /*104*/  IRONMAN_MTIP_MAC_10G_BR_BR_STATUS_TX_PREEMPT_STATUS_E,
  /*105*/  IRONMAN_MTIP_MAC_10G_BR_BR_STATUS_ASSY_ERR_LH_E,
  /*106*/  IRONMAN_MTIP_MAC_10G_BR_BR_STATUS_SMD_ERR_LH_E,
  /*107*/  IRONMAN_MTIP_MAC_10G_BR_BR_STATUS_VERIF_SEEN_LH_E,
  /*108*/  IRONMAN_MTIP_MAC_10G_BR_BR_STATUS_RESP_SEEN_LH_E,
  /*109*/  IRONMAN_MTIP_MAC_10G_BR_BR_TX_FRAG_COUNT_BR_TX_FRAG_COUNT_E,
  /*110*/  IRONMAN_MTIP_MAC_10G_BR_BR_RX_FRAG_COUNT_BR_RX_FRAG_COUNT_E,
  /*111*/  IRONMAN_MTIP_MAC_10G_BR_BR_TX_HOLD_COUNT_BR_TX_HOLD_COUNT_E,
  /*112*/  IRONMAN_MTIP_MAC_10G_BR_BR_RX_SMD_ERR_COUNT_BR_RX_SMD_ERR_COUNT_E,
  /*113*/  IRONMAN_MTIP_MAC_10G_BR_BR_RX_ASSY_ERR_COUNT_BR_RX_ASSY_ERR_COUNT_E,
  /*114*/  IRONMAN_MTIP_MAC_10G_BR_BR_RX_ASSY_OK_COUNT_BR_RX_ASSY_OK_COUNT_E,
  /*115*/  IRONMAN_MTIP_MAC_10G_BR_BR_RX_VERIFY_COUNT_GOOD_E,
  /*116*/  IRONMAN_MTIP_MAC_10G_BR_BR_RX_VERIFY_COUNT_BAD_E,
  /*117*/  IRONMAN_MTIP_MAC_10G_BR_BR_RX_RESP_COUNT_GOOD_E,
  /*118*/  IRONMAN_MTIP_MAC_10G_BR_BR_RX_RESP_COUNT_BAD_E,
  /*119*/  IRONMAN_MTIP_MAC_10G_BR_BR_TX_VERIFY_COUNT_VERIFY_E,
  /*120*/  IRONMAN_MTIP_MAC_10G_BR_BR_TX_VERIFY_COUNT_RESP_E,
  /*121*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_TX_ENA_E,
  /*122*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_RX_ENA_E,
  /*123*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_PAUSE_FWD_E,
  /*124*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_PAUSE_IGNORE_E,
  /*125*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_SW_RESET_E,
  /*126*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_CNTL_FRAME_ENA_E,
  /*127*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_PAUSE_MASK_P_E,
  /*128*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_PAUSE_MASK_E_E,
  /*129*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_PFC_MODE_E,
  /*130*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_PAUSE_PFC_COMP_E,
  /*131*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_TX_FLUSH_E,
  /*132*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_TX_FIFO_RESET_E,
  /*133*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_TX_PAUSE_DIS_E,
  /*134*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_COMMAND_CONFIG_EMAC_RX_PAUSE_DIS_E,
  /*135*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_FRM_LENGTH_FRM_LENGTH_E,
  /*136*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_FRM_LENGTH_TX_MTU_E,
  /*137*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_TX_FIFO_SECTIONS_TX_SECTION_FULL_E,
  /*138*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_TX_FIFO_SECTIONS_TX_SECTION_EMPTY_E,
  /*139*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_CL01_PAUSE_QUANTA_CL0_PAUSE_QUANTA_E,
  /*140*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_CL01_QUANTA_THRESH_CL0_QUANTA_THRESH_E,
  /*141*/  IRONMAN_MTIP_MAC_10G_BR_EMAC_RX_PAUSE_STATUS_PAUSESTATUS_E,
  /*142*/  IRONMAN_MTIP_MAC_10G_BR_TSU_CONTROL_TSU_ENA_E,
  /*143*/  IRONMAN_MTIP_MAC_10G_BR_TSU_CONTROL_MODULO_SEL_E,
  /*144*/  IRONMAN_MTIP_MAC_10G_BR_TSU_CONTROL_BLOCK_TIME_E,
    IRONMAN_MTIP_MAC_10G_BR_REGISTER_LAST_E /* should be last */
} MV_HWS_IRONMAN_MTIP_MAC_10G_BR_UNITS;

#ifdef __cplusplus
}
#endif

#endif /* __mvHwsIronmanMtip10GMacBRUnits_H */

