/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsIronmanMtipMacGlobalExtUnits.h
*
* @brief IronmanL port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsIronmanMtipMacGlobalExtUnits_H
#define __mvHwsIronmanMtipMacGlobalExtUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_LAST_VIOLATION_LAST_VIOLATION_E,
  /*1*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_MAC_METAL_FIX_MAC_METAL_FIX_E,
  /*2*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_CONTROL_MAC_ABU_WATCHDOG_E,
  /*3*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_CONTROL_CYC_TO_STRETCH_MAC2APP_E,
  /*4*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_CONTROL_CYC_TO_STRETCH_MAC2REG_E,
  /*5*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_CONTROL_CYC_TO_STRETCH_APP2REG_E,
  /*6*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_CONTROL_XOFF_GEN_ALWAYS_SYNC_E,
  /*7*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_MAC_CLOCK_AND_RESET_CONTROL_CMN_MAC_RESET__E,
  /*8*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_MAC_CLOCK_AND_RESET_CONTROL_CMN_MAC_CLK_EN_E,
  /*9*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_MAC_CLOCK_AND_RESET_CONTROL_CMN_APP_RESET__E,
  /*10*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_MAC_CLOCK_AND_RESET_CONTROL_CMN_APP_CLK_EN_E,
  /*11*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_CLOCK_DIVIDER_CONTROL_CLK_RATIO_E,
  /*12*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_USX_PCH_CONTROL_PACKET_TYPE_PCH_E,
  /*13*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_USX_PCH_CONTROL_PACKET_TYPE_NO_PCH_E,
  /*14*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_USX_PCH_CONTROL_PACKET_TYPE_IDLE_E,
  /*15*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_USX_PCH_CONTROL_PACKET_TYPE_RESERVED_E,
  /*16*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_USX_PCH_CONTROL_PCH_EXTTYPE_IGNORE_E,
  /*17*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_USX_PCH_CONTROL_PCH_EXTTYPE_PTP_E,
  /*18*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_USX_PCH_CONTROL_PCH_EXTTYPE_PTP_BR_E,
  /*19*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_USX_PCH_CONTROL_PCH_EXTTYPE_RESERVED_E,
  /*20*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_USX_PCH_CONTROL_PCH_PREEMPTION_FRAME_TYPE_HI_PRIO_FRAME_E,
  /*21*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_USX_PCH_CONTROL_PCH_PREEMPTION_FRAME_TYPE_VERIFY_RESPOND_FRAME_E,
  /*22*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_USX_PCH_CONTROL_PCH_TYPE_OF_VERIFY_RESPOND_VER_E,
  /*23*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_USX_PCH_CONTROL_PCH_TYPE_OF_VERIFY_RESPOND_RES_E,
  /*24*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_GLOBAL_INTERRUPT_SUMMARY_INT_SUM_E,
  /*25*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_GLOBAL_INT_SUM_E,
  /*26*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P0_INT_SUM_E,
  /*27*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P1_INT_SUM_E,
  /*28*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P2_INT_SUM_E,
  /*29*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P3_INT_SUM_E,
  /*30*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P4_INT_SUM_E,
  /*31*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P5_INT_SUM_E,
  /*32*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P6_INT_SUM_E,
  /*33*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_CAUSE_P7_INT_SUM_E,
  /*34*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_SUMMARY_MASK_GLOBAL_INTERRUPT_SUMMARY_MASK_E,
  /*35*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_CAUSE_GLOBAL_INTERRUPT_CAUSE_INT_SUM_E,
  /*36*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_CAUSE_ILLEGAL_ADDRESS_ACCESS_E,
  /*37*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_CAUSE_ABU_BAD_ADDRESS_ERROR_E,
  /*38*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_CAUSE_ABU_WATCHDOG_ERROR_E,
  /*39*/  IRONMAN_MTIP_MAC_GLOBAL_EXT_GLOBAL_INTERRUPT_MASK_GLOBAL_INTERRUPT_MASK_E,
    IRONMAN_MTIP_MAC_GLOBAL_EXT_REGISTER_LAST_E /* should be last */
} MV_HWS_IRONMAN_MTIP_MAC_GLOBAL_EXT_UNITS;

#ifdef __cplusplus
}
#endif

#endif /* __mvHwsIronmanMtipMacGlobalExtUnits_H */

