/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsIronmanMtip10GMacUnits.h
*
* @brief IronmanL port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsIronmanMtip10GMacUnits_H
#define __mvHwsIronmanMtip10GMacUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  IRONMAN_MTIP_MAC_10G_REVISION_CORE_REVISION_E,
  /*1*/  IRONMAN_MTIP_MAC_10G_REVISION_CORE_VERSION_E,
  /*2*/  IRONMAN_MTIP_MAC_10G_REVISION_CUSTOMER_REVISION_E,
  /*3*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_TX_ENA_E,
  /*4*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_RX_ENA_E,
  /*5*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_HD_ENA_E,
  /*6*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_CRC_FWD_E,
  /*7*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_PAUSE_FWD_E,
  /*8*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_PAUSE_IGNORE_E,
  /*9*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_LOOPBACK_EN_E,
  /*10*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_TX_PAD_EN_E,
  /*11*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_SW_RESET_E,
  /*12*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_CNTL_FRAME_ENA_E,
  /*13*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_PHY_TXENA_E,
  /*14*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_SEND_IDLE_E,
  /*15*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_PFC_MODE_E,
  /*16*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_PAUSE_PFC_COMP_E,
  /*17*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_RX_SFD_ANY_E,
  /*18*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_TX_FLUSH_E,
  /*19*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_TX_LOWP_ENA_E,
  /*20*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_LOWP_RXEMPTY_E,
  /*21*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_FLT_TX_STOP_DIS_E,
  /*22*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_TX_FIFO_RESET_E,
  /*23*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_FLT_HDL_DIS_E,
  /*24*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_TX_PAUSE_DIS_E,
  /*25*/  IRONMAN_MTIP_MAC_10G_COMMAND_CONFIG_RX_PAUSE_DIS_E,
  /*26*/  IRONMAN_MTIP_MAC_10G_MAC_ADDR_0_MAC_ADDRESS_0_E,
  /*27*/  IRONMAN_MTIP_MAC_10G_MAC_ADDR_1_MAC_ADDRESS_1_E,
  /*28*/  IRONMAN_MTIP_MAC_10G_FRM_LENGTH_FRM_LENGTH_E,
  /*29*/  IRONMAN_MTIP_MAC_10G_FRM_LENGTH_TX_MTU_E,
  /*30*/  IRONMAN_MTIP_MAC_10G_TX_FIFO_SECTIONS_TX_SECTION_FULL_E,
  /*31*/  IRONMAN_MTIP_MAC_10G_TX_FIFO_SECTIONS_TX_SECTION_EMPTY_E,
  /*32*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_PCH_ENA_E,
  /*33*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_CRC_REVERSE_E,
  /*34*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_TX_FORCE_1S_PTP_E,
  /*35*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_TX_PTP_DIS_E,
  /*36*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_TX_TS_CAP_DIS_E,
  /*37*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_TX_TSID_OVR_E,
  /*38*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_TX_NOTS_PCH_MODE_E,
  /*39*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_TX_TS_PCH_MODE_E,
  /*40*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_RX_KEEP_PCH_E,
  /*41*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_RX_PTP_DIS_E,
  /*42*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_RX_NOPTP_USE_FRC_E,
  /*43*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_RX_CRCERR_USE_FRC_E,
  /*44*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_RX_SUBPORT_CHK_DIS_E,
  /*45*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_RX_CRC_CHK_DIS_E,
  /*46*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_RX_BADCRC_DISCARD_E,
  /*47*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_RX_NOPCH_CRC_DIS_E,
  /*48*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_RX_FWD_IDLE_E,
  /*49*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_RX_FWD_RSVD_E,
  /*50*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_RX_DROP_FE_E,
  /*51*/  IRONMAN_MTIP_MAC_10G_USX_PCH_CONTROL_SUBPORT_E,
  /*52*/  IRONMAN_MTIP_MAC_10G_STATUS_RX_LOC_FAULT_E,
  /*53*/  IRONMAN_MTIP_MAC_10G_STATUS_RX_REM_FAULT_E,
  /*54*/  IRONMAN_MTIP_MAC_10G_STATUS_PHY_LOS_E,
  /*55*/  IRONMAN_MTIP_MAC_10G_STATUS_RX_LOWP_E,
  /*56*/  IRONMAN_MTIP_MAC_10G_STATUS_TX_EMPTY_E,
  /*57*/  IRONMAN_MTIP_MAC_10G_STATUS_RX_EMPTY_E,
  /*58*/  IRONMAN_MTIP_MAC_10G_STATUS_RX_LINT_FAULT_E,
  /*59*/  IRONMAN_MTIP_MAC_10G_STATUS_TX_IS_IDLE_E,
  /*60*/  IRONMAN_MTIP_MAC_10G_STATUS_PCH_RX_SUBPORT_ERR_E,
  /*61*/  IRONMAN_MTIP_MAC_10G_STATUS_PCH_RX_CRC_ERR_E,
  /*62*/  IRONMAN_MTIP_MAC_10G_STATUS_PCH_RX_UNSUP_E,
  /*63*/  IRONMAN_MTIP_MAC_10G_STATUS_PCH_RX_FRM_DROP_E,
  /*64*/  IRONMAN_MTIP_MAC_10G_STATUS_PCH_RX_SUBPORT_E,
  /*65*/  IRONMAN_MTIP_MAC_10G_TX_IPG_LENGTH_TXIPG_DIC_DISABLE_E,
  /*66*/  IRONMAN_MTIP_MAC_10G_TX_IPG_LENGTH_TXIPG_RESERVED1_E,
  /*67*/  IRONMAN_MTIP_MAC_10G_TX_IPG_LENGTH_TXIPG_RESERVED2_E,
  /*68*/  IRONMAN_MTIP_MAC_10G_TX_IPG_LENGTH_TXIPG_E,
  /*69*/  IRONMAN_MTIP_MAC_10G_TX_IPG_LENGTH_TXIPG_RESERVED6_E,
  /*70*/  IRONMAN_MTIP_MAC_10G_TX_IPG_LENGTH_COMPENSATION_HI_E,
  /*71*/  IRONMAN_MTIP_MAC_10G_TX_IPG_LENGTH_COMPENSATION_E,
  /*72*/  IRONMAN_MTIP_MAC_10G_CRC_MODE_DIS_RX_CRC_CHK_E,
  /*73*/  IRONMAN_MTIP_MAC_10G_CL01_PAUSE_QUANTA_CL0_PAUSE_QUANTA_E,
  /*74*/  IRONMAN_MTIP_MAC_10G_CL01_QUANTA_THRESH_CL0_QUANTA_THRESH_E,
  /*75*/  IRONMAN_MTIP_MAC_10G_RX_PAUSE_STATUS_PAUSESTATUS_E,
  /*76*/  IRONMAN_MTIP_MAC_10G_CF_GEN_STATUS_CF_FRM_SENT_E,
  /*77*/  IRONMAN_MTIP_MAC_10G_XIF_MODE_XGMII_E,
  /*78*/  IRONMAN_MTIP_MAC_10G_XIF_MODE_PAUSETIMERX8_E,
  /*79*/  IRONMAN_MTIP_MAC_10G_XIF_MODE_ONESTEP_ENA_E,
  /*80*/  IRONMAN_MTIP_MAC_10G_XIF_MODE_RX_PAUSE_BYPASS_E,
  /*81*/  IRONMAN_MTIP_MAC_10G_XIF_MODE_TX_MAC_RS_ERR_E,
  /*82*/  IRONMAN_MTIP_MAC_10G_XIF_MODE_TS_BINARY_MODE_E,
  /*83*/  IRONMAN_MTIP_MAC_10G_XIF_MODE_PFC_PULSE_MODE_E,
  /*84*/  IRONMAN_MTIP_MAC_10G_XIF_MODE_PFC_LP_MODE_E,
  /*85*/  IRONMAN_MTIP_MAC_10G_XIF_MODE_TS_SFD_ENA_E,
  /*86*/  IRONMAN_MTIP_MAC_10G_TSU_CONTROL_TSU_ENA_E,
  /*87*/  IRONMAN_MTIP_MAC_10G_TSU_CONTROL_MODULO_SEL_E,
  /*88*/  IRONMAN_MTIP_MAC_10G_TSU_CONTROL_BLOCK_TIME_E,
    IRONMAN_MTIP_MAC_10G_REGISTER_LAST_E /* should be last */
} MV_HWS_IRONMAN_MTIP_MAC_10G_UNITS;

#ifdef __cplusplus
}
#endif

#endif /* __mvHwsIronmanMtip10GMacUnits_H */

