/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsIronmanMtip10GPcsBaseRPcsUnits.h
*
* @brief IronmanL port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsIronmanMtip10GPcsBaseRPcsUnits_H
#define __mvHwsIronmanMtip10GPcsBaseRPcsUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  IRONMAN_BASE_R_PCS_DEVICE_ID0_IDENTIFIER_E,
  /*1*/  IRONMAN_BASE_R_PCS_PKG_ID0_IDENTIFIER_E,
  /*2*/  IRONMAN_BASE_R_PCS_BASER_TEST_ERR_CNT_COUNTER_E,
  /*3*/  IRONMAN_BASE_R_PCS_VENDORMX_CORE_REV_REVISION_E,
  /*4*/  IRONMAN_BASE_R_PCS_STATUS2_C10GBASE_R_E,
  /*5*/  IRONMAN_BASE_R_PCS_STATUS2_C10GBASE_X_E,
  /*6*/  IRONMAN_BASE_R_PCS_STATUS2_C10GBASE_W_E,
  /*7*/  IRONMAN_BASE_R_PCS_STATUS2_C10GBASE_T_E,
  /*8*/  IRONMAN_BASE_R_PCS_STATUS2_C40GBASE_R_E,
  /*9*/  IRONMAN_BASE_R_PCS_STATUS2_C100GBASE_R_E,
  /*10*/  IRONMAN_BASE_R_PCS_STATUS2_C25GBASE_R_E,
  /*11*/  IRONMAN_BASE_R_PCS_STATUS2_C50GBASE_R_E,
  /*12*/  IRONMAN_BASE_R_PCS_STATUS2_RECEIVE_FAULT_E,
  /*13*/  IRONMAN_BASE_R_PCS_STATUS2_TRANSMIT_FAULT_E,
  /*14*/  IRONMAN_BASE_R_PCS_STATUS2_DEVICE_PRESENT_E,
  /*15*/  IRONMAN_BASE_R_PCS_SEED_B2_SEED_E,
  /*16*/  IRONMAN_BASE_R_PCS_VENDORMX_TXLANE_THRESH_THRESHOLD_E,
  /*17*/  IRONMAN_BASE_R_PCS_SPEED_ABILITY_C10GETH_E,
  /*18*/  IRONMAN_BASE_R_PCS_SPEED_ABILITY_C10PASS_TS_E,
  /*19*/  IRONMAN_BASE_R_PCS_SPEED_ABILITY_C40G_E,
  /*20*/  IRONMAN_BASE_R_PCS_SPEED_ABILITY_C100G_E,
  /*21*/  IRONMAN_BASE_R_PCS_SPEED_ABILITY_C25G_E,
  /*22*/  IRONMAN_BASE_R_PCS_SPEED_ABILITY_C50G_E,
  /*23*/  IRONMAN_BASE_R_PCS_WAKE_ERR_COUNTER_COUNTER_E,
  /*24*/  IRONMAN_BASE_R_PCS_SEED_B0_SEED_E,
  /*25*/  IRONMAN_BASE_R_PCS_DEVICE_ID1_IDENTIFIER_E,
  /*26*/  IRONMAN_BASE_R_PCS_BASER_STATUS1_BLOCK_LOCK_E,
  /*27*/  IRONMAN_BASE_R_PCS_BASER_STATUS1_HIGH_BER_E,
  /*28*/  IRONMAN_BASE_R_PCS_BASER_STATUS1_RECEIVE_LINK_E,
  /*29*/  IRONMAN_BASE_R_PCS_SEED_A3_SEED_E,
  /*30*/  IRONMAN_BASE_R_PCS_SEED_B3_SEED_E,
  /*31*/  IRONMAN_BASE_R_PCS_BER_HIGH_ORDER_CNT_BER_COUNTER_E,
  /*32*/  IRONMAN_BASE_R_PCS_CONTROL1_SPEED_SELECTION_E,
  /*33*/  IRONMAN_BASE_R_PCS_CONTROL1_SPEED_ALWAYS1_E,
  /*34*/  IRONMAN_BASE_R_PCS_CONTROL1_LOW_POWER_E,
  /*35*/  IRONMAN_BASE_R_PCS_CONTROL1_SPEED_SELECT_ALWAYS1_E,
  /*36*/  IRONMAN_BASE_R_PCS_CONTROL1_LOOPBACK_E,
  /*37*/  IRONMAN_BASE_R_PCS_CONTROL1_RESET_E,
  /*38*/  IRONMAN_BASE_R_PCS_DEVICES_IN_PKG1_CLAUSE22_E,
  /*39*/  IRONMAN_BASE_R_PCS_DEVICES_IN_PKG1_PMD_PMA_E,
  /*40*/  IRONMAN_BASE_R_PCS_DEVICES_IN_PKG1_WIS_PRES_E,
  /*41*/  IRONMAN_BASE_R_PCS_DEVICES_IN_PKG1_PCS_PRES_E,
  /*42*/  IRONMAN_BASE_R_PCS_DEVICES_IN_PKG1_PHY_XS_E,
  /*43*/  IRONMAN_BASE_R_PCS_DEVICES_IN_PKG1_DTE_XS_E,
  /*44*/  IRONMAN_BASE_R_PCS_DEVICES_IN_PKG1_TC_PRES_E,
  /*45*/  IRONMAN_BASE_R_PCS_BASER_TEST_CONTROL_DATA_PATTERN_SEL_E,
  /*46*/  IRONMAN_BASE_R_PCS_BASER_TEST_CONTROL_SELECT_SQUARE_E,
  /*47*/  IRONMAN_BASE_R_PCS_BASER_TEST_CONTROL_RX_TESTPATTERN_E,
  /*48*/  IRONMAN_BASE_R_PCS_BASER_TEST_CONTROL_TX_TESTPATTERN_E,
  /*49*/  IRONMAN_BASE_R_PCS_BASER_TEST_CONTROL_SELECT_RANDOM_E,
  /*50*/  IRONMAN_BASE_R_PCS_DEVICES_IN_PKG2_CLAUSE22_E,
  /*51*/  IRONMAN_BASE_R_PCS_DEVICES_IN_PKG2_DEVICE1_E,
  /*52*/  IRONMAN_BASE_R_PCS_DEVICES_IN_PKG2_DEVICE2_E,
  /*53*/  IRONMAN_BASE_R_PCS_EEE_CTRL_CAPABILITY_LPI_FW_E,
  /*54*/  IRONMAN_BASE_R_PCS_EEE_CTRL_CAPABILITY_EEE_10GBASE_KR_E,
  /*55*/  IRONMAN_BASE_R_PCS_EEE_CTRL_CAPABILITY_EEE_40GBASE_RAWAKE_E,
  /*56*/  IRONMAN_BASE_R_PCS_EEE_CTRL_CAPABILITY_EEE_40GBASE_RSLEEP_E,
  /*57*/  IRONMAN_BASE_R_PCS_EEE_CTRL_CAPABILITY_EEE_25GBASE_RAWAKE_E,
  /*58*/  IRONMAN_BASE_R_PCS_EEE_CTRL_CAPABILITY_EEE_25GBASE_RSLEEP_E,
  /*59*/  IRONMAN_BASE_R_PCS_EEE_CTRL_CAPABILITY_EEE_100GBASE_RAWAKE_E,
  /*60*/  IRONMAN_BASE_R_PCS_EEE_CTRL_CAPABILITY_EEE_50GBASE_RAWAKE_E,
  /*61*/  IRONMAN_BASE_R_PCS_BASER_STATUS2_ERRORED_CNT_E,
  /*62*/  IRONMAN_BASE_R_PCS_BASER_STATUS2_BER_COUNTER_E,
  /*63*/  IRONMAN_BASE_R_PCS_BASER_STATUS2_HIGH_BER_E,
  /*64*/  IRONMAN_BASE_R_PCS_BASER_STATUS2_BLOCK_LOCK_E,
  /*65*/  IRONMAN_BASE_R_PCS_SEED_A0_SEED_E,
  /*66*/  IRONMAN_BASE_R_PCS_CONTROL2_PCS_TYPE_E,
  /*67*/  IRONMAN_BASE_R_PCS_PKG_ID1_IDENTIFIER_E,
  /*68*/  IRONMAN_BASE_R_PCS_SEED_A1_SEED_E,
  /*69*/  IRONMAN_BASE_R_PCS_SEED_A2_SEED_E,
  /*70*/  IRONMAN_BASE_R_PCS_VENDORMX_SCRATCH_SCRATCH_E,
  /*71*/  IRONMAN_BASE_R_PCS_VENDORMX_PCS_MODE_ENA_CLAUSE49_E,
  /*72*/  IRONMAN_BASE_R_PCS_VENDORMX_PCS_MODE_DISABLE_MLD_E,
  /*73*/  IRONMAN_BASE_R_PCS_VENDORMX_PCS_MODE_HI_BER25_E,
  /*74*/  IRONMAN_BASE_R_PCS_VENDORMX_PCS_MODE_HI_BER5_E,
  /*75*/  IRONMAN_BASE_R_PCS_VENDORMX_PCS_MODE_ST_ENA_CLAUSE49_E,
  /*76*/  IRONMAN_BASE_R_PCS_VENDORMX_PCS_MODE_ST_DISABLE_MLD_E,
  /*77*/  IRONMAN_BASE_R_PCS_VENDORMX_PCS_MODE_ST_HIBER25_E,
  /*78*/  IRONMAN_BASE_R_PCS_VENDORMX_PCS_MODE_ST_HIBER5_E,
  /*79*/  IRONMAN_BASE_R_PCS_STATUS1_LOW_POWER_ABILITY_E,
  /*80*/  IRONMAN_BASE_R_PCS_STATUS1_PCS_RECEIVE_LINK_E,
  /*81*/  IRONMAN_BASE_R_PCS_STATUS1_FAULT_E,
  /*82*/  IRONMAN_BASE_R_PCS_STATUS1_RX_LPI_ACTIVE_E,
  /*83*/  IRONMAN_BASE_R_PCS_STATUS1_TX_LPI_ACTIVE_E,
  /*84*/  IRONMAN_BASE_R_PCS_STATUS1_RX_LPI_E,
  /*85*/  IRONMAN_BASE_R_PCS_STATUS1_TX_LPI_E,
  /*86*/  IRONMAN_BASE_R_PCS_SEED_B1_SEED_E,
  /*87*/  IRONMAN_BASE_R_PCS_ERR_BLK_HIGH_ORDER_CNT_ERRORED_BLOCKS_COUNTER_E,
  /*88*/  IRONMAN_BASE_R_PCS_ERR_BLK_HIGH_ORDER_CNT_HIGH_ORDER_PRESENT_E,
  /*89*/  IRONMAN_BASE_R_PCS_MULTILANE_ALIGN_STAT1_BLOCK_LOCK_L_E,
    IRONMAN_BASE_R_PCS_REGISTER_LAST_E /* should be last */
} MV_HWS_IRONMAN_BASE_R_PCS_UNITS_E;

#ifdef __cplusplus
}
#endif

#endif /* __mvHwsIronmanMtip10GPcsBaseRPcsUnits_H */

