/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,     *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
*
* prvCpssIronmanTxqPdsRegFile.h
*
*Automaticly generated from :
*
* DESCRIPTION:
*      Describe TXQ PDS registers (Automaticly generated from CIDER)
*
* DEPENDENCIES:
*       None.
*
* FILE REVISION NUMBER:
*       $Revision: 1 $
*
*******************************************************************************/
#ifndef _TXQ_IRONMAN__PDS_REGFILE_H_
#define _TXQ_IRONMAN__PDS_REGFILE_H_

/* start of register Max_PDS_size_limit_for_pdx*/

#define      TXQ_IRONMAN_PDS_MAX_PDS_SIZE_LIMIT_FOR_PDX_MAX_PDS_SIZE_LIMIT_FOR_PDX_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDS_MAX_PDS_SIZE_LIMIT_FOR_PDX_MAX_PDS_SIZE_LIMIT_FOR_PDX_FIELD_SIZE           15

/* end of Max_PDS_size_limit_for_pdx*/


/* start of register PDS_Metal_Fix*/

#define      TXQ_IRONMAN_PDS_PDS_METAL_FIX_PDS_METAL_FIX_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDS_PDS_METAL_FIX_PDS_METAL_FIX_FIELD_SIZE         32

/* end of PDS_Metal_Fix*/


/* start of register Queue_Length_Adjust_Profile*/

#define      TXQ_IRONMAN_PDS_QUEUE_LENGTH_ADJUST_PROFILE_QUEUE_LENGTH_ADJUST_PROFILE_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDS_QUEUE_LENGTH_ADJUST_PROFILE_QUEUE_LENGTH_ADJUST_PROFILE_FIELD_SIZE         4

/* end of Queue_Length_Adjust_Profile*/


/* start of register L2_CutThrough_Byte_Count_Enqueue*/

#define      TXQ_IRONMAN_PDS_L2_CUTTHROUGH_BYTE_COUNT_ENQUEUE_L2CT_BYTE_COUNT_FIELD_OFFSET          0


#define      TXQ_IRONMAN_PDS_L2_CUTTHROUGH_BYTE_COUNT_ENQUEUE_L2CT_BYTE_COUNT_FIELD_SIZE            14

/* end of L2_CutThrough_Byte_Count_Enqueue*/


/* start of register PTP_Size_Adjust*/

#define      TXQ_IRONMAN_PDS_PTP_SIZE_ADJUST_PTP_SIZE_ADJUST_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDS_PTP_SIZE_ADJUST_PTP_SIZE_ADJUST_FIELD_SIZE         14

/* end of PTP_Size_Adjust*/


/* start of register queue_counter_select*/

#define      TXQ_IRONMAN_PDS_QUEUE_COUNTER_SELECT_QUEUE_COUNTER_SELECT_0_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDS_QUEUE_COUNTER_SELECT_QUEUE_COUNTER_SELECT_0_FIELD_SIZE         9

/* end of queue_counter_select*/


/* start of register PDS_Interrupt_Debug_Cause*/

#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_CAUSE_PDS_DEBUG_INTSUM_FIELD_OFFSET            0
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_CAUSE_TOTAL_PDS_CNTR_OVRRUN_INT_FIELD_OFFSET           7
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_CAUSE_PDS_FULL_INT_FIELD_OFFSET            9
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_CAUSE_LENGTH_ADJUST_CONSTANT_BIGGER_THAN_THE_PACKETS_BYTE_COUNT_INT_FIELD_OFFSET           13
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_CAUSE_DESC_ILLEGAL_QUEUE_NUMBER_INT_FIELD_OFFSET           14
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_CAUSE_QUEUE_READ_RATE_EXCEEDED_INT_FIELD_OFFSET            21


#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_CAUSE_PDS_DEBUG_INTSUM_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_CAUSE_TOTAL_PDS_CNTR_OVRRUN_INT_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_CAUSE_PDS_FULL_INT_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_CAUSE_LENGTH_ADJUST_CONSTANT_BIGGER_THAN_THE_PACKETS_BYTE_COUNT_INT_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_CAUSE_DESC_ILLEGAL_QUEUE_NUMBER_INT_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_CAUSE_QUEUE_READ_RATE_EXCEEDED_INT_FIELD_SIZE          1

/* end of PDS_Interrupt_Debug_Cause*/


/* start of register PDS_Interrupt_Debug_Mask*/

#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_0_FIELD_OFFSET         1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_1_FIELD_OFFSET         2
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_2_FIELD_OFFSET         3
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_3_FIELD_OFFSET         4
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_4_FIELD_OFFSET         5
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_5_FIELD_OFFSET         6
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_6_FIELD_OFFSET         7
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_7_FIELD_OFFSET         8
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_8_FIELD_OFFSET         9
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_9_FIELD_OFFSET         10
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_10_FIELD_OFFSET            11
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_11_FIELD_OFFSET            12
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_12_FIELD_OFFSET            13
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_13_FIELD_OFFSET            14
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_14_FIELD_OFFSET            15
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_15_FIELD_OFFSET            16
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_16_FIELD_OFFSET            17
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_17_FIELD_OFFSET            18
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_18_FIELD_OFFSET            19
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_19_FIELD_OFFSET            20
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_20_FIELD_OFFSET            21


#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_0_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_1_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_2_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_3_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_4_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_5_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_6_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_7_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_8_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_9_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_10_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_11_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_12_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_13_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_14_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_15_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_16_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_17_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_18_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_19_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_DEBUG_MASK_PDS_INTERRUPT_DEBUG_CAUSE_MASK_20_FIELD_SIZE          1

/* end of PDS_Interrupt_Debug_Mask*/


/* start of register PDS_Last_Address_Violation*/

#define      TXQ_IRONMAN_PDS_PDS_LAST_ADDRESS_VIOLATION_LAST_ADDRESS_VIOLATION_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDS_PDS_LAST_ADDRESS_VIOLATION_LAST_ADDRESS_VIOLATION_FIELD_SIZE           32

/* end of PDS_Last_Address_Violation*/


/* start of register PDS_Interrupt_Summary_Mask*/

#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_SUMMARY_MASK_PDS_INTERRUPT_SUMMARY_MASK_1_FIELD_OFFSET           1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_SUMMARY_MASK_PDS_INTERRUPT_SUMMARY_MASK_2_FIELD_OFFSET           2


#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_SUMMARY_MASK_PDS_INTERRUPT_SUMMARY_MASK_1_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_SUMMARY_MASK_PDS_INTERRUPT_SUMMARY_MASK_2_FIELD_SIZE         1

/* end of PDS_Interrupt_Summary_Mask*/


/* start of register PDS_Interrupt_Summary_Cause*/

#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_SUMMARY_CAUSE_PDS_INTSUM_FIELD_OFFSET            0
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_SUMMARY_CAUSE_PDS_FUNCTIONAL_INT_SUM_FIELD_OFFSET            1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_SUMMARY_CAUSE_PDS_DEBUG_INT_SUM_FIELD_OFFSET         2


#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_SUMMARY_CAUSE_PDS_INTSUM_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_SUMMARY_CAUSE_PDS_FUNCTIONAL_INT_SUM_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_SUMMARY_CAUSE_PDS_DEBUG_INT_SUM_FIELD_SIZE           1

/* end of PDS_Interrupt_Summary_Cause*/


/* start of register PDS_Interrupt_Functional_Mask*/

#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_MASK_PDS_INTERRUPT_FUNCTIONAL_CAUSE_MASK_0_FIELD_OFFSET           1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_MASK_PDS_INTERRUPT_FUNCTIONAL_CAUSE_MASK_1_FIELD_OFFSET           2
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_MASK_PDS_INTERRUPT_FUNCTIONAL_CAUSE_MASK_2_FIELD_OFFSET           3
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_MASK_PDS_INTERRUPT_FUNCTIONAL_CAUSE_MASK_3_FIELD_OFFSET           4
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_MASK_PDS_INTERRUPT_FUNCTIONAL_CAUSE_MASK_4_FIELD_OFFSET           5


#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_MASK_PDS_INTERRUPT_FUNCTIONAL_CAUSE_MASK_0_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_MASK_PDS_INTERRUPT_FUNCTIONAL_CAUSE_MASK_1_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_MASK_PDS_INTERRUPT_FUNCTIONAL_CAUSE_MASK_2_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_MASK_PDS_INTERRUPT_FUNCTIONAL_CAUSE_MASK_3_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_MASK_PDS_INTERRUPT_FUNCTIONAL_CAUSE_MASK_4_FIELD_SIZE         1

/* end of PDS_Interrupt_Functional_Mask*/


/* start of register PDS_Interrupt_Functional_Cause*/

#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_CAUSE_PDS_FUNCTIONAL_INTSUM_FIELD_OFFSET          0
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_CAUSE_PDS_BAD_ADDRESS_INT_FIELD_OFFSET            1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_CAUSE_OVERLAP_INT_FIELD_OFFSET            2
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_CAUSE_PDS_MEM_DOUBLE_ERROR_INT_FIELD_OFFSET           5


#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_CAUSE_PDS_FUNCTIONAL_INTSUM_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_CAUSE_PDS_BAD_ADDRESS_INT_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_CAUSE_OVERLAP_INT_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_INTERRUPT_FUNCTIONAL_CAUSE_PDS_MEM_DOUBLE_ERROR_INT_FIELD_SIZE         1

/* end of PDS_Interrupt_Functional_Cause*/


/* start of register Total_PDS_Counter*/

#define      TXQ_IRONMAN_PDS_TOTAL_PDS_COUNTER_TOTAL_PDS_COUNTER_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDS_TOTAL_PDS_COUNTER_TOTAL_PDS_COUNTER_FIELD_SIZE         15

/* end of Total_PDS_Counter*/


/* start of register Idle_Register*/

#define      TXQ_IRONMAN_PDS_IDLE_REGISTER_PDS_IS_EMPTY_FIELD_OFFSET            0


#define      TXQ_IRONMAN_PDS_IDLE_REGISTER_PDS_IS_EMPTY_FIELD_SIZE          1

/* end of Idle_Register*/


/* start of register Total_PDS_Count_Max_Peak*/

#define      TXQ_IRONMAN_PDS_TOTAL_PDS_COUNT_MAX_PEAK_TOTAL_PDS_COUNT_MAX_PEAK_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDS_TOTAL_PDS_COUNT_MAX_PEAK_TOTAL_PDS_COUNT_MAX_PEAK_FIELD_SIZE           15

/* end of Total_PDS_Count_Max_Peak*/


/* start of register Active_Queue_Counter*/

#define      TXQ_IRONMAN_PDS_ACTIVE_QUEUE_COUNTER_ACTIVE_QUEUE_COUNTER_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDS_ACTIVE_QUEUE_COUNTER_ACTIVE_QUEUE_COUNTER_FIELD_SIZE           9

/* end of Active_Queue_Counter*/


/* start of register Active_Queue_Count_Max_Peak*/

#define      TXQ_IRONMAN_PDS_ACTIVE_QUEUE_COUNT_MAX_PEAK_ACTIVE_QUEUE_COUNT_MAX_PEAK_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDS_ACTIVE_QUEUE_COUNT_MAX_PEAK_ACTIVE_QUEUE_COUNT_MAX_PEAK_FIELD_SIZE         9

/* end of Active_Queue_Count_Max_Peak*/


/* start of register Free_PID_FIFO_Max_Peak*/

#define      TXQ_IRONMAN_PDS_FREE_PID_FIFO_MAX_PEAK_FREE_PID_FIFO_MAX_PEAK_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDS_FREE_PID_FIFO_MAX_PEAK_FREE_PID_FIFO_MAX_PEAK_FIELD_SIZE           15

/* end of Free_PID_FIFO_Max_Peak*/


/* start of register Free_PID_FIFO_Min_Peak*/

#define      TXQ_IRONMAN_PDS_FREE_PID_FIFO_MIN_PEAK_FREE_PID_FIFO_MIN_PEAK_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDS_FREE_PID_FIFO_MIN_PEAK_FREE_PID_FIFO_MIN_PEAK_FIELD_SIZE           15

/* end of Free_PID_FIFO_Min_Peak*/


/* start of register Profile_Dequeue_Length_Adjust*/

#define      TXQ_IRONMAN_PDS_PROFILE_DEQUEUE_LENGTH_ADJUST_LENGTH_ADJUST_ENABLE_PROFILE_FIELD_OFFSET          0
#define      TXQ_IRONMAN_PDS_PROFILE_DEQUEUE_LENGTH_ADJUST_LENGTH_ADJUST_SUB_PROFILE_FIELD_OFFSET          1
#define      TXQ_IRONMAN_PDS_PROFILE_DEQUEUE_LENGTH_ADJUST_LENGTH_ADJUST_CONSTANT_BYTE_COUNT_PROFILE_FIELD_OFFSET           2
#define      TXQ_IRONMAN_PDS_PROFILE_DEQUEUE_LENGTH_ADJUST_PTP_LENGTH_ADJUST_ENABLE_PROFILE_FIELD_OFFSET          10


#define      TXQ_IRONMAN_PDS_PROFILE_DEQUEUE_LENGTH_ADJUST_LENGTH_ADJUST_ENABLE_PROFILE_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PROFILE_DEQUEUE_LENGTH_ADJUST_LENGTH_ADJUST_SUB_PROFILE_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PROFILE_DEQUEUE_LENGTH_ADJUST_LENGTH_ADJUST_CONSTANT_BYTE_COUNT_PROFILE_FIELD_SIZE         8
#define      TXQ_IRONMAN_PDS_PROFILE_DEQUEUE_LENGTH_ADJUST_PTP_LENGTH_ADJUST_ENABLE_PROFILE_FIELD_SIZE            1

/* end of Profile_Dequeue_Length_Adjust*/


/* start of register pds_debug_configurations*/

#define      TXQ_IRONMAN_PDS_PDS_DEBUG_CONFIGURATIONS_ENABLE_DEBUG_GROUP_COUNTING_FIELD_OFFSET          0
#define      TXQ_IRONMAN_PDS_PDS_DEBUG_CONFIGURATIONS_COUNT_USING_TIMER_FIELD_OFFSET            1
#define      TXQ_IRONMAN_PDS_PDS_DEBUG_CONFIGURATIONS_COUNT_ROC_FIELD_OFFSET            2


#define      TXQ_IRONMAN_PDS_PDS_DEBUG_CONFIGURATIONS_ENABLE_DEBUG_GROUP_COUNTING_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PDS_DEBUG_CONFIGURATIONS_COUNT_USING_TIMER_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_DEBUG_CONFIGURATIONS_COUNT_ROC_FIELD_SIZE          1

/* end of pds_debug_configurations*/


/* start of register pds_enable_debug_counters*/

#define      TXQ_IRONMAN_PDS_PDS_ENABLE_DEBUG_COUNTERS_ENABLE_DEBUG_COUNTERS_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDS_PDS_ENABLE_DEBUG_COUNTERS_ENABLE_DEBUG_COUNTERS_FIELD_SIZE         1

/* end of pds_enable_debug_counters*/


/* start of register pds_debug_cycles_to_count_lsb*/

#define      TXQ_IRONMAN_PDS_PDS_DEBUG_CYCLES_TO_COUNT_LSB_CYCLES_TO_COUNT_LSB_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDS_PDS_DEBUG_CYCLES_TO_COUNT_LSB_CYCLES_TO_COUNT_LSB_FIELD_SIZE           32

/* end of pds_debug_cycles_to_count_lsb*/


/* start of register pds_debug_cycles_to_count_msb*/

#define      TXQ_IRONMAN_PDS_PDS_DEBUG_CYCLES_TO_COUNT_MSB_CYCLES_TO_COUNT_MSB_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDS_PDS_DEBUG_CYCLES_TO_COUNT_MSB_CYCLES_TO_COUNT_MSB_FIELD_SIZE           32

/* end of pds_debug_cycles_to_count_msb*/


/* start of register pds_desc_in_count_lsb*/

#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_LSB_PDS_DESC_IN_COUNT_LSB_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_LSB_PDS_DESC_IN_COUNT_LSB_FIELD_SIZE         32

/* end of pds_desc_in_count_lsb*/


/* start of register pds_desc_in_count_type_ref*/

#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_QUEUE_FIELD_OFFSET            0
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_PORT_FIELD_OFFSET         10
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_MSG_FIELD_OFFSET          16
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_QCN2PFC_FIELD_OFFSET          17
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_DP_GLOBAL_SRC_PORT_FIELD_OFFSET           18
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_TAIL_EXISTS_FIELD_OFFSET          27
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_MDB_FIELD_OFFSET          28
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_L2_CT_FIELD_OFFSET            29


#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_QUEUE_FIELD_SIZE          10
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_PORT_FIELD_SIZE           6
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_MSG_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_QCN2PFC_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_DP_GLOBAL_SRC_PORT_FIELD_SIZE         9
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_TAIL_EXISTS_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_MDB_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_REF_PDS_DESC_IN_COUNT_REF_L2_CT_FIELD_SIZE          1

/* end of pds_desc_in_count_type_ref*/


/* start of register pds_desc_in_count_type_mask*/

#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_QUEUE_FIELD_OFFSET          0
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_PORT_FIELD_OFFSET           10
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_MSG_FIELD_OFFSET            16
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_QCN2PFC_FIELD_OFFSET            17
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_DP_GLOBAL_SRC_PORT_FIELD_OFFSET         18
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_TAIL_EXISTS_FIELD_OFFSET            27
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_MDB_FIELD_OFFSET            28
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_L2_CT_FIELD_OFFSET          29


#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_QUEUE_FIELD_SIZE            10
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_PORT_FIELD_SIZE         6
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_MSG_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_QCN2PFC_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_DP_GLOBAL_SRC_PORT_FIELD_SIZE           9
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_TAIL_EXISTS_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_MDB_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_TYPE_MASK_PDS_DESC_IN_COUNT_MASK_L2_CT_FIELD_SIZE            1

/* end of pds_desc_in_count_type_mask*/


/* start of register pds_desc_in_count_msb*/

#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_MSB_PDS_DESC_IN_COUNT_MSB_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDS_PDS_DESC_IN_COUNT_MSB_PDS_DESC_IN_COUNT_MSB_FIELD_SIZE         32

/* end of pds_desc_in_count_msb*/


/* start of register pds_desc_out_count_lsb*/

#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_LSB_PDS_DESC_OUT_COUNT_LSB_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_LSB_PDS_DESC_OUT_COUNT_LSB_FIELD_SIZE           32

/* end of pds_desc_out_count_lsb*/


/* start of register pds_desc_out_count_type_ref*/

#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_QUEUE_FIELD_OFFSET          0
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_PORT_FIELD_OFFSET           10
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_HIGH_PRIO_REQ_FIELD_OFFSET          16
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_HIGH_PRIO_RES_FIELD_OFFSET          17
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_SEL_FIELD_OFFSET           18
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_ATTR_FIELD_OFFSET          19
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_LONG_QUEUE_HEAD_EMPTY_FIELD_OFFSET         23
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_SDQ_OR_INIT_FIELD_OFFSET           24
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_PB_NOT_READY_FIELD_OFFSET          25
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_QUEUE_EMPTY_FIELD_OFFSET           26
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_MG_READ_FIELD_OFFSET           27
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_PKT_BC_FIELD_OFFSET            28


#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_QUEUE_FIELD_SIZE            10
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_PORT_FIELD_SIZE         6
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_HIGH_PRIO_REQ_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_HIGH_PRIO_RES_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_SEL_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_ATTR_FIELD_SIZE            4
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_LONG_QUEUE_HEAD_EMPTY_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_SDQ_OR_INIT_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_PB_NOT_READY_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_QUEUE_EMPTY_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_MG_READ_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_REF_PDS_DESC_OUT_COUNT_REF_NULL_PKT_BC_FIELD_SIZE          1

/* end of pds_desc_out_count_type_ref*/


/* start of register pds_desc_out_count_type_mask*/

#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_QUEUE_FIELD_OFFSET            0
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_PORT_FIELD_OFFSET         10
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_HIGH_PRIO_REQ_FIELD_OFFSET            16
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_HIGH_PRIO_RES_FIELD_OFFSET            17
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_SEL_FIELD_OFFSET         18
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_ATTR_FIELD_OFFSET            19
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_LONG_QUEUE_HEAD_EMPTY_FIELD_OFFSET           23
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_SDQ_OR_INIT_FIELD_OFFSET         24
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_PB_NOT_READY_FIELD_OFFSET            25
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_QUEUE_EMPTY_FIELD_OFFSET         26
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_MG_READ_FIELD_OFFSET         27
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_PKT_BC_FIELD_OFFSET          28


#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_QUEUE_FIELD_SIZE          10
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_PORT_FIELD_SIZE           6
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_HIGH_PRIO_REQ_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_HIGH_PRIO_RES_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_SEL_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_ATTR_FIELD_SIZE          4
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_LONG_QUEUE_HEAD_EMPTY_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_SDQ_OR_INIT_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_PB_NOT_READY_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_QUEUE_EMPTY_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_MG_READ_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_TYPE_MASK_PDS_DESC_OUT_COUNT_MASK_NULL_PKT_BC_FIELD_SIZE            1

/* end of pds_desc_out_count_type_mask*/


/* start of register pds_desc_out_count_msb*/

#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_MSB_PDS_DESC_OUT_COUNT_MSB_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDS_PDS_DESC_OUT_COUNT_MSB_PDS_DESC_OUT_COUNT_MSB_FIELD_SIZE           32

/* end of pds_desc_out_count_msb*/


/* start of register pds_sdq_select_count_lsb*/

#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_LSB_PDS_SDQ_SELECT_COUNT_LSB_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_LSB_PDS_SDQ_SELECT_COUNT_LSB_FIELD_SIZE           32

/* end of pds_sdq_select_count_lsb*/


/* start of register pds_sdq_select_count_type_ref*/

#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_REF_PDS_SDQ_SELECT_COUNT_REF_QUEUE_FIELD_OFFSET          0
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_REF_PDS_SDQ_SELECT_COUNT_REF_PORT_FIELD_OFFSET           10
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_REF_PDS_SDQ_SELECT_COUNT_REF_HIGH_PRIO_REQ_FIELD_OFFSET          16
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_REF_PDS_SDQ_SELECT_COUNT_REF_HIGH_PRIO_RES_FIELD_OFFSET          17
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_REF_PDS_SDQ_SELECT_COUNT_REF_NULL_SEL_FIELD_OFFSET           18
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_REF_PDS_SDQ_SELECT_COUNT_REF_NULL_ATTR_FIELD_OFFSET          19


#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_REF_PDS_SDQ_SELECT_COUNT_REF_QUEUE_FIELD_SIZE            10
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_REF_PDS_SDQ_SELECT_COUNT_REF_PORT_FIELD_SIZE         6
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_REF_PDS_SDQ_SELECT_COUNT_REF_HIGH_PRIO_REQ_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_REF_PDS_SDQ_SELECT_COUNT_REF_HIGH_PRIO_RES_FIELD_SIZE            1
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_REF_PDS_SDQ_SELECT_COUNT_REF_NULL_SEL_FIELD_SIZE         1
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_REF_PDS_SDQ_SELECT_COUNT_REF_NULL_ATTR_FIELD_SIZE            6

/* end of pds_sdq_select_count_type_ref*/


/* start of register pds_sdq_select_count_type_mask*/

#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_MASK_PDS_SDQ_SELECT_COUNT_MASK_QUEUE_FIELD_OFFSET            0
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_MASK_PDS_SDQ_SELECT_COUNT_MASK_PORT_FIELD_OFFSET         10
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_MASK_PDS_SDQ_SELECT_COUNT_MASK_HIGH_PRIO_REQ_FIELD_OFFSET            16
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_MASK_PDS_SDQ_SELECT_COUNT_MASK_HIGH_PRIO_RES_FIELD_OFFSET            17
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_MASK_PDS_SDQ_SELECT_COUNT_MASK_NULL_SEL_FIELD_OFFSET         18
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_MASK_PDS_SDQ_SELECT_COUNT_MASK_NULL_ATTR_FIELD_OFFSET            19


#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_MASK_PDS_SDQ_SELECT_COUNT_MASK_QUEUE_FIELD_SIZE          10
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_MASK_PDS_SDQ_SELECT_COUNT_MASK_PORT_FIELD_SIZE           6
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_MASK_PDS_SDQ_SELECT_COUNT_MASK_HIGH_PRIO_REQ_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_MASK_PDS_SDQ_SELECT_COUNT_MASK_HIGH_PRIO_RES_FIELD_SIZE          1
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_MASK_PDS_SDQ_SELECT_COUNT_MASK_NULL_SEL_FIELD_SIZE           1
#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_TYPE_MASK_PDS_SDQ_SELECT_COUNT_MASK_NULL_ATTR_FIELD_SIZE          6

/* end of pds_sdq_select_count_type_mask*/


/* start of register pds_sdq_select_count_msb*/

#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_MSB_PDS_SDQ_SELECT_COUNT_MSB_FIELD_OFFSET         0


#define      TXQ_IRONMAN_PDS_PDS_SDQ_SELECT_COUNT_MSB_PDS_SDQ_SELECT_COUNT_MSB_FIELD_SIZE           32

/* end of pds_sdq_select_count_msb*/


/* start of table entry Next_Desc*/

#define      TXQ_IRONMAN_PDS_NEXT_DESC_NEXT_PTR_FIELD_OFFSET            0
#define      TXQ_IRONMAN_PDS_NEXT_DESC_DESCRIPTOR_FIELD_OFFSET          15


#define      TXQ_IRONMAN_PDS_NEXT_DESC_NEXT_PTR_FIELD_SIZE          15
#define      TXQ_IRONMAN_PDS_NEXT_DESC_DESCRIPTOR_FIELD_SIZE            59

/* end of Next_Desc*/


/* start of table entry write_pointer*/

#define      TXQ_IRONMAN_PDS_WRITE_POINTER_WR_PTR_FIELD_OFFSET          0


#define      TXQ_IRONMAN_PDS_WRITE_POINTER_WR_PTR_FIELD_SIZE            15

/* end of write_pointer*/


/* start of table entry read_pointer*/

#define      TXQ_IRONMAN_PDS_READ_POINTER_RD_PTR_FIELD_OFFSET           0


#define      TXQ_IRONMAN_PDS_READ_POINTER_RD_PTR_FIELD_SIZE         15

/* end of read_pointer*/


#endif
