/*===========================================================================*/
#ifndef exp_h_data_PKS_INCLUDED
#define exp_h_data_PKS_INCLUDED
/*!**************************************************RND Template version 4.1
*!                      P A C K A G E       S P E C I F I C A T I O N
*!==========================================================================
*$ TITLE: host io 
*!--------------------------------------------------------------------------
*$ FILENAME: c:\temp\radlan\local\h_data\EXP\h_data.h
*!--------------------------------------------------------------------------
*$ SYSTEM, SUBSYSTEM: ET16
*!--------------------------------------------------------------------------
*$ AUTHORS: eyran 
*!--------------------------------------------------------------------------
*$ LATEST UPDATE:                              CREATION DATE: 16-Jan-94
*!**************************************************************************
*!
*!**************************************************************************
*!
*$ GENERAL DESCRIPTION:
*!  
*! PROCESS AND ALGORITHM: (local)
*!  
*$ PACKAGE GLOBAL SERVICES:
*!     (A list of package global services).
*!
*$ PACKAGE LOCAL SERVICES:  (local)
*!     (A list of package local services).
*!
*$ PACKAGE USAGE:
*!     (How to use the package services, 
*!     routines calling order, restrictions, etc.)
*!
*$ ASSUMPTIONS:
*! 
*$ SIDE EFFECTS:
*! 
*$ RELATED DOCUMENTS:     (local)
*! 
*$ REMARKS:               (local)
*! 
*!**************************************************************************
*!*/
/*!**************************************************************************
*$              EXTERNAL DECLARATIONS (IMPORT AND EXPORT)
*!**************************************************************************
*!*/
#include <HOST_D/EXP/HOST_D.H>
/*!**************************************************************************
*$              PUBLIC DECLARATIONS (EXPORT)
*!**************************************************************************
*!*/
/*===========================================================================*/
/*!**************************************************RND Template version 4.1
 *!                 D A T A   T Y P E   D E F I N I T I O N
 *!==========================================================================
 *$ TITLE: <Title>
 *!--------------------------------------------------------------------------
 *$ FILENAME: u:\next\simulat\shost\local\h_dll\inc\h_dll.dtd
 *!--------------------------------------------------------------------------
 *$ SYSTEM, SUBSYSTEM: ????
 *!--------------------------------------------------------------------------
 *$ AUTHORS: AlexV     
 *!--------------------------------------------------------------------------
 *$ LATEST UPDATE: 01-Jul-98  18:41:17         CREATION DATE: 01-Jul-98
 *!**************************************************************************
 *!
 *!**************************************************************************
 *!
 *$ GENERAL DESCRIPTION:
 *!
 *$ REMARKS:
 *!
 *!**************************************************************************
 *!*/

/*abort function type*/
typedef void SHOSTG_abort_FUN(UINT_8 *msg) ;

/*fatal error function type*/
typedef void SHOSTC_fatal_error_FUN(UINT_8 *msg) ;

/*fatal error function type*/
typedef void SHOSTC_free_net_tx_FUN(void *id) ;

/*tick function type*/
#ifndef SHOSTG_TICK_FUN_CNS
  #define SHOSTG_TICK_FUN_CNS
  typedef void SHOSTG_tick_FUN ( void );
#endif
/*===========================================================================*/
/*!**************************************************************************
*$              PUBLIC VARIABLE DEFINITIONS (EXPORT)
*!**************************************************************************
*!*/
/*===========================================================================*/
/*!**************************************************RND Template version 4.1
 *!           L O C A L   V A R I A B L E   D E C L A R A T I O N S
 *!==========================================================================
 *$ TITLE: the dll local env functions
 *!--------------------------------------------------------------------------
 *$ FILENAME: u:\next\simulat\shost\local\h_dll\inc\h_dll.pub
 *!--------------------------------------------------------------------------
 *$ SYSTEM, SUBSYSTEM: nste
 *!--------------------------------------------------------------------------
 *$ AUTHORS: EYRAN     
 *!--------------------------------------------------------------------------
 *$ LATEST UPDATE: 01-Jul-98  18:54:18        CREATION DATE: 07-Jan-97
 *!**************************************************************************
 *!
 *!**************************************************************************
 *!
 *$ GENERAL DESCRIPTION:
 *!
 *$ INCLUDE REQUIRED:
 *!
 *$ REMARKS:
 *!
 *!**************************************************************************
 *!*/

/*
 * Who initializes:
 * Who reads (uses):
 * Who updates:
 * Protecting mechanism:
 */

extern SHOSTG_abort_FUN         *HDLLG_abort_fun ;    
#define KOKOHHH         300

extern SHOSTC_fatal_error_FUN   *HDLLG_fatal_error_fun ;
#define KOKOHHH         300

extern SHOSTC_free_net_tx_FUN   *HDLLG_free_net_tx_fun ;
#define KOKOHHH         300

extern SHOSTG_tick_FUN          *HDLLG_tick_fun ;


#undef  KOKOHHH

/*===========================================================================*/
/*!**************************************************************************
*$              PUBLIC FUNCTION DEFINITIONS (EXPORT)
*!**************************************************************************
*!*/
/*===========================================================================*/
/*!**************************************************RND Template version 4.1
 *!                   M A C R O   D E F I N I T I O N S
 *!==========================================================================
 *$ TITLE: the h_dll macros of env services
 *!--------------------------------------------------------------------------
 *$ FILENAME: c:\temp\radlan\local\h_data\EXP\h_dll.fud
 *!--------------------------------------------------------------------------
 *$ SYSTEM, SUBSYSTEM: nste
 *!--------------------------------------------------------------------------
 *$ AUTHORS: EYRAN     
 *!--------------------------------------------------------------------------
 *$ LATEST UPDATE:                             CREATION DATE: 07-Jan-97
 *!**************************************************************************
 *!
 *!**************************************************************************
 *!
 *$ MACRO: <MacroName>
 *!
 *$ GENERAL DESCRIPTION:
 *!
 *$ RETURNS:
 *!
 *$ ALGORITHM: (local)
 *!                      
 *$ ASSUMPTIONS:
 *!
 *$ REMARKS:   (local)
 *!
 *!**************************************************************************
 *!*/

#define HDLLG_abort         (*HDLLG_abort_fun)
#define HDLLG_fatal_error   (*HDLLG_fatal_error_fun)
#define HDLLG_free_net_tx   (*HDLLG_free_net_tx_fun)
#define HDLLG_tick          (*HDLLG_tick_fun)
                            
/*===========================================================================*/
/*===========================================================================*/
/**
* @internal SHOSTG_date_get function
* @endinternal
*
*/

extern  void SHOSTG_date_get (

    UINT_32 *year_PTR,

    UINT_32 *month_PTR,

    UINT_32 *day_PTR,

    UINT_32 *hour_PTR,

    UINT_32 *minute_PTR,

    UINT_32 *second_PTR,

    UINT_32 *millisec_PTR
);
/*$ END OF SHOSTG_date_get */
/*===========================================================================*/
/*===========================================================================*/
/**
* @internal SHOSTG_date_set function
* @endinternal
*
*/

extern  void SHOSTG_date_set (

    UINT_32 year,

    UINT_32 month,

    UINT_32 day,

    UINT_32 hour,

    UINT_32 minute,

    UINT_32 second,

    UINT_32 millisec
);
/*$ END OF SHOSTG_date_set */
/*===========================================================================*/

#endif
/*$ END OF h_data */

