/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,       *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
*/
/**
********************************************************************************
* @file prvCpssDxChTtiTypes.h
*
* @brief prv CPSS definitions for tunnel.
*
* @version   1
********************************************************************************
*/

#ifndef __prvCpssDxChTtiTypesh
#define __prvCpssDxChTtiTypesh

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

typedef enum{
    /*common to all*/
    TTI_LEGACY_KEY_FIELDS_PCLID_4_0_E,
    TTI_LEGACY_KEY_FIELDS_LOCAL_DEVICE_SOURCE_IS_TRUNK_E,
    TTI_LEGACY_KEY_FIELDS_DSA_TAG_SRCISTRUNK_E,
    TTI_LEGACY_KEY_FIELDS_MAC_TO_ME_E,
    TTI_LEGACY_KEY_FIELDS_PCLID_9_5_E,
    TTI_LEGACY_KEY_FIELDS_SRC_COREID_E,
    TTI_LEGACY_KEY_FIELDS_EVLAN_7_0_E,
    TTI_LEGACY_KEY_FIELDS_EVLAN_12_8_E,
    TTI_LEGACY_KEY_FIELDS_RESERVED_0_E,
    TTI_LEGACY_KEY_FIELDS_LOCAL_DEVICE_SOURCE_EPORT_TRUNKID_7_0_E,
    TTI_LEGACY_KEY_FIELDS_LOCAL_DEVICE_SOURCE_EPORT_TRUNKID_12_8_E,
    TTI_LEGACY_KEY_FIELDS_RESERVED_1_E,
    TTI_LEGACY_KEY_FIELDS_DSA_TAG_SRCPORT_SRCEPORT_TRUNKID_7_0_E,
    TTI_LEGACY_KEY_FIELDS_DSA_TAG_SRCPORT_SRCEPORT_TRUNKID_12_8_E,
    TTI_LEGACY_KEY_FIELDS_RESERVED_2_E,

    /* mim and trill and ethernet */
    TTI_LEGACY_KEY_FIELDS_UP0_E,
    TTI_LEGACY_KEY_FIELDS_CFI0_E,
    TTI_LEGACY_KEY_FIELDS_VLAN_TAG0_EXISTS_E,
    TTI_LEGACY_KEY_FIELDS_RESERVED_4_E,
    TTI_LEGACY_KEY_FIELDS_PASSENGER_OUTER_CFI_E,
    /* end mim and trill */

    TTI_LEGACY_KEY_FIELDS_MAC_DA_MAC_SA_E,

    TTI_LEGACY_KEY_FIELDS_DSA_TAG_SRCDEV_7_0_E,
    TTI_LEGACY_KEY_FIELDS_DSA_TAG_SRCDEV_9_8_E,
    TTI_LEGACY_KEY_FIELDS_RESERVED_3_E,
    TTI_LEGACY_KEY_FIELDS_MUST_BE_1_E,

    /* ipv4 */
    TTI_LEGACY_KEY_FIELDS_IPV4_SIP_E,
    TTI_LEGACY_KEY_FIELDS_IPV4_DIP_E,
    TTI_LEGACY_KEY_FIELDS_IPV4_IS_ARP_E,
    TTI_LEGACY_KEY_FIELDS_IPV4_TUNNELING_PROTOCOL_E,

    /* mpls */
    TTI_LEGACY_KEY_FIELDS_MPLS_S0_E      ,
    TTI_LEGACY_KEY_FIELDS_MPLS_EXP0_E    ,
    TTI_LEGACY_KEY_FIELDS_MPLS_LABEL0_E  ,
    TTI_LEGACY_KEY_FIELDS_MPLS_S1_E      ,
    TTI_LEGACY_KEY_FIELDS_MPLS_EXP1_E    ,
    TTI_LEGACY_KEY_FIELDS_MPLS_LABEL1_E  ,
    TTI_LEGACY_KEY_FIELDS_MPLS_S2_E      ,
    TTI_LEGACY_KEY_FIELDS_MPLS_EXP2_E    ,
    TTI_LEGACY_KEY_FIELDS_MPLS_LABEL2_E  ,
    TTI_LEGACY_KEY_FIELDS_MPLS_RESERVED_LABEL_VALUE_E      ,
    TTI_LEGACY_KEY_FIELDS_MPLS_CONTROL_WORD_CHANNEL_TYPE_PROFILE_E      ,
    TTI_LEGACY_KEY_FIELDS_MPLS_PROTOCOL_AFTER_MPLS_E      ,
    TTI_LEGACY_KEY_FIELDS_MPLS_RESERVED_LABEL_EXISTS_E      ,
    TTI_LEGACY_KEY_FIELDS_MPLS_DATA_AFTER_INNER_LABEL_E      ,

    /* mim (part2)*/
    TTI_LEGACY_KEY_FIELDS_MIM_I_SID_E      ,
    TTI_LEGACY_KEY_FIELDS_MIM_I_TAG_OCTET1_BITS_1_4_E      ,
    TTI_LEGACY_KEY_FIELDS_MIM_I_DP_E      ,
    TTI_LEGACY_KEY_FIELDS_MIM_I_UP_E      ,
    TTI_LEGACY_KEY_FIELDS_MIM_PASSENGER_S_TAG_VID_E      ,
    TTI_LEGACY_KEY_FIELDS_MIM_PASSENGER_S_TAG_UP_E      ,
    TTI_LEGACY_KEY_FIELDS_MIM_PASSENGER_S_TAG_EXISTS_E      ,

    /*ethernet*/
    TTI_LEGACY_KEY_FIELDS_ETHERNET_VLAN1_E      ,
    TTI_LEGACY_KEY_FIELDS_ETHERNET_UP1_E      ,
    TTI_LEGACY_KEY_FIELDS_ETHERNET_CFI1_E      ,
    TTI_LEGACY_KEY_FIELDS_ETHERNET_ETHERTYPE_E      ,
    TTI_LEGACY_KEY_FIELDS_ETHERNET_VLAN_TAG1_EXISTS_E      ,
    TTI_LEGACY_KEY_FIELDS_ETHERNET_TAG0_TPID_INDEX_E      ,
    TTI_LEGACY_KEY_FIELDS_ETHERNET_TAG1_TPID_INDEX_E      ,
    TTI_LEGACY_KEY_FIELDS_ETHERNET_RESERVED_E      ,
    TTI_LEGACY_KEY_FIELDS_ETHERNET_DSA_QOS_PROFILE_E      ,
    TTI_LEGACY_KEY_FIELDS_ETHERNET_RESERVED1_E      ,
    TTI_LEGACY_KEY_FIELDS_ETHERNET_DSA_SOURCE_ID_11_0_E      ,

    TTI_LEGACY_KEY_FIELDS___LAST_VALUE___E/* used for array size */
}TTI_LEGACY_KEY_FIELDS_ENT;

typedef enum {
    TTI_META_DATA_FIELDS_IS_ARP_E,
    TTI_META_DATA_FIELDS_IPV4_TUNNELING_PROTOCOL_E,
    TTI_META_DATA_FIELDS_RESERVED_0_E,
    TTI_META_DATA_FIELDS_IPV4_ARP_DIP_E,
    TTI_META_DATA_FIELDS_IPV4_ARP_SIP_E,
    TTI_META_DATA_FIELDS_PROTOCOL_ABOVE_MPLS_E,
    TTI_META_DATA_FIELDS_RESERVED_LABEL_EXISTS_E,
    TTI_META_DATA_FIELDS_DATA_AFTER_INNER_LABEL_E,
    TTI_META_DATA_FIELDS_RESERVED_LABEL_VALUE_E,
    TTI_META_DATA_FIELDS_CONTROL_WORD_CHANNEL_TYPE_PROFILE_E,
    TTI_META_DATA_FIELDS_UP0_B_UP_E,
    TTI_META_DATA_FIELDS_CFI0_B_DEI__E,
    TTI_META_DATA_FIELDS_VLAN_TAG0_EXISTS_E,
    TTI_META_DATA_FIELDS_RESERVED_1_E,
    TTI_META_DATA_FIELDS_PASSENGER_OUTER_CFI_E,
    TTI_META_DATA_FIELDS_PASSENGER_OUTER_TAG_VID_7_0_E,
    TTI_META_DATA_FIELDS_PASSENGER_OUTER_TAG_VID_11_8_E,
    TTI_META_DATA_FIELDS_PASSENGER_OUTER_TAG_UP_E,
    TTI_META_DATA_FIELDS_PASSENGER_OUTER_TAG_EXIST_E,
    TTI_META_DATA_FIELDS_VLAN1_7_0_E,
    TTI_META_DATA_FIELDS_VLAN1_11_8_E,
    TTI_META_DATA_FIELDS_UP1_E,
    TTI_META_DATA_FIELDS_CFI1_E,
    TTI_META_DATA_FIELDS_VLAN1_EXIST_E,
    TTI_META_DATA_FIELDS_TAG0_TPID_INDEX_E,
    TTI_META_DATA_FIELDS_TAG1_TPID_INDEX_E,
    TTI_META_DATA_FIELDS_RESERVED_2_E,
    TTI_META_DATA_FIELDS_DSA_QOS_PROFILE_E,
    TTI_META_DATA_FIELDS_RESERVED_3_E,
    TTI_META_DATA_FIELDS_DSA_SOURCE_ID__7_0_E,
    TTI_META_DATA_FIELDS_DSA_SOURCE_ID__11_8_E,
    TTI_META_DATA_FIELDS_NUMBER_OF_MPLS_LABELS_14_12_E,
    TTI_META_DATA_FIELDS_RESERVED_4_E,
    TTI_META_DATA_FIELDS_TRILL_OPTIONS_1ST_NIBBLE_E,
    TTI_META_DATA_FIELDS_TRILL_OPTIONS_EXIST_E,
    TTI_META_DATA_FIELDS_TRILL_M_BIT_E,
    TTI_META_DATA_FIELDS_TRILL_OPTION_LENGTH_EXCEEDED_E,
    TTI_META_DATA_FIELDS_REP_LAST_E,
    TTI_META_DATA_FIELDS_IPV6_TUNNELING_PROTOCOL_E,
    TTI_META_DATA_FIELDS_L3_DATA_WORD0_FIRST_NIBBLE_E,
    TTI_META_DATA_FIELDS_IPV6_L4_VALID_E,
    TTI_META_DATA_FIELDS_PCLID_4_0_E,
    TTI_META_DATA_FIELDS_LOCAL_DEVICE_SOURCE_IS_TRUNK_E,
    TTI_META_DATA_FIELDS_DSA_TAG_SRCISTRUNK_E,
    TTI_META_DATA_FIELDS_MAC_TO_ME_E,
    TTI_META_DATA_FIELDS_PCLID_9_5_E,
    TTI_META_DATA_FIELDS_SRC_COREID_E,
    TTI_META_DATA_FIELDS_EVLAN_7_0_E,
    TTI_META_DATA_FIELDS_EVLAN_12_8_E,
    TTI_META_DATA_FIELDS_RESERVED_5_E,
    TTI_META_DATA_FIELDS_LOCAL_DEVICE_SOURCE_EPORT_TRUNKID_7_0_E,
    TTI_META_DATA_FIELDS_LOCAL_DEVICE_SOURCE_EPORT_TRUNKID_12_8_E,
    TTI_META_DATA_FIELDS_RESERVED_6_E,
    TTI_META_DATA_FIELDS_DSA_TAG_SRCPORT_SRCEPORT_TRUNKID_7_0_E,
    TTI_META_DATA_FIELDS_DSA_TAG_SRCPORT_SRCEPORT_TRUNKID_12_8_E,
    TTI_META_DATA_FIELDS_RESERVED_7_E,
    TTI_META_DATA_FIELDS_DSA_TAG_SRCDEV_7_0_E,
    TTI_META_DATA_FIELDS_DSA_TAG_SRCDEV_9_8_E,
    TTI_META_DATA_FIELDS_RESERVED_8_E,
    TTI_META_DATA_FIELDS_MUST_BE_1_E,
    TTI_META_DATA_FIELDS_SIP5_LAST_VALUE_E,
    /* SIP6 META_DATA_FIELDS */
    TTI_META_DATA_FIELDS_RESERVED_9_E,
    TTI_META_DATA_FIELDS_SRC_PHY_PORT_7_0_E,
    TTI_META_DATA_FIELDS_SRC_PHY_PORT_9_8_E,
    TTI_META_DATA_FIELDS_PREEMPTED_E,
    TTI_META_DATA_FIELDS_RESERVED_10_E,
    TTI_META_DATA_FIELDS_IPVX_PROTOCOL_E,
    TTI_META_DATA_FIELDS_SIP6_20_LAST_VALUE_E,
    /* SIP6_30 META_DATA_FIELDS */
    TTI_META_DATA_FIELDS_IP2ME_MATCH_FOUND_E,
    TTI_META_DATA_FIELDS_IP2ME_MATCH_INDEX_E,

    TTI_META_DATA_FIELDS___LAST_VALUE___E/* used for array size */
}TTI_META_DATA_FIELDS_ENT;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* __prvCpssDxChTTiTypesh */

