/*===========================================================================*/
#ifndef exp_sagent_PKS_INCLUDED
#define exp_sagent_PKS_INCLUDED
/*!**************************************************RND Template version 4.1
*!                      P A C K A G E       S P E C I F I C A T I O N
*!==========================================================================
*$ TITLE: sagent
*!--------------------------------------------------------------------------
*$ FILENAME: c:\temp\radlan\sagent\EXP\sagent.h
*!--------------------------------------------------------------------------
*$ SYSTEM, SUBSYSTEM: VG98, SAGENT
*!--------------------------------------------------------------------------
*$ AUTHORS: AlexV,BoazK,Moish
*!--------------------------------------------------------------------------
*$ LATEST UPDATE:                     CREATION DATE: 17-May-98
*!**************************************************************************
*!
*!**************************************************************************
*!
*$ GENERAL DESCRIPTION:
*!
*$ PROCESS AND ALGORITHM: (local)
*!
*$ PACKAGE GLOBAL SERVICES:
*!     (A list of package global services).
*!
*$ PACKAGE LOCAL SERVICES:  (local)
*!     (A list of package local services).
*!
*$ PACKAGE USAGE:
*!     (How to use the package services,
*!     routines calling order, restrictions, etc.)
*!
*$ ASSUMPTIONS:
*!
*$ SIDE EFFECTS:
*!
*$ RELATED DOCUMENTS:     (local)
*!
*$ REMARKS:               (local)
*!
*!**************************************************************************
*!*/
/*!**************************************************************************
*$              EXTERNAL DECLARATIONS (IMPORT AND EXPORT)
*!**************************************************************************
*!*/
#ifdef WINDOWS_COMPATIBLE
    #include         <windows.h>
    #include         <process.h>
#endif /*WINDOWS_COMPATIBLE*/
/*!**************************************************************************
*$              PUBLIC DECLARATIONS (EXPORT)
*!**************************************************************************
*!*/
/*===========================================================================*/
/*!**************************************************RND Template version 4.1
 *!                 D A T A   T Y P E   D E F I N I T I O N
 *!==========================================================================
 *$ TITLE: Global declarations
 *!--------------------------------------------------------------------------
 *$ FILENAME: u:\next\nste\sagent\inc\sagent.dtd
 *!--------------------------------------------------------------------------
 *$ SYSTEM, SUBSYSTEM: VG98, NSTE, SAGENT
 *!--------------------------------------------------------------------------
 *$ AUTHORS: AlexV
 *!--------------------------------------------------------------------------
 *$ LATEST UPDATE: 17-May-98  16:14:52         CREATION DATE: 17-May-98
 *!**************************************************************************
 *!
 *!**************************************************************************
 *!
 *$ GENERAL DESCRIPTION:
 *!
 *$ REMARKS:
 *!
 *!**************************************************************************
 *!*/

#define SAGNTG_normal_msg_rsn_CNS       0
#define SAGNTG_get_buff_rsn_CNS         1
#define SAGNTG_give_buff_succs_rsn_CNS  2
#define SAGNTG_give_buff_err_rsn_CNS    3

#define SAGNTG_user_first_msg_CNS (WM_USER + 8)
#define SAGNTG_max_name_CNS    8

typedef struct  SAGNTG_frame_data_STCT {
    char sender[SAGNTG_max_name_CNS + 1] ;       /*sender name*/
    char target[SAGNTG_max_name_CNS + 1] ;       /*target name*/
} SAGNTG_frame_data_STC ;

typedef char*  (*SAGNTG_rcv_FUN)(
    DWORD         msg_code,
    DWORD         Reason,
    DWORD         sender_tid,
    DWORD         len,
    void         *usr_info,
    char        *buff
) ;

/*typedef SAGNTP_rcv_FUN*  SAGNTG_rcv_FUN;*/

/*===========================================================================*/
/*!**************************************************************************
*$              PUBLIC VARIABLE DEFINITIONS (EXPORT)
*!**************************************************************************
*!*/
/*!**************************************************************************
*$              PUBLIC FUNCTION DEFINITIONS (EXPORT)
*!**************************************************************************
*!*/
/*===========================================================================*/
/**
* @internal SAGNTG_ChangeLinkStatus function
* @endinternal
*
*/
extern void SAGNTG_ChangeLinkStatus (
  /*!     INPUTS:             */
   void                        *slan_id,
   GT_BOOL      linkstate
  /*!     INPUTS / OUTPUTS:   */

  /*!     OUTPUTS:            */

);
/*$ END OF SAGNTG_ChangeLinkStatus */

/*$ END OF  SAGNTG_ChangeLinkStatus */

/*===========================================================================*/
/*===========================================================================*/
/*!**************************************************RND Template version 4.1
 *!     F U N C T I O N    P R O T O T Y P E    D E F I N I T I O N
 *!==========================================================================
 *$ TITLE: Bind
 *!--------------------------------------------------------------------------
 *$ FILENAME: c:\temp\radlan\sagent\EXP\BIND.fud
 *!--------------------------------------------------------------------------
 *$ SYSTEM, SUBSYSTEM: VG98, NSTE, SAGENT
 *!--------------------------------------------------------------------------
 *$ AUTHORS: AlexV,BoazK,radlanuser
 *!--------------------------------------------------------------------------
 *$ LATEST UPDATE:                       CREATION DATE: 17-May-98
 *!**************************************************************************
 *!
 *!**************************************************************************
 *!
 *$ FUNCTION: SAGNTG_bind
 *!
 *$ GENERAL DESCRIPTION:
 *!
 *$ RETURNS:
 *!
 *$ ALGORITHM:   (local)
 *!
 *$ ASSUMPTIONS:
 *!
 *$ REMARKS:     (local)
 *!
 *!**************************************************************************
 *!*/

extern void* SAGNTG_bind (

    /*!     INPUTS:             */

    char                        *slan_name,

    char                        *client_name,

    DWORD                        PoolSize,

    DWORD                        MaxClients,

    void                        *usr_info,

    SAGNTG_rcv_FUN                func

    /*!     INPUTS / OUTPUTS:   */
    /*!     OUTPUTS:            */
);
/*$ END OF SAGNTG_bind */

/*===========================================================================*/
/*===========================================================================*/
/**
* @internal SAGNTG_bind_event function
* @endinternal
*
*/

extern void SAGNTG_bind_event (

    /*!     INPUTS:             */

    void                        *slan_id,

    HANDLE                        *ev_ptr

    /*!     INPUTS / OUTPUTS:   */
    /*!     OUTPUTS:            */
);
/*$ END OF SAGNTG_bind_event */
/*===========================================================================*/
/*===========================================================================*/
/*!**************************************************RND Template version 4.1
 *!     F U N C T I O N    P R O T O T Y P E    D E F I N I T I O N
 *!==========================================================================
 *$ TITLE: NSTE bind function
 *!--------------------------------------------------------------------------
 *$ FILENAME: c:\temp\radlan\sagent\EXP\NSTE_BND.fud
 *!--------------------------------------------------------------------------
 *$ SYSTEM, SUBSYSTEM: VG98, NSTE, SAGENT
 *!--------------------------------------------------------------------------
 *$ AUTHORS: AlexV
 *!--------------------------------------------------------------------------
 *$ LATEST UPDATE:                             CREATION DATE: 17-May-98
 *!**************************************************************************
 *!
 *!**************************************************************************
 *!
 *$ FUNCTION: SAGNTG_nste_bind_func
 *!
 *$ GENERAL DESCRIPTION:
 *!
 *$ RETURNS:
 *!
 *$ ALGORITHM:   (local)
 *!
 *$ ASSUMPTIONS:
 *!
 *$ REMARKS:     (local)
 *!
 *!**************************************************************************
 *!*/

extern unsigned int SAGNTG_nste_bind_func (

    /*!     INPUTS:             */

    void                        *nste_id,

    DWORD                        msg_code,

    SAGNTG_rcv_FUN                func

    /*!     INPUTS / OUTPUTS:   */
    /*!     OUTPUTS:            */
);
/*$ END OF SAGNTG_nste_bind_func */
/*===========================================================================*/
/*===========================================================================*/
/*!**************************************************RND Template version 4.1
 *!     F U N C T I O N    P R O T O T Y P E    D E F I N I T I O N
 *!==========================================================================
 *$ TITLE: SLAN name get
 *!--------------------------------------------------------------------------
 *$ FILENAME: c:\temp\radlan\sagent\EXP\SLNM_GET.fud
 *!--------------------------------------------------------------------------
 *$ SYSTEM, SUBSYSTEM: VG98, NSTE, SAGENT
 *!--------------------------------------------------------------------------
 *$ AUTHORS: AlexV
 *!--------------------------------------------------------------------------
 *$ LATEST UPDATE:                             CREATION DATE: 17-May-98
 *!**************************************************************************
 *!
 *!**************************************************************************
 *!
 *$ FUNCTION: SAGNTG_get_slan_name
 *!
 *$ GENERAL DESCRIPTION:
 *!
 *$ RETURNS:
 *!
 *$ ALGORITHM:   (local)
 *!
 *$ ASSUMPTIONS:
 *!
 *$ REMARKS:     (local)
 *!
 *!**************************************************************************
 *!*/

extern char* SAGNTG_get_slan_name (

    /*!     INPUTS:             */

    void                        *slan_id

    /*!     INPUTS / OUTPUTS:   */
    /*!     OUTPUTS:            */
);
/*$ END OF SAGNTG_get_slan_name */
/*===========================================================================*/
/*===========================================================================*/
/**
* @internal SAGNTG_search_client_name function
* @endinternal
*
*/

extern DWORD SAGNTG_search_client_name (

    /*!     INPUTS:             */

    void                        *slan_id,

    char                        *client_name

    /*!     INPUTS / OUTPUTS:   */
    /*!     OUTPUTS:            */
);
/*$ END OF SAGNTG_search_client_name */
/*===========================================================================*/
/*===========================================================================*/
/**
* @internal SAGNTG_search_next_client_name function
* @endinternal
*
*/

extern DWORD SAGNTG_search_next_client_name (

    /*!     INPUTS:             */

    void                        *slan_id,

    char                        *client_name

    /*!     INPUTS / OUTPUTS:   */
    /*!     OUTPUTS:            */
);
/*$ END OF SAGNTG_search_next_client_name */
/*===========================================================================*/
/*===========================================================================*/
/*!**************************************************RND Template version 4.1
 *!     F U N C T I O N    P R O T O T Y P E    D E F I N I T I O N
 *!==========================================================================
 *$ TITLE: Transmit
 *!--------------------------------------------------------------------------
 *$ FILENAME: c:\temp\radlan\sagent\EXP\TRANSMIT.fud
 *!--------------------------------------------------------------------------
 *$ SYSTEM, SUBSYSTEM: VG98, NSTE, SAGENT
 *!--------------------------------------------------------------------------
 *$ AUTHORS: AlexV,radlanuser
 *!--------------------------------------------------------------------------
 *$ LATEST UPDATE:                      CREATION DATE: 17-May-98
 *!**************************************************************************
 *!
 *!**************************************************************************
 *!
 *$ FUNCTION: SAGNTG_transmit
 *!
 *$ GENERAL DESCRIPTION:
 *!
 *$ RETURNS:
 *!
 *$ ALGORITHM:   (local)
 *!
 *$ ASSUMPTIONS:
 *!
 *$ REMARKS:     (local)
 *!
 *!**************************************************************************
 *!*/

extern unsigned int SAGNTG_transmit (

    /*!     INPUTS:             */

    void            *slan_id,

    char            *client_name,

    DWORD           msg_code,

    DWORD           len,

    char            *msg

    /*!     INPUTS / OUTPUTS:   */
    /*!     OUTPUTS:            */
);
/*$ END OF SAGNTG_transmit */

/*===========================================================================*/
/*===========================================================================*/
/**
* @internal SAGNTG_unbind function
* @endinternal
*
*/

extern void SAGNTG_unbind (

    /*!     INPUTS:             */

    void                        *slan_id

    /*!     INPUTS / OUTPUTS:   */
    /*!     OUTPUTS:            */
);
/*$ END OF SAGNTG_unbind */
/*===========================================================================*/

#endif
/*$ END OF sagent */

