/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,       *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
*/
/**
********************************************************************************
* @file tgfDiagGen.c
*
* @brief Diag Descriptor APIs.
*
* @version   4
********************************************************************************
*/

#include <cpssCommon/cpssPresteraDefs.h>
#include <cpss/extServices/private/prvCpssBindFunc.h>

#include <utf/private/prvUtfHelpers.h>
#include <utf/utfMain.h>
#include <utf/private/prvUtfExtras.h>

#include <trafficEngine/tgfTrafficEngine.h>
#include <trafficEngine/tgfTrafficGenerator.h>
#include <trafficEngine/tgfTrafficTable.h>

#include <common/tgfCommon.h>
#include <common/tgfDiagGen.h>

#ifdef CHX_FAMILY
    #include <cpss/dxCh/dxChxGen/diag/cpssDxChDiagDescriptor.h>
#endif /* CHX_FAMILY */

#include <cpss/common/private/globalShared/prvCpssGlobalDb.h>
#include <cpss/common/private/globalShared/prvCpssGlobalDbInterface.h>

#ifdef CHX_FAMILY

/* Functions to convert PRV_TGF_DIAG_DESCRIPTOR_ to CPSS_DXCH_DIAG_DESCRIPTOR_ */

static void cnvDIAG_DESCRIPTOR_TYPE_ENT_tgf2dxch
(
    IN  PRV_TGF_DIAG_DESCRIPTOR_TYPE_ENT   tgfDiagDescriptorType,
    OUT CPSS_DXCH_DIAG_DESCRIPTOR_TYPE_ENT *dxchDiagDescriptorType
)
{
    switch (tgfDiagDescriptorType)
    {
        case PRV_TGF_DIAG_DESCRIPTOR_WR_DMA_TO_TTI_E:
            *dxchDiagDescriptorType = CPSS_DXCH_DIAG_DESCRIPTOR_WR_DMA_TO_TTI_E;
            break;
        case PRV_TGF_DIAG_DESCRIPTOR_TTI_TO_PCL_E:
            *dxchDiagDescriptorType = CPSS_DXCH_DIAG_DESCRIPTOR_TTI_TO_PCL_E;
            break;
        case PRV_TGF_DIAG_DESCRIPTOR_PCL_TO_BRIDGE_E:
            *dxchDiagDescriptorType = CPSS_DXCH_DIAG_DESCRIPTOR_PCL_TO_BRIDGE_E;
            break;
        case PRV_TGF_DIAG_DESCRIPTOR_BRIDGE_TO_ROUTER_E:
            *dxchDiagDescriptorType = CPSS_DXCH_DIAG_DESCRIPTOR_BRIDGE_TO_ROUTER_E;
            break;
        case PRV_TGF_DIAG_DESCRIPTOR_INGRESS_POLICER0_TO_INGRESS_POLICER1_E:
            *dxchDiagDescriptorType = CPSS_DXCH_DIAG_DESCRIPTOR_INGRESS_POLICER0_TO_INGRESS_POLICER1_E;
            break;
        case PRV_TGF_DIAG_DESCRIPTOR_INGRESS_POLICER1_TO_PRE_EGRESS_E:
            *dxchDiagDescriptorType = CPSS_DXCH_DIAG_DESCRIPTOR_INGRESS_POLICER1_TO_PRE_EGRESS_E;
            break;
        case PRV_TGF_DIAG_DESCRIPTOR_PRE_EGRESS_TO_TXQ_E:
            *dxchDiagDescriptorType = CPSS_DXCH_DIAG_DESCRIPTOR_PRE_EGRESS_TO_TXQ_E;
            break;
        case PRV_TGF_DIAG_DESCRIPTOR_TXQ_TO_HEADER_ALTERATION_E:
            *dxchDiagDescriptorType = CPSS_DXCH_DIAG_DESCRIPTOR_TXQ_TO_HEADER_ALTERATION_E;
            break;
        case PRV_TGF_DIAG_DESCRIPTOR_EGRESS_POLICER_TO_EGRESS_PCL_E:
            *dxchDiagDescriptorType = CPSS_DXCH_DIAG_DESCRIPTOR_EGRESS_POLICER_TO_EGRESS_PCL_E;
            break;
        case PRV_TGF_DIAG_DESCRIPTOR_ROUTER_TO_INGRESS_POLICER_E:
            *dxchDiagDescriptorType = CPSS_DXCH_DIAG_DESCRIPTOR_ROUTER_TO_INGRESS_POLICER_E;
            break;
        case PRV_TGF_DIAG_DESCRIPTOR_LAST_E:
            *dxchDiagDescriptorType = CPSS_DXCH_DIAG_DESCRIPTOR_LAST_E;
            break;
        default:
            *dxchDiagDescriptorType = CPSS_DXCH_DIAG_DESCRIPTOR_LAST_E;
            break;
    }
}

#define PRV_INVALID_DESCRIPTOR_FIELD_ID_CNS 0xFFFFFFFF

static GT_U32 cnvDIAG_DESCRIPTOR_ID_dxch2tgf
(
    IN GT_U32 dxChDescriptorId
)
{
    switch (dxChDescriptorId)
    {
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_APPSPECIFICCPUCODE_E:                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_APPSPECIFICCPUCODE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ARPPTR_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ARPPTR_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_BADIPXBC_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_BADIPXBC_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_BANK_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_BANK_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_BILLINGEN_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_BILLINGEN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_BUFREUSE_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_BUFREUSE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_BYPASSBRIDGE_DUP_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_BYPASSBRIDGE_DUP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_BYPASSBRIDGE_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_BYPASSBRIDGE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_BYPASSINGRESSPIPE_E:                               return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_BYPASSINGRESSPIPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_BYTECOUNT_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_BYTECOUNT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CCFC_E:                                            return PRV_INVALID_DESCRIPTOR_FIELD_ID_CNS;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CFI0_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CFI0_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CFI1_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CFI1_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CFI_E:                                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CFI_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CFMPKT_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CFMPKT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CONGESTEDPORTNUMBER_E:                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CONGESTEDPORTNUMBER_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CONGESTEDQUEUENUMBER_E:                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CONGESTEDQUEUENUMBER_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CONTROLTC_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CONTROLTC_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_COPYTTL_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_COPYTTL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CPIDMATCH_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CPIDMATCH_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CPU2CPUMIRROR_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CPU2CPUMIRROR_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CPUCODE_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CPUCODE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CPUMAILTONEIGBORCPU_E:                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CPUMAILTONEIGBORCPU_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CPUTRGDEV_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CPUTRGDEV_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DECTTL_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DECTTL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DIP_0_31_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DIP_0_31_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DIP_32_63_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DIP_32_63_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DIP_64_95_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DIP_64_95_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DIP_96_127_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DIP_96_127_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DIP_E:                                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DIP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DISABLEIPCL1_FOR_ROUTEDPACKETS_E:                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DISABLEIPCL1_FOR_ROUTEDPACKETS_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DOROUTEHA_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DOROUTEHA_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DOROUTE_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DOROUTE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DP_E:                                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DROPCODE_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DROPCODE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DROPONSOURCE_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DROPONSOURCE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DROPPKT_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DROPPKT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_DSCP_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_DSCP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_EGRESSFILTEREN_E:                                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_EGRESSFILTEREN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_EGRESSFILTERREGISTERED_E:                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_EGRESSFILTERREGISTERED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_EGRESSTRGDEV_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_EGRESSTRGDEV_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_EGRESSTRGPORT_DUP_2_0_E:                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_EGRESSTRGPORT_DUP_2_0_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_EGRESSTRGPORT_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_EGRESSTRGPORT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLEBRIDGELOGFLOW_E:                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLEBRIDGELOGFLOW_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLEBRIDGE_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLEBRIDGE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLEDSATAGMANIPULATION_E:                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLEDSATAGMANIPULATION_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLEROUTERLOGFLOW_E:                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLEROUTERLOGFLOW_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLESOURCELOCALFILTERING_E:                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLESOURCELOCALFILTERING_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLE_IPCL0_LOOKUP_E:                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLE_IPCL0_LOOKUP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLE_POLICY_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ENABLE_POLICY_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ETHERTYPE_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ETHERTYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_EXCLUDEDDEVISLOCAL_E:                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_EXCLUDEDDEVISLOCAL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_EXCLUDEDPORT_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_EXCLUDEDPORT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_EXCLUDEDTRUNK_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_EXCLUDEDTRUNK_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_EXCLUDEISTRUNK_E:                                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_EXCLUDEISTRUNK_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_EXP_E:                                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_EXP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_FIRSTBUFFER_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_FIRSTBUFFER_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_FLOODMLLPOINTER_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_FLOODMLLPOINTER_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_FLOWID_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_FLOWID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_FLOWSUBTEMPLATE_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_FLOWSUBTEMPLATE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_FORCE_IPCL1_CONFIGURATIONS_E:                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_FORCE_IPCL1_CONFIGURATIONS_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_FRAGMENTED_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_FRAGMENTED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_FROMCPUDP_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_FROMCPUDP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_FROMCPUTC_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_FROMCPUTC_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_HASHMASKINDEX_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_HASHMASKINDEX_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IGMPNONQUERY_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IGMPNONQUERY_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IGMPQUERY_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IGMPQUERY_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_INLIF_MODE_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_INLIF_MODE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_INNERISLLCNONSNAP_E:                               return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_INNERISLLCNONSNAP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_INNERL3OFFSET1_DUP_E:                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_INNERL3OFFSET1_DUP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_INNERL3OFFSET_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_INNERL3OFFSET_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_INNERPKTTYPE_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_INNERPKTTYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPCL_PROFILE_INDEX_E:                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPCL_PROFILE_INDEX_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPLEGAL_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPLEGAL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPMGMNTEN_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPMGMNTEN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPMODIFYDSCP_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPMODIFYDSCP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPMODIFYUP_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPMODIFYUP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPM_E:                                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPM_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPQOSPROFILE_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPQOSPROFILE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV4MULTICASTEN_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV4MULTICASTEN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV4OPTIONFIELD_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV4OPTIONFIELD_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV4RIPV1_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV4RIPV1_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV4UNICASTEN_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV4UNICASTEN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV4_BAD_GRE_HEADER_E:                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV4_BAD_GRE_HEADER_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV4_DF_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV4_DF_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6FLOWLABEL_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6FLOWLABEL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6HBHEXT_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6HBHEXT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6HBHOPTIONS_E:                                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6HBHOPTIONS_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6ICMPTYPE_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6ICMPTYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6ICMP_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6ICMP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6MULTICASTEN_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6MULTICASTEN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6NONHBHEXT_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6NONHBHEXT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6SITEID_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6SITEID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6UNICASTEN_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6UNICASTEN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6_EH_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPV6_EH_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPXHEADERTOTALLENGTH_E:                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPXHEADERTOTALLENGTH_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPXMACMCMISMATCH_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPXMACMCMISMATCH_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPXMCLINKLOCALPROT_E:                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPXMCLINKLOCALPROT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IPXPROTOCOL_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IPXPROTOCOL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IP_FRAGMENTED_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IP_FRAGMENTED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_IP_HEADER_INFO_E:                                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_IP_HEADER_INFO_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISARPREPLY_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISARPREPLY_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISARP_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISARP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISBC_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISBC_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISIPV4_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISIPV4_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISIPV4_FORKEY_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISIPV4_FORKEY_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISIPV6LINKLOCAL_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISIPV6LINKLOCAL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISIPV6MLD_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISIPV6MLD_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISIPV6_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISIPV6_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISIPV6_FORKEY_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISIPV6_FORKEY_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISIP_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISIP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISIP_FORKEY_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISIP_FORKEY_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISMPLS_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISMPLS_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISND_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISND_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISPTP_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISPTP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ISSYN_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ISSYN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_L2ECHO_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_L2ECHO_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_L2ENCAPSULATION_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_L2ENCAPSULATION_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_L2_VALID_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_L2_VALID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_L3OFFSETINVALID_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_L3OFFSETINVALID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_L3TOTALOFFSET_OR_INNERHEADERTOTALOFFSET_E:         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_L3TOTALOFFSET_OR_INNERHEADERTOTALOFFSET_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_L4BYTE13_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_L4BYTE13_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_L4BYTES3_0_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_L4BYTES3_0_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_L4OFFSETINVALID_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_L4OFFSETINVALID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_L4VALID_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_L4VALID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_LLT_E:                                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_LLT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_LOCALDEVICESRCTRUNKID_E:                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_LOCALDEVICESRCTRUNKID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_LOCALDEVSRCPORT_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_LOCALDEVSRCPORT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_LOOKUP0_PCL_MODE_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_LOOKUP0_PCL_MODE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_LOOKUP0_USEINDEXFROMDESC_E:                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_LOOKUP0_USEINDEXFROMDESC_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_LOOKUP1_PCL_MODE_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_LOOKUP1_PCL_MODE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_LOOKUP1_USEINDEXFROMDESC_E:                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_LOOKUP1_USEINDEXFROMDESC_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_LOOKUP2_PCL_MODE_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_LOOKUP2_PCL_MODE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_LOOKUP2_USEINDEXFROMDESC_E:                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_LOOKUP2_USEINDEXFROMDESC_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MAC2ME_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MAC2ME_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MACDATYPE_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MACDATYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MACDA_0_31_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MACDA_0_31_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MACDA_32_48_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MACDA_32_48_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MACSAARPSAMISMATCH_E:                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MACSAARPSAMISMATCH_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MACSA_0_31_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MACSA_0_31_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MACSA_32_48_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MACSA_32_48_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MAILBOXTONEIGHBORCPU_E:                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MAILBOXTONEIGHBORCPU_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MARVELLTAGGEDEXTENDED_E:                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MARVELLTAGGEDEXTENDED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MARVELLTAGGED_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MARVELLTAGGED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MCRPFFAIL_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MCRPFFAIL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MDB_E:                                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MDB_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_METERINGEN_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_METERINGEN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MLLEN_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MLLEN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MLLLAST_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MLLLAST_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MLLPTR_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MLLPTR_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MLL_E:                                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MLL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MLL_POINTER_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MLL_POINTER_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MODIFYDP_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MODIFYDP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MODIFYDSCP_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MODIFYDSCP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MODIFYDSCP_EXP_E:                                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MODIFYDSCP_EXP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MODIFYEXP_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MODIFYEXP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MODIFYTC_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MODIFYTC_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MODIFYUP_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MODIFYUP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MPLSCMD_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MPLSCMD_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MPLSLABEL_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MPLSLABEL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MPLS_LABEL0_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MPLS_LABEL0_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MPLS_LABEL1_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MPLS_LABEL1_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MPLS_LABEL2_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MPLS_LABEL2_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MPLS_OUTEREXP_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MPLS_OUTEREXP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MPLS_OUTERLABEL_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MPLS_OUTERLABEL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_MPLS_OUTERS_BIT_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_MPLS_OUTERS_BIT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_NESTEDVLANACCESSPORT_E:                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_NESTEDVLANACCESSPORT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_NHEMCRPFFAILCMD_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_NHEMCRPFFAILCMD_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_NUM_OF_INGRESSTAGS_E:                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_NUM_OF_INGRESSTAGS_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ORIGISTRUNK_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ORIGISTRUNK_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ORIGQCNPRIO_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ORIGQCNPRIO_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ORIGSRCDEV_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ORIGSRCDEV_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ORIGSRCPORT_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ORIGSRCPORT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ORIGSRCTRUNK_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ORIGSRCTRUNK_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ORIGVID_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ORIGVID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_OUTERISLLCNONSNAP_E:                               return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_OUTERISLLCNONSNAP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_OUTERL3TOTALOFFSET_E:                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_OUTERL3TOTALOFFSET_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_OUTERSRCTAG_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_OUTERSRCTAG_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_OUTGOINGMTAGCMD_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_OUTGOINGMTAGCMD_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_OUTLIF_TYPE_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_OUTLIF_TYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETCMD_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETCMD_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETISCNTAGGED_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETISCNTAGGED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETISLLCSNAP_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETISLLCSNAP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETREJECT_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETREJECT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETTOS_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETTOS_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETTYPE_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETTYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETUP_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PACKETUP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PCL1_IPV4_KEY_TYPE_E:                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PCL1_IPV4_KEY_TYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PCL1_IPV6_KEY_TYPE_E:                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PCL1_IPV6_KEY_TYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PCL1_LOOKUP_MODE_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PCL1_LOOKUP_MODE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PCL1_LOOKUP_TYPE_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PCL1_LOOKUP_TYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PCL1_NONIP_KEY_TYPE_E:                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PCL1_NONIP_KEY_TYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PCL1_PCL_ID_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PCL1_PCL_ID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PCLASSIGNEDSSTID_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PCLASSIGNEDSSTID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PKTCMD_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PKTCMD_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PKTHASH_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PKTHASH_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PKTISLOOPED_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PKTISLOOPED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PKTTYPEFORKEY_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PKTTYPEFORKEY_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_POLICEREN_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_POLICEREN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_POLICERPTR_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_POLICERPTR_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_POLICYBASEDROUTED_E:                               return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_POLICYBASEDROUTED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_POLICYRTTINDEX_E:                                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_POLICYRTTINDEX_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PORTSPEEDINDEX_OR_ORIGQCNPRIO_E:                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PORTSPEEDINDEX_OR_ORIGQCNPRIO_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PRIOTAGGED_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PRIOTAGGED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PSEUDOWIREID_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PSEUDOWIREID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_PTPTRIGGERTYPE_E:                                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_PTPTRIGGERTYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_QCNPACKET_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_QCNPACKET_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_QCNQDELTA_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_QCNQDELTA_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_QCNQFB_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_QCNQFB_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_QCNQOFFSET_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_QCNQOFFSET_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_QCNQSATURATED_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_QCNQSATURATED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_QCN_E:                                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_QCN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_QINQ_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_QINQ_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_QOSPROFILEPRECEDENCE_E:                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_QOSPROFILEPRECEDENCE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_QOSPROFILE_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_QOSPROFILE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RECALCCRC_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RECALCCRC_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_REDIRECTCMD_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_REDIRECTCMD_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RESERVED_0_31_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RESERVED_0_31_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RESERVED_32_63_E:                                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RESERVED_32_63_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RESERVED_64_65_E:                                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RESERVED_64_65_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RESERVED_64_90_E:                                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RESERVED_64_90_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RESERVED_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RESERVED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGARPINDEX_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGARPINDEX_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGBYPASSTTLANDOPTIONCHECKS_E:                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGBYPASSTTLANDOPTIONCHECKS_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGDECTTL_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGDECTTL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGEGRESSINTERFACE_E:                               return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGEGRESSINTERFACE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGFWDCMD_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGFWDCMD_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGICMP_REDIRECTCHECKEN_E:                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGICMP_REDIRECTCHECKEN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGMIRRORTOINGRESSANALYZERPORT_E:                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGMIRRORTOINGRESSANALYZERPORT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGMODIFYDSCP_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGMODIFYDSCP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGMODIFYUP_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGMODIFYUP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGNHEVID_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGNHEVID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGPCEROUTEENTRY_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGPCEROUTEENTRY_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGQOSPROFILE_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGQOSPROFILE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGQOS_PRECEDENCE_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGQOS_PRECEDENCE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RGQOS_PROFILEMARKINGEN_E:                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RGQOS_PROFILEMARKINGEN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ROUTED_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ROUTED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_ROUTETOENTRY_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_ROUTETOENTRY_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RSRVDCOPY_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RSRVDCOPY_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_RXSNIFF_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_RXSNIFF_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SIP_0_31_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SIP_0_31_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SIP_32_63_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SIP_32_63_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SIP_64_95_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SIP_64_95_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SIP_96_127_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SIP_96_127_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SNIFFTRGDEV_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SNIFFTRGDEV_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SNIFFTRGPORT_E:                                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SNIFFTRGPORT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SNIFFVIDX_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SNIFFVIDX_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SOLICITATIONMULTICASTMESSAGE_E:                    return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SOLICITATIONMULTICASTMESSAGE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SRCDEVISOWN_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SRCDEVISOWN_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SRCDEV_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SRCDEV_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SRCISLOOPBACK_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SRCISLOOPBACK_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SRCPORT_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SRCPORT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SRCTAGGED_DUP_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SRCTAGGED_DUP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SRCTAGGED_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SRCTAGGED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SRCTCPUDPPORTIS0_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SRCTCPUDPPORTIS0_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SRCTRG_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SRCTRG_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SRC_IS_PE_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SRC_IS_PE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SST_ID_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SST_ID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SYNWITHDATA_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SYNWITHDATA_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TARGETISTRUNK_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TARGETISTRUNK_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TCPFLAGS_E:                                        return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TCPFLAGS_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TCP_UDPDESTPORT_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TCP_UDPDESTPORT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TCP_UDP_SRCPORT_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TCP_UDP_SRCPORT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TC_E:                                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TC_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TRGDEVICE_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TRGDEVICE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TRGDEVICE_VIRTUALSRCDEV_E:                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TRGDEVICE_VIRTUALSRCDEV_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TRGDEV_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TRGDEV_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TRGISTRUNK_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TRGISTRUNK_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TRGPORT_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TRGPORT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TRGPORT_VIRTUALSRCPORT_E:                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TRGPORT_VIRTUALSRCPORT_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TRGTAGGED_DUP_E:                                   return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TRGTAGGED_DUP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TRGTAGGED_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TRGTAGGED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TRGTRUNKID_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TRGTRUNKID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TRUNCATED_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TRUNCATED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TS_PASSENGER_TYPE_E:                               return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TS_PASSENGER_TYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TTL_E:                                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TTL_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TUNNELPTR_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TUNNELPTR_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TUNNELSTART_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TUNNELSTART_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TUNNELTERMINATED_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TUNNELTERMINATED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TUNNELTYPE_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TUNNELTYPE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_TXSAMPLED_E:                                       return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_TXSAMPLED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB0_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB0_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB10_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB10_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB11_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB11_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB12_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB12_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB13_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB13_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB14_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB14_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB15_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB15_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB16_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB16_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB17_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB17_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB18_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB18_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB19_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB19_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB1_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB1_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB20_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB20_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB21_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB21_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB22_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB22_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB2_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB2_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB3_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB3_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB4_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB4_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB5_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB5_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB6_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB6_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB7_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB7_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB8_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB8_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB9_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB9_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UDB_BYTESVALID_E:                                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UDB_BYTESVALID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UP1_E:                                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UP1_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_UP_E:                                              return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_UP_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_USEINTERFACEBASEDINDEX_E:                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_USEINTERFACEBASEDINDEX_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_USEVIDX_E:                                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_USEVIDX_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_VID1_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_VID1_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_VIDMODIFIED_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_VIDMODIFIED_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_VIDX_E:                                            return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_VIDX_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_VID_E:                                             return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_VID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_VID_OR_INLIF_ID_E:                                 return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_VID_OR_INLIF_ID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_VID_PRECEDENCE_E:                                  return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_VID_PRECEDENCE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_VIRTUALINTERFACE_E:                                return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_VIRTUALINTERFACE_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_VLAN1_EXIST_E:                                     return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_VLAN1_EXIST_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_VRF_ID_E:                                          return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_VRF_ID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_VR_ID_E:                                           return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_VR_ID_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_SRCOWNDEV0_E:                                      return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_SRCOWNDEV0_E;
        case CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_CONGESTEDQUEUEFILLLEVEL_E:                         return PRV_TGF_DIAG_DESCRIPTOR_FIELD_TYPE_CONGESTEDQUEUEFILLLEVEL_E;
        default: break;
    };

    return PRV_INVALID_DESCRIPTOR_FIELD_ID_CNS;
}

/* Function to convert CPSS_DXCH_DIAG_DESCRIPTOR_STC to PRV_TGF_DIAG_DESCRIPTOR_STC*/
static void cnvDIAG_DESCRIPTOR_STC_dxch2tgf
(
    IN CPSS_DXCH_DIAG_DESCRIPTOR_STC     *dxchDiagDescriptorPtr,
    OUT  PRV_TGF_DIAG_DESCRIPTOR_STC     *tgfDiagDescriptorPtr
)
{
    GT_U32 dxChId, tgfId;

    cpssOsMemSet(tgfDiagDescriptorPtr, 0, sizeof(PRV_TGF_DIAG_DESCRIPTOR_STC));

    for(dxChId = 0; (dxChId < CPSS_DXCH_DIAG_DESCRIPTOR_FIELD_TYPE_LAST_E); dxChId++)
    {
        tgfId = cnvDIAG_DESCRIPTOR_ID_dxch2tgf(dxChId);
        if (tgfId  == PRV_INVALID_DESCRIPTOR_FIELD_ID_CNS)
            continue;
        tgfDiagDescriptorPtr->fieldValue[tgfId] = dxchDiagDescriptorPtr->fieldValue[dxChId];
        tgfDiagDescriptorPtr->fieldValueValid[tgfId] = dxchDiagDescriptorPtr->fieldValueValid[dxChId];
    }
}

#endif /* CHX_FAMILY */

/******************************************************************************\
 *                       CPSS generic API section                             *
\******************************************************************************/


/**
* @internal prvTgfDiagDescriptorGet function
* @endinternal
*
* @brief   Get the descriptor information.
*
* @note   APPLICABLE DEVICES:      xCat2, Lion, Lion2.
* @note   NOT APPLICABLE DEVICES:  DxCh1; DxCh1_Diamond; DxCh2; DxCh3; xCat; xCat3; AC5.
*
* @param[in] devNum                   - device number
* @param[in] descriptorType           - descriptor type
*
* @param[out] descriptorPtr            - pointer to descriptor information.
*
* @retval GT_OK                    - on success
* @retval GT_BAD_PARAM             - bad device number, portGroupsBmp,
*                                       descriptorType.
* @retval GT_BAD_PTR               - on NULL pointer value.
* @retval GT_FAIL                  - on error
* @retval GT_NOT_APPLICABLE_DEVICE - on not applicable device
*/
GT_STATUS prvTgfDiagDescriptorGet
(
    IN  GT_U8                              devNum,
    IN  PRV_TGF_DIAG_DESCRIPTOR_TYPE_ENT   descriptorType,
    OUT PRV_TGF_DIAG_DESCRIPTOR_STC        *descriptorPtr
)
{
#ifdef CHX_FAMILY
CPSS_DXCH_DIAG_DESCRIPTOR_TYPE_ENT dxchDescriptorType;
CPSS_DXCH_DIAG_DESCRIPTOR_STC *dxchDescriptorPtr;
GT_STATUS rc;

    /* call device specific API */
    cnvDIAG_DESCRIPTOR_TYPE_ENT_tgf2dxch(descriptorType, &dxchDescriptorType);

    dxchDescriptorPtr = (CPSS_DXCH_DIAG_DESCRIPTOR_STC*)cpssOsMalloc(
        sizeof(CPSS_DXCH_DIAG_DESCRIPTOR_STC));
    rc = cpssDxChDiagDescriptorGet(devNum, dxchDescriptorType, dxchDescriptorPtr);
    if (GT_OK != rc)
    {
        PRV_UTF_LOG1_MAC("[TGF]: cpssDxChDiagDescriptorGet FAILED, rc = [%d]", rc);
    }
    cnvDIAG_DESCRIPTOR_STC_dxch2tgf(dxchDescriptorPtr, descriptorPtr);
    cpssOsFree(dxchDescriptorPtr);
    return rc;

#endif /* CHX_FAMILY */

}

/**
* @internal prvTgfDiagDescriptorPortGroupGet function
* @endinternal
*
* @brief   Get the descriptor information.
*
* @note   APPLICABLE DEVICES:      xCat2, Lion, Lion2.
* @note   NOT APPLICABLE DEVICES:  DxCh1; DxCh1_Diamond; DxCh2; DxCh3; xCat; xCat3; AC5.
*
* @param[in] devNum                   - device number
* @param[in] portGroupsBmp            - bitmap of Port Groups.
*                                      NOTEs:
*                                      1. for non multi-port groups device this parameter is IGNORED.
*                                      2. for multi-port groups device :
*                                      bitmap must be set with at least one bit representing
*                                      valid port group(s). If a bit of non valid port group
*                                      is set then function returns GT_BAD_PARAM.
*                                      Value CPSS_PORT_GROUP_UNAWARE_MODE_CNS is supported.
* @param[in] descriptorType           - descriptor type
*
* @param[out] descriptorPtr            - pointer to descriptor information.
*
* @retval GT_OK                    - on success
* @retval GT_BAD_PARAM             - bad device number, portGroupsBmp,
*                                       descriptorType.
* @retval GT_BAD_PTR               - on NULL pointer value.
* @retval GT_FAIL                  - on error
* @retval GT_NOT_APPLICABLE_DEVICE - on not applicable device
*/
GT_STATUS prvTgfDiagDescriptorPortGroupGet
(
    IN  GT_U8                                devNum,
    IN  GT_PORT_GROUPS_BMP                   portGroupsBmp,
    IN  PRV_TGF_DIAG_DESCRIPTOR_TYPE_ENT     descriptorType,
    OUT PRV_TGF_DIAG_DESCRIPTOR_STC          *descriptorPtr
)
{
#ifdef CHX_FAMILY
CPSS_DXCH_DIAG_DESCRIPTOR_TYPE_ENT dxchDescriptorType;
CPSS_DXCH_DIAG_DESCRIPTOR_STC *dxchDescriptorPtr;
GT_STATUS rc;

    /* call device specific API */
    cnvDIAG_DESCRIPTOR_TYPE_ENT_tgf2dxch(descriptorType, &dxchDescriptorType);

    dxchDescriptorPtr = (CPSS_DXCH_DIAG_DESCRIPTOR_STC*)cpssOsMalloc(
        sizeof(CPSS_DXCH_DIAG_DESCRIPTOR_STC));
    rc = cpssDxChDiagDescriptorPortGroupGet(devNum, portGroupsBmp,
                                        dxchDescriptorType, dxchDescriptorPtr);
    if (GT_OK != rc)
    {
        PRV_UTF_LOG1_MAC("[TGF]: cpssDxChDiagDescriptorGet FAILED, rc = [%d]", rc);
    }
    cnvDIAG_DESCRIPTOR_STC_dxch2tgf(dxchDescriptorPtr, descriptorPtr);
    cpssOsFree(dxchDescriptorPtr);
    return rc;

#endif /* CHX_FAMILY */

}
/**
* @internal prvTgfDiagDescriptorRawGet function
* @endinternal
*
* @brief   Get the descriptor information in raw (HW) format
*
* @note   APPLICABLE DEVICES:      xCat2, Lion, Lion2.
* @note   NOT APPLICABLE DEVICES:  DxCh1; DxCh1_Diamond; DxCh2; DxCh3; xCat; xCat3; AC5.
*
* @param[in] devNum                   - device number
* @param[in] descriptorType           - descriptor type
* @param[in,out] rawDataLengthPtr         - pointer to descriptor raw (HW) data length (bytes).
* @param[in,out] rawDataLengthPtr         - pointer to actual descriptor raw (HW) data length (bytes).
*
* @param[out] rawDataPtr               - pointer to descriptor data in raw (HW) format.
*
* @retval GT_OK                    - on success
* @retval GT_BAD_PARAM             - bad device number, portGroupsBmp,
*                                       descriptorType.
* @retval GT_BAD_SIZE              - on insufficient descriptor raw (HW) data size.
* @retval GT_BAD_PTR               - on NULL pointer value.
* @retval GT_FAIL                  - on error
* @retval GT_NOT_APPLICABLE_DEVICE - on not applicable device
*/
GT_STATUS prvTgfDiagDescriptorRawGet
(
    IN GT_U8                                devNum,
    IN PRV_TGF_DIAG_DESCRIPTOR_TYPE_ENT     descriptorType,
    INOUT GT_U32                            *rawDataLengthPtr,
    OUT GT_U32                              *rawDataPtr
)
{
#ifdef CHX_FAMILY
    CPSS_DXCH_DIAG_DESCRIPTOR_TYPE_ENT dxchDescriptorType;
    cnvDIAG_DESCRIPTOR_TYPE_ENT_tgf2dxch(descriptorType, &dxchDescriptorType);
    /* call device specific API */
    return cpssDxChDiagDescriptorRawGet(devNum, dxchDescriptorType,
                                        rawDataLengthPtr, rawDataPtr);
#endif /* CHX_FAMILY */

}

/**
* @internal prvTgfDiagDescriptorPortGroupRawGet function
* @endinternal
*
* @brief   Get the descriptor information in raw (HW) format
*
* @note   APPLICABLE DEVICES:      xCat2, Lion, Lion2.
* @note   NOT APPLICABLE DEVICES:  DxCh1; DxCh1_Diamond; DxCh2; DxCh3; xCat; xCat3; AC5.
*
* @param[in] devNum                   - device number
* @param[in] portGroupsBmp            - bitmap of Port Groups.
*                                      NOTEs:
*                                      1. for non multi-port groups device this parameter is IGNORED.
*                                      2. for multi-port groups device :
*                                      bitmap must be set with at least one bit representing
*                                      valid port group(s). If a bit of non valid port group
*                                      is set then function returns GT_BAD_PARAM.
*                                      Value CPSS_PORT_GROUP_UNAWARE_MODE_CNS is supported.
* @param[in] descriptorType           - descriptor type
* @param[in,out] rawDataLengthPtr         - pointer to descriptor raw (HW) data length (bytes).
* @param[in,out] rawDataLengthPtr         - pointer to actual descriptor raw (HW) data length (bytes).
*
* @param[out] rawDataPtr               - pointer to descriptor data in raw (HW) format.
*
* @retval GT_OK                    - on success
* @retval GT_BAD_PARAM             - bad device number, portGroupsBmp,
*                                       descriptorType.
* @retval GT_BAD_SIZE              - on insufficient descriptor raw (HW) data size.
* @retval GT_BAD_PTR               - on NULL pointer value.
* @retval GT_FAIL                  - on error
* @retval GT_NOT_APPLICABLE_DEVICE - on not applicable device
*/
GT_STATUS prvTgfDiagDescriptorPortGroupRawGet
(
    IN GT_U8                                devNum,
    IN  GT_PORT_GROUPS_BMP                  portGroupsBmp,
    IN PRV_TGF_DIAG_DESCRIPTOR_TYPE_ENT     descriptorType,
    INOUT GT_U32                            *rawDataLengthPtr,
    OUT GT_U32                              *rawDataPtr
)
{
#ifdef CHX_FAMILY
    CPSS_DXCH_DIAG_DESCRIPTOR_TYPE_ENT dxchDescriptorType;
    cnvDIAG_DESCRIPTOR_TYPE_ENT_tgf2dxch(descriptorType, &dxchDescriptorType);
    /* call device specific API */
    return cpssDxChDiagDescriptorPortGroupRawGet(devNum, portGroupsBmp,
                                                 dxchDescriptorType,
                                        rawDataLengthPtr, rawDataPtr);
#endif /* CHX_FAMILY */

}

/**
* @internal prvTgfDiagDescriptorRawSizeGet function
* @endinternal
*
* @brief   Get the descriptor raw (HW) size.
*
* @note   APPLICABLE DEVICES:      xCat2, Lion, Lion2.
* @note   NOT APPLICABLE DEVICES:  DxCh1; DxCh1_Diamond; DxCh2; DxCh3; xCat; xCat3; AC5.
*
* @param[in] devNum                   - device number
* @param[in] descriptorType           - descriptor type
*
* @param[out] rawDataLengthPtr         - pointer to actual descriptor raw (HW) data length (bytes).
*
* @retval GT_OK                    - on success
* @retval GT_BAD_PARAM             - bad device number, portGroupsBmp,
*                                       descriptorType.
* @retval GT_BAD_PTR               - on NULL pointer value.
* @retval GT_FAIL                  - on error
* @retval GT_NOT_APPLICABLE_DEVICE - on not applicable device
*/
GT_STATUS prvTgfDiagDescriptorRawSizeGet
(
    IN  GT_U8                               devNum,
    IN  PRV_TGF_DIAG_DESCRIPTOR_TYPE_ENT    descriptorType,
    OUT GT_U32                              *rawDataLengthPtr
)
{
#ifdef CHX_FAMILY
    CPSS_DXCH_DIAG_DESCRIPTOR_TYPE_ENT dxchDescriptorType;
    cnvDIAG_DESCRIPTOR_TYPE_ENT_tgf2dxch(descriptorType, &dxchDescriptorType);
    /* call device specific API */
    return cpssDxChDiagDescriptorRawSizeGet(devNum, dxchDescriptorType,
                                            rawDataLengthPtr);
#endif /* CHX_FAMILY */

}

/**
* @internal prvTgfDiagPortGroupRegsDump function
* @endinternal
*
* @brief   Prints the device register addresses and values for the specific port
*         group in the PP.
*
* @note   APPLICABLE DEVICES:      DxCh1; DxCh1_Diamond; DxCh2; DxCh3; xCat; xCat3; AC5; Lion; xCat2; Lion2; Bobcat2; Caelum; Aldrin; AC3X; Bobcat3; Aldrin2; Falcon; AC5P; AC5X; Harrier; Ironman.
* @note   NOT APPLICABLE DEVICES:  None.
*
* @param[in] devNum                   - The device number
* @param[in] portGroupsBmp            - bitmap of Port Groups.
*                                      NOTEs:
*                                      1. for non multi-port groups device this parameter is IGNORED.
*                                      2. for multi-port groups device :
*                                      (APPLICABLE DEVICES Lion; Lion2; Bobcat3; Aldrin2; Falcon; AC5P; AC5X; Harrier; Ironman)
*                                      bitmap must be set with at least one bit representing
*                                      valid port group(s). If a bit of non valid port group
*                                      is set then function returns GT_BAD_PARAM.
*                                      value CPSS_PORT_GROUP_UNAWARE_MODE_CNS is supported,
*                                      in this case read is done from first active port group.
* @param[in] startRegAddr             - The first register address to dump
* @param[in] endRegAddr             - The upper bound of register address to dump
* @param[in] printWordsInLine       - width of listing in words
* @param[in] maxDataWithoutAddress  - maximal number of Data words between Address words
* @param[in] addressFromNewLine     - 1 - print each address from new line
*                                   - 0 - print addresses at the line continuation.
*
* @retval GT_OK                    - on success
* @retval GT_FAIL                  - on error
* @retval GT_NOT_APPLICABLE_DEVICE - on not applicable device
*
*/
GT_STATUS prvTgfDiagPortGroupRegsDump
(
    IN    GT_U8                 devNum,
    IN    GT_PORT_GROUPS_BMP    portGroupsBmp,
    IN    GT_U32                startRegAddr,
    IN    GT_U32                endRegAddr,
    IN    GT_U32                printWordsInLine,
    IN    GT_U32                maxDataWithoutAddress,
    IN    GT_U32                addressFromNewLine
)
{
#ifdef CHX_FAMILY
    GT_U32                *regAddrArrPtr;
    GT_U32                *regDataArrPtr;
    GT_STATUS             rc;
    GT_U32                maxRegsNum;
    GT_U32                retrievedRegsNum;
    GT_U32                saveAddr;
    GT_U32                saveData;
    GT_U32                ndx;
    GT_U32                sortStep;
    GT_U32                sortBreak;
    GT_U32                expectedRegAddr;
    GT_U32                printedWordsInLine;
    GT_U32                printedWordsInAddr;
    GT_U32                lastData;
    GT_U32                dataDuplicates;

    /* get amount of regs */
    rc = cpssDxChDiagPortGroupRegsNumGet(
        devNum, portGroupsBmp, &maxRegsNum);
    if (rc != GT_OK)
    {
        cpssOsPrintf("\ncpssDxChDiagRegsNumGet failed rc = %d\n",rc);
        return rc;
    }

    /* allocate arrays for regs */
    regAddrArrPtr = (GT_U32*)cpssOsMalloc(maxRegsNum *sizeof(GT_U32));
    if (regAddrArrPtr == NULL)
    {
        cpssOsPrintf("\nMemory allocation error\n");
        return GT_OUT_OF_CPU_MEM;
    }
    regDataArrPtr = (GT_U32*)cpssOsMalloc(maxRegsNum *sizeof(GT_U32));
    if (regDataArrPtr == NULL)
    {
        cpssOsFree(regAddrArrPtr);
        cpssOsPrintf("\nMemory allocation error\n");
        return GT_OUT_OF_CPU_MEM;
    }
    /* retrieve regs addresses and values */
    retrievedRegsNum = maxRegsNum;
    rc = cpssDxChDiagPortGroupRegsDump(
        devNum, portGroupsBmp, &retrievedRegsNum, startRegAddr,
        regAddrArrPtr, regDataArrPtr);
    if (rc != GT_OK)
    {
        cpssOsFree(regAddrArrPtr);
        cpssOsFree(regDataArrPtr);
        cpssOsPrintf(
            "\ncpssDxChDiagPortGroupRegsDump failed, rc = %d\n", rc);
        return rc;
    }

    /* bubble sorting of arrays */
    for (sortStep = (retrievedRegsNum - 1); (sortStep > 0); sortStep--)
    {
        sortBreak = 1;
        for (ndx = 0; (ndx < sortStep); ndx++)
        {
            if (regAddrArrPtr[ndx] <= regAddrArrPtr[ndx + 1]) continue;
            sortBreak = 0;
            saveAddr              = regAddrArrPtr[ndx];
            saveData              = regDataArrPtr[ndx];
            regAddrArrPtr[ndx]    = regAddrArrPtr[ndx + 1];
            regDataArrPtr[ndx]    = regDataArrPtr[ndx + 1];
            regAddrArrPtr[ndx + 1] = saveAddr;
            regDataArrPtr[ndx + 1] = saveData;
        }
        if (sortBreak) break;
    }

    /* print dump */
    expectedRegAddr = 0xFFFFFFFF;
    printedWordsInLine = 0;
    printedWordsInAddr = 0;
    dataDuplicates     = 0;
    lastData           = 0;
    for (ndx = 0; (ndx < retrievedRegsNum); ndx++)
    {
        if (regAddrArrPtr[ndx] < startRegAddr) continue;
        if (regAddrArrPtr[ndx] >= endRegAddr) break;
        /* overriding DB possible bug - duplicated registers (maybe with different names) */
        if ((ndx != 0) && (regAddrArrPtr[ndx] == regAddrArrPtr[ndx-1])) continue;

        if (printedWordsInLine >= printWordsInLine)
        {
            cpssOsPrintf("\n");
            printedWordsInLine = 0;
        }
        if ((regAddrArrPtr[ndx] != expectedRegAddr)
            || (printedWordsInAddr >= maxDataWithoutAddress))
        {
            if (dataDuplicates > 0)
            {
                cpssOsPrintf("(*%d) ", (dataDuplicates + 1));
                dataDuplicates = 0;
            }
            if ((addressFromNewLine) && (printedWordsInLine != 0))
            {
                cpssOsPrintf("\n");
                printedWordsInLine = 0;
            }
            printedWordsInAddr = 0;
            cpssOsPrintf("<%08X> ", regAddrArrPtr[ndx]);
            printedWordsInLine ++;
            expectedRegAddr    = regAddrArrPtr[ndx];
            dataDuplicates = 0;
        }
        if (printedWordsInAddr != 0)
        {
            if (lastData == regDataArrPtr[ndx])
            {
                dataDuplicates ++;
                expectedRegAddr    += 4;
                continue;
            }
            else if (dataDuplicates > 0)
            {
                cpssOsPrintf("(*%d) ", (dataDuplicates + 1));
                dataDuplicates = 0;
            }
        }
        cpssOsPrintf("%08X ", regDataArrPtr[ndx]);
        expectedRegAddr    += 4;
        printedWordsInLine ++;
        printedWordsInAddr ++;
        lastData = regDataArrPtr[ndx];
    }

    if (dataDuplicates > 0)
    {
        cpssOsPrintf("(*%d) ", (dataDuplicates + 1));
        dataDuplicates = 0;
    }
    cpssOsPrintf("\n");

    cpssOsFree(regAddrArrPtr);
    cpssOsFree(regDataArrPtr);
    return GT_OK;
#else
    /* avoid warnings */
    TGF_PARAM_NOT_USED(devNum);
    TGF_PARAM_NOT_USED(portGroupsBmp);
    TGF_PARAM_NOT_USED(startRegAddr);
    TGF_PARAM_NOT_USED(endRegAddr);
    TGF_PARAM_NOT_USED(printWordsInLine);
    TGF_PARAM_NOT_USED(maxDataWithoutAddress);
    TGF_PARAM_NOT_USED(addressFromNewLine);
    return GT_NOT_APPLICABLE_DEVICE;
#endif
}


