/*******************************************************************************
*              (c), Copyright 2018, Marvell International Ltd.                 *
* THIS CODE IS A REFERENCE CODE FOR MARVELL SWITCH PRODUCTS.  IT IS PROVIDED   *
* "AS IS" WITH NO WARRANTIES, EXPRESSED, IMPLIED OR OTHERWISE, REGARDING ITS   *
* ACCURACY, COMPLETENESS OR PERFORMANCE.                                       *
* CUSTOMERS ARE FREE TO MODIFY IT AND USE IT ONLY IN THEIR PRODUCTION          *
* SOFTWARE RELEASES WITH MARVELL SWITCH CHIPSETS.                              *
*******************************************************************************/
/**
********************************************************************************
* @file DB-98DX7312-8SFP-1QSFP.c
*
* @brief AC5X CAP main profiles
*
* @version   1
********************************************************************************
*/

#include <profiles/cpssAppPlatformProfile.h>
#include <profiles/cpssAppPlatformProfileDecl.h>

/**** AC5X full profile - 1 PP ****/
CPSS_CAP_PROFILE_START( DB_AC5X_8SFP_all )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_AC5X_8SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_AC5X_8SFP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( DB_AC5X_8SFP_all, "AC5X DB - External Cpu" )

/**** AC5X full profile - 1 PP ****/
CPSS_CAP_PROFILE_START( DB_AC5X_8SFP_int_cpu_all )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_AC5X_8SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_INT_CPU_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_AC5X_8SFP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( DB_AC5X_8SFP_int_cpu_all, "AC5X DB - Internal Cpu" )

/**** AC5X full profile - 1 PP ****/
CPSS_CAP_PROFILE_START( RD_AC5X_32SFP_int_cpu_all )
  CPSS_CAP_ADD_BOARD_PROFILE( &RD_AC5X_32SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_INT_CPU_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_RD_AC5X_32SFP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( RD_AC5X_32SFP_int_cpu_all, "AC5X RD - Internal Cpu" )

/*** AC5X - board only profile ****/
CPSS_CAP_PROFILE_START( DB_AC5X_8SFP_board_only )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_AC5X_8SFP_BOARD_INFO )
CPSS_CAP_PROFILE_END( DB_AC5X_8SFP_board_only, "AC5X DB - Board only" )

/*** AC5X with one PP****/
CPSS_CAP_PROFILE_START( DB_AC5X_8SFP_PP_only)
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_PP_INFO, &WM_AC5X_PP_MAP_INFO )
CPSS_CAP_PROFILE_END( DB_AC5X_8SFP_PP_only, "AC5X DB - PP only" )

/*** AC5X RT Profile ****/
CPSS_CAP_PROFILE_START( DB_AC5X_8SFP_RT)
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_AC5X_8SFP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( DB_AC5X_8SFP_RT, "AC5X DB - runtime profile" )


/**** AC5X full profile - 1 PP - No Ports ****/
CPSS_CAP_PROFILE_START( DB_AC5X_8SFP_all_noports )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_AC5X_8SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_AC5X_8SFP_NOPORTS_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( DB_AC5X_8SFP_all_noports, "AC5X DB - External Cpu with No Ports Initialized" )

/**** AC5X full profile - 1 PP - No Ports ****/
CPSS_CAP_PROFILE_START( DB_AC5X_8SFP_int_cpu_all_noports )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_AC5X_8SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_INT_CPU_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_AC5X_8SFP_NOPORTS_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( DB_AC5X_8SFP_int_cpu_all_noports, "AC5X DB - Internal Cpu with No Ports Initialized" )

/*** AC5X RT Profile - No Ports ****/
CPSS_CAP_PROFILE_START( DB_AC5X_8SFP_RT_noports)
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_AC5X_8SFP_NOPORTS_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( DB_AC5X_8SFP_RT_noports, "AC5X DB - runtime profile with No Ports Initialized" )

