/*******************************************************************************
*              (c), Copyright 2018, Marvell International Ltd.                 *
* THIS CODE IS A REFERENCE CODE FOR MARVELL SWITCH PRODUCTS.  IT IS PROVIDED   *
* "AS IS" WITH NO WARRANTIES, EXPRESSED, IMPLIED OR OTHERWISE, REGARDING ITS   *
* ACCURACY, COMPLETENESS OR PERFORMANCE.                                       *
* CUSTOMERS ARE FREE TO MODIFY IT AND USE IT ONLY IN THEIR PRODUCTION          *
* SOFTWARE RELEASES WITH MARVELL SWITCH CHIPSETS.                              *
*******************************************************************************/
/**
********************************************************************************
* @file DB-98EX5520-6ZQSFP-48SFP.c
*
* @brief Aldrin profile related file.
*
* @version   1
********************************************************************************
*/

#include <profiles/cpssAppPlatformProfile.h>
#include <profiles/cpssAppPlatformProfileDecl.h>

/*** Aldrin2 with one PP ****/
CPSS_CAP_PROFILE_START( DB_ALD2_48MG6CG_all )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_98EX5520_6ZQSFP_48SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &DB_98EX5520_PP_INFO, &DB_98EX5520_6ZQSFP_48SFP_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_98EX5520_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_98EX5520_GEN_EVENT_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO )
CPSS_CAP_PROFILE_END( DB_ALD2_48MG6CG_all, "Aldrin2 DB" )

CPSS_CAP_PROFILE_START( DB_ALD2_48MG6CG_all_ap )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_98EX5520_6ZQSFP_48SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &DB_98EX5520_PP_INFO_AP, &DB_98EX5520_6ZQSFP_48SFP_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_98EX5520_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_98EX5520_GEN_EVENT_AP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO )
CPSS_CAP_PROFILE_END( DB_ALD2_48MG6CG_all_ap, "Aldrin2 DB - AP enabled" )

/*** Aldrin2 with one PP + legacy ports ***/
CPSS_CAP_PROFILE_START( DB_ALD2_48MG6CG_all_legacy )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_98EX5520_6ZQSFP_48SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &DB_98EX5520_PP_INFO, &DB_98EX5520_6ZQSFP_48SFP_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_98EX5520_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_98EX5520_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( DB_ALD2_48MG6CG_all_legacy, "Aldrin2 DB - Legacy Ports" )

CPSS_CAP_PROFILE_START( DB_ALD2_48MG6CG_all_legacy_ap )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_98EX5520_6ZQSFP_48SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &DB_98EX5520_PP_INFO_AP, &DB_98EX5520_6ZQSFP_48SFP_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_98EX5520_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_98EX5520_GEN_EVENT_AP_INFO )
CPSS_CAP_PROFILE_END( DB_ALD2_48MG6CG_all_legacy_ap, "Aldrin2 DB - Legacy Ports + AP enabled" )

CPSS_CAP_PROFILE_START( DB_ALD2_48MG6CG_board )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_98EX5520_6ZQSFP_48SFP_BOARD_INFO )
  CPSS_CAP_ADD_BOARD_PROFILE( &DB_98EX5520_6ZQSFP_48SFP_LED_INFO )
CPSS_CAP_PROFILE_END( DB_ALD2_48MG6CG_board, "Aldrin2 DB - Board only" )


CPSS_CAP_PROFILE_START( DB_ALD2_48MG6CG_pp )
  CPSS_CAP_ADD_PP_PROFILE( &DB_98EX5520_PP_INFO, &DB_98EX5520_6ZQSFP_48SFP_PP_MAP_INFO )
CPSS_CAP_PROFILE_END( DB_ALD2_48MG6CG_pp, "Aldrin2 DB - PP only" )


CPSS_CAP_PROFILE_START( DB_ALD2_48MG6CG_runtime )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_DB_98EX5520_INFO )
CPSS_CAP_PROFILE_END( DB_ALD2_48MG6CG_runtime, "Aldrin2 DB - runtime only" )

/**********TEST/VALIDATION Profiles*********/
CPSS_CAP_TEST_PROFILE_START( TEST_DB_ALD2_48MG6CG_all_legacy )
  CPSS_CAP_ADD_BOARD_TEST_PROFILE( &DB_98EX5520_6ZQSFP_48SFP_BOARD_INFO )
  CPSS_CAP_ADD_PP_TEST_PROFILE( &DB_98EX5520_PP_INFO, &DB_98EX5520_6ZQSFP_48SFP_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_TEST_PROFILE( &RUNTIME_DB_98EX5520_INFO )
  CPSS_CAP_ADD_RUNTIME_TEST_PROFILE( &RUNTIME_DB_98EX5520_GEN_EVENT_INFO )
CPSS_CAP_TEST_PROFILE_END( TEST_DB_ALD2_48MG6CG_all_legacy, "Aldrin2 DB - Legacy Ports" )

