/*******************************************************************************
*              (c), Copyright 2018, Marvell International Ltd.                 *
* THIS CODE IS A REFERENCE CODE FOR MARVELL SWITCH PRODUCTS.  IT IS PROVIDED   *
* "AS IS" WITH NO WARRANTIES, EXPRESSED, IMPLIED OR OTHERWISE, REGARDING ITS   *
* ACCURACY, COMPLETENESS OR PERFORMANCE.                                       *
* CUSTOMERS ARE FREE TO MODIFY IT AND USE IT ONLY IN THEIR PRODUCTION          *
* SOFTWARE RELEASES WITH MARVELL SWITCH CHIPSETS.                              *
*******************************************************************************/
/**
********************************************************************************
* @file WM-AC5X.c
*
* @brief AC5X CAP main profiles
*
* @version   1
********************************************************************************
*/

#include <profiles/cpssAppPlatformProfile.h>
#include <profiles/cpssAppPlatformProfileDecl.h>

/**** AC5X full profile - 1 PP ****/
CPSS_CAP_PROFILE_START( WM_AC5X_all )
  CPSS_CAP_ADD_BOARD_PROFILE( &WM_AC5X_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_AC5X_all, "AC5X - External Cpu" )

/**** AC5X full profile - 1 PP ****/
CPSS_CAP_PROFILE_START( WM_AC5X_int_cpu_all )
  CPSS_CAP_ADD_BOARD_PROFILE( &WM_AC5X_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_INT_CPU_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_AC5X_int_cpu_all, "AC5X - Internal Cpu" )


/*** AC5X - board only profile ****/
CPSS_CAP_PROFILE_START( WM_AC5X_board_only )
  CPSS_CAP_ADD_BOARD_PROFILE( &WM_AC5X_BOARD_INFO )
CPSS_CAP_PROFILE_END( WM_AC5X_board_only, "AC5X - Board only" )

/*** AC5X with one PP****/
CPSS_CAP_PROFILE_START( WM_AC5X_PP_only)
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_PP_INFO, &WM_AC5X_PP_MAP_INFO )
CPSS_CAP_PROFILE_END( WM_AC5X_PP_only, "AC5X - PP only" )

/*** AC5X RT Profile ****/
CPSS_CAP_PROFILE_START( WM_AC5X_RT)
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_AC5X_RT, "AC5X - runtime profile" )


/**** AC5X full profile - 1 PP - No Ports ****/
CPSS_CAP_PROFILE_START( WM_AC5X_all_noports )
  CPSS_CAP_ADD_BOARD_PROFILE( &WM_AC5X_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_NOPORTS_AC5X_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_AC5X_all_noports, "AC5X - External Cpu with No Ports Initialized" )

/**** AC5X full profile - 1 PP - No Ports ****/
CPSS_CAP_PROFILE_START( WM_AC5X_int_cpu_all_noports )
  CPSS_CAP_ADD_BOARD_PROFILE( &WM_AC5X_BOARD_INFO )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_INT_CPU_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_NOPORTS_AC5X_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_AC5X_int_cpu_all_noports, "AC5X - Internal Cpu with No Ports Initialized" )

/*** AC5X RT Profile - No Ports ****/
CPSS_CAP_PROFILE_START( WM_AC5X_RT_noports)
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_NOPORTS_AC5X_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_AC5X_RT_noports, "AC5X - runtime profile with No Ports Initialized" )

/**** AC5X full profile extCpu- 1 PP + RT ****/
CPSS_CAP_PROFILE_START( WM_AC5X_PP_RT )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_AC5X_PP_RT, "AC5X - External Cpu with PP+RT" )

/**** AC5X full profile intCpu - 1 PP + RT ****/
CPSS_CAP_PROFILE_START( WM_AC5X_PP_RT_int_cpu )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_INT_CPU_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_AC5X_PP_RT_int_cpu, "AC5X - Internal Cpu with PP+RT" )

/**** AC5X full profile extCpu - 1 PP - No Ports ****/
CPSS_CAP_PROFILE_START( WM_AC5X_PP_RT_noports )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_NOPORTS_AC5X_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_AC5X_PP_RT_noports, "AC5X - External Cpu PP+RT with No Ports Initialized" )

/**** AC5X full profile - 1 PP - No Ports ****/
CPSS_CAP_PROFILE_START( WM_AC5X_PP_RT_int_cpu_noports )
  CPSS_CAP_ADD_PP_PROFILE( &WM_AC5X_INT_CPU_PP_INFO, &WM_AC5X_PP_MAP_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_NOPORTS_AC5X_INFO )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_PORT_MANAGER_INFO_AC5X )
  CPSS_CAP_ADD_RUNTIME_PROFILE( &RUNTIME_WM_AC5X_GEN_EVENT_INFO )
CPSS_CAP_PROFILE_END( WM_AC5X_PP_RT_int_cpu_noports, "AC5X - Internal Cpu PP+RT with No Ports Initialized" )

