{
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 0,  112,   0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0},  0 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 1,  113,   0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0},  1 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 2,  114,   0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0},  2 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 3,  115,   0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0},  3 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 4,  116,   0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0},  4 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 5,  117,   0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0},  5 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 6,  118,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 6}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 7,  119,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 7}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 8,  120,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 8}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 9,  121,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 9}},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 10, 122,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 10 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 11, 123,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 11 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 12, 124,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 12 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 13, 125,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 13 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 14, 126,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 14 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 15, 127,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 15 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 16, 0,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 16 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 17, 1,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 17 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 18, 2,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 18 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 19, 3,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 19 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 20, 4,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 20 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 21, 5,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 21 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 22, 6,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 22 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 23, 7,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 23 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 24, 8,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 24 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 25, 9,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 25 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 26, 10,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 26 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 27, 11,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 27 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 28, 12,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 28 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 29, 13,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 29 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 30, 14,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 30 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 31, 15,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 31 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 32, 32,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 32 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 33, 33,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 33 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 34, 34,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 34 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 35, 35,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 35 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 36, 36,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 36 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 37, 37,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 37 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 38, 38,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 38 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 39, 39,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 39 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 40, 40,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 40 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 41, 41,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 41 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 42, 42,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 42 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 43, 43,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 43 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 44, 44,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 44 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 45, 45,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 45 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 46, 46,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 46 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 47, 47,  0, PROFILE_INTERFACE_MODE_KR_E, 250, .phyInfo = {0, 0, 0, 0}, 47 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 48, 64,  0, PROFILE_INTERFACE_MODE_KR4_E, 1000, .phyInfo = {0, 0, 0, 0}, 48 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 49, 68,  0, PROFILE_INTERFACE_MODE_KR4_E, 1000, .phyInfo = {0, 0, 0, 0}, 52 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 50, 72,  0, PROFILE_INTERFACE_MODE_KR4_E, 1000, .phyInfo = {0, 0, 0, 0}, 56 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 51, 76,  0, PROFILE_INTERFACE_MODE_KR4_E, 1000, .phyInfo = {0, 0, 0, 0}, 64 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 52, 80,  0, PROFILE_INTERFACE_MODE_KR4_E, 1000, .phyInfo = {0, 0, 0, 0}, 68 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 53, 84,  0, PROFILE_INTERFACE_MODE_KR4_E, 1000, .phyInfo = {0, 0, 0, 0}, 72 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 54, 88,  0, PROFILE_INTERFACE_MODE_KR4_E, 1000, .phyInfo = {0, 0, 0, 0}, 76 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 55, 92,  0, PROFILE_INTERFACE_MODE_KR4_E, 1000, .phyInfo = {0, 0, 0, 0}, 80 }},

    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 56, 133, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 84 }},
    {.profileType = PROFILE_TYPE_PORT_MAP_E,    .profileValue.portMap = { 57, 135, 0, PROFILE_INTERFACE_MODE_KR_E, 100, .phyInfo = {0, 0, 0, 0}, 85 }},

    // CPU PORT
    {.profileType = PROFILE_TYPE_CPU_PORT_MAP_E,    .profileValue.portMap = {63,   136,    0,  PROFILE_INTERFACE_MODE_KR_E,        10}},

    /* simulation */
    {.profileType = PROFILE_TYPE_SIM_INIFILE_E, .profileValue.sim_inifile = "-i ./iniFiles/falcon_4T_A0_wm.ini"},
    {.profileType = PROFILE_TYPE_HW_SKU_E, .profileValue.hwTableSizes = &hw_sku_profiles_falcon[0]},

    /* last */
    {.profileType = PROFILE_TYPE_LAST_E, .profileValue.no_param = 0}

};
