{
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    32,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    38,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    34,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    39,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    33,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    37,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    36,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    35,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    40,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    45,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    41,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    46,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    42,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    47,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    44,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    43,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    50,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    54,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    49,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    51,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    48,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    52,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    53,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    55,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    57,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    62,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    58,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    63,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    56,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    60,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    59,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    61,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    64,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    71,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    66,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    68,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    65,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    69,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    67,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    70,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    72,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    77,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    73,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    79,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    75,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    74,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    76,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    78,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    81,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    85,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    80,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    87,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    84,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    82,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    83,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    86,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    88,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    94,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    89,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    95,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    90,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    91,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    92,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    93,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    96,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   102,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    98,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   103,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    97,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   101,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   100,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    99,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   104,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   109,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   105,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   110,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   106,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   111,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   108,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   107,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   114,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   118,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   113,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   115,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   112,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   116,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   117,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   119,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   121,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   126,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   122,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   127,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   120,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   124,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   123,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   125,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   128,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   135,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   130,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   132,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   129,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   133,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   131,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   134,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   136,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   141,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   137,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   143,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   139,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   138,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   140,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   142,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   145,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   149,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   144,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   151,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   148,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   146,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   147,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   150,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   152,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   158,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   153,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   159,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   154,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   155,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   156,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   157,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   160,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   166,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   162,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   167,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   161,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   165,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   164,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   163,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   168,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   173,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   169,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   174,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   170,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   175,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   172,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   171,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   178,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   182,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   177,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   179,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   176,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   180,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   181,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   183,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   185,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   190,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   186,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   191,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   184,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   188,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   187,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   189,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   192,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   199,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   194,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   196,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   193,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   197,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   195,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   198,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   200,  GT_TRUE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   205,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   201,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   207,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   203,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   202,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   204,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   206,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   209,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   213,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   208,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   215,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   212,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   210,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   211,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   214,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   216,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   222,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   217,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   223,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   218,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   219,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   220,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   221,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   224,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   230,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   226,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   231,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   225,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   229,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   228,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   227,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   232,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   237,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   233,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   238,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   234,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   239,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   236,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   235,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   242,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   246,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   241,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   243,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   240,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   244,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   245,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   247,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   249,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   254,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   250,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   255,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   248,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   252,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   251,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {   253,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {     0,  GT_TRUE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {     7,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {     2,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {     4,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {     1,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {     5,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {     3,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {     6,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {     8,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    13,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {     9,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    15,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    11,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    10,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    12,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    14,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    17,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    21,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    16,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    23,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    20,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    18,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    19,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    22,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    24,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    30,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    25,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    31,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    26,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    27,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    28,  GT_FALSE, GT_TRUE } },
    {.profileType = PROFILE_TYPE_LANE_SWAP_E,   .profileValue.serdes_polarity = {    29,  GT_FALSE, GT_FALSE} },
    {.profileType = PROFILE_TYPE_LAST_E, .profileValue.no_param = 0}
};
