{
    /* Polarity                                                                lane   invTx    invRx */
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  1, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  0, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  5, GT_FALSE, GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  4, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 14, GT_FALSE, GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 15, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 10, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 11, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 33, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 32, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 37, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 36, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 46, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 47, GT_FALSE, GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 42, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 43, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  3, GT_FALSE, GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  2, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  7, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  6, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 12, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 13, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  8, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {  9, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 35, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 34, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 39, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 38, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 44, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 45, GT_FALSE, GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 40, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 41, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 80, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 81, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 84, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 85, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 82, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 83, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 93, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 95, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 89, GT_FALSE, GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 91, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 86, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 87, GT_FALSE, GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 92, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 94, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 88, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 90, GT_FALSE, GT_TRUE }},
    /*100G                                                                     lane   invTx    invRx */
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 98, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 99, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 97, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = { 96, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {103, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {102, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {100, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {101, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {108, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {109, GT_FALSE, GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {110, GT_FALSE, GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {111, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {104, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {105, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {106, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {107, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {114, GT_FALSE, GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {115, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {113, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {112, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {119, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {118, GT_FALSE, GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {116, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {117, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {124, GT_TRUE,  GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {126, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {125, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {127, GT_FALSE, GT_TRUE }},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {120, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {121, GT_TRUE,  GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {123, GT_FALSE, GT_FALSE}},
    {.profileType = PROFILE_TYPE_LANE_SWAP_E, .profileValue.serdes_polarity = {122, GT_FALSE, GT_FALSE}},

    {.profileType = PROFILE_TYPE_LAST_E, .profileValue.no_param = 0}
};



