/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsUsxPcsUnits.h
*
* @brief Hawk port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsUsxPcsUnits_H
#define __mvHwsUsxPcsUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  USX_PCS_UNITS_CONTROL1_P0_SPEED_SELECTION_E,
  /*1*/  USX_PCS_UNITS_CONTROL1_P0_SPEED_ALWAYS1_E,
  /*2*/  USX_PCS_UNITS_CONTROL1_P0_LOW_POWER_E,
  /*3*/  USX_PCS_UNITS_CONTROL1_P0_SPEED_SELECT_ALWAYS1_E,
  /*4*/  USX_PCS_UNITS_CONTROL1_P0_LOOPBACK_E,
  /*5*/  USX_PCS_UNITS_CONTROL1_P0_RESET_E,
  /*6*/  USX_PCS_UNITS_STATUS1_P0_LOW_POWER_ABILITY_E,
  /*7*/  USX_PCS_UNITS_STATUS1_P0_PCS_RECEIVE_LINK_E,
  /*8*/  USX_PCS_UNITS_STATUS1_P0_FAULT_E,
  /*9*/  USX_PCS_UNITS_STATUS1_P0_RX_LPI_ACTIVE_E,
  /*10*/  USX_PCS_UNITS_STATUS1_P0_TX_LPI_ACTIVE_E,
  /*11*/  USX_PCS_UNITS_STATUS1_P0_RX_LPI_E,
  /*12*/  USX_PCS_UNITS_STATUS1_P0_TX_LPI_E,
  /*13*/  USX_PCS_UNITS_DEVICE_ID0_P0_IDENTIFIER0_E,
  /*14*/  USX_PCS_UNITS_DEVICE_ID1_P0_IDENTIFIER1_E,
  /*15*/  USX_PCS_UNITS_SPEED_ABILITY_P0_C10GETH_E,
  /*16*/  USX_PCS_UNITS_SPEED_ABILITY_P0_C10PASS_TS_E,
  /*17*/  USX_PCS_UNITS_SPEED_ABILITY_P0_C40G_E,
  /*18*/  USX_PCS_UNITS_SPEED_ABILITY_P0_C100G_E,
  /*19*/  USX_PCS_UNITS_SPEED_ABILITY_P0_C25G_E,
  /*20*/  USX_PCS_UNITS_SPEED_ABILITY_P0_C50G_E,
  /*21*/  USX_PCS_UNITS_DEVICES_IN_PKG1_P0_CLAUSE22_E,
  /*22*/  USX_PCS_UNITS_DEVICES_IN_PKG1_P0_PMD_PMA_E,
  /*23*/  USX_PCS_UNITS_DEVICES_IN_PKG1_P0_WIS_PRES_E,
  /*24*/  USX_PCS_UNITS_DEVICES_IN_PKG1_P0_PCS_PRES_E,
  /*25*/  USX_PCS_UNITS_DEVICES_IN_PKG1_P0_PHY_XS_E,
  /*26*/  USX_PCS_UNITS_DEVICES_IN_PKG1_P0_DTE_XS_E,
  /*27*/  USX_PCS_UNITS_DEVICES_IN_PKG1_P0_TC_PRES_E,
  /*28*/  USX_PCS_UNITS_DEVICES_IN_PKG2_P0_CLAUSE22_E,
  /*29*/  USX_PCS_UNITS_DEVICES_IN_PKG2_P0_DEVICE1_E,
  /*30*/  USX_PCS_UNITS_DEVICES_IN_PKG2_P0_DEVICE2_E,
  /*31*/  USX_PCS_UNITS_CONTROL2_P0_PCS_TYPE_E,
  /*32*/  USX_PCS_UNITS_STATUS2_P0_C10GBASE_R_E,
  /*33*/  USX_PCS_UNITS_STATUS2_P0_C10GBASE_X_E,
  /*34*/  USX_PCS_UNITS_STATUS2_P0_C10GBASE_W_E,
  /*35*/  USX_PCS_UNITS_STATUS2_P0_C10GBASE_T_E,
  /*36*/  USX_PCS_UNITS_STATUS2_P0_C40GBASE_R_E,
  /*37*/  USX_PCS_UNITS_STATUS2_P0_C100GBASE_R_E,
  /*38*/  USX_PCS_UNITS_STATUS2_P0_C25GBASE_R_E,
  /*39*/  USX_PCS_UNITS_STATUS2_P0_C50GBASE_R_E,
  /*40*/  USX_PCS_UNITS_STATUS2_P0_RECEIVE_FAULT_E,
  /*41*/  USX_PCS_UNITS_STATUS2_P0_TRANSMIT_FAULT_E,
  /*42*/  USX_PCS_UNITS_STATUS2_P0_C2_5GBASE_T_E,
  /*43*/  USX_PCS_UNITS_STATUS2_P0_C5GBASE_T_E,
  /*44*/  USX_PCS_UNITS_STATUS2_P0_DEVICE_PRESENT_E,
  /*45*/  USX_PCS_UNITS_PKG_ID0_P0_IDENTIFIER_E,
  /*46*/  USX_PCS_UNITS_PKG_ID1_P0_IDENTIFIER_E,
  /*47*/  USX_PCS_UNITS_BASER_STATUS1_P0_BLOCK_LOCK_E,
  /*48*/  USX_PCS_UNITS_BASER_STATUS1_P0_HIGH_BER_E,
  /*49*/  USX_PCS_UNITS_BASER_STATUS1_P0_RECEIVE_LINK_E,
  /*50*/  USX_PCS_UNITS_BASER_STATUS2_P0_ERRORED_CNT_E,
  /*51*/  USX_PCS_UNITS_BASER_STATUS2_P0_BER_COUNTER_E,
  /*52*/  USX_PCS_UNITS_BASER_STATUS2_P0_HIGH_BER_E,
  /*53*/  USX_PCS_UNITS_BASER_STATUS2_P0_BLOCK_LOCK_E,
  /*54*/  USX_PCS_UNITS_SEED_A0_P0_SEED_E,
  /*55*/  USX_PCS_UNITS_SEED_A1_P0_SEED_E,
  /*56*/  USX_PCS_UNITS_SEED_A2_P0_SEED_E,
  /*57*/  USX_PCS_UNITS_SEED_A3_P0_SEED_E,
  /*58*/  USX_PCS_UNITS_SEED_B0_P0_SEED_E,
  /*59*/  USX_PCS_UNITS_SEED_B1_P0_SEED_E,
  /*60*/  USX_PCS_UNITS_SEED_B2_P0_SEED_E,
  /*61*/  USX_PCS_UNITS_SEED_B3_P0_SEED_E,
  /*62*/  USX_PCS_UNITS_BASER_TEST_CONTROL_P0_DATA_PATTERN_SEL_E,
  /*63*/  USX_PCS_UNITS_BASER_TEST_CONTROL_P0_SELECT_SQUARE_E,
  /*64*/  USX_PCS_UNITS_BASER_TEST_CONTROL_P0_RX_TESTPATTERN_E,
  /*65*/  USX_PCS_UNITS_BASER_TEST_CONTROL_P0_TX_TESTPATTERN_E,
  /*66*/  USX_PCS_UNITS_BASER_TEST_CONTROL_P0_SELECT_RANDOM_E,
  /*67*/  USX_PCS_UNITS_BASER_TEST_ERR_CNT_P0_COUNTER_E,
  /*68*/  USX_PCS_UNITS_BER_HIGH_ORDER_CNT_P0_BER_COUNTER_E,
  /*69*/  USX_PCS_UNITS_ERR_BLK_HIGH_ORDER_CNT_P0_ERRORED_BLOCKS_COUNTER_E,
  /*70*/  USX_PCS_UNITS_ERR_BLK_HIGH_ORDER_CNT_P0_HIGH_ORDER_PRESENT_E,
  /*71*/  USX_PCS_UNITS_MULTILANE_ALIGN_STAT1_P0_LANE0_BLOCK_LOCK_E,
  /*72*/  USX_PCS_UNITS_VENDOR_SCRATCH_P0_SCRATCH_E,
  /*73*/  USX_PCS_UNITS_VENDOR_CORE_REV_P0_REVISION_E,
  /*74*/  USX_PCS_UNITS_VENDOR_TXLANE_THRESH_P0_THRESHOLD0_E,
  /*75*/  USX_PCS_UNITS_VENDOR_PCS_MODE_P0_ENA_CLAUSE49_E,
  /*76*/  USX_PCS_UNITS_VENDOR_PCS_MODE_P0_DISABLE_MLD_E,
  /*77*/  USX_PCS_UNITS_VENDOR_PCS_MODE_P0_HI_BER25_E,
  /*78*/  USX_PCS_UNITS_VENDOR_PCS_MODE_P0_HI_BER5_E,
  /*79*/  USX_PCS_UNITS_VENDOR_PCS_MODE_P0_ST_ENA_CLAUSE49_E,
  /*80*/  USX_PCS_UNITS_VENDOR_PCS_MODE_P0_ST_DISABLE_MLD_E,
  /*81*/  USX_PCS_UNITS_VENDOR_PCS_MODE_P0_ST_HI_BER25_E,
  /*82*/  USX_PCS_UNITS_VENDOR_PCS_MODE_P0_ST_HI_BER5_E,
  /*83*/  USX_PCS_UNITS_STATUS3_P0_C200GBASE_R_E,
  /*84*/  USX_PCS_UNITS_STATUS3_P0_C400GBASE_R_E,
    USX_PCS_UNITS_REGISTER_LAST_E /* should be last */
} MV_HWS_USX_PCS_UNITS_FIELDS_E;


#ifdef __cplusplus
}
#endif

#endif /* __mvHwsUsxPcsUnits_H */

