/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsCpuSgpcsUnits.h
*
* @brief Hawk port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsCpuSgpcsUnits_H
#define __mvHwsCpuSgpcsUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  CPU_SGPCS_UNIT_PORT_CONTROL_PORT_SPEED_6_E,
  /*1*/  CPU_SGPCS_UNIT_PORT_CONTROL_PORT_DUPLEX_E,
  /*2*/  CPU_SGPCS_UNIT_PORT_CONTROL_PORT_AN_RESTART_E,
  /*3*/  CPU_SGPCS_UNIT_PORT_CONTROL_PORT_ISOLATE_E,
  /*4*/  CPU_SGPCS_UNIT_PORT_CONTROL_PORT_POWERDOWN_E,
  /*5*/  CPU_SGPCS_UNIT_PORT_CONTROL_PORT_AN_ENABLE_E,
  /*6*/  CPU_SGPCS_UNIT_PORT_CONTROL_PORT_SPEED_13_E,
  /*7*/  CPU_SGPCS_UNIT_PORT_CONTROL_PORT_LOOPBACK_E,
  /*8*/  CPU_SGPCS_UNIT_PORT_CONTROL_PORT_RESET_E,
  /*9*/  CPU_SGPCS_UNIT_PORT_STATUS_PORT_EXTDCAPABILITY_E,
  /*10*/  CPU_SGPCS_UNIT_PORT_STATUS_PORT_LINKSTATUS_E,
  /*11*/  CPU_SGPCS_UNIT_PORT_STATUS_PORT_ANEGABILITY_E,
  /*12*/  CPU_SGPCS_UNIT_PORT_STATUS_PORT_ANEGCOMPLETE_E,
  /*13*/  CPU_SGPCS_UNIT_PORT_PHY_ID0_PORT_PHYID0_E,
  /*14*/  CPU_SGPCS_UNIT_PORT_PHY_ID1_PORT_PHYID1_E,
  /*15*/  CPU_SGPCS_UNIT_PORT_DEV_ABILITY_PORT_LD_ABILITY_RSV05_E,
  /*16*/  CPU_SGPCS_UNIT_PORT_DEV_ABILITY_PORT_LD_FD_E,
  /*17*/  CPU_SGPCS_UNIT_PORT_DEV_ABILITY_PORT_LD_HD_E,
  /*18*/  CPU_SGPCS_UNIT_PORT_DEV_ABILITY_PORT_LD_PS1_E,
  /*19*/  CPU_SGPCS_UNIT_PORT_DEV_ABILITY_PORT_LD_PS2_E,
  /*20*/  CPU_SGPCS_UNIT_PORT_DEV_ABILITY_PORT_LD_ABILITY_RSV9_E,
  /*21*/  CPU_SGPCS_UNIT_PORT_DEV_ABILITY_PORT_LD_RF1_E,
  /*22*/  CPU_SGPCS_UNIT_PORT_DEV_ABILITY_PORT_LD_RF2_E,
  /*23*/  CPU_SGPCS_UNIT_PORT_DEV_ABILITY_PORT_LD_ACK_E,
  /*24*/  CPU_SGPCS_UNIT_PORT_DEV_ABILITY_PORT_LD_NP_E,
  /*25*/  CPU_SGPCS_UNIT_PORT_PARTNER_ABILITY_PORT_LP_PABILITY_RSV05_E,
  /*26*/  CPU_SGPCS_UNIT_PORT_PARTNER_ABILITY_PORT_LP_FD_E,
  /*27*/  CPU_SGPCS_UNIT_PORT_PARTNER_ABILITY_PORT_LP_HD_E,
  /*28*/  CPU_SGPCS_UNIT_PORT_PARTNER_ABILITY_PORT_LP_PS1_E,
  /*29*/  CPU_SGPCS_UNIT_PORT_PARTNER_ABILITY_PORT_LP_PS2_E,
  /*30*/  CPU_SGPCS_UNIT_PORT_PARTNER_ABILITY_PORT_LP_PABILITY_RSV9_E,
  /*31*/  CPU_SGPCS_UNIT_PORT_PARTNER_ABILITY_PORT_LP_PABILITY_RSV10_E,
  /*32*/  CPU_SGPCS_UNIT_PORT_PARTNER_ABILITY_PORT_LP_RF1_E,
  /*33*/  CPU_SGPCS_UNIT_PORT_PARTNER_ABILITY_PORT_LP_RF2_E,
  /*34*/  CPU_SGPCS_UNIT_PORT_PARTNER_ABILITY_PORT_LP_ACK_E,
  /*35*/  CPU_SGPCS_UNIT_PORT_PARTNER_ABILITY_PORT_LP_NP_E,
  /*36*/  CPU_SGPCS_UNIT_PORT_AN_EXPANSION_PORT_PAGERECEIVEDREALTIME_E,
  /*37*/  CPU_SGPCS_UNIT_PORT_AN_EXPANSION_PORT_PAGERECEIVED_E,
  /*38*/  CPU_SGPCS_UNIT_PORT_AN_EXPANSION_PORT_NEXTPAGEABLE_E,
  /*39*/  CPU_SGPCS_UNIT_PORT_NP_TX_PORT_LD_NP_DATA_E,
  /*40*/  CPU_SGPCS_UNIT_PORT_NP_TX_PORT_LD_NP_TOGGLE_E,
  /*41*/  CPU_SGPCS_UNIT_PORT_NP_TX_PORT_LD_NP_ACK2_E,
  /*42*/  CPU_SGPCS_UNIT_PORT_NP_TX_PORT_LD_NP_MP_E,
  /*43*/  CPU_SGPCS_UNIT_PORT_NP_TX_PORT_LD_NP_LD_NP_ACK_E,
  /*44*/  CPU_SGPCS_UNIT_PORT_NP_TX_PORT_LD_NP_NP_E,
  /*45*/  CPU_SGPCS_UNIT_PORT_LP_NP_RX_PORT_LP_NP_DATA_E,
  /*46*/  CPU_SGPCS_UNIT_PORT_LP_NP_RX_PORT_LP_NP_TOGGLE_E,
  /*47*/  CPU_SGPCS_UNIT_PORT_LP_NP_RX_PORT_LP_NP_ACK2_E,
  /*48*/  CPU_SGPCS_UNIT_PORT_LP_NP_RX_PORT_LP_NP_MP_E,
  /*49*/  CPU_SGPCS_UNIT_PORT_LP_NP_RX_PORT_LP_NP_ACK_E,
  /*50*/  CPU_SGPCS_UNIT_PORT_LP_NP_RX_PORT_LP_NP_NP_E,
  /*51*/  CPU_SGPCS_UNIT_PORT_SCRATCH_PORT_SCRATCH_E,
  /*52*/  CPU_SGPCS_UNIT_PORT_REV_PORT_REVISION_E,
  /*53*/  CPU_SGPCS_UNIT_PORT_LINK_TIMER_0_PORT_TIMER0_E,
  /*54*/  CPU_SGPCS_UNIT_PORT_LINK_TIMER_0_PORT_TIMER15_1_E,
  /*55*/  CPU_SGPCS_UNIT_PORT_LINK_TIMER_1_PORT_TIMER20_16_E,
  /*56*/  CPU_SGPCS_UNIT_PORT_IF_MODE_PORT_SGMII_ENA_E,
  /*57*/  CPU_SGPCS_UNIT_PORT_IF_MODE_PORT_USE_SGMII_AN_E,
  /*58*/  CPU_SGPCS_UNIT_PORT_IF_MODE_PORT_SGMII_SPEED_E,
  /*59*/  CPU_SGPCS_UNIT_PORT_IF_MODE_PORT_SGMII_DUPLEX_E,
  /*60*/  CPU_SGPCS_UNIT_PORT_DEC_ERR_CNT_PORT_DECODER_ERR_COUNTER_E,
  /*61*/  CPU_SGPCS_UNIT_PORT_VENDOR_CONTROL_PORT_SGPCS_ENA_R_E,
  /*62*/  CPU_SGPCS_UNIT_PORT_VENDOR_CONTROL_PORT_VC_RESERVED_E,
  /*63*/  CPU_SGPCS_UNIT_PORT_VENDOR_CONTROL_PORT_CFG_CLOCK_RATE_E,
  /*64*/  CPU_SGPCS_UNIT_PORT_VENDOR_CONTROL_PORT_VC_RESERVED2_E,
  /*65*/  CPU_SGPCS_UNIT_PORT_VENDOR_CONTROL_PORT_SGPCS_ENA_ST_E,
    CPU_SGPCS_REGISTER_LAST_E /* should be last */
} MV_HWS_CPU_SGPCS_UNIT_FIELDS_E;



#ifdef __cplusplus
}
#endif

#endif /* __mvHwsCpuSgpcsUnits_H */

