/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsLpcsUnits.h
*
* @brief Hawk port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsLpcsUnits_H
#define __mvHwsLpcsUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  LPCS_UNITS_CONTROL_P0_SPEED_6_E,
  /*1*/  LPCS_UNITS_CONTROL_P0_DUPLEX_E,
  /*2*/  LPCS_UNITS_CONTROL_P0_ANRESTART_E,
  /*3*/  LPCS_UNITS_CONTROL_IP0_SOLATE_E,
  /*4*/  LPCS_UNITS_CONTROL_P0_POWERDOWN_E,
  /*5*/  LPCS_UNITS_CONTROL_P0_ANENABLE_E,
  /*6*/  LPCS_UNITS_CONTROL_P0_SPEED_13_E,
  /*7*/  LPCS_UNITS_CONTROL_P0_LOOPBACK_E,
  /*8*/  LPCS_UNITS_CONTROL_P0_RESET_E,
  /*9*/  LPCS_UNITS_STATUS_P0_EXTDCAPABILITY_E,
  /*10*/  LPCS_UNITS_STATUS_P0_LINKSTATUS_E,
  /*11*/  LPCS_UNITS_STATUS_P0_ANEGABILITY_E,
  /*12*/  LPCS_UNITS_STATUS_P0_ANEGCOMPLETE_E,
  /*13*/  LPCS_UNITS_PHY_ID_0_P0_PHYID0_E,
  /*14*/  LPCS_UNITS_PHY_ID_1_P0_PHYID1_E,
  /*15*/  LPCS_UNITS_DEV_ABILITY_P0_LD_ABILITY_RSV05_E,
  /*16*/  LPCS_UNITS_DEV_ABILITY_P0_LD_FD_E,
  /*17*/  LPCS_UNITS_DEV_ABILITY_P0_LD_HD_E,
  /*18*/  LPCS_UNITS_DEV_ABILITY_P0_LD_PS1_E,
  /*19*/  LPCS_UNITS_DEV_ABILITY_P0_LD_PS2_E,
  /*20*/  LPCS_UNITS_DEV_ABILITY_P0_LD_ABILITY_RSV9_E,
  /*21*/  LPCS_UNITS_DEV_ABILITY_P0_LD_RF1_E,
  /*22*/  LPCS_UNITS_DEV_ABILITY_P0_LD_RF2_E,
  /*23*/  LPCS_UNITS_DEV_ABILITY_P0_LD_ACK_E,
  /*24*/  LPCS_UNITS_DEV_ABILITY_P0_LD_NP_E,
  /*25*/  LPCS_UNITS_PARTNER_ABILITY_P0_LP_PABILITY_RSV05_E,
  /*26*/  LPCS_UNITS_PARTNER_ABILITY_P0_LP_FD_E,
  /*27*/  LPCS_UNITS_PARTNER_ABILITY_P0_LP_HD_E,
  /*28*/  LPCS_UNITS_PARTNER_ABILITY_P0_LP_PS1_E,
  /*29*/  LPCS_UNITS_PARTNER_ABILITY_P0_LP_PS2_E,
  /*30*/  LPCS_UNITS_PARTNER_ABILITY_P0_LP_PABILITY_RSV9_E,
  /*31*/  LPCS_UNITS_PARTNER_ABILITY_P0_LP_PABILITY_RSV10_E,
  /*32*/  LPCS_UNITS_PARTNER_ABILITY_P0_LP_RF1_E,
  /*33*/  LPCS_UNITS_PARTNER_ABILITY_P0_LP_RF2_E,
  /*34*/  LPCS_UNITS_PARTNER_ABILITY_P0_LP_ACK_E,
  /*35*/  LPCS_UNITS_PARTNER_ABILITY_P0_LP_NP_E,
  /*36*/  LPCS_UNITS_AN_EXPANSION_P0_PAGERECEIVEDREALTIME_E,
  /*37*/  LPCS_UNITS_AN_EXPANSION_P0_PAGERECEIVED_E,
  /*38*/  LPCS_UNITS_AN_EXPANSION_P0_NEXTPAGEABLE_E,
  /*39*/  LPCS_UNITS_NP_TX_P0_LD_NP_DATA_E,
  /*40*/  LPCS_UNITS_NP_TX_P0_LD_NP_TOGGLE_E,
  /*41*/  LPCS_UNITS_NP_TX_P0_LD_NP_ACK2_E,
  /*42*/  LPCS_UNITS_NP_TX_P0_LD_NP_MP_E,
  /*43*/  LPCS_UNITS_NP_TX_P0_LD_NP_LD_NP_ACK_E,
  /*44*/  LPCS_UNITS_NP_TX_P0_LD_NP_NP_E,
  /*45*/  LPCS_UNITS_LP_NP_RX_P0_LP_NP_DATA_E,
  /*46*/  LPCS_UNITS_LP_NP_RX_P0_LP_NP_TOGGLE_E,
  /*47*/  LPCS_UNITS_LP_NP_RX_P0_LP_NP_ACK2_E,
  /*48*/  LPCS_UNITS_LP_NP_RX_P0_LP_NP_MP_E,
  /*49*/  LPCS_UNITS_LP_NP_RX_P0_LP_NP_ACK_E,
  /*50*/  LPCS_UNITS_LP_NP_RX_P0_LP_NP_NP_E,
  /*51*/  LPCS_UNITS_SCRATCH_P0_SCRATCH_E,
  /*52*/  LPCS_UNITS_REV_P0_REVISION_E,
  /*53*/  LPCS_UNITS_LINK_TIMER_0_P0_TIMER0_E,
  /*54*/  LPCS_UNITS_LINK_TIMER_0_P0_TIMER15_1_E,
  /*55*/  LPCS_UNITS_LINK_TIMER_1_P0_TIMER20_16_E,
  /*56*/  LPCS_UNITS_IF_MODE_P0_SGMII_ENA_E,
  /*57*/  LPCS_UNITS_IF_MODE_P0_USE_SGMII_AN_E,
  /*58*/  LPCS_UNITS_IF_MODE_P0_SGMII_SPEED_E,
  /*59*/  LPCS_UNITS_IF_MODE_P0_SGMII_DUPLEX_E,
  /*60*/  LPCS_UNITS_IF_MODE_P0_IFMODE_RSV5_E,
  /*61*/  LPCS_UNITS_IF_MODE_P0_IFMODE_TX_PREAMBLE_SYNC_E,
  /*62*/  LPCS_UNITS_IF_MODE_P0_IFMODE_RX_PREAMBLE_SYNC_E,
  /*63*/  LPCS_UNITS_IF_MODE_P0_IFMODE_MODE_XGMII_BASEX_E,
  /*64*/  LPCS_UNITS_IF_MODE_P0_IFMODE_SEQ_ENA_E,
  /*65*/  LPCS_UNITS_DECODE_ERRORS_P0_DECODEERRORS_E,
  /*66*/  LPCS_UNITS_USXGMII_REP_USXGMIIREP_E,
  /*67*/  LPCS_UNITS_USXGMII_REP_P0_USXGMII2_5_E,
  /*68*/  LPCS_UNITS_GMODE_LPCS_ENABLE_E,
  /*69*/  LPCS_UNITS_GMODE_QSGMII_0_ENABLE_E,
  /*70*/  LPCS_UNITS_GMODE_QSGMII_1_ENABLE_E,
  /*71*/  LPCS_UNITS_GMODE_USGMII8_ENABLE_E,
  /*72*/  LPCS_UNITS_GMODE_USGMII_SCRAMBLE_ENABLE_E,
  /*73*/  LPCS_UNITS_GSTATUS_GSYNC_STATUS_E,
  /*74*/  LPCS_UNITS_GSTATUS_GAN_DONE_STATUS_E,
  /*75*/  LPCS_UNITS_CFG_CLOCK_RATE_CFGCLOCKRATE_E,
  /*76*/  LPCS_UNITS_USXGMII_ENABLE_INDICATION_USXGMII_ENABLE_IND_E,
  /*77*/  LPCS_UNITS_TX_IPG_LENGTH_P0_TX_IPG_LENGTH_E,
  /*78*/  LPCS_UNITS_USXM1_PORTS_ENA_USXM1_PORTS_ENA_E,
  /*79*/  LPCS_UNITS_USXM0_PORTS_ENA_USXM0_PORTS_ENA_E,
    LPCS_UNITS_REGISTER_LAST_E /* should be last */
} MV_HWS_LPCS_UNITS_FIELDS_E;


#ifdef __cplusplus
}
#endif

#endif /* __mvHwsLpcsUnits_H */

