/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsRsfecUnits.h
*
* @brief Hawk port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsRsfecUnits_H
#define __mvHwsRsfecUnits_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  RSFEC_UNIT_RSFEC_CONTROL_P0_BYPASS_CORRECTION_E,
  /*1*/  RSFEC_UNIT_RSFEC_CONTROL_P0_BYPASS_ERROR_INDICATION_E,
  /*2*/  RSFEC_UNIT_RSFEC_CONTROL_P0_DEGRADE_ENABLE_E,
  /*3*/  RSFEC_UNIT_RSFEC_CONTROL_P0_AM16_COPY_DIS_E,
  /*4*/  RSFEC_UNIT_RSFEC_CONTROL_P0_KP_ENABLE_E,
  /*5*/  RSFEC_UNIT_RSFEC_CONTROL_P0_TC_PAD_VALUE_E,
  /*6*/  RSFEC_UNIT_RSFEC_CONTROL_P0_TC_PAD_ALTER_E,
  /*7*/  RSFEC_UNIT_RSFEC_STATUS_P0_BYPASS_CORRECTION_ABILITY_E,
  /*8*/  RSFEC_UNIT_RSFEC_STATUS_P0_BYPASS_INDICATION_ABILITY_E,
  /*9*/  RSFEC_UNIT_RSFEC_STATUS_P0_HIGH_SER_E,
  /*10*/  RSFEC_UNIT_RSFEC_STATUS_P0_DEGRADE_SER_ABILITY_E,
  /*11*/  RSFEC_UNIT_RSFEC_STATUS_P0_DEGRADE_SER_E,
  /*12*/  RSFEC_UNIT_RSFEC_STATUS_P0_RX_AM_SF2_E,
  /*13*/  RSFEC_UNIT_RSFEC_STATUS_P0_RX_AM_SF1_E,
  /*14*/  RSFEC_UNIT_RSFEC_STATUS_P0_RX_AM_SF0_E,
  /*15*/  RSFEC_UNIT_RSFEC_STATUS_P0_AMPS_LOCK_E,
  /*16*/  RSFEC_UNIT_RSFEC_STATUS_P0_FEC_ALIGN_STATUS_E,
  /*17*/  RSFEC_UNIT_RSFEC_CCW_LO_P0_RSFEC_CCW_LO_E,
  /*18*/  RSFEC_UNIT_RSFEC_CCW_HI_P0_RSFEC_CCW_HI_E,
  /*19*/  RSFEC_UNIT_RSFEC_NCCW_LO_P0_RSFEC_NCCW_LO_E,
  /*20*/  RSFEC_UNIT_RSFEC_NCCW_HI_P0_RSFEC_NCCW_HI_E,
  /*21*/  RSFEC_UNIT_RSFEC_LANE_MAP_P0_RSFEC_LANE_MAP_E,
  /*22*/  RSFEC_UNIT_RSFEC_DEC_THRESH_P0_RSFEC_DEC_THRESH_E,
  /*23*/  RSFEC_UNIT_HISER_CW_HISER_CW_E,
  /*24*/  RSFEC_UNIT_HISER_THRESH_HISER_THRESH_E,
  /*25*/  RSFEC_UNIT_HISER_TIME_HISER_TIME_E,
  /*26*/  RSFEC_UNIT_DEGRADE_SET_CW_DEGRADE_SET_CW_E,
  /*27*/  RSFEC_UNIT_DEGRADE_SET_CW_HI_DEGRADE_SET_CW_HI_E,
  /*28*/  RSFEC_UNIT_DEGRADE_SET_THRESH_DEGRADE_SET_THRESH_E,
  /*29*/  RSFEC_UNIT_DEGRADE_SET_THRESH_HI_DEGRADE_SET_THRESH_HI_E,
  /*30*/  RSFEC_UNIT_DEGRADE_CLEAR_CW_DEGRADE_CLEAR_CW_E,
  /*31*/  RSFEC_UNIT_DEGRADE_CLEAR_CW_HI_DEGRADE_CLEAR_CW_HI_E,
  /*32*/  RSFEC_UNIT_DEGRADE_CLEAR_THRESH_DEGRADE_CLEAR_THRESH_E,
  /*33*/  RSFEC_UNIT_DEGRADE_CLEAR_THRESH_HI_DEGRADE_CLEAR_THRESH_HI_E,
  /*34*/  RSFEC_UNIT_VENDOR_VL0_0_UM0_E,
  /*35*/  RSFEC_UNIT_VENDOR_VL0_0_UM1_E,
  /*36*/  RSFEC_UNIT_VENDOR_VL0_1_UM2_E,
  /*37*/  RSFEC_UNIT_VENDOR_VL1_0_UM0_E,
  /*38*/  RSFEC_UNIT_VENDOR_VL1_0_UM1_E,
  /*39*/  RSFEC_UNIT_VENDOR_VL1_1_UM2_E,
  /*40*/  RSFEC_UNIT_VENDOR_VL2_0_UM0_E,
  /*41*/  RSFEC_UNIT_VENDOR_VL2_0_UM1_E,
  /*42*/  RSFEC_UNIT_VENDOR_VL2_1_UM2_E,
  /*43*/  RSFEC_UNIT_VENDOR_VL3_0_UM0_E,
  /*44*/  RSFEC_UNIT_VENDOR_VL3_0_UM1_E,
  /*45*/  RSFEC_UNIT_VENDOR_VL3_1_UM2_E,
  /*46*/  RSFEC_UNIT_VENDOR_VL4_0_UM0_E,
  /*47*/  RSFEC_UNIT_VENDOR_VL4_0_UM1_E,
  /*48*/  RSFEC_UNIT_VENDOR_VL4_1_UM2_E,
  /*49*/  RSFEC_UNIT_VENDOR_VL5_0_UM0_E,
  /*50*/  RSFEC_UNIT_VENDOR_VL5_0_UM1_E,
  /*51*/  RSFEC_UNIT_VENDOR_VL5_1_UM2_E,
  /*52*/  RSFEC_UNIT_VENDOR_VL6_0_UM0_E,
  /*53*/  RSFEC_UNIT_VENDOR_VL6_0_UM1_E,
  /*54*/  RSFEC_UNIT_VENDOR_VL6_1_UM2_E,
  /*55*/  RSFEC_UNIT_VENDOR_VL7_0_UM0_E,
  /*56*/  RSFEC_UNIT_VENDOR_VL7_0_UM1_E,
  /*57*/  RSFEC_UNIT_VENDOR_VL7_1_UM2_E,
  /*58*/  RSFEC_UNIT_VENDOR_VL8_0_UM0_E,
  /*59*/  RSFEC_UNIT_VENDOR_VL8_0_UM1_E,
  /*60*/  RSFEC_UNIT_VENDOR_VL8_1_UM2_E,
  /*61*/  RSFEC_UNIT_VENDOR_VL9_0_UM0_E,
  /*62*/  RSFEC_UNIT_VENDOR_VL9_0_UM1_E,
  /*63*/  RSFEC_UNIT_VENDOR_VL9_1_UM2_E,
  /*64*/  RSFEC_UNIT_VENDOR_VL10_0_UM0_E,
  /*65*/  RSFEC_UNIT_VENDOR_VL10_0_UM1_E,
  /*66*/  RSFEC_UNIT_VENDOR_VL10_1_UM2_E,
  /*67*/  RSFEC_UNIT_VENDOR_VL11_0_UM0_E,
  /*68*/  RSFEC_UNIT_VENDOR_VL11_0_UM1_E,
  /*69*/  RSFEC_UNIT_VENDOR_VL11_1_UM2_E,
  /*70*/  RSFEC_UNIT_VENDOR_VL12_0_UM0_E,
  /*71*/  RSFEC_UNIT_VENDOR_VL12_0_UM1_E,
  /*72*/  RSFEC_UNIT_VENDOR_VL12_1_UM2_E,
  /*73*/  RSFEC_UNIT_VENDOR_VL13_0_UM0_E,
  /*74*/  RSFEC_UNIT_VENDOR_VL13_0_UM1_E,
  /*75*/  RSFEC_UNIT_VENDOR_VL13_1_UM2_E,
  /*76*/  RSFEC_UNIT_VENDOR_VL14_0_UM0_E,
  /*77*/  RSFEC_UNIT_VENDOR_VL14_0_UM1_E,
  /*78*/  RSFEC_UNIT_VENDOR_VL14_1_UM2_E,
  /*79*/  RSFEC_UNIT_VENDOR_VL15_0_UM0_E,
  /*80*/  RSFEC_UNIT_VENDOR_VL15_0_UM1_E,
  /*81*/  RSFEC_UNIT_VENDOR_VL15_1_UM2_E,
  /*82*/  RSFEC_UNIT_RSFEC_SYMBLERR0_LO_SYMBLERR0_LO_E,
  /*83*/  RSFEC_UNIT_RSFEC_SYMBLERR0_HI_SYMBLERR0_HI_E,
  /*84*/  RSFEC_UNIT_RSFEC_SYMBLERR1_LO_SYMBLERR1_LO_E,
  /*85*/  RSFEC_UNIT_RSFEC_SYMBLERR1_HI_SYMBLERR1_HI_E,
  /*86*/  RSFEC_UNIT_RSFEC_SYMBLERR2_LO_SYMBLERR2_LO_E,
  /*87*/  RSFEC_UNIT_RSFEC_SYMBLERR2_HI_SYMBLERR2_HI_E,
  /*88*/  RSFEC_UNIT_RSFEC_SYMBLERR3_LO_SYMBLERR3_LO_E,
  /*89*/  RSFEC_UNIT_RSFEC_SYMBLERR3_HI_SYMBLERR3_HI_E,
  /*90*/  RSFEC_UNIT_RSFEC_SYMBLERR4_LO_SYMBLERR4_LO_E,
  /*91*/  RSFEC_UNIT_RSFEC_SYMBLERR4_HI_SYMBLERR4_HI_E,
  /*92*/  RSFEC_UNIT_RSFEC_SYMBLERR5_LO_SYMBLERR5_LO_E,
  /*93*/  RSFEC_UNIT_RSFEC_SYMBLERR5_HI_SYMBLERR5_HI_E,
  /*94*/  RSFEC_UNIT_RSFEC_SYMBLERR6_LO_SYMBLERR6_LO_E,
  /*95*/  RSFEC_UNIT_RSFEC_SYMBLERR6_HI_SYMBLERR6_HI_E,
  /*96*/  RSFEC_UNIT_RSFEC_SYMBLERR7_LO_SYMBLERR7_LO_E,
  /*97*/  RSFEC_UNIT_RSFEC_SYMBLERR7_HI_SYMBLERR7_HI_E,
  /*98*/  RSFEC_UNIT_RSFEC_SYMBLERR8_LO_SYMBLERR8_LO_E,
  /*99*/  RSFEC_UNIT_RSFEC_SYMBLERR8_HI_SYMBLERR8_HI_E,
  /*100*/  RSFEC_UNIT_RSFEC_SYMBLERR9_LO_SYMBLERR9_LO_E,
  /*101*/  RSFEC_UNIT_RSFEC_SYMBLERR9_HI_SYMBLERR9_HI_E,
  /*102*/  RSFEC_UNIT_RSFEC_SYMBLERR10_LO_SYMBLERR10_LO_E,
  /*103*/  RSFEC_UNIT_RSFEC_SYMBLERR10_HI_SYMBLERR10_HI_E,
  /*104*/  RSFEC_UNIT_RSFEC_SYMBLERR11_LO_SYMBLERR11_LO_E,
  /*105*/  RSFEC_UNIT_RSFEC_SYMBLERR11_HI_SYMBLERR11_HI_E,
  /*106*/  RSFEC_UNIT_RSFEC_SYMBLERR12_LO_SYMBLERR12_LO_E,
  /*107*/  RSFEC_UNIT_RSFEC_SYMBLERR12_HI_SYMBLERR12_HI_E,
  /*108*/  RSFEC_UNIT_RSFEC_SYMBLERR13_LO_SYMBLERR13_LO_E,
  /*109*/  RSFEC_UNIT_RSFEC_SYMBLERR13_HI_SYMBLERR13_HI_E,
  /*110*/  RSFEC_UNIT_RSFEC_SYMBLERR14_LO_SYMBLERR14_LO_E,
  /*111*/  RSFEC_UNIT_RSFEC_SYMBLERR14_HI_SYMBLERR14_HI_E,
  /*112*/  RSFEC_UNIT_RSFEC_SYMBLERR15_LO_SYMBLERR15_LO_E,
  /*113*/  RSFEC_UNIT_RSFEC_SYMBLERR15_HI_SYMBLERR15_HI_E,
  /*114*/  RSFEC_UNIT_RSFEC_VENDOR_INFO1_VENDOR_AMPS_LOCK_E,
  /*115*/  RSFEC_UNIT_RSFEC_VENDOR_INFO1_VENDOR_ALIGN_STATUS_LH_E,
  /*116*/  RSFEC_UNIT_RSFEC_VENDOR_INFO1_VENDOR_MARKER_CHECK_RESTART_E,
  /*117*/  RSFEC_UNIT_RSFEC_VENDOR_INFO1_VENDOR_ALIGN_STATUS_LL_E,
  /*118*/  RSFEC_UNIT_RSFEC_VENDOR_INFO2_VENDOR_AMPS_LOCK_LANES_E,
  /*119*/  RSFEC_UNIT_RSFEC_VENDOR_REVISION_REVISION_E,
  /*120*/  RSFEC_UNIT_RSFEC_VENDOR_ALIGN_STATUS_RSFEC_VENDOR_ALIGN_STATUS_E,
    RSFEC_REGISTER_LAST_E
} MV_HWS_RSFEC_UNIT_FIELDS_E;



#ifdef __cplusplus
}
#endif

#endif /* __mvHwsRsfecUnits_H */

