/*******************************************************************************
*                Copyright 2001, Marvell International Ltd.
* This code contains confidential information of Marvell semiconductor, inc.
* no rights are granted herein under any patent, mask work right or copyright
* of Marvell or any third party.
* Marvell reserves the right at its sole discretion to request that this code
* be immediately returned to Marvell. This code is provided "as is".
* Marvell makes no warranties, express, implied or otherwise, regarding its
* accuracy, completeness or performance.
********************************************************************************
*/
/**
********************************************************************************
* @file mvHwsMacCpuRegDb.h
*
* @brief Hawk port interface header file
*
* @version   1
********************************************************************************
*/
#ifndef __mvHwsMacCpuRegDb_H
#define __mvHwsMacCpuRegDb_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  /*0*/  CPU_MAC_UNITS_REVISION_CORE_REVISION_E,
  /*1*/  CPU_MAC_UNITS_REVISION_CORE_VERSION_E,
  /*2*/  CPU_MAC_UNITS_REVISION_CUSTOMER_REVISION_E,
  /*3*/  CPU_MAC_UNITS_SCRATCH_SCRATCH_E,
  /*4*/  CPU_MAC_UNITS_COMMAND_CONFIG_TX_ENA_E,
  /*5*/  CPU_MAC_UNITS_COMMAND_CONFIG_RX_ENA_E,
  /*6*/  CPU_MAC_UNITS_COMMAND_CONFIG_PROMIS_EN_E,
  /*7*/  CPU_MAC_UNITS_COMMAND_CONFIG_PAD_EN_E,
  /*8*/  CPU_MAC_UNITS_COMMAND_CONFIG_CRC_FWD_E,
  /*9*/  CPU_MAC_UNITS_COMMAND_CONFIG_PAUSE_FWD_E,
  /*10*/  CPU_MAC_UNITS_COMMAND_CONFIG_PAUSE_IGNORE_E,
  /*11*/  CPU_MAC_UNITS_COMMAND_CONFIG_TX_ADDR_INS_E,
  /*12*/  CPU_MAC_UNITS_COMMAND_CONFIG_LOOPBACK_EN_E,
  /*13*/  CPU_MAC_UNITS_COMMAND_CONFIG_TX_PAD_EN_E,
  /*14*/  CPU_MAC_UNITS_COMMAND_CONFIG_SW_RESET_E,
  /*15*/  CPU_MAC_UNITS_COMMAND_CONFIG_CNTL_FRAME_ENA_E,
  /*16*/  CPU_MAC_UNITS_COMMAND_CONFIG_RX_ERR_DISC_E,
  /*17*/  CPU_MAC_UNITS_COMMAND_CONFIG_PHY_TXENA_E,
  /*18*/  CPU_MAC_UNITS_COMMAND_CONFIG_SEND_IDLE_E,
  /*19*/  CPU_MAC_UNITS_COMMAND_CONFIG_PFC_MODE_E,
  /*20*/  CPU_MAC_UNITS_COMMAND_CONFIG_PAUSE_PFC_COMP_E,
  /*21*/  CPU_MAC_UNITS_COMMAND_CONFIG_RX_SFD_ANY_E,
  /*22*/  CPU_MAC_UNITS_COMMAND_CONFIG_TX_FLUSH_E,
  /*23*/  CPU_MAC_UNITS_COMMAND_CONFIG_TX_LOWP_ENA_E,
  /*24*/  CPU_MAC_UNITS_COMMAND_CONFIG_TX_FIFO_RESET_E,
  /*25*/  CPU_MAC_UNITS_COMMAND_CONFIG_FLT_HDL_DIS_E,
  /*26*/  CPU_MAC_UNITS_COMMAND_CONFIG_SHORT_PREAMBLE_E,
  /*27*/  CPU_MAC_UNITS_COMMAND_CONFIG_NO_PREAMBLE_E,
  /*28*/  CPU_MAC_UNITS_MAC_ADDR_0_MAC_ADDRESS_0_E,
  /*29*/  CPU_MAC_UNITS_MAC_ADDR_1_MAC_ADDRESS_1_E,
  /*30*/  CPU_MAC_UNITS_FRM_LENGTH_FRM_LENGTH_E,
  /*31*/  CPU_MAC_UNITS_FRM_LENGTH_TX_MTU_E,
  /*32*/  CPU_MAC_UNITS_RX_FIFO_SECTIONS_RX_SECTION_FULL_E,
  /*33*/  CPU_MAC_UNITS_RX_FIFO_SECTIONS_RX_SECTION_EMPTY_E,
  /*34*/  CPU_MAC_UNITS_TX_FIFO_SECTIONS_TX_SECTION_FULL_E,
  /*35*/  CPU_MAC_UNITS_TX_FIFO_SECTIONS_TX_SECTION_EMPTY_E,
  /*36*/  CPU_MAC_UNITS_MDIO_CFG_STATUS_MDIO_BUSY_E,
  /*37*/  CPU_MAC_UNITS_MDIO_CFG_STATUS_MDIO_READ_ERROR_E,
  /*38*/  CPU_MAC_UNITS_MDIO_CFG_STATUS_MDIO_HOLD_TIME_SETTING_E,
  /*39*/  CPU_MAC_UNITS_MDIO_CFG_STATUS_MDIO_DISABLE_PREAMBLE_E,
  /*40*/  CPU_MAC_UNITS_MDIO_CFG_STATUS_MDIO_CLAUSE45_E,
  /*41*/  CPU_MAC_UNITS_MDIO_CFG_STATUS_MDIO_CLOCK_DIVISOR_E,
  /*42*/  CPU_MAC_UNITS_MDIO_COMMAND_DEVICE_ADDRESS_E,
  /*43*/  CPU_MAC_UNITS_MDIO_COMMAND_PORT_ADDRESS_E,
  /*44*/  CPU_MAC_UNITS_MDIO_COMMAND_READ_ADDRESS_POST_INCREMENT_E,
  /*45*/  CPU_MAC_UNITS_MDIO_COMMAND_NORMAL_READ_TRANSACTION_E,
  /*46*/  CPU_MAC_UNITS_MDIO_DATA_MDIO_DATA_E,
  /*47*/  CPU_MAC_UNITS_MDIO_REGADDR_MDIO_REGADDR_E,
  /*48*/  CPU_MAC_UNITS_STATUS_RX_LOC_FAULT_E,
  /*49*/  CPU_MAC_UNITS_STATUS_RX_REM_FAULT_E,
  /*50*/  CPU_MAC_UNITS_STATUS_PHY_LOS_E,
  /*51*/  CPU_MAC_UNITS_STATUS_TS_AVAIL_E,
  /*52*/  CPU_MAC_UNITS_STATUS_RX_LOWP_E,
  /*53*/  CPU_MAC_UNITS_STATUS_TX_EMPTY_E,
  /*54*/  CPU_MAC_UNITS_STATUS_RX_EMPTY_E,
  /*55*/  CPU_MAC_UNITS_STATUS_RX_LINT_FAULT_E,
  /*56*/  CPU_MAC_UNITS_STATUS_TX_IS_IDLE_E,
  /*57*/  CPU_MAC_UNITS_TX_IPG_LENGTH_TXIPG_E,
  /*58*/  CPU_MAC_UNITS_TX_IPG_LENGTH_COMPENSATION_E,
  /*59*/  CPU_MAC_UNITS_CRC_MODE_DISABLE_RX_CRC_CHECK_E,
  /*60*/  CPU_MAC_UNITS_CRC_MODE_CRC_1BYTE_E,
  /*61*/  CPU_MAC_UNITS_CRC_MODE_CRC_2BYTE_E,
  /*62*/  CPU_MAC_UNITS_CRC_MODE_CRC_0BYTE_E,
  /*63*/  CPU_MAC_UNITS_CL01_PAUSE_QUANTA_CL0_PAUSE_QUANTA_E,
  /*64*/  CPU_MAC_UNITS_CL01_PAUSE_QUANTA_CL1_PAUSE_QUANTA_E,
  /*65*/  CPU_MAC_UNITS_CL23_PAUSE_QUANTA_CL2_PAUSE_QUANTA_E,
  /*66*/  CPU_MAC_UNITS_CL23_PAUSE_QUANTA_CL3_PAUSE_QUANTA_E,
  /*67*/  CPU_MAC_UNITS_CL45_PAUSE_QUANTA_CL4_PAUSE_QUANTA_E,
  /*68*/  CPU_MAC_UNITS_CL45_PAUSE_QUANTA_CL5_PAUSE_QUANTA_E,
  /*69*/  CPU_MAC_UNITS_CL67_PAUSE_QUANTA_CL6_PAUSE_QUANTA_E,
  /*70*/  CPU_MAC_UNITS_CL67_PAUSE_QUANTA_CL7_PAUSE_QUANTA_E,
  /*71*/  CPU_MAC_UNITS_CL01_QUANTA_THRESH_CL0_QUANTA_THRESH_E,
  /*72*/  CPU_MAC_UNITS_CL01_QUANTA_THRESH_CL1_QUANTA_THRESH_E,
  /*73*/  CPU_MAC_UNITS_CL23_QUANTA_THRESH_CL2_QUANTA_THRESH_E,
  /*74*/  CPU_MAC_UNITS_CL23_QUANTA_THRESH_CL3_QUANTA_THRESH_E,
  /*75*/  CPU_MAC_UNITS_CL45_QUANTA_THRESH_CL4_QUANTA_THRESH_E,
  /*76*/  CPU_MAC_UNITS_CL45_QUANTA_THRESH_CL5_QUANTA_THRESH_E,
  /*77*/  CPU_MAC_UNITS_CL67_QUANTA_THRESH_CL6_QUANTA_THRESH_E,
  /*78*/  CPU_MAC_UNITS_CL67_QUANTA_THRESH_CL7_QUANTA_THRESH_E,
  /*79*/  CPU_MAC_UNITS_RX_PAUSE_STATUS_PAUSESTATUS_E,
  /*80*/  CPU_MAC_UNITS_TS_TIMESTAMP_TS_TIMESTAMP_E,
  /*81*/  CPU_MAC_UNITS_XIF_MODE_XGMII_E,
  /*82*/  CPU_MAC_UNITS_XIF_MODE_PAUSETIMERX8_E,
  /*83*/  CPU_MAC_UNITS_XIF_MODE_ONESTEPENA_E,
  /*84*/  CPU_MAC_UNITS_XIF_MODE_RX_PAUSE_BYPASS_E,
  /*85*/  CPU_MAC_UNITS_XIF_MODE_TX_MAC_RS_ERR_E,
  /*86*/  CPU_MAC_UNITS_CL89_PAUSE_QUANTA_CL8_PAUSE_QUANTA_E,
  /*87*/  CPU_MAC_UNITS_CL89_PAUSE_QUANTA_CL9_PAUSE_QUANTA_E,
  /*88*/  CPU_MAC_UNITS_CL1011_PAUSE_QUANTA_CL10_PAUSE_QUANTA_E,
  /*89*/  CPU_MAC_UNITS_CL1011_PAUSE_QUANTA_CL11_PAUSE_QUANTA_E,
  /*90*/  CPU_MAC_UNITS_CL1213_PAUSE_QUANTA_CL12_PAUSE_QUANTA_E,
  /*91*/  CPU_MAC_UNITS_CL1213_PAUSE_QUANTA_CL13_PAUSE_QUANTA_E,
  /*92*/  CPU_MAC_UNITS_CL1415_PAUSE_QUANTA_CL14_PAUSE_QUANTA_E,
  /*93*/  CPU_MAC_UNITS_CL1415_PAUSE_QUANTA_CL15_PAUSE_QUANTA_E,
  /*94*/  CPU_MAC_UNITS_CL89_QUANTA_THRESH_CL8_QUANTA_THRESH_E,
  /*95*/  CPU_MAC_UNITS_CL89_QUANTA_THRESH_CL9_QUANTA_THRESH_E,
  /*96*/  CPU_MAC_UNITS_CL1011_QUANTA_THRESH_CL10_QUANTA_THRESH_E,
  /*97*/  CPU_MAC_UNITS_CL1011_QUANTA_THRESH_CL11_QUANTA_THRESH_E,
  /*98*/  CPU_MAC_UNITS_CL1213_QUANTA_THRESH_CL12_QUANTA_THRESH_E,
  /*99*/  CPU_MAC_UNITS_CL1213_QUANTA_THRESH_CL13_QUANTA_THRESH_E,
  /*100*/  CPU_MAC_UNITS_CL1415_QUANTA_THRESH_CL14_QUANTA_THRESH_E,
  /*101*/  CPU_MAC_UNITS_CL1415_QUANTA_THRESH_CL15_QUANTA_THRESH_E,
    CPU_MAC_REGISTER_LAST_E
} MV_HWS_CPU_MAC_UNITS_FIELDS_E;


#ifdef __cplusplus
}
#endif

#endif /* __mvHwsMacCpuRegDb_H */
