/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,       *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
*/
/**
********************************************************************************
* @file cpssDxChTables.h
 *
* @brief API definition for tables access
*
* @version   1
********************************************************************************
*/

#ifndef __cpssDxChTablesh
#define __cpssDxChTablesh

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <cpss/common/cpssTypes.h>

#define CPSS_DXCH_SIP6_PDS_UNITS_PER_TILE_MAC 8
#define CPSS_DXCH_SIP6_SDQ_UNITS_PER_TILE_MAC 8
#define CPSS_DXCH_SIP6_QFC_UNITS_PER_TILE_MAC 8
#define CPSS_DXCH_SIP6_MAX_PDX_PAC_UNITS_PER_DEVICE_MAC 4
#define CPSS_DXCH_SIP6_MAX_SDQ_UNITS_PER_DEVICE_MAC 32
#define CPSS_DXCH_SIP6_MAX_PDS_UNITS_PER_DEVICE_MAC 32
#define CPSS_DXCH_SIP6_MAX_PSI_UNITS_PER_DEVICE_MAC 4
#define CPSS_DXCH_SIP6_MAX_QFC_UNITS_PER_DEVICE_MAC 32
#define CPSS_DXCH_SIP6_MAX_PFCC_UNITS_PER_DEVICE_MAC 4
#define CPSS_DXCH_SIP6_MAX_GOP_LMU_STATISTICS_MAC 32
#define CPSS_DXCH_SIP6_MAX_GOP_LMU_CONFIGURATION_MAC 32
#define CPSS_DXCH_SIP6_SDQ_QUEUE_CNS 400


#define CPSS_DXCH_SIP6_10_SDQ_QUEUE_CNS 256
#define CPSS_DXCH_SIP6_10_MAX_PDS_UNITS_PER_DEVICE_MAC 4

#define PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(_name,_numOfMult)\
    _name##_E,\
    _name##_LAST_E = _name##_E+_numOfMult-1


/*******************************************************************************
* PRV_CPSS_DXCH_TABLE_SIZE_GET_MAC
*
* DESCRIPTION:
*       get the number of table in accessTableInfoPtr (see PRV_TABLE_INFO_PTR_GET_MAC)
* INPUTS:
*       devNum - device number
*
* OUTPUTS:
*       NONE
*
* RETURNS:
*       the number of table in accessTableInfoPtr (see PRV_TABLE_INFO_PTR_GET_MAC)
*
* COMMENTS:
*
*
*******************************************************************************/
#define PRV_CPSS_DXCH_TABLE_SIZE_GET_MAC(devNum) \
           (PRV_CPSS_DXCH_PP_MAC(devNum)->accessTableInfoSize)

/*******************************************************************************
* PRV_TABLE_INFO_PTR_GET_MAC
*
* DESCRIPTION:
*       get the table info
* INPUTS:
*       devNum - device number
*       tableType - the table to get info
* OUTPUTS:
*       NONE
*
* RETURNS:
*       pointer to the table's info
*
* COMMENTS:
*
*
*******************************************************************************/
#define PRV_TABLE_INFO_PTR_GET_MAC(_devNum, _tableType) \
 (&PRV_CPSS_DXCH_PP_MAC(_devNum)->accessTableInfoPtr[_tableType])

/**
* @enum CPSS_DXCH_TABLE_ENT
 *
 * @brief names of the tables that are non-direct accessed
 * !!!! Values of enum linked with tables DB. Tables DB must be updated
 * in any cases of changes in the enum !!!!!!
 *
 * Enumerations:
 *  CPSS_DXCH_TABLE_VLAN_PORT_PROTOCOL_E  - VLAN_PORT_PROTOCOL table
 *  CPSS_DXCH_TABLE_PORT_VLAN_QOS_E - PORT_VLAN_QOS table
 *  CPSS_DXCH_TABLE_TRUNK_MEMBERS_E - TABLE_TRUNK_MEMBERS.
 *  CPSS_DXCH_TABLE_STATISTICAL_RATE_LIMIT_E - STATISTICAL_RATE_LIMIT table.
 *  CPSS_DXCH_TABLE_CPU_CODE_E -  CPU_CODE table.
 *  CPSS_DXCH_TABLE_PCL_CONFIG_E - PCL_CONFIG table
 *  CPSS_DXCH_TABLE_QOS_PROFILE_E - QOS_PROFILE table.
 *  CPSS_DXCH_TABLE_REMARKING_E - REMARKING table.
 *  CPSS_DXCH_TABLE_STG_E - STG table.
 *  CPSS_DXCH_TABLE_VLAN_E -  VLAN table.
 *  CPSS_DXCH_TABLE_MULTICAST_E - MULTICAST table
 *  CPSS_DXCH_TABLE_ROUTE_HA_MAC_SA_E - ROUTE_HA_MAC_SA table.
 *  CPSS_DXCH_TABLE_ROUTE_HA_ARP_DA_E - ROUTE_HA_ARP_DA table. only in CH 1. - for others see 'tunnel start'
 *  CPSS_DXCH_TABLE_FDB_E - FDB table.
 *  CPSS_DXCH_TABLE_POLICER_E - POLICER table
 *  CPSS_DXCH_TABLE_POLICER_COUNTERS_E - POLICER_COUNTERS table.
 *  CPSS_DXCH2_TABLE_EGRESS_PCL_CONFIG_E -  EGRESS_PCL_CONFIG table.
 *  CPSS_DXCH2_TABLE_TUNNEL_START_CONFIG_E -  TUNNEL_START table.
 *  CPSS_DXCH2_TABLE_QOS_PROFILE_TO_ROUTE_BLOCK_E - QOS_PROFILE_TO_ROUTE table.
 *  CPSS_DXCH2_TABLE_ROUTE_ACCESS_MATRIX_E - ROUTE_ACCESS_MATRIX table.
 *  CPSS_DXCH2_LTT_TT_ACTION_E - LTT_TT_ACTION table.
 *  CPSS_DXCH2_UC_MC_ROUTE_NEXT_HOP_E - UC_MC_ROUTE_NEXT_HOP table.
 *  CPSS_DXCH2_ROUTE_NEXT_HOP_AGE_E - ROUTE_NEXT_HOP_AGE table.
 *  CPSS_DXCH3_TABLE_MAC2ME_E - MAC2ME table.
 *  CPSS_DXCH3_TABLE_INGRESS_VLAN_TRANSLATION_E - INGRESS_VLAN_TRANSLATION table.
 *  CPSS_DXCH3_TABLE_EGRESS_VLAN_TRANSLATION_E - EGRESS_VLAN_TRANSLATION table.
 *  CPSS_DXCH3_TABLE_VRF_ID_E - VRF_ID table.
 *  CPSS_DXCH3_LTT_TT_ACTION_E - LTT_TT_ACTION table.
 *  CPSS_DXCH_XCAT_TABLE_INGRESS_PCL_LOOKUP1_CONFIG_E - INGRESS_PCL_LOOKUP1 table.
 *  CPSS_DXCH_XCAT_TABLE_INGRESS_PCL_UDB_CONFIG_E - INGRESS_PCL_UDB table.
 *  CPSS_DXCH_XCAT_TABLE_LOGICAL_TARGET_MAPPING_E -LOGICAL_TARGET_MAPPING table.
 *  CPSS_DXCH_XCAT_TABLE_BCN_PROFILES_E -BCN_PROFILES table.
 *  CPSS_DXCH_XCAT_TABLE_EGRESS_POLICER_REMARKING_E - Egress Policer Remarking table.
 *  CPSS_DXCH_XCAT_TABLE_EQ_VLAN_MAPPING_E - Egress Filter Vlan Mapping table.
 *  CPSS_DXCH_XCAT_TABLE_EQ_LP_EGRESS_VLAN_MEMBER_E - Egress Filter Vlan Member table.
 *  CPSS_DXCH_XCAT_TABLE_MLL_L2MLL_VIDX_ENABLE_E - L2MLL VIDX enable table.
 *  CPSS_DXCH_XCAT_TABLE_MLL_L2MLL_POINTER_MAPPING_E - L2MLL Pointer Mapping table.
 *  CPSS_DXCH_XCAT_TABLE_LAST_E - last for XCAT supported tables.
 *  CPSS_DXCH_XCAT3_TABLE_LAST_E - last for XCAT3 supported tables.
 *  xCat2, Lion2 and above tables:
 *  CPSS_DXCH_XCAT2_TABLE_INGRESS_PCL_LOOKUP01_CONFIG_E - INGRESS_PCL_LOOKUP01 table.
 *  CPSS_DXCH_LION_TABLE_TRUNK_HASH_MASK_CRC_E -  trunk hash mask crc table
 *  CPSS_DXCH_XCAT2_TABLE_LAST_E - last for XCAT2 supported tables.
 *  CPSS_DXCH_LION_TABLE_VLAN_INGRESS_E        - ingress VLAN table
 *  CPSS_DXCH_LION_TABLE_VLAN_EGRESS_E         - egress VLAN table
 *  CPSS_DXCH_LION_TABLE_STG_INGRESS_E         - ingress STG table
 *  CPSS_DXCH_LION_TABLE_STG_EGRESS_E          - egress STG table
 *  CPSS_DXCH_LION_TABLE_PORT_ISOLATION_L2_E   - port isolation L2 table
 *  CPSS_DXCH_LION_TABLE_PORT_ISOLATION_L3_E   - port isolation L3 table
 *  CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E -
 *              txq shaper - per port per TC token bucket configuration
 *  CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG_E -
 *              txq shaper - per port token bucket configuration
 *  CPSS_DXCH_LION_TABLE_TXQ_SOURCE_ID_MEMBERS_E -
 *              txq source Id members table
 *  CPSS_DXCH_LION_TABLE_TXQ_NON_TRUNK_MEMBERS_E -
 *              txq non trunk members table
 *  CPSS_DXCH_LION_TABLE_TXQ_DESIGNATED_PORT_E -
 *              txq designated port table
 *  CPSS_DXCH_LION_TABLE_TXQ_EGRESS_STC_E -
 *              txq egress STC (Sampling To CPU) table
 *  CPSS_DXCH_LION_TABLE_ROUTER_VLAN_URPF_STC_E -
 *              unicast RPF STC (Sampling To CPU) table
 *  CPSS_DXCH_LION_TABLE_LAST_E - last table ID supported by Lion devices
 *
 *  Bobcat2 and above
 *  CPSS_DXCH_SIP5_TABLE_TTI_PHYSICAL_PORT_ATTRIBUTE_E -
 *              TTI Physical ports attributes table
 *  CPSS_DXCH_SIP5_TABLE_PRE_TTI_LOOKUP_INGRESS_EPORT_E -
 *              TTI pre lookup ingress ePort table
 *  CPSS_DXCH_SIP5_TABLE_POST_TTI_LOOKUP_INGRESS_EPORT_E -
 *              TTI post lookup ingress ePort table
 *  CPSS_DXCH_SIP5_TABLE_BRIDGE_INGRESS_EPORT_E -
 *              Bridge ingress ePort table
 *  CPSS_DXCH_SIP5_TABLE_BRIDGE_INGRESS_EPORT_LEARN_PRIO_E -
 *              Bridge ingress ePort table - for learn priority
 *  CPSS_DXCH_SIP5_TABLE_BRIDGE_SOURCE_TRUNK_ATTRIBUTE_E -
 *              Bridge source trunk attribute table
 *  CPSS_DXCH_SIP5_TABLE_BRIDGE_PHYSICAL_PORT_E -
 *              Bridge per physical port info table (rate limit configuration)
 *  CPSS_DXCH_SIP5_TABLE_BRIDGE_PHYSICAL_PORT_RATE_LIMIT_COUNTERS_E,
 *              Bridge per physical port rate limit counters table
 *  CPSS_DXCH_SIP5_TABLE_EQ_INGRESS_EPORT_E -
 *              Pre-egress ingress ePort table
 *  PRV_CPSS_DXCH_SIP5_TABLE_EQ_EGRESS_EPORT_E -
 *              Pre-egress egress ePort table
 *  PRV_CPSS_DXCH_SIP5_TABLE_L2_ECMP_LTT_E -
 *              L2 ECMP LTT table
 *  PRV_CPSS_DXCH_SIP5_TABLE_L2_ECMP_E -
 *              L2 ECMP table
 *  PRV_CPSS_DXCH_SIP5_TABLE_EPORT_TO_PHYSICAL_PORT_TARGET_MAPPING_E -
 *              ePort to physical port mapping table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_EFT_FAST_STACK_FAILOVER_SECONDARY_TARGET_PORT_E -
 *              EGF - Fast Stack Failover Secondary Target Port Table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_EGRESS_EPORT_E -
 *              EGF_QAG - egress ePort table (in addition to the one in EGF_SHT !!!)
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_EGRESS_VLAN_E -
 *              EGF_QAG - egress eVlan table (in addition to the one in EGF_SHT !!!)
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_TARGET_PORT_MAPPER_E -
 *              EGF_QAG - Target Port Mapper
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_CPU_CODE_TO_LOOPBACK_MAPPER_E -
 *              EGF_QAG - CPU Code To Loopback Mapper
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_FWD_FROM_CPU_TO_LOOPBACK_MAPPER_E -
 *              EGF_QAG - Forward from CPU To Loopback Mapper
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_EGRESS_EPORT_E -
 *              EGF_SHT - egress ePort table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_DEVICE_MAP_TABLE_E -
 *              EGF_SHT - device map table
 *  CPSS_DXCH_SIP5_TABLE_HA_EGRESS_EPORT_1_E -
 *              Header Alteration egress ePort table 1
 *  CPSS_DXCH_SIP5_TABLE_HA_EGRESS_EPORT_2_E -
 *              Header Alteration egress ePort table 2
 *  CPSS_DXCH_SIP5_TABLE_HA_PHYSICAL_PORT_1_E -
 *              Header Alteration physical port table 1
 *  CPSS_DXCH_SIP5_TABLE_HA_PHYSICAL_PORT_2_E -
 *              Header Alteration physical port table 2
 *  CPSS_DXCH_SIP5_TABLE_HA_QOS_PROFILE_TO_EXP_E -
 *              Header Alteration - QosProfile to EXP mapping
 *  CPSS_DXCH_SIP5_TABLE_HA_EPCL_UDB_CONFIG_E -
 *              Header Alteration - EPCL UDB configuration table
 *  CPSS_DXCH_SIP5_TABLE_HA_PTP_DOMAIN_E -
 *              Header Alteration - PTP Domain table
 *  CPSS_DXCH_SIP5_TABLE_HA_GENERIC_TS_PROFILE_E -
 *              Header Alteration - Generic Tunnel Start Profile table
 *  CPSS_DXCH_SIP5_TABLE_HA_GLOBAL_MAC_SA_E -
 *              Header Alteration - Global MAC SA table
 *  CPSS_DXCH_SIP5_TABLE_IP_MLL_E -
 *              MLL - IP MLL table
 *              NOTE: the table is same one as 'L2 MLL' , but the separation is ONLY for 'fields' format usage.
 *  CPSS_DXCH_SIP5_TABLE_L2_MLL_E -
 *              MLL - L2 MLL table
 *              NOTE: the table is same one as 'IP MLL' , but the separation is ONLY for 'fields' format usage.
 *  CPSS_DXCH_SIP5_TABLE_L2_MLL_LTT_E -
 *              L2 MLL LTT table
 *  PRV_CPSS_DXCH_SIP5_TABLE_EGRESS_PCL_EPORT_ATTRIBUTES_E -
 *              Egress PCL ePort attributes table
 *  CPSS_DXCH_SIP5_TABLE_ADJACENCY_E -
 *              TRILL Adjacency table
 *
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_E_ATTRIBUTES_E -
 *              ingress policer stage 0 e-attributes table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_REMARKING_E -
 *              ingress policer stage 0 Re-marking table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_HIERARCHICAL_E -
 *              ingress policer stage 0 hierarchical policing table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_METERING_E -
 *              ingress policer stage 0 metering table
 *
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_E_ATTRIBUTES_E -
 *              ingress policer stage 1 e-attributes table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_REMARKING_E -
 *              ingress policer stage 1 Re-marking table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_METERING_E -
 *              ingress policer stage 1 metering table
 *
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_POLICER_E_ATTRIBUTES_E -
 *              egress policer e-attributes table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_POLICER_METERING_E -
 *              egress policer metering table
 *
 *  CPSS_DXCH_SIP5_TABLE_IPVX_INGRESS_EPORT_E -
 *              IPvX Ingress ePort table
 *  CPSS_DXCH_SIP5_TABLE_IPVX_EVLAN_E -
 *              IPvX eVlan table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_E -
 *              ingress OAM table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_KEEPALIVE_AGING_E -
 *              ingress OAM Aging table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_MEG_EXCEPTION_E -
 *              ingress OAM MEG Exception table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_SOURCE_INTERFACE_EXCEPTION_E -
 *              ingress OAM Source Interface Exception table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_INVALID_KEEPALIVE_HASH_E -
 *              ingress OAM Invalid Keepalive Hash table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_KEEPALIVE_EXCESS_E -
 *              ingress OAM Excess Keepalive table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_EXCEPTION_SUMMARY_E -
 *              ingress OAM Exception Summary table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_RDI_STATUS_CHANGE_EXCEPTION_E -
 *              ingress OAM RDI Status Cheange Exception table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_TX_PERIOD_EXCEPTION_E -
 *              ingress OAM Tx Period Exception table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_OPCODE_PACKET_COMMAND_E -
 *              ingress OAM Opcode Packet Command table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_E
 *              egress OAM table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_KEEPALIVE_AGING_E
 *              egress OAM aging table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_MEG_EXCEPTION_E
 *              egress OAM MEG Exception table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_SOURCE_INTERFACE_EXCEPTION_E
 *              egress OAM Source Interface Exception table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_INVALID_KEEPALIVE_HASH_E
 *              egress OAM Invalid Keepalive Hash table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_KEEPALIVE_EXCESS_E
 *              egress OAM Excess Keepalive table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_EXCEPTION_SUMMARY_E
 *              egress OAM Exception Summary table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_RDI_STATUS_CHANGE_EXCEPTION_E
 *              egress OAM RDI Status Cheange Exception table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_TX_PERIOD_EXCEPTION_E
 *              egress OAM Tx Period Exception table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_OPCODE_PACKET_COMMAND_E
 *              egress OAM Opcode Packet Command table
 *  CPSS_DXCH_SIP5_TABLE_OAM_LM_OFFSET_E
 *              OAM Loss Measurement Offset Table
 *  CPSS_DXCH_SIP5_TABLE_TTI_QOS_MAP_DSCP_TO_QOS_PROFILE_E
 *              TTI unit : Qos mapping : dscp to qos profile
 *  CPSS_DXCH_SIP5_TABLE_TTI_QOS_MAP_UP_CFI_TO_QOS_PROFILE_E
 *              TTI unit : Qos mapping : up,cfi to qos profile
 *  CPSS_DXCH_SIP5_TABLE_TTI_QOS_MAP_EXP_TO_QOS_PROFILE_E
 *              TTI unit : Qos mapping : ext to qos profile
 *  CPSS_DXCH_SIP5_TABLE_TTI_QOS_MAP_DSCP_TO_DSCP_E
 *              TTI unit : Qos mapping : dscp to dscp
 *  CPSS_DXCH_SIP5_TABLE_TTI_UDB_CONFIG_E -
 *              TTI User Defined Bytes Configuration Memory
 *  CPSS_DXCH_SIP5_TABLE_TTI_PTP_COMMAND_E
 *              TTI PTP Command table
 *  CPSS_DXCH_SIP5_TABLE_IPCL0_UDB_SELECT_E -
 *              IPCL UDB selection table for lookup 0 (first lookup)
 *  CPSS_DXCH_SIP5_TABLE_IPCL1_UDB_SELECT_E -
 *              IPCL UDB selection table for lookup 1 (second lookup)
 *  CPSS_DXCH_SIP5_TABLE_IPCL2_UDB_SELECT_E -
 *              IPCL UDB selection table for lookup 2 (third lookup)
 *  CPSS_DXCH_SIP5_TABLE_TCAM_PCL_TTI_ACTION_E -
 *              the action table that is associated with the TCAM of TTI,IPCL(0,1,2),EPCL
 *  CPSS_DXCH_SIP5_TABLE_ERMRK_TIMESTAMP_CFG_E -
 *              Timestamp Configuration Table, ERMRK
 *  CPSS_DXCH_SIP5_TABLE_ERMRK_PTP_LOCAL_ACTION_E -
 *              Local Action Table, ERMRK
 *  CPSS_DXCH_SIP5_TABLE_ERMRK_PTP_TARGET_PORT_E -
 *              Target Port Table, ERMRK
 *  CPSS_DXCH_SIP5_TABLE_ERMRK_PTP_SOURCE_PORT_E -
 *              Source Port Table, ERMRK
 *  CPSS_DXCH_SIP5_TABLE_TCAM_E -
 *              TCAM memory table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_BRIDGE_PORT_MEMBERS_E -
 *              ingress Bridge Port Membership Table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_SPAN_STATE_GROUP_INDEX_E -
 *              ingress Span State Group Index Table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_VLAN_ATTRIBUTES_E  -
 *              egress VLAN attributes table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_VLAN_SPANNING_E    -
 *              egress VLAN spanning tree table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_VLAN_MAPPER_E      -
 *              egress VLAN ID mapper table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_NON_TRUNK_MEMBERS2_E -
 *              non trunk members2 table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_EPORT_FILTER_E -
 *              ePort egress filtering table
 *  CPSS_DXCH_SIP5_TABLE_EPCL_UDB_SELECT_E             -
 *              EPCL UDB selection.
 *  CPSS_DXCH_SIP5_TABLE_BMA_PORT_MAPPING_E
 *              BMA port mapping
 *  CPSS_DXCH_SIP5_TABLE_BMA_MULTICAST_COUNTERS_E -
 *              BMA multicast counters
 *  CPSS_DXCH_SIP5_TABLE_TAIL_DROP_MAX_QUEUE_LIMITS_E -
 *              Tail Drop Maximum Queue Limits
 *  CPSS_DXCH_SIP5_TABLE_TAIL_DROP_EQ_QUEUE_LIMITS_DP0_E -
 *              Tail Drop Queue Limits DP0 - Enqueue
 *  CPSS_DXCH_SIP5_TABLE_TAIL_DROP_DQ_QUEUE_BUF_LIMITS_E -
 *              Tail Drop Queue Buffer Limits - Dequeue
 *  CPSS_DXCH_SIP5_TABLE_TAIL_DROP_DQ_QUEUE_DESC_LIMITS_E -
 *              Tail Drop Queue Descriptor Limits - Dequeue
 *  CPSS_DXCH_SIP5_TABLE_TAIL_DROP_EQ_QUEUE_LIMITS_DP1_E -
 *              Tail Drop Queue Limits DP1 - Enqueue
 *  CPSS_DXCH_SIP5_TABLE_TAIL_DROP_EQ_QUEUE_LIMITS_DP2_E -
 *              Tail Drop Queue Limits DP2 - Enqueue
 *
 *  CPSS_DXCH_SIP5_TABLE_TAIL_DROP_COUNTERS_Q_MAIN_BUFF_E -
 *              Tail Drop Counters - Buffers Queue Maintenance counters
 *  CPSS_DXCH_SIP5_TABLE_TAIL_DROP_COUNTERS_Q_MAIN_MC_BUFF_E -
 *              Tail Drop Counters - Multicast Buffers Queue Maintenance counters.
 *
 *  CPSS_DXCH_SIP5_TABLE_TXQ_LINK_LIST_COUNTERS_Q_MAIN_DESC_E -
 *              TXQ LL - Queue Maintenance Descriptors Counters.
 *
 *  CPSS_DXCH_SIP5_TABLE_PFC_MODE_PROFILE_TC_XOFF_THRESHOLDS_E -
 *              FC Mode Profile TC XOff Thresholds
 *  CPSS_DXCH_SIP5_TABLE_PFC_MODE_PROFILE_TC_XON_THRESHOLDS_E -
 *              FC Mode Profile TC XOn Thresholds
 *  CPSS_DXCH_SIP5_TABLE_PFC_LLFC_COUNTERS_E -
 *              PFC Counters
 *
 *  CPSS_DXCH_SIP5_TABLE_TM_DROP_DROP_MASKING_E       -
 *              indicates if to use recommendation from TM for dropping decision.
 *  CPSS_DXCH_SIP5_TABLE_TM_DROP_QUEUE_PROFILE_ID_E   -
 *              maps every queue to its profile.
 *
 *  PCPSS_DXCH_SIP5_TABLE_TM_QMAP_CPU_CODE_TO_TC_E         -
 *              map CpuCode to TC for TO_CPU packets.
 *  PCPSS_DXCH_SIP5_TABLE_TM_QMAP_TARGET_DEV_TO_INDEX_E    -
 *              map TrgDev to an index which used to access Queue Selector table.
 *  PCPSS_DXCH_SIP5_TABLE_TM_QMAP_POLICING_ENABLE_E        -
 *              force policing per TM-Queue-ID.
 *  PCPSS_DXCH_SIP5_TABLE_TM_QMAP_QUEUE_ID_SELECTOR_E -
 *              indicates how to build the TM-Queue-ID.
 *
 *  CPSS_DXCH_SIP5_TABLE_TM_INGR_GLUE_L1_PKT_LEN_OFFSET_E -
 *              TM ingress L1 packet length offset configuration.
 *
 *  CPSS_DXCH_SIP5_TABLE_TM_EGR_GLUE_AGING_QUEUE_PROFILE_E     -
 *              TM Egress Aging Queue Profile.
 *  CPSS_DXCH_SIP5_TABLE_TM_EGR_GLUE_AGING_PROFILE_THESHOLDS_E -
 *              TM Egress Aging Profile Thresholds.
 *  CPSS_DXCH_SIP5_TABLE_TM_EGR_GLUE_TARGET_INTERFACE_E        -
 *              TM Egress Target Interface.
 *
 *  CPSS_DXCH_SIP5_TABLE_TM_FCU_ETH_DMA_TO_TM_PORT_MAPPING_E -
 *              Ethernet DMA to TM port mapping.
 *  CPSS_DXCH_SIP5_TABLE_TM_FCU_ILK_DMA_TO_TM_PORT_MAPPING_E -
 *              Interlaken DMA to TM port mapping.
 *  CPSS_DXCH_SIP5_TABLE_TM_FCU_TC_PORT_TO_CNODE_PORT_MAPPING_E -
 *              TC port to CNode port mapping.
 *  CPSS_DXCH_SIP5_TABLE_TM_FCU_PORT_INGRESS_TIMERS_CONFIG_E -
 *              IPort Configuration.
 *  CPSS_DXCH_SIP5_TABLE_TM_FCU_INGRESS_TIMERS_E -
 *              Ingress Timers.
 *  CPSS_DXCH_SIP5_TABLE_TM_FCU_PORT_TO_PHYSICAL_PORT_MAPPING_E -
 *              FCU PFC port to Physical port mapping.
 *
 *  CPSS_DXCH_SIP5_TABLE_CN_SAMPLE_INTERVALS_E -
 *              CN Sample Intervals table
 *
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_COUNTING_E -
 *              ingress policer stage 0 counting table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_COUNTING_E -
 *              ingress policer stage 1 counting table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_POLICER_COUNTING_E -
 *              egress policer counting table
 *
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_IPFIX_ALERT_AGING_E -
 *              ingress policer stage 0 IPFIX alert aging table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_IPFIX_ALERT_AGING_E -
 *              ingress policer stage 1 IPFIX alert aging table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_POLICER_IPFIX_ALERT_AGING_E -
 *              egress policer IPFIX alert aging table
 *
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_IPFIX_ALERT_WRAPAROUND_E -
 *              ingress policer stage 0 IPFIX alert wraparound table
 *  CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_IPFIX_ALERT_WRAPAROUND_E -
 *              ingress policer stage 1 IPFIX alert wraparound table
 *  CPSS_DXCH_SIP5_TABLE_EGRESS_POLICER_IPFIX_ALERT_WRAPAROUND_E -
 *              egress policer IPFIX alert wraparound table
 *
 *  CPSS_DXCH_SIP5_TABLE_CNC_0_COUNTERS_E  - cnc block 0 (out of 31)
 *      ... cnc block 1..30
 *  CPSS_DXCH_SIP5_TABLE_CNC_31_COUNTERS_E - cnc block 31 (out of 31)
 *
 *
 *  CPSS_DXCH_BOBCAT2_TABLE_LAST_E - last table ID supported by Bobcat2 devices
 *
 *  CPSS_DXCH_SIP5_15_TABLE_INGRESS_POLICER_0_METERING_CONFIG_E - bobk : iplr0 : meter config table.
 *  CPSS_DXCH_SIP5_15_TABLE_INGRESS_POLICER_1_METERING_CONFIG_E - bobk : iplr1 : meter config table.
 *  CPSS_DXCH_SIP5_15_TABLE_EGRESS_POLICER_METERING_CONFIG_E - bobk : eplr  : meter config table.
 *  CPSS_DXCH_SIP5_15_TABLE_INGRESS_POLICER_0_METERING_CONFORM_SIGN_E - bobk : iplr0 : conformance sign
 *  CPSS_DXCH_SIP5_15_TABLE_INGRESS_POLICER_1_METERING_CONFORM_SIGN_E - bobk : iplr1 : conformance sign
 *  CPSS_DXCH_SIP5_15_TABLE_EGRESS_POLICER_METERING_CONFORM_SIGN_E    - bobk : eplr  : conformance sign
 *
 *  CPSS_DXCH_SIP5_15_TABLE_LAST_E - last table ID supported by BobK devices
 *
 *  CPSS_DXCH_SIP5_20_TABLE_EGF_QAG_PORT_TARGET_ATTRIBUTES_E - (sip_5_20) EGF_QAG : physical port target attribute table
 *  CPSS_DXCH_SIP5_20_TABLE_TTI_PHYSICAL_PORT_ATTRIBUTE_2_E - (sip_5_20) TTI : physical port target attribute table 2
 *  CPSS_DXCH_SIP5_20_TABLE_TTI_QCN_TO_TIMER_PAUSE_MAP_E - (sip_5_20) TTI : QCN to Pause Timer Map
 *  CPSS_DXCH_SIP5_20_TABLE_EQ_TX_PROTECTION_LOC_E  - (sip_5_20) EQ : TX protection LOC table
 *  CPSS_DXCH_SIP5_20_TABLE_EGF_QAG_TC_DP_MAPPER_E  - (sip_5_20) EGF_QAG : TC,DP mapping table
 *
 *   ------------ MULTI-instance support
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_1_E    - CPSS_DXCH_LION_TABLE_TXQ_EGRESS_STC_E : DQ[1]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_2_E    - CPSS_DXCH_LION_TABLE_TXQ_EGRESS_STC_E : DQ[2]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_3_E    - CPSS_DXCH_LION_TABLE_TXQ_EGRESS_STC_E : DQ[3]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_4_E    - CPSS_DXCH_LION_TABLE_TXQ_EGRESS_STC_E : DQ[4]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_5_E    - CPSS_DXCH_LION_TABLE_TXQ_EGRESS_STC_E : DQ[5]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_LAST_E = CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_5_E
 *
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_1_E    - CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG_E : DQ[1]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_2_E    - CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG_E : DQ[2]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_3_E    - CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG_E : DQ[3]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_4_E    - CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG_E : DQ[4]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_5_E    - CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG_E : DQ[4]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_LAST_E = CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_5_E
 *
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_1_E    - CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E : DQ[1]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_2_E    - CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E : DQ[2]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_3_E    - CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E : DQ[3]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_4_E    - CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E : DQ[4]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_5_E    - CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E : DQ[5]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_LAST_E = CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_5_E
 *
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_0_E : TTI Port Mapping Table (= PFC Response Port Mapping Table), DQ[0]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_1_E : TTI Port Mapping Table (= PFC Response Port Mapping Table), DQ[1]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_2_E : TTI Port Mapping Table (= PFC Response Port Mapping Table), DQ[2]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_3_E : TTI Port Mapping Table (= PFC Response Port Mapping Table), DQ[3]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_4_E : TTI Port Mapping Table (= PFC Response Port Mapping Table), DQ[4]
 *   CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_5_E : TTI Port Mapping Table (= PFC Response Port Mapping Table), DQ[5]
 *
 *  CPSS_DXCH_SIP5_20_TABLE_LAST_E - last table ID supported by Bobcat3 devices
 *
 *  PRV_DXCH_SIP5_25_TABLE_IPVX_ROUTER_ECMP_POINTER_E - (sip_5_25) IPvX : ECMP pointer table.
 *
 *  CPSS_DXCH_SIP5_25_TABLE_LAST_E - last table ID supported by Aldrin2 devices
 *
 *  CPSS_DXCH_SIP6_TABLE_INGRESS_PCL_HASH_MODE_CRC_E - IPCL Hash Mode Table
 *
 *  CPSS_DXCH_SIP6_TABLE_TTI_PORT_TO_QUEUE_TRANSLATION_TABLE_E - TTI port2Queue translation Table
 *
 *  CPSS_DXCH_SIP6_TABLE_EXACT_MATCH_E - Exact Match table
 *
 *  CPSS_DXCH_SIP6_TABLE_LAST_E,
 *
 *  CPSS_DXCH_TABLE_LAST_E - last table (must be last enum value)
 *
 *  NOTE:
 *
*/

typedef enum
{
    CPSS_DXCH_TABLE_VLAN_PORT_PROTOCOL_E = 0,
    CPSS_DXCH_TABLE_PORT_VLAN_QOS_E,
    CPSS_DXCH_TABLE_TRUNK_MEMBERS_E,
    CPSS_DXCH_TABLE_STATISTICAL_RATE_LIMIT_E,
    CPSS_DXCH_TABLE_CPU_CODE_E,
    CPSS_DXCH_TABLE_PCL_CONFIG_E,     /*first lookup (00)*/
    CPSS_DXCH_TABLE_QOS_PROFILE_E,
    CPSS_DXCH_TABLE_REMARKING_E,
    CPSS_DXCH_TABLE_STG_E,
    CPSS_DXCH_TABLE_VLAN_E,
    CPSS_DXCH_TABLE_MULTICAST_E,
    CPSS_DXCH_TABLE_ROUTE_HA_MAC_SA_E,
    CPSS_DXCH_TABLE_ROUTE_HA_ARP_DA_E, /* only in CH 1 - for others see 'tunnel start' */
    CPSS_DXCH_TABLE_FDB_E,
    CPSS_DXCH_TABLE_POLICER_E,
    CPSS_DXCH_TABLE_POLICER_COUNTERS_E,
    CPSS_DXCH2_TABLE_EGRESS_PCL_CONFIG_E,
    CPSS_DXCH2_TABLE_TUNNEL_START_CONFIG_E,
    CPSS_DXCH2_TABLE_QOS_PROFILE_TO_ROUTE_BLOCK_E,
    CPSS_DXCH2_TABLE_ROUTE_ACCESS_MATRIX_E,
    CPSS_DXCH2_LTT_TT_ACTION_E,
    CPSS_DXCH2_UC_MC_ROUTE_NEXT_HOP_E,
    CPSS_DXCH2_ROUTE_NEXT_HOP_AGE_E,
    CPSS_DXCH3_TABLE_MAC2ME_E,
    CPSS_DXCH3_TABLE_INGRESS_VLAN_TRANSLATION_E,
    CPSS_DXCH3_TABLE_EGRESS_VLAN_TRANSLATION_E,
    CPSS_DXCH3_TABLE_VRF_ID_E,
    CPSS_DXCH3_LTT_TT_ACTION_E,
    CPSS_DXCH_XCAT_TABLE_INGRESS_PCL_LOOKUP1_CONFIG_E,/*third lookup(1)*/
    CPSS_DXCH_XCAT_TABLE_INGRESS_PCL_UDB_CONFIG_E,
    CPSS_DXCH_XCAT_TABLE_LOGICAL_TARGET_MAPPING_E,
    CPSS_DXCH_XCAT_TABLE_BCN_PROFILES_E,
    CPSS_DXCH_XCAT_TABLE_EGRESS_POLICER_REMARKING_E,
    CPSS_DXCH_XCAT_TABLE_EQ_VLAN_MAPPING_E,
    CPSS_DXCH_XCAT_TABLE_EQ_LP_EGRESS_VLAN_MEMBER_E,
    CPSS_DXCH_XCAT_TABLE_MLL_L2MLL_VIDX_ENABLE_E,
    CPSS_DXCH_XCAT_TABLE_MLL_L2MLL_POINTER_MAPPING_E,
    CPSS_DXCH_XCAT_TABLE_INGRESS_ECID_E,

    /* "L2 MLL" and "IP MLL" Table */
    CPSS_DXCH_XCAT_TABLE_MLL_E,

    /* MIB Counters Table */
    CPSS_DXCH_XCAT_TABLE_MIB_COUNTERS_E,

    /* Port isolation tables supported from XCAT3, AC5 and above devices */
    CPSS_DXCH_LION_TABLE_PORT_ISOLATION_L2_E,
    CPSS_DXCH_LION_TABLE_PORT_ISOLATION_L3_E,

    /* Policer metering tables, supported from XCAT3, AC5 and above devices */
    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_METERING_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_METERING_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_POLICER_METERING_E,

    /* Policer counting tables, supported from XCAT3, AC5 and above devices */
    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_COUNTING_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_COUNTING_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_POLICER_COUNTING_E,

    /* must be last for XCAT supported tables */
    CPSS_DXCH_XCAT_TABLE_LAST_E,

    /* must be last for XCAT3 supported tables */
    CPSS_DXCH_XCAT3_TABLE_LAST_E =
        CPSS_DXCH_XCAT_TABLE_LAST_E,

    /* based on the end of XCAT values end */
    CPSS_DXCH_XCAT2_TABLE_INGRESS_PCL_LOOKUP01_CONFIG_E = /*second lookup(01)*/
        CPSS_DXCH_XCAT3_TABLE_LAST_E,

    /* supported in XCAT2, Lion2 and above devices*/
    CPSS_DXCH_LION_TABLE_TRUNK_HASH_MASK_CRC_E,

    /* must be last for XCAT2 supported tables */
    CPSS_DXCH_XCAT2_TABLE_LAST_E,

    /* based on the end of XCAT2 values end */
    CPSS_DXCH_LION_TABLE_VLAN_INGRESS_E =
        CPSS_DXCH_XCAT2_TABLE_LAST_E,
    CPSS_DXCH_LION_TABLE_VLAN_EGRESS_E,
    CPSS_DXCH_LION_TABLE_STG_INGRESS_E,
    CPSS_DXCH_LION_TABLE_STG_EGRESS_E,

    CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E,
    CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG_E,

    CPSS_DXCH_LION_TABLE_TXQ_SOURCE_ID_MEMBERS_E,
    CPSS_DXCH_LION_TABLE_TXQ_NON_TRUNK_MEMBERS_E,
    CPSS_DXCH_LION_TABLE_TXQ_DESIGNATED_PORT_E,
    CPSS_DXCH_LION_TABLE_TXQ_EGRESS_STC_E,

    CPSS_DXCH_LION_TABLE_ROUTER_VLAN_URPF_STC_E,

    /* must be last for LION supported tables */
    CPSS_DXCH_LION_TABLE_LAST_E,

    /* must be last for LION2 supported tables */
    CPSS_DXCH_LION2_TABLE_LAST_E,

    /* based on the end of LION values end */
    CPSS_DXCH_SIP5_TABLE_TTI_PHYSICAL_PORT_ATTRIBUTE_E =
        CPSS_DXCH_LION2_TABLE_LAST_E,
    CPSS_DXCH_SIP5_TABLE_PRE_TTI_LOOKUP_INGRESS_EPORT_E,
    CPSS_DXCH_SIP5_TABLE_POST_TTI_LOOKUP_INGRESS_EPORT_E,
    CPSS_DXCH_SIP5_TABLE_BRIDGE_INGRESS_EPORT_E,
    CPSS_DXCH_SIP5_TABLE_BRIDGE_INGRESS_EPORT_LEARN_PRIO_E,
    CPSS_DXCH_SIP5_TABLE_BRIDGE_SOURCE_TRUNK_ATTRIBUTE_E,
    CPSS_DXCH_SIP5_TABLE_BRIDGE_PHYSICAL_PORT_E,
    CPSS_DXCH_SIP5_TABLE_BRIDGE_PHYSICAL_PORT_RATE_LIMIT_COUNTERS_E,

    CPSS_DXCH_SIP5_TABLE_EQ_INGRESS_EPORT_E,
    CPSS_DXCH_SIP5_TABLE_EQ_INGRESS_STC_PHYSICAL_PORT_E,
    CPSS_DXCH_SIP5_TABLE_EQ_INGRESS_MIRROR_PHYSICAL_PORT_E,
    CPSS_DXCH_SIP5_TABLE_EQ_TRUNK_LTT_E,
    CPSS_DXCH_SIP5_TABLE_EQ_L2_ECMP_LTT_E,
    CPSS_DXCH_SIP5_TABLE_EQ_L2_ECMP_E,
    CPSS_DXCH_SIP5_TABLE_EQ_EPORT_TO_PHYSICAL_PORT_TARGET_MAPPING_E,
    CPSS_DXCH_SIP5_TABLE_EQ_TO_CPU_RATE_LIMITER_CONFIG_E,
    CPSS_DXCH_SIP5_TABLE_EQ_TX_PROTECTION_E,
    CPSS_DXCH_SIP5_TABLE_EQ_EPORT_TO_LOC_MAPPING_E,
    CPSS_DXCH_SIP5_TABLE_EQ_PROTECTION_LOC_E,

    CPSS_DXCH_SIP5_TABLE_LPM_MEM_E,
    CPSS_DXCH_SIP5_TABLE_IPV4_VRF_E,
    CPSS_DXCH_SIP5_TABLE_IPV6_VRF_E,
    CPSS_DXCH_SIP5_TABLE_FCOE_VRF_E,
    CPSS_DXCH_SIP5_TABLE_ECMP_E,

    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_EFT_FAST_STACK_FAILOVER_SECONDARY_TARGET_PORT_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_EGRESS_EPORT_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_EGRESS_VLAN_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_TARGET_PORT_MAPPER_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_CPU_CODE_TO_LOOPBACK_MAPPER_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_QAG_FWD_FROM_CPU_TO_LOOPBACK_MAPPER_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_EGRESS_EPORT_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_DEVICE_MAP_TABLE_E,
    CPSS_DXCH_SIP5_TABLE_HA_EGRESS_EPORT_1_E,
    CPSS_DXCH_SIP5_TABLE_HA_EGRESS_EPORT_2_E,
    CPSS_DXCH_SIP5_TABLE_HA_PHYSICAL_PORT_1_E,
    CPSS_DXCH_SIP5_TABLE_HA_PHYSICAL_PORT_2_E,
    CPSS_DXCH_SIP5_TABLE_HA_QOS_PROFILE_TO_EXP_E,
    CPSS_DXCH_SIP5_TABLE_HA_EPCL_UDB_CONFIG_E,
    CPSS_DXCH_SIP5_TABLE_HA_PTP_DOMAIN_E,
    CPSS_DXCH_SIP5_TABLE_HA_GENERIC_TS_PROFILE_E,
    CPSS_DXCH_SIP5_TABLE_HA_GLOBAL_MAC_SA_E,
    CPSS_DXCH_SIP5_TABLE_IP_MLL_E,
    CPSS_DXCH_SIP5_TABLE_L2_MLL_E,
    CPSS_DXCH_SIP5_TABLE_L2_MLL_LTT_E,
    CPSS_DXCH_SIP5_TABLE_ADJACENCY_E,

    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_E_ATTRIBUTES_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_REMARKING_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_HIERARCHICAL_E,

    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_E_ATTRIBUTES_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_REMARKING_E,

    CPSS_DXCH_SIP5_TABLE_EGRESS_POLICER_E_ATTRIBUTES_E,

    CPSS_DXCH_SIP5_TABLE_IPVX_INGRESS_EPORT_E,
    CPSS_DXCH_SIP5_TABLE_IPVX_EVLAN_E,
    CPSS_DXCH_SIP5_TABLE_IPVX_ROUTER_NEXTHOP_E,
    CPSS_DXCH_SIP5_TABLE_IPVX_ROUTER_NEXTHOP_AGE_BITS_E,
    CPSS_DXCH_SIP5_TABLE_IPVX_ROUTER_ACCESS_MATRIX_E,
    CPSS_DXCH_SIP5_TABLE_IPVX_ROUTER_QOS_PROFILE_OFFSETS_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_KEEPALIVE_AGING_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_MEG_EXCEPTION_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_SOURCE_INTERFACE_EXCEPTION_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_INVALID_KEEPALIVE_HASH_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_KEEPALIVE_EXCESS_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_EXCEPTION_SUMMARY_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_RDI_STATUS_CHANGE_EXCEPTION_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_TX_PERIOD_EXCEPTION_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_OAM_OPCODE_PACKET_COMMAND_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_KEEPALIVE_AGING_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_MEG_EXCEPTION_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_SOURCE_INTERFACE_EXCEPTION_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_INVALID_KEEPALIVE_HASH_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_KEEPALIVE_EXCESS_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_EXCEPTION_SUMMARY_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_RDI_STATUS_CHANGE_EXCEPTION_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_TX_PERIOD_EXCEPTION_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_OAM_OPCODE_PACKET_COMMAND_E,
    CPSS_DXCH_SIP5_TABLE_OAM_LM_OFFSET_E,

    CPSS_DXCH_SIP5_TABLE_TTI_QOS_MAP_DSCP_TO_QOS_PROFILE_E,
    CPSS_DXCH_SIP5_TABLE_TTI_QOS_MAP_UP_CFI_TO_QOS_PROFILE_E,
    CPSS_DXCH_SIP5_TABLE_TTI_QOS_MAP_EXP_TO_QOS_PROFILE_E,
    CPSS_DXCH_SIP5_TABLE_TTI_QOS_MAP_DSCP_TO_DSCP_E,
    CPSS_DXCH_SIP5_TABLE_TTI_UDB_CONFIG_E,
    CPSS_DXCH_SIP5_TABLE_TTI_PTP_COMMAND_E,

    CPSS_DXCH_SIP5_TABLE_IPCL0_UDB_SELECT_E,
    CPSS_DXCH_SIP5_TABLE_IPCL1_UDB_SELECT_E,
    CPSS_DXCH_SIP5_TABLE_IPCL2_UDB_SELECT_E,

    CPSS_DXCH_SIP5_TABLE_TCAM_PCL_TTI_ACTION_E,

    CPSS_DXCH_SIP5_TABLE_ERMRK_TIMESTAMP_CFG_E,
    CPSS_DXCH_SIP5_TABLE_ERMRK_PTP_LOCAL_ACTION_E,
    CPSS_DXCH_SIP5_TABLE_ERMRK_PTP_TARGET_PORT_E,
    CPSS_DXCH_SIP5_TABLE_ERMRK_PTP_SOURCE_PORT_E,
    CPSS_DXCH_SIP5_TABLE_ERMRK_QOS_DSCP_MAP_E,
    CPSS_DXCH_SIP5_TABLE_ERMRK_QOS_TC_DP_MAP_E,

    CPSS_DXCH_SIP5_TABLE_TCAM_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_BRIDGE_PORT_MEMBERS_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_SPAN_STATE_GROUP_INDEX_E,

    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_VLAN_ATTRIBUTES_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_VLAN_SPANNING_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_VLAN_MAPPER_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_NON_TRUNK_MEMBERS2_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_EGF_SHT_EPORT_FILTER_E,

    CPSS_DXCH_SIP5_TABLE_EPCL_UDB_SELECT_E,

    CPSS_DXCH_SIP5_TABLE_BMA_PORT_MAPPING_E,
    CPSS_DXCH_SIP5_TABLE_BMA_MULTICAST_COUNTERS_E,

    CPSS_DXCH_SIP5_TABLE_TAIL_DROP_MAX_QUEUE_LIMITS_E,
    CPSS_DXCH_SIP5_TABLE_TAIL_DROP_EQ_QUEUE_LIMITS_DP0_E,
    CPSS_DXCH_SIP5_TABLE_TAIL_DROP_DQ_QUEUE_BUF_LIMITS_E,
    CPSS_DXCH_SIP5_TABLE_TAIL_DROP_DQ_QUEUE_DESC_LIMITS_E,
    CPSS_DXCH_SIP5_TABLE_TAIL_DROP_EQ_QUEUE_LIMITS_DP1_E,
    CPSS_DXCH_SIP5_TABLE_TAIL_DROP_EQ_QUEUE_LIMITS_DP2_E,

    CPSS_DXCH_SIP5_TABLE_TAIL_DROP_COUNTERS_Q_MAIN_BUFF_E,
    CPSS_DXCH_SIP5_TABLE_TAIL_DROP_COUNTERS_Q_MAIN_MC_BUFF_E,

    CPSS_DXCH_SIP5_TABLE_TXQ_LINK_LIST_COUNTERS_Q_MAIN_DESC_E,

    CPSS_DXCH_SIP5_TABLE_PFC_MODE_PROFILE_TC_XOFF_THRESHOLDS_E,
    CPSS_DXCH_SIP5_TABLE_PFC_MODE_PROFILE_TC_XON_THRESHOLDS_E,
    CPSS_DXCH_SIP5_TABLE_PFC_LLFC_COUNTERS_E,

    CPSS_DXCH_SIP5_TABLE_TM_DROP_DROP_MASKING_E,
    CPSS_DXCH_SIP5_TABLE_TM_DROP_QUEUE_PROFILE_ID_E,

    CPSS_DXCH_SIP5_TABLE_TM_QMAP_CPU_CODE_TO_TC_E,
    CPSS_DXCH_SIP5_TABLE_TM_QMAP_TARGET_DEV_TO_INDEX_E,
    CPSS_DXCH_SIP5_TABLE_TM_QMAP_POLICING_ENABLE_E,
    CPSS_DXCH_SIP5_TABLE_TM_QMAP_QUEUE_ID_SELECTOR_E,

    CPSS_DXCH_SIP5_TABLE_TM_INGR_GLUE_L1_PKT_LEN_OFFSET_E,

    CPSS_DXCH_SIP5_TABLE_TM_EGR_GLUE_AGING_QUEUE_PROFILE_E,
    CPSS_DXCH_SIP5_TABLE_TM_EGR_GLUE_AGING_PROFILE_THESHOLDS_E,
    CPSS_DXCH_SIP5_TABLE_TM_EGR_GLUE_TARGET_INTERFACE_E,

    CPSS_DXCH_SIP5_TABLE_TM_FCU_ETH_DMA_TO_TM_PORT_MAPPING_E,
    CPSS_DXCH_SIP5_TABLE_TM_FCU_ILK_DMA_TO_TM_PORT_MAPPING_E,
    CPSS_DXCH_SIP5_TABLE_TM_FCU_TC_PORT_TO_CNODE_PORT_MAPPING_E,
    CPSS_DXCH_SIP5_TABLE_TM_FCU_PORT_INGRESS_TIMERS_CONFIG_E,
    CPSS_DXCH_SIP5_TABLE_TM_FCU_INGRESS_TIMERS_E,
    CPSS_DXCH_SIP5_TABLE_TM_FCU_PORT_TO_PHYSICAL_PORT_MAPPING_E,

    CPSS_DXCH_SIP5_TABLE_CN_SAMPLE_INTERVALS_E,

    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_IPFIX_ALERT_WRAPAROUND_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_IPFIX_ALERT_WRAPAROUND_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_POLICER_IPFIX_ALERT_WRAPAROUND_E,

    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_0_IPFIX_ALERT_AGING_E,
    CPSS_DXCH_SIP5_TABLE_INGRESS_POLICER_1_IPFIX_ALERT_AGING_E,
    CPSS_DXCH_SIP5_TABLE_EGRESS_POLICER_IPFIX_ALERT_AGING_E,

    /* CNC counters for blocks 0..31 */
    CPSS_DXCH_SIP5_TABLE_CNC_0_COUNTERS_E ,
    CPSS_DXCH_SIP5_TABLE_CNC_31_COUNTERS_E = CPSS_DXCH_SIP5_TABLE_CNC_0_COUNTERS_E + 31,

    /* bobcat2 have no extra tables */
    CPSS_DXCH_BOBCAT2_TABLE_LAST_E,

    CPSS_DXCH_SIP5_15_TABLE_INGRESS_POLICER_0_METERING_CONFIG_E,
    CPSS_DXCH_SIP5_15_TABLE_INGRESS_POLICER_1_METERING_CONFIG_E,
    CPSS_DXCH_SIP5_15_TABLE_EGRESS_POLICER_METERING_CONFIG_E,

    CPSS_DXCH_SIP5_15_TABLE_INGRESS_POLICER_0_METERING_CONFORM_SIGN_E,
    CPSS_DXCH_SIP5_15_TABLE_INGRESS_POLICER_1_METERING_CONFORM_SIGN_E,
    CPSS_DXCH_SIP5_15_TABLE_EGRESS_POLICER_METERING_CONFORM_SIGN_E,

    CPSS_DXCH_SIP5_15_TABLE_LAST_E,

    CPSS_DXCH_SIP5_20_TABLE_EGF_QAG_PORT_SOURCE_ATTRIBUTES_E,
    CPSS_DXCH_SIP5_20_TABLE_EGF_QAG_PORT_TARGET_ATTRIBUTES_E,
    CPSS_DXCH_SIP5_20_TABLE_TTI_PHYSICAL_PORT_ATTRIBUTE_2_E,
    CPSS_DXCH_SIP5_20_TABLE_TTI_QCN_TO_TIMER_PAUSE_MAP_E,
    CPSS_DXCH_SIP5_20_TABLE_EQ_TX_PROTECTION_LOC_E,
    CPSS_DXCH_SIP5_20_TABLE_EGF_QAG_TC_DP_MAPPER_E,

    /* MULTI-instance support */
    /* DQ[0] is CPSS_DXCH_LION_TABLE_TXQ_EGRESS_STC_E */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_1_E,        /* DQ[1] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_2_E,        /* DQ[2] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_3_E,        /* DQ[3] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_4_E,        /* DQ[4] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_5_E,        /* DQ[5] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_LAST_E =
        CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TXQ_EGRESS_STC__DQ_5_E,

    /* DQ[0] is CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_1_E,         /* DQ[1] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_2_E,         /* DQ[2] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_3_E,         /* DQ[3] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_4_E,         /* DQ[4] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_5_E,         /* DQ[5] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_LAST_E =
        CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG__DQ_5_E,

    /* DQ[0] is CPSS_DXCH_LION_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_1_E,      /* DQ[1] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_2_E,      /* DQ[2] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_3_E,      /* DQ[3] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_4_E,      /* DQ[4] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_5_E,      /* DQ[5] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_LAST_E=   /* DQ[5] */
        CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG__DQ_5_E,

    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_EQ_INGRESS_STC_PHYSICAL_PORT_PIPE_1_E, /* pipe[1] */

    CPSS_DXCH_SIP5_20_TABLE_LPM_MEM_PIPE_1_E, /* LPM for pipe 1 (applicable for half memory mode) */

    /* CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_[0..5]_E are assumed to have consecutive numbers! */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_0_E,   /* DQ[0] */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_1_E,   /* DQ[1], value = "..._DQ_0_E" + 1 */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_2_E,   /* DQ[2], value = "..._DQ_0_E" + 2 */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_3_E,   /* DQ[3], value = "..._DQ_0_E" + 3 */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_4_E,   /* DQ[4], value = "..._DQ_0_E" + 4 */
    CPSS_DXCH_SIP5_20_MULTI_INSTANCE_TABLE_TTI_PORT_MAPPING__DQ_5_E,   /* DQ[5], value = "..._DQ_0_E" + 5 */

    CPSS_DXCH_SIP5_20_TABLE_LAST_E,

    CPSS_DXCH_SIP5_25_TABLE_IPVX_ROUTER_ECMP_POINTER_E,
    CPSS_DXCH_SIP5_25_TABLE_TAIL_DROP_PORT_MAX_BUFFER_FILL_LEVEL_E,
    CPSS_DXCH_SIP5_25_TABLE_TAIL_DROP_QUEUE_MAX_BUFFER_FILL_LEVEL_E,

    CPSS_DXCH_SIP5_25_TABLE_LAST_E,

    CPSS_DXCH_SIP6_TABLE_INGRESS_POLICER_0_QOS_ATTRIBUTE_TABLE_E,/* replaces regsAddrPtr->PLR[plrUnit].policerInitialDP[n] */
    CPSS_DXCH_SIP6_TABLE_INGRESS_POLICER_1_QOS_ATTRIBUTE_TABLE_E,/* replaces regsAddrPtr->PLR[plrUnit].policerInitialDP[n] */
    CPSS_DXCH_SIP6_TABLE_EGRESS_POLICER_QOS_ATTRIBUTE_TABLE_E,   /* replaces regsAddrPtr->PLR[plrUnit].policerInitialDP[n] */

    CPSS_DXCH_SIP6_TABLE_INGRESS_POLICER_0_PORT_ATTRIBUTE_TABLE_E,/* replaces regsAddrPtr->PLR[plrUnit].policerPortMeteringReg[n] */
    CPSS_DXCH_SIP6_TABLE_INGRESS_POLICER_1_PORT_ATTRIBUTE_TABLE_E,/* replaces regsAddrPtr->PLR[plrUnit].policerPortMeteringReg[n] */
    CPSS_DXCH_SIP6_TABLE_EGRESS_POLICER_PORT_ATTRIBUTE_TABLE_E,   /* replaces regsAddrPtr->PLR[plrUnit].policerPortMeteringReg[n] */

    /* SIP6 IPCL */
    CPSS_DXCH_SIP6_TABLE_INGRESS_PCL_HASH_MODE_CRC_E,

    /* SIP6 EPCL */
    CPSS_DXCH_SIP6_TABLE_EGRESS_PCL_EXACT_MATCH_PROFILE_ID_MAPPING_E,
    CPSS_DXCH_SIP6_TABLE_EGRESS_PCL_LATENCY_MONITORING_PROFILE_TO_SAMPLING_PROFILE_E,
    CPSS_DXCH_SIP6_TABLE_EGRESS_PCL_PORT_LATENCY_MONITORING_E,
    CPSS_DXCH_SIP6_TABLE_EGRESS_PCL_SOURCE_PHYSICAL_PORT_MAPPING_E,
    CPSS_DXCH_SIP6_TABLE_EGRESS_PCL_TARGET_PHYSICAL_PORT_MAPPING_E,

    /*TXQ - PDX tables*/

    CPSS_DXCH_SIP6_TXQ_PDX_DX_QGRPMAP_E,

    /*TXQ - PDS tables*/
    CPSS_DXCH_SIP6_TXQ_PDS_PER_QUEUE_COUNTERS_E,
    CPSS_DXCH_SIP6_TXQ_PDS_PER_QUEUE_COUNTERS_LAST_E = CPSS_DXCH_SIP6_TXQ_PDS_PER_QUEUE_COUNTERS_E+CPSS_DXCH_SIP6_MAX_PDS_UNITS_PER_DEVICE_MAC-1
     /*debug*/
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_PDS_DATA_STORAGE,CPSS_DXCH_SIP6_MAX_SDQ_UNITS_PER_DEVICE_MAC)
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_PDS_NXT_TABLE,CPSS_DXCH_SIP6_MAX_PDS_UNITS_PER_DEVICE_MAC)
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_PDS_PID_TABLE,CPSS_DXCH_SIP6_MAX_PDS_UNITS_PER_DEVICE_MAC)
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_PDS_HEAD_HEAD,CPSS_DXCH_SIP6_MAX_PDS_UNITS_PER_DEVICE_MAC)
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_PDS_HEAD_TAIL,CPSS_DXCH_SIP6_MAX_PDS_UNITS_PER_DEVICE_MAC)
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_PDS_TAIL_TAIL,CPSS_DXCH_SIP6_MAX_PDS_UNITS_PER_DEVICE_MAC)
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_PDS_TAIL_HEAD,CPSS_DXCH_SIP6_MAX_PDS_UNITS_PER_DEVICE_MAC)
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_PDS_FRAG_HEAD,CPSS_DXCH_SIP6_MAX_PDS_UNITS_PER_DEVICE_MAC)
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_PDS_FRAG_TAIL,CPSS_DXCH_SIP6_MAX_PDS_UNITS_PER_DEVICE_MAC)

    /*TXQ - SDQ tables*/

    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_SDQ_QUEUE_CFG,CPSS_DXCH_SIP6_MAX_SDQ_UNITS_PER_DEVICE_MAC)
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_SDQ_QUEUE_CRDT_BLNC,CPSS_DXCH_SIP6_MAX_SDQ_UNITS_PER_DEVICE_MAC)
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_SDQ_QUEUE_ELIG_STATE,CPSS_DXCH_SIP6_MAX_SDQ_UNITS_PER_DEVICE_MAC)
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_SDQ_PORT_CRDT_BLNC,CPSS_DXCH_SIP6_MAX_SDQ_UNITS_PER_DEVICE_MAC)
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_SDQ_SEL_LIST_PTRS,CPSS_DXCH_SIP6_MAX_SDQ_UNITS_PER_DEVICE_MAC)

    /*TXQ - PFCC tables*/
    ,PRV_CPSS_DXCH_TXQ_MULTIPLE_TABLE(CPSS_DXCH_SIP6_TXQ_PFCC_PFCC_CFG,CPSS_DXCH_SIP6_MAX_PFCC_UNITS_PER_DEVICE_MAC),

    /* TTI */
    CPSS_DXCH_SIP6_TABLE_TTI_PORT_TO_QUEUE_TRANSLATION_TABLE_E,
    CPSS_DXCH_SIP6_TABLE_TTI_VLAN_TO_VRF_ID_TABLE_E,

    /* PREQ */
    CPSS_DXCH_SIP6_TABLE_PREQ_CNC_PORT_MAPPING_E,
    CPSS_DXCH_SIP6_TABLE_PREQ_QUEUE_DP_CONFIGURATIONS_E,
    CPSS_DXCH_SIP6_TABLE_PREQ_QUEUE_CONFIGURATIONS_E,
    CPSS_DXCH_SIP6_TABLE_PREQ_PORT_PROFILE_E,
    CPSS_DXCH_SIP6_TABLE_PREQ_TARGET_PHYSICAL_PORT_E,

    /* EQ */
    CPSS_DXCH_SIP6_TABLE_EQ_L2ECMP_PATH_UTILIZATION_TABLE0_E,
    CPSS_DXCH_SIP6_TABLE_EQ_L2ECMP_PATH_UTILIZATION_TABLE1_E,
    CPSS_DXCH_SIP6_TABLE_EQ_L2ECMP_PATH_UTILIZATION_TABLE2_E,
    CPSS_DXCH_SIP6_TABLE_EQ_L2ECMP_PATH_UTILIZATION_TABLE3_E,

    /* IPVX */
    CPSS_DXCH_SIP6_TABLE_IPVX_ECMP_E,

    /* LPM */
    CPSS_DXCH_SIP6_TABLE_PBR_E,

    /* LPM Aging*/
    CPSS_DXCH_SIP6_TABLE_LPM_AGING_E,

    /* LMU */
    CPSS_DXCH_SIP6_TABLE_LMU_STATISTICS_E,
    CPSS_DXCH_SIP6_TABLE_LMU_STATISTICS_LAST_E = CPSS_DXCH_SIP6_TABLE_LMU_STATISTICS_E+CPSS_DXCH_SIP6_MAX_GOP_LMU_STATISTICS_MAC-1,
    CPSS_DXCH_SIP6_TABLE_LMU_CONFIGURATION_E,
    CPSS_DXCH_SIP6_TABLE_LMU_CONFIGURATION_LAST_E = CPSS_DXCH_SIP6_TABLE_LMU_CONFIGURATION_E+CPSS_DXCH_SIP6_MAX_GOP_LMU_CONFIGURATION_MAC-1,

    /* PHA */
    CPSS_DXCH_SIP6_TABLE_PHA_PPA_THREADS_CONF_1_E,
    CPSS_DXCH_SIP6_TABLE_PHA_PPA_THREADS_CONF_2_E,
    CPSS_DXCH_SIP6_TABLE_PHA_SOURCE_PHYSICAL_PORT_E,
    CPSS_DXCH_SIP6_TABLE_PHA_TARGET_PHYSICAL_PORT_E,
    CPSS_DXCH_SIP6_TABLE_PHA_FW_IMAGE_E,
    CPSS_DXCH_SIP6_TABLE_PHA_SHARED_DMEM_E,

    /* EXACT MATCH */
    CPSS_DXCH_SIP6_TABLE_EXACT_MATCH_E,

    /* PORT MAC COUNTERS */
    CPSS_DXCH_SIP6_TABLE_MTIP_MAC_STAT_E,

    CPSS_DXCH_SIP6_TABLE_LAST_E,        /* Falcon */

    /* Sip 6.10 - PPU */
    CPSS_DXCH_SIP6_10_TABLE_PPU_ACTION_TABLE_0_E,
    CPSS_DXCH_SIP6_10_TABLE_PPU_ACTION_TABLE_1_E,
    CPSS_DXCH_SIP6_10_TABLE_PPU_ACTION_TABLE_2_E,
    CPSS_DXCH_SIP6_10_TABLE_PPU_DAU_PROFILE_TABLE_E,

    /* sip6_10 */
    CPSS_DXCH_SIP6_10_TABLE_EXACT_MATCH_AUTO_LEARNED_ENTRY_INDEX_E,

    /* SIP6_10 - EPCL */
    CPSS_DXCH_SIP6_10_TABLE_EGRESS_PCL_QUEUE_GROUP_LATENCY_PROFILE_CONFIG_E,

    /* SIP6_10 - IPFIX 1st N PACKETS */
    CPSS_DXCH_SIP6_10_TABLE_INGRESS_POLICER_0_IPFIX_FIRST_N_PACKETS_E,
    CPSS_DXCH_SIP6_10_TABLE_INGRESS_POLICER_1_IPFIX_FIRST_N_PACKETS_E,
    CPSS_DXCH_SIP6_10_TABLE_EGRESS_POLICER_IPFIX_FIRST_N_PACKETS_E,

    /* SIP6_10 */
    CPSS_DXCH_SIP6_10_TABLE_SOURCE_PORT_HASH_ENTRY_E,

    /* SIP6_10 - IPCL: Source Port Configuration Table (PCL-ID2 bytes) */
    CPSS_DXCH_SIP6_10_TABLE_IPCL0_SOURCE_PORT_CONFIG_E,
    CPSS_DXCH_SIP6_10_TABLE_IPCL1_SOURCE_PORT_CONFIG_E,
    CPSS_DXCH_SIP6_10_TABLE_IPCL2_SOURCE_PORT_CONFIG_E,

    /* CNC counters for blocks 32..63 */
    CPSS_DXCH_SIP6_10_TABLE_CNC_32_COUNTERS_E ,
    CPSS_DXCH_SIP6_10_TABLE_CNC_63_COUNTERS_E = CPSS_DXCH_SIP6_10_TABLE_CNC_32_COUNTERS_E + 31,

    CPSS_DXCH_SIP6_10_TABLE_LAST_E,     /* AC5P   */

    CPSS_DXCH_SIP6_15_TXQ_SDQ_PORT_PFC_STATE_E,
    CPSS_DXCH_SIP6_15_TABLE_LAST_E,     /* AC5X   */

    CPSS_DXCH_SIP6_20_EGF_QAG_PORT_VLAN_Q_OFFSET_E,
    CPSS_DXCH_SIP6_20_TABLE_LAST_E,     /* Harrier   */

    CPSS_DXCH_SIP6_30_TABLE_IPCL0_UDB_REPLACEMENT_E,
    CPSS_DXCH_SIP6_30_TABLE_IPCL1_UDB_REPLACEMENT_E,
    CPSS_DXCH_SIP6_30_TABLE_IPCL2_UDB_REPLACEMENT_E,

    /* SMU unit*/
    CPSS_DXCH_SIP6_30_TABLE_SMU_IRF_SNG_E,
    CPSS_DXCH_SIP6_30_TABLE_SMU_IRF_COUNTING_E,

    CPSS_DXCH_SIP6_30_TABLE_TXQ_PDS_NEXT_DESC_E,
    CPSS_DXCH_SIP6_30_TABLE_TXQ_PDS_WRITE_POINTER_E,
    CPSS_DXCH_SIP6_30_TABLE_TXQ_PDS_READ_POINTER_E,

    CPSS_DXCH_SIP6_30_TXQ_SDQ_QBV_CFG_E,

    CPSS_DXCH_SIP6_30_TABLE_PREQ_SRF_MAPPING_E,
    CPSS_DXCH_SIP6_30_TABLE_PREQ_SRF_CONFIG_E,
    CPSS_DXCH_SIP6_30_TABLE_PREQ_SRF_COUNTERS_E,
    CPSS_DXCH_SIP6_30_TABLE_PREQ_SRF_DAEMON_E,
    CPSS_DXCH_SIP6_30_TABLE_PREQ_SRF_HISTORY_BUFFER_E,
    CPSS_DXCH_SIP6_30_TABLE_PREQ_SRF_ZERO_BIT_VECTOR_0_E,
    CPSS_DXCH_SIP6_30_TABLE_PREQ_SRF_ZERO_BIT_VECTOR_1_E,


    CPSS_DXCH_SIP6_30_TABLE_LAST_E,     /* Ironman   */

    /* HW tables that are NOT under CPSS control */
    CPSS_DXCH_INTERNAL_TABLE_PACKET_DATA_PARITY_E,
    CPSS_DXCH_INTERNAL_TABLE_PACKET_DATA_ECC_E,
    CPSS_DXCH_INTERNAL_TABLE_DESCRIPTORS_CONTROL_PARITY_E,
    CPSS_DXCH_INTERNAL_TABLE_DESCRIPTORS_CONTROL_ECC_E,
    CPSS_DXCH_INTERNAL_TABLE_PACKET_DATA_CONTROL_PARITY_E,
    CPSS_DXCH_INTERNAL_TABLE_PACKET_DATA_CONTROL_ECC_E,
    CPSS_DXCH_INTERNAL_TABLE_PHA_RAM_E,
    CPSS_DXCH_INTERNAL_TABLE_CM3_RAM_E,
    CPSS_DXCH_INTERNAL_TABLE_MANAGEMENT_E,

    /* must be last */
    CPSS_DXCH_TABLE_LAST_E

} CPSS_DXCH_TABLE_ENT;



/**
* @enum CPSS_DXCH_LOGICAL_TABLE_ENT
 *
 * @brief names of the 'logical' tables
 *
 * Enumerations:
 *  CPSS_DXCH_LOGICAL_TABLE_VLAN_E - vlan logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EPORT_E - ePort logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PHYSICAL_PORT_E - physical port logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PORT_ISOLATION_E - port isolation logical table
 *  CPSS_DXCH_LOGICAL_TABLE_STG_E - STG logical table
 *  CPSS_DXCH_LOGICAL_TABLE_VLAN_TRANSLATION_E - vlan translation logical table
 *  CPSS_DXCH_LOGICAL_TABLE_VRF_E - vrf logical table
 *  CPSS_DXCH_LOGICAL_TABLE_QOS_PROFILE_E - qos profile logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PROTECTION_LOC_E - protection loc logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TRUNK_MEMBERS_E - trunk members logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TM_MAPPING_E - tm mapping logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PFC_MODE_PROFILE_TC_THRESHOLDS_E
 *                 - pfc mode profile tc thresholds logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_QUEUE_LIMITS_E - tail drop queue limits logical table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_PCL_CONFIG_E - ingress pcl config logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PCL_UDB_CONFIG_E - pcl udb config logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PCL_UDB_SELECT_E - pcl udb select logical table
 *  CPSS_DXCH_LOGICAL_TABLE_OAM_E - oam logical table
 *  CPSS_DXCH_LOGICAL_TABLE_OAM_KEEPALIVE_AGING_E - oam keepalive aging logical table
 *  CPSS_DXCH_LOGICAL_TABLE_OAM_EXCEPTION_SUMMARY_E - oam exception summary logical table
 *  CPSS_DXCH_LOGICAL_TABLE_OAM_EXCEPTIONS_E - oam exceptions logical table
 *  CPSS_DXCH_LOGICAL_TABLE_OAM_OPCODE_PACKET_COMMAND_E - oam opcode packet command logical table
 *  CPSS_DXCH_LOGICAL_TABLE_POLICER_ATTRIBUTES_E - policer attributes logical table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_REMARKING_E - ingress policer remarking logical table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_0_METERING_E - ingress policer 0 metering logical table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_1_METERING_E - ingress policer 1 metering logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_POLICER_METERING_E - egress policer metering logical table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_0_COUNTING_E -
 *              ingress policer stage 0 counting table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_1_COUNTING_E -
 *              ingress policer stage 1 counting table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_POLICER_COUNTING_E -
 *              egress policer counting table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_0_IPFIX_ALERT_AGING_E -
 *              ingress policer stage 0 IPFIX alert aging table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_1_IPFIX_ALERT_AGING_E -
 *              ingress policer stage 1 IPFIX alert aging table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_POLICER_IPFIX_ALERT_AGING_E -
 *              egress policer IPFIX alert aging table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_0_IPFIX_ALERT_WRAPAROUND_E -
 *              ingress policer stage 0 IPFIX alert wraparound table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_1_IPFIX_ALERT_WRAPAROUND_E -
 *              ingress policer stage 1 IPFIX alert wraparound table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_POLICER_IPFIX_ALERT_WRAPAROUND_E -
 *              egress policer IPFIX alert wraparound table
 *  CPSS_DXCH_LOGICAL_TABLE_DEFAULT_EPORT_E - default eport logical table
 *  CPSS_DXCH_LOGICAL_TABLE_FDB_E - fdb logical table
 *  CPSS_DXCH_LOGICAL_TABLE_IPVX_ROUTER_ACCESS_MATRIX_E - ipvx router access matrix logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TM_QUEUE_MAP_CPU_CODE_TO_TC_E - tm queue map cpu code to tc logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TM_QUEUE_MAP_TARGET_DEV_TO_INDEX_E
 *                 - tm queue map target dev to index logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TM_QUEUE_MAP_POLICING_ENABLE_E - tm queue map policing enable logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TM_QUEUE_MAP_QUEUE_ID_SELECTOR_E - tm queue map queue id selector logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TM_L1_PACKET_LENGTH_OFFSET_E - tm l1 packet length offset logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TM_DROP_MASKING_E - tm drop masking logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TM_DROP_QUEUE_PROFILE_ID_E - tm drop queue profile id logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TCAM_E - tcam logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TCAM_ACTION_E - tcam action logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_FORWARD_FROM_CPU_TO_LOOPBACK_MAPPER_E
 *                 - egress forward from cpu to loopback mapper logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_FAST_STACK_FAILOVER_SECONDARY_TARGET_PORT_E
 *                 - egress fast stack failover secondary target port logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_DEVICE_MAP_TABLE_E - egress device map table logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TX_PROTECTION_E - tx protection logical table
 *  CPSS_DXCH_LOGICAL_TABLE_L2_MLL_E - l2 mll logical table
 *  CPSS_DXCH_LOGICAL_TABLE_L2_MLL_LTT_E - l2 mll ltt logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TRUNK_HASH_MASK_CRC_E - trunk hash mask crc logical table
 *  CPSS_DXCH_LOGICAL_TABLE_BRIDGE_SOURCE_TRUNK_ATTRIBUTE_E - bridge source trunk attribute logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TUNNEL_START_CONFIG_E - tunnel start config logical table
 *                     NOTE: in SIP5 the IPv6 TS entries are twice longer than non-IPv6 TS
 *                     entries and can have only even entry indexes while non-IPv6 enty
 *                     indexes can be any.  DataIntegrity API can't distinguish
 *                     kind of logical entry so it can return odd index for IPv6 entry too
 *                     (see CPSS_DXCH_LOGICAL_TABLE_INFO_STC::logicalTableEntryIndex).
 *                     An application is responsible to treat logicalTableEntryIndex 2n, 2n+1
 *                     return by such API (cpssDxChDiagDataIntegrityEventsGet)
 *                     as the same logical entry in case of IPv6.
 *  CPSS_DXCH_LOGICAL_TABLE_ARP_E - ARP logical table - one of three parts of physical
 *                                  Tunnel-Start/ARP/NAT Table.
 *  CPSS_DXCH_LOGICAL_TABLE_NAT_E - NAT logical table - one of three parts of physical
 *                                  Tunnel-Start/ARP/NAT Table.
 *  CPSS_DXCH_LOGICAL_TABLE_GENERIC_TUNNEL_START_PROFILE_E - generic tunnel start profile logical table
 *  CPSS_DXCH_LOGICAL_TABLE_CN_SAMPLE_INTERVALS_E - cn sample intervals logical table
 *  CPSS_DXCH_LOGICAL_TABLE_BUFFERS_MANAGER_MULTICAST_COUNTERS_E
 *                 - buffers manager multicast counters logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PFC_LLFC_COUNTERS_E - pfc llfc counters logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_QUEUES_BUFFERS_COUNTERS_E
 *                 - tail drop queues buffers counters logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_QUEUES_MULTICASTC_BUFFERS_COUNTERS_E
 *                 - tail drop queues multicastc buffers counters logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TXQ_LINK_LIST_QUEUES_DESCRIPTORS_COUNTERS_E
 *                 - txq link list queues descriptors counters logical table
 *  CPSS_DXCH_LOGICAL_TABLE_IP_MLL_E - ip mll logical table
 *  CPSS_DXCH_LOGICAL_TABLE_IPVX_ROUTER_NEXTHOP_E - ipvx router nexthop logical table
 *  CPSS_DXCH_LOGICAL_TABLE_IPVX_ROUTER_NEXTHOP_AGE_BITS_E - ipvx router nexthop age bits logical table
 *  CPSS_DXCH_LOGICAL_TABLE_ROUTER_MAC_SA_E - router mac sa logical table
 *  CPSS_DXCH_LOGICAL_TABLE_GLOBAL_MAC_SA_E - global mac sa logical table
 *  CPSS_DXCH_LOGICAL_TABLE_IPVX_ROUTER_QOS_PROFILE_OFFSETS_E
 *                 - ipvx router qos profile offsets logical table
 *  CPSS_DXCH_LOGICAL_TABLE_MAC2ME_E - mac2me logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TTI_UDB_CONFIG_E - tti udb config logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PTP_DOMAIN_E - ptp domain logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_REMARKING_TIMESTAMP_CFG_E
 *                 - egress remarking timestamp cfg logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_REMARKING_PTP_LOCAL_ACTION_E
 *                 - egress remarking ptp local action logical table
 *  CPSS_DXCH_LOGICAL_TABLE_OAM_LM_OFFSET_E - oam lm offset logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_POLICER_REMARKING_E - egress policer remarking logical table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_0_HIERARCHICAL_E
 *                 - ingress policer 0 hierarchical logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TXQ_DESIGNATED_PORT_E - txq designated port logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_TC_DP_MAPPER_E - egress tc dp mapper logical table
 *  CPSS_DXCH_LOGICAL_TABLE_MULTICAST_E - multicast logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TXQ_SOURCE_ID_MEMBERS_E - txq source id members logical table
 *  CPSS_DXCH_LOGICAL_TABLE_STATISTICAL_RATE_LIMIT_E - statistical rate limit logical table
 *  CPSS_DXCH_LOGICAL_TABLE_CPU_CODE_E - cpu code logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TO_CPU_RATE_LIMITER_CONFIG_E - to cpu rate limiter config logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_E_VLAN_MAPPER_E - egress e vlan mapper logical table
 *  CPSS_DXCH_LOGICAL_TABLE_LPM_MEM_E - lpm mem logical table
 *  CPSS_DXCH_LOGICAL_TABLE_ECMP_E - ecmp logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TTI_QOS_MAP_DSCP_TO_QOS_PROFILE_E
 *                 - tti qos map dscp to qos profile logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TTI_QOS_MAP_UP_CFI_TO_QOS_PROFILE_E
 *                 - tti qos map up cfi to qos profile logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TTI_QOS_MAP_EXP_TO_QOS_PROFILE_E
 *                 - tti qos map exp to qos profile logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TTI_QOS_MAP_DSCP_TO_DSCP_E - tti qos map dscp to dscp logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_REMARKING_QOS_DSCP_MAP_E - egress remarking qos dscp map logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_REMARKING_QOS_TC_DP_MAP_E - egress remarking qos tc dp map logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TM_FCU_PORT_INGRESS_TIMERS_CONFIG_E
 *                 - tm fcu port ingress timers config logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TM_AGING_QUEUE_PROFILE_E - tm aging queue profile logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TM_AGING_PROFILE_THESHOLDS_E - tm aging profile thesholds logical table
 *  CPSS_DXCH_LOGICAL_TABLE_L2_ECMP_E - l2 ecmp logical table
 *  CPSS_DXCH_LOGICAL_TABLE_VLAN_PORT_PROTOCOL_E - vlan port protocol logical table
 *  CPSS_DXCH_LOGICAL_TABLE_L2_ECMP_LTT_E - l2 ecmp ltt logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E
 *                 - txq shaper per port per prio token bucket config logical table
 *  CPSS_DXCH_LOGICAL_TABLE_CNC_BLOCK_0_E  - cnc block 0 (out of 63)
 *      ... cnc block 1..62
 *  CPSS_DXCH_LOGICAL_TABLE_CNC_BLOCK_63_E - cnc block 63 (out of 63)
 *  CPSS_DXCH_LOGICAL_TABLE_IPVX_ROUTER_ECMP_INDIRECT_NEXT_HOP_E - ipvx router ecmp indirect next hop logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_PORT_MAX_BUFFER_FILL_LEVEL_E - tail drop port max buffer fill level logical table
 *  CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_QUEUE_MAX_BUFFER_FILL_LEVEL_E  - tail drop queue max buffer fill level logical table
 *  CPSS_DXCH_LOGICAL_TABLE_LATENCY_MONITORING_E - egress pcl port latency monitoring logical table
 *  CPSS_DXCH_LOGICAL_TABLE_LATENCY_MONITORING_PORT_CONFIG_E - egress pcl source/target physical port mapping logical table
 *  CPSS_DXCH_LOGICAL_TABLE_LATENCY_MONITORING_CONFIG_E - latency monitoring config logical table
 *  CPSS_DXCH_LOGICAL_TABLE_LATENCY_MONITORING_STATISTICS_E - latency monitoring statistics logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_PROFILE_CONFIG_E - preq port profile logical table
 *  CPSS_DXCH_LOGICAL_TABLE_BRIDGE_L2_DLB_PATH_UTILIZATION_TABLE_E - l2 ecmp path utilization logical table
 *  CPSS_DXCH_LOGICAL_TABLE_POLICER_PORT_CONFIG_E - policer port attribute logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PHA_FW_IMAGE_E - pha fw image logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PHA_SHARED_DMEM_E - pha ppa shared logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PHA_THREAD_ID_E - pha ppa threads configuration logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PHA_SOURCE_PORT_E - pha source physical port logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PHA_TARGET_PORT_E - pha target physical port logical table
 *  CPSS_DXCH_LOGICAL_TABLE_LPM_AGING_E - lpm aging logical table
 *  - brief not under CPSS control - internal tables
 *  CPSS_DXCH_LOGICAL_TABLE_EXACT_MATCH_E - exact match logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PORT_MAC_COUNTERS_E - port mac counters logical table
 *  CPSS_DXCH_LOGICAL_INTERNAL_TABLE_PACKET_DATA_ECC_E - packet data logical table with ECC protection
 *  CPSS_DXCH_LOGICAL_INTERNAL_TABLE_PACKET_DATA_PARITY_E - packet data logical table with Parity protection
 *   CPSS_DXCH_LOGICAL_INTERNAL_TABLE_DESCRIPTORS_CONTROL_ECC_E - descriptors control logical table with ECC protection
 *   CPSS_DXCH_LOGICAL_INTERNAL_TABLE_DESCRIPTORS_CONTROL_PARITY_E - descriptors control logical table with Parity protection
 *  CPSS_DXCH_LOGICAL_INTERNAL_TABLE_PACKET_DATA_CONTROL_ECC_E - packet data control logical table with ECC protection
 *  CPSS_DXCH_LOGICAL_INTERNAL_TABLE_PACKET_DATA_CONTROL_PARITY_E - packet data control logical table with Parity protection
 *  CPSS_DXCH_LOGICAL_INTERNAL_TABLE_PHA_RAM_E - ppa scratchpad logical table
 *  CPSS_DXCH_LOGICAL_INTERNAL_TABLE_CM3_RAM_E - mg configuration processor logical table
 *  CPSS_DXCH_LOGICAL_INTERNAL_TABLE_MANAGEMENT_E - management logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EXACT_MATCH_AUTO_LEARNED_ENTRY_INDEX_E - exact match auto learn entry index logical table
 *  CPSS_DXCH_LOGICAL_TABLE_PPU_ACTION_TABLE_E - Programmable Parser Unit action logical table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_0_IPFIX_FIRST_N_PACKETS_E - ingress policer stage 0 IPFIX first n packets logical table
 *  CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_1_IPFIX_FIRST_N_PACKETS_E - ingress policer stage 1 IPFIX first n packets logical table
 *  CPSS_DXCH_LOGICAL_TABLE_EGRESS_POLICER_IPFIX_FIRST_N_PACKETS_E - egress policer IPFIX first n packets logical table
 *
 * Note: Values of enum linked with tables DB cpssLogicalToHwTablesDB.
 *       The DB  _MUST BE_ updated in case of changes the enum values (order).
 */
typedef enum
{
    CPSS_DXCH_LOGICAL_TABLE_VLAN_E,
    CPSS_DXCH_LOGICAL_TABLE_EPORT_E,
    CPSS_DXCH_LOGICAL_TABLE_PHYSICAL_PORT_E,
    CPSS_DXCH_LOGICAL_TABLE_PORT_ISOLATION_E,
    CPSS_DXCH_LOGICAL_TABLE_STG_E,
    CPSS_DXCH_LOGICAL_TABLE_VLAN_TRANSLATION_E,
    CPSS_DXCH_LOGICAL_TABLE_VRF_E,
    CPSS_DXCH_LOGICAL_TABLE_QOS_PROFILE_E,
    CPSS_DXCH_LOGICAL_TABLE_PROTECTION_LOC_E,
    CPSS_DXCH_LOGICAL_TABLE_TRUNK_MEMBERS_E,
    CPSS_DXCH_LOGICAL_TABLE_TM_MAPPING_E,
    CPSS_DXCH_LOGICAL_TABLE_PFC_MODE_PROFILE_TC_THRESHOLDS_E,
    CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_QUEUE_LIMITS_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_PCL_CONFIG_E,
    CPSS_DXCH_LOGICAL_TABLE_PCL_UDB_CONFIG_E,
    CPSS_DXCH_LOGICAL_TABLE_PCL_UDB_SELECT_E,
    CPSS_DXCH_LOGICAL_TABLE_OAM_E,
    CPSS_DXCH_LOGICAL_TABLE_OAM_KEEPALIVE_AGING_E,
    CPSS_DXCH_LOGICAL_TABLE_OAM_EXCEPTION_SUMMARY_E,
    CPSS_DXCH_LOGICAL_TABLE_OAM_EXCEPTIONS_E,
    CPSS_DXCH_LOGICAL_TABLE_OAM_OPCODE_PACKET_COMMAND_E,
    CPSS_DXCH_LOGICAL_TABLE_POLICER_ATTRIBUTES_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_REMARKING_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_0_METERING_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_1_METERING_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_POLICER_METERING_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_0_COUNTING_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_1_COUNTING_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_POLICER_COUNTING_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_0_IPFIX_ALERT_WRAPAROUND_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_1_IPFIX_ALERT_WRAPAROUND_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_POLICER_IPFIX_ALERT_WRAPAROUND_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_0_IPFIX_ALERT_AGING_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_1_IPFIX_ALERT_AGING_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_POLICER_IPFIX_ALERT_AGING_E,
    CPSS_DXCH_LOGICAL_TABLE_DEFAULT_EPORT_E,
    CPSS_DXCH_LOGICAL_TABLE_FDB_E,
    CPSS_DXCH_LOGICAL_TABLE_IPVX_ROUTER_ACCESS_MATRIX_E,
    CPSS_DXCH_LOGICAL_TABLE_TM_QUEUE_MAP_CPU_CODE_TO_TC_E,
    CPSS_DXCH_LOGICAL_TABLE_TM_QUEUE_MAP_TARGET_DEV_TO_INDEX_E,
    CPSS_DXCH_LOGICAL_TABLE_TM_QUEUE_MAP_POLICING_ENABLE_E,
    CPSS_DXCH_LOGICAL_TABLE_TM_QUEUE_MAP_QUEUE_ID_SELECTOR_E,
    CPSS_DXCH_LOGICAL_TABLE_TM_L1_PACKET_LENGTH_OFFSET_E,
    CPSS_DXCH_LOGICAL_TABLE_TM_DROP_MASKING_E,
    CPSS_DXCH_LOGICAL_TABLE_TM_DROP_QUEUE_PROFILE_ID_E,
    CPSS_DXCH_LOGICAL_TABLE_TCAM_E,
    CPSS_DXCH_LOGICAL_TABLE_TCAM_ACTION_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_FORWARD_FROM_CPU_TO_LOOPBACK_MAPPER_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_FAST_STACK_FAILOVER_SECONDARY_TARGET_PORT_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_DEVICE_MAP_TABLE_E,
    CPSS_DXCH_LOGICAL_TABLE_TX_PROTECTION_E,
    CPSS_DXCH_LOGICAL_TABLE_L2_MLL_E,
    CPSS_DXCH_LOGICAL_TABLE_L2_MLL_LTT_E,
    CPSS_DXCH_LOGICAL_TABLE_TRUNK_HASH_MASK_CRC_E,
    CPSS_DXCH_LOGICAL_TABLE_BRIDGE_SOURCE_TRUNK_ATTRIBUTE_E,
    CPSS_DXCH_LOGICAL_TABLE_TUNNEL_START_CONFIG_E,
    CPSS_DXCH_LOGICAL_TABLE_ARP_E,
    CPSS_DXCH_LOGICAL_TABLE_NAT_E,
    CPSS_DXCH_LOGICAL_TABLE_GENERIC_TUNNEL_START_PROFILE_E,
    CPSS_DXCH_LOGICAL_TABLE_CN_SAMPLE_INTERVALS_E,
    CPSS_DXCH_LOGICAL_TABLE_BUFFERS_MANAGER_MULTICAST_COUNTERS_E,
    CPSS_DXCH_LOGICAL_TABLE_PFC_LLFC_COUNTERS_E,
    CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_QUEUES_BUFFERS_COUNTERS_E,
    CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_QUEUES_MULTICASTC_BUFFERS_COUNTERS_E,
    CPSS_DXCH_LOGICAL_TABLE_TXQ_LINK_LIST_QUEUES_DESCRIPTORS_COUNTERS_E,
    CPSS_DXCH_LOGICAL_TABLE_IP_MLL_E,
    CPSS_DXCH_LOGICAL_TABLE_IPVX_ROUTER_NEXTHOP_E,
    CPSS_DXCH_LOGICAL_TABLE_IPVX_ROUTER_NEXTHOP_AGE_BITS_E,
    CPSS_DXCH_LOGICAL_TABLE_ROUTER_MAC_SA_E,
    CPSS_DXCH_LOGICAL_TABLE_GLOBAL_MAC_SA_E,
    CPSS_DXCH_LOGICAL_TABLE_IPVX_ROUTER_QOS_PROFILE_OFFSETS_E,
    CPSS_DXCH_LOGICAL_TABLE_MAC2ME_E,
    CPSS_DXCH_LOGICAL_TABLE_TTI_UDB_CONFIG_E,
    CPSS_DXCH_LOGICAL_TABLE_PTP_DOMAIN_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_REMARKING_TIMESTAMP_CFG_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_REMARKING_PTP_LOCAL_ACTION_E,
    CPSS_DXCH_LOGICAL_TABLE_OAM_LM_OFFSET_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_POLICER_REMARKING_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_0_HIERARCHICAL_E,
    CPSS_DXCH_LOGICAL_TABLE_TXQ_DESIGNATED_PORT_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_TC_DP_MAPPER_E,
    CPSS_DXCH_LOGICAL_TABLE_MULTICAST_E,
    CPSS_DXCH_LOGICAL_TABLE_TXQ_SOURCE_ID_MEMBERS_E,
    CPSS_DXCH_LOGICAL_TABLE_STATISTICAL_RATE_LIMIT_E,
    CPSS_DXCH_LOGICAL_TABLE_CPU_CODE_E,
    CPSS_DXCH_LOGICAL_TABLE_TO_CPU_RATE_LIMITER_CONFIG_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_E_VLAN_MAPPER_E,
    CPSS_DXCH_LOGICAL_TABLE_LPM_MEM_E,
    CPSS_DXCH_LOGICAL_TABLE_ECMP_E,
    CPSS_DXCH_LOGICAL_TABLE_TTI_QOS_MAP_DSCP_TO_QOS_PROFILE_E,
    CPSS_DXCH_LOGICAL_TABLE_TTI_QOS_MAP_UP_CFI_TO_QOS_PROFILE_E,
    CPSS_DXCH_LOGICAL_TABLE_TTI_QOS_MAP_EXP_TO_QOS_PROFILE_E,
    CPSS_DXCH_LOGICAL_TABLE_TTI_QOS_MAP_DSCP_TO_DSCP_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_REMARKING_QOS_DSCP_MAP_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_REMARKING_QOS_TC_DP_MAP_E,
    CPSS_DXCH_LOGICAL_TABLE_TM_FCU_PORT_INGRESS_TIMERS_CONFIG_E,
    CPSS_DXCH_LOGICAL_TABLE_TM_AGING_QUEUE_PROFILE_E,
    CPSS_DXCH_LOGICAL_TABLE_TM_AGING_PROFILE_THESHOLDS_E,
    CPSS_DXCH_LOGICAL_TABLE_L2_ECMP_E,
    CPSS_DXCH_LOGICAL_TABLE_VLAN_PORT_PROTOCOL_E,
    CPSS_DXCH_LOGICAL_TABLE_L2_ECMP_LTT_E,
    CPSS_DXCH_LOGICAL_TABLE_TXQ_SHAPER_PER_PORT_PER_PRIO_TOKEN_BUCKET_CONFIG_E,
    CPSS_DXCH_LOGICAL_TABLE_TXQ_SHAPER_PER_PORT_TOKEN_BUCKET_CONFIG_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_PCL_CONFIG_E,

    CPSS_DXCH_LOGICAL_TABLE_CNC_BLOCK_0_E,
    CPSS_DXCH_LOGICAL_TABLE_CNC_BLOCK_63_E = CPSS_DXCH_LOGICAL_TABLE_CNC_BLOCK_0_E + 63,

    CPSS_DXCH_LOGICAL_TABLE_IPVX_ROUTER_ECMP_INDIRECT_NEXT_HOP_E,
    CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_PORT_MAX_BUFFER_FILL_LEVEL_E,
    CPSS_DXCH_LOGICAL_TABLE_TAIL_DROP_QUEUE_MAX_BUFFER_FILL_LEVEL_E,
    CPSS_DXCH_LOGICAL_TABLE_LATENCY_MONITORING_E,
    CPSS_DXCH_LOGICAL_TABLE_LATENCY_MONITORING_PORT_CONFIG_E,
    CPSS_DXCH_LOGICAL_TABLE_LATENCY_MONITORING_CONFIG_E,
    CPSS_DXCH_LOGICAL_TABLE_LATENCY_MONITORING_STATISTICS_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_PROFILE_CONFIG_E,
    CPSS_DXCH_LOGICAL_TABLE_BRIDGE_L2_DLB_PATH_UTILIZATION_TABLE_E,
    CPSS_DXCH_LOGICAL_TABLE_POLICER_PORT_CONFIG_E,
    CPSS_DXCH_LOGICAL_TABLE_PHA_FW_IMAGE_E,
    CPSS_DXCH_LOGICAL_TABLE_PHA_SHARED_DMEM_E,
    CPSS_DXCH_LOGICAL_TABLE_PHA_THREAD_ID_E,
    CPSS_DXCH_LOGICAL_TABLE_PHA_SOURCE_PORT_E,
    CPSS_DXCH_LOGICAL_TABLE_PHA_TARGET_PORT_E,
    CPSS_DXCH_LOGICAL_TABLE_LPM_AGING_E,
    CPSS_DXCH_LOGICAL_TABLE_EXACT_MATCH_E,
    CPSS_DXCH_LOGICAL_TABLE_PORT_MAC_COUNTERS_E,
    CPSS_DXCH_LOGICAL_TABLE_EXACT_MATCH_AUTO_LEARNED_ENTRY_INDEX_E,
    CPSS_DXCH_LOGICAL_TABLE_PPU_ACTION_TABLE_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_0_IPFIX_FIRST_N_PACKETS_E,
    CPSS_DXCH_LOGICAL_TABLE_INGRESS_POLICER_1_IPFIX_FIRST_N_PACKETS_E,
    CPSS_DXCH_LOGICAL_TABLE_EGRESS_POLICER_IPFIX_FIRST_N_PACKETS_E,
    CPSS_DXCH_LOGICAL_INTERNAL_TABLE_PACKET_DATA_ECC_E,
    CPSS_DXCH_LOGICAL_INTERNAL_TABLE_PACKET_DATA_PARITY_E,
    CPSS_DXCH_LOGICAL_INTERNAL_TABLE_DESCRIPTORS_CONTROL_ECC_E,
    CPSS_DXCH_LOGICAL_INTERNAL_TABLE_DESCRIPTORS_CONTROL_PARITY_E,
    CPSS_DXCH_LOGICAL_INTERNAL_TABLE_PACKET_DATA_CONTROL_ECC_E,
    CPSS_DXCH_LOGICAL_INTERNAL_TABLE_PACKET_DATA_CONTROL_PARITY_E,
    CPSS_DXCH_LOGICAL_INTERNAL_TABLE_PHA_RAM_E,
    CPSS_DXCH_LOGICAL_INTERNAL_TABLE_CM3_RAM_E,
    CPSS_DXCH_LOGICAL_INTERNAL_TABLE_MANAGEMENT_E,

    /* must be last */
    CPSS_DXCH_LOGICAL_TABLE_LAST_E
} CPSS_DXCH_LOGICAL_TABLE_ENT;


/**
* @enum CPSS_DXCH_SHADOW_TYPE_ENT
 *
 * @brief Defines HW tables shadow type
*/
typedef enum{

    /** @brief shadow is not used type (default)
     *  the table not require shadow (mirrored copy)
     */
    CPSS_DXCH_SHADOW_TYPE_NONE_E,

    /** @brief cpss shadow type
     *  the table hold/require shadow that is kept by the CPSS (in SW)
     */
    CPSS_DXCH_SHADOW_TYPE_CPSS_E,

    /** @brief hw shadow type
     *  the table hold/require shadow that is kept by the HW (when
     *  table hold identical 'image' in more than single instance)
     */
    CPSS_DXCH_SHADOW_TYPE_HW_E

} CPSS_DXCH_SHADOW_TYPE_ENT;

/* value to state that need support from the shadow for ALL supported tables
    to use shadow that will use as many tables as possible in as type
    'CPSS_DXCH_SHADOW_TYPE_HW_E' , and if not possible then use type
    'CPSS_DXCH_SHADOW_TYPE_CPSS_E'
*/
#define CPSS_DXCH_SHADOW_TYPE_AS_MANY_HW_CNS 0xEEEEEEEE

/* value to state that need support from the shadow for ALL supported tables
    to use CPSS shadow (type CPSS_DXCH_SHADOW_TYPE_CPSS_E)
*/
#define CPSS_DXCH_SHADOW_TYPE_ALL_CPSS_CNS 0xFFFFFFFF

/**
* @struct CPSS_DXCH_LOGICAL_TABLES_SHADOW_STC
 *
 * @brief This struct defines logical table shadow entry
*/
typedef struct{

    /** name of the logical table */
    CPSS_DXCH_LOGICAL_TABLE_ENT logicalTableName;

    /** type of the shadow */
    CPSS_DXCH_SHADOW_TYPE_ENT shadowType;

} CPSS_DXCH_LOGICAL_TABLES_SHADOW_STC;


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* __cpssDxChTablesh */
