/*******************************************************************************
*              (c), Copyright 2021, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,       *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
*/
/**
********************************************************************************
* @file prvAppIpfixManagerDbg.c
*
* @brief Application Code Debug APIs for IPFIX Manager
*
* @version   1
*********************************************************************************
**/

#include <cpss/dxCh/dxChxGen/networkIf/cpssDxChNetIf.h>
#include <cpss/dxCh/dxChxGen/networkIf/cpssDxChNetIfTypes.h>
#include <cpss/generic/networkIf/cpssGenNetIfTypes.h>
#include <cpss/dxCh/dxChxGen/pcl/cpssDxChPcl.h>
#include <cpss/extServices/private/prvCpssBindFunc.h>
#include <cpss/dxCh/dxChxGen/config/private/prvCpssDxChInfo.h>
#include <cpss/dxCh/dxChxGen/pcl/cpssDxChPcl.h>
#include <cpss/common/private/globalShared/prvCpssGlobalDb.h>
#include <cpss/common/private/globalShared/prvCpssGlobalDbInterface.h>
#include <ipfixManager/prvAppIpfixManager.h>
#include <cpss/dxCh/dxChxGen/ipfixManager/prvCpssDxChIpfixManager.h>
#include <cpss/dxCh/dxChxGen/ipfixManager/cpssDxChIpfixManager.h>
#include <cpss/dxCh/dxChxGen/ipfix/cpssDxChIpfix.h>
#include <appDemo/sysHwConfig/gtAppDemoSysConfig.h>
#include <appDemo/sysHwConfig/gtAppDemoSysConfigDefaults.h>
#include <cpss/common/config/private/prvCpssConfigTypes.h>
#include <cpss/generic/cpssHwInit/private/prvCpssHwInit.h>
#include <cpss/dxCh/dxChxGen/networkIf/private/prvCpssDxChNetIf.h>
#include <cpss/dxCh/dxChxGen/port/cpssDxChPortManagerSamples.h>
#include <cpss/dxCh/dxChxGen/port/private/prvCpssDxChPortCtrl.h>
#include <ipfixManager/prvAppIpfixManagerDbg.h>

extern PRV_APP_IPFIX_MGR_DB_STC *appIpfixManagerDbPtr;

extern void dxChNetIfRxPacketParse_DebugDumpEnable
(
    IN GT_BOOL  enableDumpRxPacket
);

/**
 * @internal appDemoIpfixManagerConfigCheck function
 * @endinternal
 *
 * @brief  Read config parameters from firmware and check
 *         they are in sync with the configuration in the application database.
 *
 * @param[in] devNum   -  device number
 *
 * @return GT_OK  - on success
 */
GT_STATUS appDemoIpfixManagerConfigCheck
(
    GT_U8           devNum
)
{
    GT_STATUS   rc               = GT_OK;
    GT_U32      numOfMsgFetched  = 0;
    GT_U32      mgNum;
    CPSS_DXCH_IPFIX_MANAGER_IPC_MSG_RECV_UNT configReturnIpcMsg;
    GT_U32      i = 0;

    rc = cpssDxChIpfixManagerConfigGet(devNum);
    if (rc != GT_OK)
    {
        __IPFIX_MANAGER_LOG("cpssDxChIpfixManagerConfigGet failed: rc=%d\n", rc);
        return rc;
    }

    /* wait for few micro seconds so that configReturn IPC messages
       is generated by firmware */
    cpssOsTimerWkAfter(100);

    rc = cpssDxChIpfixManagerIpcMsgFetch(devNum, &numOfMsgFetched);
    if (rc != GT_OK)
    {
        __IPFIX_MANAGER_LOG("cpssDxChIpfixManagerIpcMsgFetch failed: rc=%d\n", rc);
        return rc;
    }

    if (numOfMsgFetched != 1)
    {
        __IPFIX_MANAGER_LOG("numOfMsgFetched = %d, Expected:1\n", numOfMsgFetched);
        return GT_FAIL;
    }

    rc = prvAppDemoIpfixManagerSingleEventHandle(&configReturnIpcMsg);
    if (rc != GT_OK)
    {
        __IPFIX_MANAGER_LOG("prvAppDemoIpfixManagerSingleEventHandle failed: rc=%d\n", rc);
        return rc;
    }

    if (configReturnIpcMsg.opcodeGet.opcode !=
            CPSS_DXCH_IPFIX_MANAGER_IPC_MSG_OPCODE_CONFIG_RETURN_E)
    {
        __IPFIX_MANAGER_LOG("Opcode: %d, Expected: CPSS_DXCH_IPFIX_MANAGER_IPC_MSG_OPCODE_CONFIG_RETURN_E\n",
                             configReturnIpcMsg.opcodeGet.opcode);
        return GT_FAIL;
    }

    /* Compare all params */
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.ipfixEnable,
                                appIpfixManagerDbPtr->ipfixEnable);
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.policerStage,
                                appIpfixManagerDbPtr->globalCfg.policerStage);
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.agingOffload,
                                appIpfixManagerDbPtr->globalCfg.agingOffload);
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.monitoringOffload,
                                appIpfixManagerDbPtr->globalCfg.monitoringOffload);
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.deltaMode,
                                appIpfixManagerDbPtr->globalCfg.deltaMode);
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.idleTimeout,
                                appIpfixManagerDbPtr->globalCfg.idleTimeout);
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.activeTimeout,
                                appIpfixManagerDbPtr->globalCfg.activeTimeout);
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.dataPktMtu,
                                appIpfixManagerDbPtr->globalCfg.dataPktMtu);
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.localQueueNum,
                                (appIpfixManagerDbPtr->globalCfg.ipfixDataQueueNum & 0x7));
    rc = prvCpssDxChNetifCheckNetifNumAndConvertToMgUnitId(devNum,
              appIpfixManagerDbPtr->globalCfg.ipfixDataQueueNum >> 3, &mgNum);
    if (rc != GT_OK)
    {
        __IPFIX_MANAGER_LOG("prvCpssDxChNetifCheckNetifNumAndConvertToMgUnitId failed\n");
        return rc;
    }
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.mgNum,
                                (mgNum));
    for (i=0; i<16; i++) {
        __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.txDsaTag[i],
                                    appIpfixManagerDbPtr->globalCfg.txDsaTag[i]);
    }
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.maxIpfixIndex[0],
                                appIpfixManagerDbPtr->portGroupCfg[0].maxIpfixIndex);
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.maxIpfixIndex[1*2],
                                appIpfixManagerDbPtr->portGroupCfg[1*2].maxIpfixIndex);
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.maxIpfixIndex[2*2],
                                appIpfixManagerDbPtr->portGroupCfg[2*2].maxIpfixIndex);
    __IPFIX_MANAGER_VAL_COMPARE(configReturnIpcMsg.configReturn.maxIpfixIndex[3*2],
                                appIpfixManagerDbPtr->portGroupCfg[3*2].maxIpfixIndex);

    return rc;
}

/**
 * @internal appDemoIpfixManagerDebugCountersDump function
 *
 * @brief  Dump debug counters
 *
 */
GT_STATUS appDemoIpfixManagerDebugCountersDump
(
    GT_VOID
)
{
    if ((appIpfixManagerDbPtr != NULL) &&
        (appIpfixManagerDbPtr->debugPrintsEnable == GT_TRUE))
    {
        cpssOsPrintf("Debug Counters:\n");
    }

    /*__IPFIX_MANAGER_DBG_COUNTER_PRINT(pktsMirroredToHost);*/
    __IPFIX_MANAGER_DBG_COUNTER_PRINT(pktsFetchedByHost);
    __IPFIX_MANAGER_DBG_COUNTER_PRINT(pktsFilteredByHost);
    __IPFIX_MANAGER_DBG_COUNTER_PRINT(pktsDrops);
    __IPFIX_MANAGER_DBG_COUNTER_PRINT(activeEntries);
    __IPFIX_MANAGER_DBG_COUNTER_PRINT(flowsTerminatedByIdleTimeout);
    __IPFIX_MANAGER_DBG_COUNTER_PRINT(flowsTerminatedByActiveTimeout);
    __IPFIX_MANAGER_DBG_COUNTER_PRINT(flowsLearningFails);
    __IPFIX_MANAGER_DBG_COUNTER_PRINT(dataGetAllRequests);
    __IPFIX_MANAGER_DBG_COUNTER_PRINT(exportCompleteMsgs);
    __IPFIX_MANAGER_DBG_COUNTER_PRINT(dataPktsFetchedByHost);
    /*__IPFIX_MANAGER_DBG_COUNTER_PRINT(dataPktsSentByFw);*/
    __IPFIX_MANAGER_DBG_COUNTER_PRINT(dataPktsDrops);
    /*__IPFIX_MANAGER_DBG_COUNTER_PRINT(timeForLastDataGetAllCompletion);*/

    if ((appIpfixManagerDbPtr != NULL) &&
        (appIpfixManagerDbPtr->debugPrintsEnable == GT_TRUE))
    {
        cpssOsPrintf("\n");
    }

    return GT_OK;
}

/**
 * @internal appDemoIpfixManagerDebugCountersReset function
 *
 * @brief  Reset debug counters
 *
 */
GT_STATUS appDemoIpfixManagerDebugCountersReset
(
    GT_VOID
)
{
    cpssOsMemSet(&appIpfixManagerDbPtr->dbgCounters, 0,
                 sizeof(appIpfixManagerDbPtr->dbgCounters));
    return GT_OK;
}

/**
 * @internal appDemoIpfixManagerDebugCountersGet function
 *
 * @brief Get debug counters
 *
 * @param[in]  dbgCountersPtr - (pointer to) debug counters structure
 */
GT_STATUS appDemoIpfixManagerDebugCountersGet
(
    PRV_APP_IPFIX_MGR_DBG_COUNTERS_STC *dbgCountersPtr
)
{
    if (appIpfixManagerDbPtr == NULL)
    {
        __IPFIX_MANAGER_LOG("appIpfixManagerDbPtr is not initialized\n");
        return GT_NOT_INITIALIZED;
    }

    cpssOsMemCpy(dbgCountersPtr, &appIpfixManagerDbPtr->dbgCounters,
                 sizeof(PRV_APP_IPFIX_MGR_DBG_COUNTERS_STC));
    return GT_OK;
}

/**
 * @internal appDemoIpfixManagerFlowGet function
 *
 * @brief Get debug counters
 *
 * @param[in]  dbgCountersPtr - (pointer to) debug counters structure
 */
GT_STATUS appDemoIpfixManagerFlowGet
(
    IN  GT_U32                      portGroupId,
    IN  GT_U32                      flowId,
    OUT PRV_APP_IPFIX_MGR_FLOWS_STC *flowPtr
)
{
    if (appIpfixManagerDbPtr == NULL)
    {
        __IPFIX_MANAGER_LOG("Application DB not initialized\n");
        return GT_NOT_INITIALIZED;
    }

    cpssOsMemCpy(flowPtr,
               &appIpfixManagerDbPtr->flowsDb[portGroupId][flowId],
               sizeof(PRV_APP_IPFIX_MGR_FLOWS_STC));

    return GT_OK;
}

/**
 * @internal appDemoIpfixManagerTestParamsAllSet function
 * @endinternal
 *
 * @brief Set test params database structure
 *
 * @param[in] testParamsPtr - (pointer to) test params structure
 *
 * @retval GT_OK    - on success
 */
GT_STATUS appDemoIpfixManagerTestParamsAllSet
(
    IN PRV_APP_IPFIX_MGR_TEST_PARAMS_STC *testParamsPtr
)
{
    if (appIpfixManagerDbPtr == NULL)
    {
        __IPFIX_MANAGER_LOG("Application DB not initialized\n");
        return GT_NOT_INITIALIZED;
    }

    if (testParamsPtr == NULL)
    {
        __IPFIX_MANAGER_LOG("testParamsPtr cannot be null\n");
        return GT_BAD_PTR;
    }

    cpssOsMemCpy(&appIpfixManagerDbPtr->testParams,
                 testParamsPtr,
                 sizeof(PRV_APP_IPFIX_MGR_TEST_PARAMS_STC));

    return GT_OK;
}

/**
 * @internal appDemoIpfixManagerTestParamsAllGet function
 * @endinternal
 *
 * @brief Get test params database structure
 *
 * @param[out] testParamsPtr - (pointer to) test params structure
 *
 * @retval GT_OK    - on success
 */
GT_STATUS appDemoIpfixManagerTestParamsAllGet
(
    OUT PRV_APP_IPFIX_MGR_TEST_PARAMS_STC *testParamsPtr
)
{
    if (appIpfixManagerDbPtr == NULL)
    {
        __IPFIX_MANAGER_LOG("Application DB not initialized\n");
        return GT_NOT_INITIALIZED;
    }

    if (testParamsPtr == NULL)
    {
        __IPFIX_MANAGER_LOG("testParamsPtr cannot be null\n");
        return GT_BAD_PTR;
    }

    cpssOsMemCpy(testParamsPtr,
               &appIpfixManagerDbPtr->testParams,
               sizeof(PRV_APP_IPFIX_MGR_TEST_PARAMS_STC));

    return GT_OK;
}

/**
 * @internal appDemoIpfixManagerCpuRxDumpEnable function
 * @endinternal
 *
 * @brief Enable CPU Rx Dump
 *
 * @param[in] enable - GT_TRUE/GT_FALSE enable/disable
 *
 * @retval GT_OK    - on success
 */
GT_STATUS  appDemoIpfixManagerCpuRxDumpEnable
(
    IN GT_BOOL enable
)
{
    appIpfixManagerDbPtr->cpuRxDumpEnable = enable;

    /* allow to 'see' the packets that we get (with the DSA) */
    dxChNetIfRxPacketParse_DebugDumpEnable(enable);


    return GT_OK;
}

/**
 * @internal appDemoIpfixManagerStatisticsDump function
 *
 * @brief  Dump flow statistics
 *
 */
GT_STATUS appDemoIpfixManagerStatisticsDump
(
    GT_VOID
)
{
    GT_U32      i = 0;
    GT_U32      j = 0;
    GT_U32      k = 0;
    PRV_APP_IPFIX_MGR_FLOWS_STC *dataRecordPtr;
    GT_U32      usedKeyLength = 14;
    GT_BOOL     printHeading = GT_TRUE;

    if ((appIpfixManagerDbPtr != NULL) &&
        (appIpfixManagerDbPtr->debugPrintsEnable == GT_TRUE))
    {
        cpssOsPrintf("Flow Statistics:\n");

        for (i=0; i<CPSS_DXCH_MAX_PORT_GROUPS_CNS; i++)
        {
            for (j = 0; j < PRV_APP_IPFIX_MGR_FLOWS_PER_PORT_GROUP_MAX_CNS; j++)
            {
                dataRecordPtr = &(appIpfixManagerDbPtr->flowsDb[i][j]);
                if (dataRecordPtr->isactive == GT_FALSE)
                {
                    continue;
                }

                if (printHeading == GT_TRUE)
                {
                    cpssOsPrintf("FlowId, Type,                   key, firstTs, lastTs, pktCnt, dropCnt, byteCnt\n");
                    printHeading = GT_FALSE;
                }
                cpssOsPrintf("%4X ", dataRecordPtr->data.flowId);
                cpssOsPrintf("%2d ", dataRecordPtr->pktType);
                for (k = 0; k < usedKeyLength; k++)
                {
                    cpssOsPrintf("%02X", dataRecordPtr->key.pattern[k]);
                }

                cpssOsPrintf("  %4X    ", dataRecordPtr->data.firstTs);
                cpssOsPrintf("%4X   ", dataRecordPtr->data.lastTs);
                cpssOsPrintf("%6d ", dataRecordPtr->data.packetCount[0]);
                cpssOsPrintf("%6d ", dataRecordPtr->data.dropCount[0]);
                cpssOsPrintf("%8d ", dataRecordPtr->data.byteCount[0]);
                cpssOsPrintf("\n");
            }
        }

        cpssOsPrintf("\n");
    }
    else if (appIpfixManagerDbPtr != NULL)
    {
        cpssOsPrintf("Error: appIpfixManagerDb no created\n");
    }
    return GT_OK;
}

GT_VOID  appDemoIpfixManagerDataRecordDump
(
    PRV_APP_IPFIX_MGR_DATA_PKT_STC   *dataPktPtr
)
{
    GT_U32 i;

    if (dataPktPtr == NULL)
    {
        cpssOsPrintf("dataPktPtr cannot be NULL\n");
        return;
    }

    cpssOsPrintf("Header:\n");
    cpssOsPrintf("    PacketType      : %X \n", dataPktPtr->header.packetType);
    cpssOsPrintf("    Sequence number : %X \n", dataPktPtr->header.seqNum);
    cpssOsPrintf("    No. Exported    : %X \n", dataPktPtr->header.numExported);
    cpssOsPrintf("    First FlowId    : %X \n", dataPktPtr->header.firstFlowId);
    cpssOsPrintf("    Last  FlowId    : %X \n", dataPktPtr->header.lastFlowId);
    cpssOsPrintf("    Time of the Day : %06X %08X \n", dataPktPtr->header.tod[1],
                                               dataPktPtr->header.tod[0]);

    for (i=0; i<dataPktPtr->header.numExported; i++)
    {
        cpssOsPrintf("Record Number: %d\n", i);
        cpssOsPrintf("    FlowId          : %04X\n", dataPktPtr->dataRecord[i].flowId);
        cpssOsPrintf("    First Time Stamp: %05X\n", dataPktPtr->dataRecord[i].firstTs);
        cpssOsPrintf("    Last Time Stamp : %05X\n", dataPktPtr->dataRecord[i].lastTs);
        cpssOsPrintf("    Packet Count    : %X %X\n", dataPktPtr->dataRecord[i].packetCount[1],
                                                    dataPktPtr->dataRecord[i].packetCount[0]);
        cpssOsPrintf("    Drop Count      : %X %X\n", dataPktPtr->dataRecord[i].dropCount[1],
                                                    dataPktPtr->dataRecord[i].dropCount[0]);
        cpssOsPrintf("    Byte Count      : %X %X\n", dataPktPtr->dataRecord[i].byteCount[1],
                                                    dataPktPtr->dataRecord[i].byteCount[0]);
        cpssOsPrintf("    Entry Status    : %X\n", dataPktPtr->dataRecord[i].entryStatus);
    }
}

GT_STATUS appDemoIpfixManagerAgingEnable
(
    IN GT_BOOL     enable
)
{
    if (appIpfixManagerDbPtr == NULL)
    {
        __IPFIX_MANAGER_LOG("IPFIX Manager not initialized\n");
        return GT_NOT_INITIALIZED;
    }

    appIpfixManagerDbPtr->agingEnable = enable;

    return GT_OK;
}
